### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by bidhya** [Esri/arcgis-python-api#1002]
**Describe the bug**
I followed the instructions from here: https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/ to setup the arcgis python api and the widgets. However, I get the "Error displaying widget: model not found" error. 

Same behaviour in Windows and Linux with Python 3.7.9 and 3.8.8 Here is a description of cloned environment from ArcgisPro 2.7.3
 
(arcgispro-py3-clone) C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>jupyter labextension list
JupyterLab v2.2.7
Known labextensions:
   app dir: C:\Users\yadav.111\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        arcgis-map-ipywidget v1.8.5 enabled  ok

(arcgispro-py3-clone) C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>

**To Reproduce**
```python
from arcgis.gis import GIS
gis = GIS()
map1 = gis.map()
map1
```
error:
```python
Error displaying widget: model not found```

**Comment by AtmaMani** [comment]
Could be the same as #1017

**Comment by CMPeng** [comment]
@bidhya Thanks for following up with us.
We have logged it an issue for future releases, and are working actively to have our api compatible with Jupyterlab3. For now, the restriction is to have jupyterlab >=2.0.0, but lower than 3.0.0
For now, please make sure the versions of your jupyter, jupyterlab, and the arcgis-map-ipywidget meet the requirements as mentioned in https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/

**Comment by owenlamont** [comment]
Any progress on this? Jupyter lab 4 has been out for several months now and I couldn't even build the lab extension without downgrading nodejs two major versions as they no longer build with the most recent one.

**Comment by CMPeng** [comment]
Hey @owenlamont Our team is still working on this issue, which is caused by the conflicts of openssl upgrades. Before the fix is out with the new map widget (not within 6 months), users are recommended to use jupyter notebook, with no jupyter lab support.
