### ISSUE TITLE
perdict_las not working on Linux

### ISSUE THREAD

**Issue by Morteza-Esfandiari** [Esri/arcgis-python-api#1007]
**Describe the bug**
I have trained PointCNN over the DALES dataset and I am trying to predict my own dataset (I have remapped the classes into ground and non-ground only).
The model gets trained and fits perfectly, however, I cannot predict any .las file. When I use predict_las function the .h5 files get generated but it suddenly stops and nothing happens. I also consider print_metrics as True and all the values are NaN. 
I saved the model and it works fine on my own computer (Windows 10), but I don't have GPU so basically, I cannot run it.

**To Reproduce**
I used the DALES dataset and I followed the same steps as provided in 
https://youtu.be/lD3_1tOs6H0
and
https://youtu.be/sSGBHHk9WGM

**Screenshots**
![11](https://user-images.githubusercontent.com/62145728/117736947-acb60280-b1ad-11eb-8806-a9d1d3f097fc.png)
![22](https://user-images.githubusercontent.com/62145728/117736955-af185c80-b1ad-11eb-97bf-777aeaa8c9a6.png)

**Platform (please complete the following information):**
 - Ubuntu 20.04 lts
 - Firefox
 - Python 3.7; arcgis.learn 1.8.5

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
