### ISSUE TITLE
Docker image referenced in install guide is not available

### ISSUE THREAD

**Issue by dstubbins** [Esri/arcgis-python-api#1008]
The docker image referenced in the install guide seems no longer to be available
https://hub.docker.com/r/esridocker/arcgis-api-python-notebook/

can it be updated or removed as an install option

**Comment by achapkowski** [comment]
@rwmajor2 and @mohi9282 can you please take a look.

**Comment by esristeinicke** [comment]
@dstubbins It seems the repo was changed from public to private.  This has been fixed. Can you please try again?

**Comment by dstubbins** [comment]
yep, thats fixed,
