### ISSUE TITLE
arcgispro-py3 missing bs4 by default

### ISSUE THREAD

**Issue by cdflint** [Esri/arcgis-python-api#1010]
The default arcgispro-py3 environment in ArcGIS Pro v2.8.0 is missing bs4 as required by arcgis\gis\_impl\_con\connection.py in _oauth_token(self)

Clone or use default arcgispro-py3 environment.

Attempt to connect to GIS enterprise portal or AGOL with locally stored credentials or similar means to trigger _oauth_token method.

error:
![image](https://user-images.githubusercontent.com/25038329/118815887-a8f64000-b87f-11eb-824e-be2135ca8b4f.png)

**Expected behavior**
authenticated access to GIS enterprise portal or AGOL with provided credentials.

**Platform (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Python API Version 1.8.5
 - ArcGIS Pro v2.8.0

**Additional context**
Interim measure install bs4==4.9.3 in cloned environment, however any further cloned env's will require this mitigation to ensure proper connectivity to GIS portal's or AGOL.  Without using administrator privilege's and editing the arcigspro-py3 env this cannot be done at the default environment and another authentication method should be used.

**Comment by AtmaMani** [comment]
@cdflint thanks for reporting. While you have the correct workaround, we will find if beautifulsoup can be added to the default env. We may have to work out the licensing aspects of including it in our software.

**Comment by AtmaMani** [comment]
I looked at the earlier conversations around this topic and we made a decision to remove it from the list of core dependencies since it is only required for oAuth interactive sign in workflows and also because it can be a big package. We are looking at an alternate solution for this workflow in the next version. So I will close this for now.

**Comment by AtmaMani** [comment]
Xref https://github.com/ArcGIS/geosaurus/issues/1105 and https://github.com/ArcGIS/geosaurus/pull/1394

**Comment by 77377** [comment]
Hi! The decision to leave out bs4 from the standard environment is as pity. 
Webscraping _is_ a common workflow to get Data into a GIS portal, and the lack of support for BeautifulSoup means that skripts and skript tools developed for AGOL or ArcGIS Pro using Beautifulsoup can't be published or used on a portal, or at least not without major pains. :(((
