### ISSUE TITLE
arcgis.geometry.areas_and_lengths() bugged on ArcGIS Online Notebooks?

### ISSUE THREAD

**Issue by wgrunberg** [Esri/arcgis-python-api#1011]
Is there a bug in the ArcGIS Online Notebook implementation (API v1.8.4 at posting time) of the arcgis.geometry.areas_and_lengths() function or is the API description missing vital information?

Through a lot of trial and error I figured out a set of parameters that ArcGIS Online Notebook Standard (no ArcPy) would accept:
- For length_unit it will only accept an ID number - e.g. 9002 - not esriSRUnit_Foot
- For area_unit it will only accept  a dictionary  - e.g. {"areaUnit" : "esriAcres"} - not an ID number or esriAcres

I could only get it to work with parameters formatted the following way:
See original post on the [ArcGIS API for Python Esri Community](https://community.esri.com/t5/arcgis-api-for-python-questions/arcgis-geometry-areas-and-lengths-bugged-on-arcgis-online/m-p/1060714#M6106) for code sample.

Re-posting here was recommended by Community MVP.

**Comment by CMPeng** [comment]
@wgrunberg Thanks for reporting the issue - information you provided is really helpful. We will start looking into the solutions, and will notify you once it is fixed.

**Comment by CMPeng** [comment]
@wgrunberg Please install the latest API, the bug has been fixed! Thanks for your reporting.
