### ISSUE TITLE
User provider property is None

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-python-api#1015]
**Describe the bug**
Whenever I try to access user "provider" property from user search results, I get "None" value:
https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#user

**To Reproduce**
```python
from arcgis.gis import GIS

portal_url = "https://myorgportal.company.com/portal"
portal_username = "admin"
portal_password = "foo"

ent_gis = GIS(portal_url, portal_username, portal_password, verify_cert=False)
portal_users = ent_gis.users.search('!esri_ & !admin', max_users=5)
for portal_user in portal_users:
    print(portal_user.username, portal_user.provider)
```
Does not return an error but the list below.
```python
user1 None
user2 None
user3 None
user4 None
user5 None
```
When I debug it, I can see that the provider property is filled by "arcgis" or "enterprise"  but I have to manually access the property in debugger so that it is "loaded" and properly printed.
There may be some lazy loading going on... ?

**Expected behavior**
I expect provider property to be filled.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 1.8.5
 
Thanks !

**Comment by jyaistMap** [comment]
Closing per above PR.
