### ISSUE TITLE
arcgis-map-ipywidget@1.8.5 is not compatible with the current JupyterLab version

### ISSUE THREAD

**Issue by powersparks** [Esri/arcgis-python-api#1017]
The python notebook extension works fine.. however, enabling the widget in Jupiter labs version 3.0.14 fails. 
I downgraded the Jupiter labs from 3.0.14 to 2.3.1 to install in a different conda environment. 
it's missing some of the nice code highlighting that comes with 3.0.14, and other things, so please fix this soon.

Maybe this is just a matter of testing to see if the version works in the latest build.

**Comment by CMPeng** [comment]
Hi @powersparks the jupyter labs (v=3.0.14) works on my local machine when I installed arcgis within anaconda (without Pro). Can you please provide more details to your repro case?
1. IS it on a Pro env? If yes, did you work on a cloned python env?
2. Have you tried updating your arcgis API version to the latest?
Thanks for your feedback!

**Comment by powersparks** [comment]
@CMPeng  thanks for the comments. This is not using arc Pro, and yes, I was using the latest at the time, so as of May 26th. The version number is hardcoded at 3.0. However, I am checking to see which version is out there today...

**Comment by CMPeng** [comment]
Hi @powersparks Thanks for following up with us. 
We have logged it an issue for future releases, and are working actively to have our api compatible with Jupyterlab3. For now, the restriction is to have jupyterlab >=2.0.0, but lower than 3.0.0

**Comment by achapkowski** [comment]
we do not support Jupyter Lab 3
