### ISSUE TITLE
JupyterLab and Jupyter Notebook static map mode option

### ISSUE THREAD

**Issue by powersparks** [Esri/arcgis-python-api#1020]
When sharing notebooks, the interactive map doesn't render for someone that just wants to read our notebooks without installing all of the packages. Analysis performed on the map can be done against the static arcgis server maps as a print task, however, this is a bit more involved and could be simplified.

```python
# I will try to come up with some examples that may just use the export webmap task as an option from arcgis server, then
# from this some more simplified pythonic methods can be derived to support the GIS method.
# The change would be implemented by a user using a new mode option
import arcgis
from arcgis.gis import GIS
map = ago_gis.map(location='USA', zoomlevel=3, mode='static-2d')
```
![image](https://user-images.githubusercontent.com/12630742/120021619-0298f180-bf87-11eb-8924-fdaaf2efd385.png)

**Comment by mohi9282** [comment]
@powersparks - thank you for suggesting the enhancement. One approach to generating a static map would be to use the [take_screenshot()](https://developers.arcgis.com/python/api-reference/arcgis.widgets.html?highlight=take_screenshot#arcgis.widgets.MapView.take_screenshot) method. The `set_as_preview` parameter, which defaults to True, will set the screenshot as a static image preview in the cell where the map widget is being displayed. You may set `output_in_cell=False` if you don't want to see another screenshot in the output area of the cell.

So, when the notebook is reopened you will see a static version of the map.

![image](https://user-images.githubusercontent.com/35741513/123176326-13c70800-d438-11eb-9a5e-d41bd9275ddb.png)

**Comment by powersparks** [comment]
Thank you so much.. that is what I needed.
