### ISSUE TITLE
The "import-toolbox" Code Generation For a Geoprocessing Service Parameter Fails: un-escaped default path name

### ISSUE THREAD

**Issue by powersparks** [Esri/arcgis-python-api#1022]
When using the import-toolbox, the code generation for a Geoprocessing Service breaks if the service provides a string default value, e.g., C:\file-path, that is not properly escaped, C:\\file-path or C:./file-path  

To reproduce, create a geoprocessing service with a parameter that contains a default value as a string, and add a file path with just one back slash.
 
<img width="1021" alt="Capture" src="https://user-images.githubusercontent.com/12630742/120358457-33886780-c2a2-11eb-9d75-79781e6d0a25.PNG">

<img width="1145" alt="Capture2" src="https://user-images.githubusercontent.com/12630742/120357623-5a926980-c2a1-11eb-9b59-96bc58597b01.PNG">

using verbose attribute to see the code generated was a huge help, but it took a bit to get here. Trapping the error, and responding back that an input has a bad default value would be ideal.

**Comment by achapkowski** [comment]
@powersparks unless the service is protected/hidden, the URL does not exist.

![image](https://user-images.githubusercontent.com/5131271/124171028-06cc9900-da76-11eb-8ed8-1ba531f88324.png)

**Comment by achapkowski** [comment]
@powersparks closing until we get a geoprocessing tool we can use to verify this issue.  If you can update the issue, please reopen.
