### ISSUE TITLE
Hyperlink to Constant References in API Documentation

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#105]
In the [`areas_and_lengths` documentation](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html#areas-and-lengths), it states:

> If calculation_type is planar, then length_unit can be any esriUnits constant. 

It would be really useful, handy even, if such references to "esriUnits constant" were actually hyperlinked to a listing and definition of those constants.  Since most users won't have the constants memorized, having a hyperlink to the appropriate documentation for those constants saves users from having to go hunt for them.

**Comment by achapkowski** [comment]
@bixb0012 for the next release v.1.4.1 we have re-written the doc for `Geometry`, hopefully this meets your needs.
