### ISSUE TITLE
Support all content items cloning and copy (especially when all hosted).

### ISSUE THREAD

**Issue by SavageTribe** [Esri/arcgis-python-api#1059]
**Need to add compatibility to all content item types especially when they are all hosted items.  ArcGIS Indoors, Scene Layers and more need to be able to copy, clone and export group package.  This is to support dev/test/prod environments.  Rollout is critical migrating from different environments that are isolated for purpose of testing and going to release.

```python
<insert your code here>
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by achapkowski** [comment]
@SavageTribe thank you for your feedback, we constantly update the `clone_items` tool as well as the group migration manager.  ArcGIS Online and ArcGIS Enterprise support 100s of item and items types.  For more complex items, like dashboards, webmaps, etc.. they have there own unique way of handling content.  So they take time to ensure we cover all cases.

That being said in future releases we plan on exposing a way for user to create and register new ```clone_items``` support types, so I we do not handle a specific Item yet, you can extend the code to fit your needs.

**Comment by achapkowski** [comment]
@SavageTribe I am closing this due to the generality of the request.  If you have specific types that you need, please let us know. The team is constantly working to ensure all types are cloned properly.

**Comment by SavageTribe** [comment]
I believe I wasn't general.  I asked that all items that Portal supports
are allowed to clone.  However, specifically mmpk files as well as indoors
category items should be supported since the deployment of this product is
dependant on the configuration and the mmpk file if using the ArcGIS
indoors apps.  I realize that this may be too hard to deal with since
adding in supported items probably wasn't maintained on a consistent
basis.  The addition in the code to accept other types seems to be a good
way to handle this but administrators need to be able to clone and copy
from one environment to the next.  I find it very hard to manage AGS
technologies when software deployment patterns are not honored.  In past
esri technologies, this wasn't as big problem and easier to remedy.  Gone
are the days of ArcIMS and we are subjected to multiple server technologies
that are more complex and less malleable.  This poses huge challenges on
the administration side.  I don't think we need to keep the ticket open as
there seems to be an upcoming soft solution.
