### ISSUE TITLE
missing properties in arcgis.gis user - im probably just not doing it right?

### ISSUE THREAD

**Issue by COFISDITGISBHopper** [Esri/arcgis-python-api#1063]
**Describe the bug**
 I am trying to write a script in python to query our enterprise portal users but I am running into an issue. in the arcgis.gis module I am looking through the User class and I am trying to get a complete list of properties, but I can't figure out how to do it.

https://developers.arcgis.com/python/api-reference/1.8.1/arcgis.gis.toc.html#user

On this site it says for example there should be a 'role', but when I put that into my query it says it cannot be found.

Do you have a way that I can query my own enterprise portal to see exactly what properties are available so I can add them into my script?

**To Reproduce**
```python
import csv
from datetime import datetime as dt
import pandas as pd
from arcgis.gis import *

gis = GIS("", "", "", verify_cert=False)

outputFile = r"C:\GIS\Exports\test.csv"

users = gis.users.search('*',  max_users=15000)

def local_time(TS):
    if len(str(TS)) == 10:
        ts = dt.fromtimestamp(int(TS)).strftime('%Y-%m-%d %H:%M:%S')
        return ts
    elif len(str(TS)) == 13:
        ts = dt.fromtimestamp(int(TS)/1000).strftime('%Y-%m-%d %H:%M:%S')
        return ts
    else:
        return TS

with open(outputFile, 'w', newline='', encoding='utf-8') as ResultFile:
    wr = csv.writer(ResultFile,)
    header = 'username', 'fullName', 'preferredView', 'description', 'email', 'idpUsername', 'lastLogin', 'mfaEnabled', 'access', 'storageUsage', 'storageQuota', 'orgId', 'disabled', 'units', 'tags', 'culture', 'cultureFormat', 'region', 'thumbnail', 'created', 'modified', 'groups', 'provider', 'id', 'role'
    wr.writerow(header)
    for user in users:
        UserRow = user.username, user.fullName, user.preferredView, user.description, user.email, user.idpUsername, local_time(user.lastLogin), user.mfaEnabled, user.access, user.storageUsage, user.storageQuota, user.orgId, user.disabled, user.units, user.tags, user.culture, user.cultureFormat, user.region, user.thumbnail, local_time(user.created), local_time(user.modified), user.groups, user.provider, user.id, user.role
        wr.writerow(UserRow)

```
error:
```python
AttributeError: 'User' object has no attribute 'role'
```
**Screenshots**

**Expected behavior**
I would expect it to allow me to see the user role

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Python API Version: 1.8.5

**Additional context**
I am trying to export a complete dataset from the User table in order to reconcile between our enterprise and our AGOL environments and use this information for many other purposes in data analytics.

**Comment by achapkowski** [comment]
Though `role` should exist, you can use the `getattr` to obtain something.  If it doesn't exist, you can set a default, like shown below.

```python
for user in gis.users.search():
    print(getattr(user, 'role', "NOT FOUND"))
```
