### ISSUE TITLE
exception in 'query' method of class FeatureLayer

### ISSUE THREAD

**Issue by erezu** [Esri/arcgis-python-api#1069]
**Describe the bug**
While trying to query layers with the query() method, I'm getting the following exception:
```python
  File "C:\miniconda3\envs\myenv\lib\site-packages\arcgis\features\layer.py", line 1699, in query
    params['where'] = f"{self.properties.objectIdField} > 0"
  File "C:\miniconda3\envs\myenv\lib\site-packages\arcgis\_impl\common\_mixins.py", line 82, in __getattr__
    raise AttributeError(
AttributeError: 'PropertyMap' instance has no attribute 'objectIdField'
```
The code assumes the existence of the key 'objectIdField' in the properties of any FeatureLayer, but in fact this key is missing
from the properties of many FeatureLayer instances.

**To Reproduce**
```python
layer = FeatureLayer('https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Property_and_Land_WebMercator/MapServer/51')
df = layer.query(where="1=1", as_df=True)
```
error:
```python
Traceback (most recent call last):
  File "C:\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-9cc5b81ddc06>", line 1, in <module>
    df = layer.query(where="1=1", as_df=True)
  File "C:\miniconda3\envs\myenv\lib\site-packages\arcgis\features\layer.py", line 1699, in query
    params['where'] = f"{self.properties.objectIdField} > 0"
  File "C:\miniconda3\envs\myenv\lib\site-packages\arcgis\_impl\common\_mixins.py", line 82, in __getattr__
    raise AttributeError(
AttributeError: 'PropertyMap' instance has no attribute 'objectIdField'
```

**Expected behavior**
The method should run without exceptions for any FeatureLayer, regardless of whether its properties has the key 'objectIdField'.
if this key is missing, one may have various ways to infer the name of the objectIdField (e.g. try the default name 'OBJECTID', search the fields for a field of type "esriFieldTypeOID").

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 1.9.0

**Comment by achapkowski** [comment]
This will be resolved in v1.9.1 of the ArcGIS API for Python.  Thank you for reporting this.

**Comment by mmachir** [comment]
I'm still seeing this issue in the Table class in v1.9.1. Can the fix be applied there too? Thanks!

**Comment by achapkowski** [comment]
Can you provide a url to test?

**Comment by mmachir** [comment]
My example isn't publicly accessible but this appears to be reproducible with the tables in the previous example, eg: 
https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Property_and_Land_WebMercator/MapServer/52

![error](https://user-images.githubusercontent.com/55209116/139707957-be61a60d-e1d4-40ac-9a85-659a3ee89ef8.PNG)

**Comment by achapkowski** [comment]
Ok, thank you

**Comment by AtmaMani** [comment]
@mmachir This will be addressed in the next release of the Python API
