### ISSUE TITLE
Unnecessarily Requiring Arguments With Optional Parameters

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#107]
I suspect what I say below applies to numerous modules, but I have only started poking around in arcgis.geometry module

I have found several functions in `arcgis.geometry` that unnecessarily require arguments when default parameters exist, `buffer` is one of them:
```python
>>> from arcgis import gis, geometry
>>>
>>> gis = gis.GIS()
>>>
>>> geom = {
...     "rings": [[[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]]],
...     "SpatialReference" : {"wkid": 3857}
... }
>>> pg = geometry.Polygon(geom)
>>>
>>> # call buffer passing arguments for non-default parameters
... geometry.buffer([pg], 3857, 100)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: buffer() missing 1 required positional argument: 'unit'
>>>
>>> # call buffer passing bogus argument for default parameters
... geometry.buffer([pg], 3857, 100, "")
[{"rings": [[[10.000100001692772, -100.67390000075102], [0, -100.67390000075102], [-8.715500000864267, 
-100.29080000147223], [-17.36479999870062, -99.14449999853969], [-25.881900001317263, 
-97.24359999969602], [-34.20199999958277, -94.60249999910593], ....,  [44.20199999958277, 
-94.60249999910593], [35.88190000131726, -97.24359999969602], [27.36479999870062, 
-99.14449999853969], [18.71559999883175, -100.29080000147223], [10.000100001692772, 
-100.67390000075102]]]}]
>>>
```
The [`buffer` documentation](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html#buffer) states for `unit`:

> If unit is not specified, the units are derived from bufferSR. If bufferSR is not specified, the units are derived from in_sr.

The documentation strongly implies `unit` is optional since it has a default value.  Additionally, passing an empty string to `unit` and having the function work verifies that `unit` has a default value because an empty string doesn't mean anything in terms of units.

Other `arcgis.geometry` functions that run into this same issue are `areas_and_lengths` and `lengths`, there may be others.

In Python, it is not idiomatic to require arguments for optional parameters.

**Comment by achapkowski** [comment]
@bixb0012 the doc strings will be updated in the next release. Let me know if you have more issues.
