### ISSUE TITLE
UNET name 'arcgis_os' is not defined

### ISSUE THREAD

**Issue by hermangeodesi** [Esri/arcgis-python-api#1072]
Hello everyone, I'm learning to use arcgis deep learning.
I'm processing Landuse Classification data with Arcgis on Google Colab using the UNET method.
but i have problem can't do modeling, and it shows UNET name 'arcgis_os' is not defined. How to solve it?
Thanks Before
![unet-problem](https://user-images.githubusercontent.com/25447604/127323258-2853c377-9189-4f9e-91b2-045469178a6c.PNG)

**Comment by achapkowski** [comment]
@priyankatuteja please take a look at this.

**Comment by AtmaMani** [comment]
@hermangeodesi what is your Python API version?
Do you still have this issue with v1.9.0?
