### ISSUE TITLE
Export log query hits 10000 record limit

### ISSUE THREAD

**Issue by phaakma** [Esri/arcgis-python-api#1073]
**Describe the bug**
Reading the documentation for the arcgis.gis.server.logs module (LogManager) found here:
https://developers.arcgis.com/python/api-reference/arcgis.gis.server.html#logmanager
The documentation makes no mention of limits when describing how to specify start and end times. The default is "the beginning of all logging".

In reality, a call using this query with the default options is likely to hit a 10,000 record api limit which is documented here:
https://developers.arcgis.com/rest/enterprise-administration/server/logsquery.htm

**To Reproduce**

from arcgis.gis import GIS
gis = GIS("home")
server = gis.admin.servers.list()[0]
logs = server.logs.query(start_time=None, end_time=None, level='DEBUG', export=True, out_path='c:/temp/logs.csv')

**Expected behavior**
Given that the ArcGIS Python API is a wrapper for the ArcGIS Enterprise api, I would have expected that it would abstract away multiple calls to the actual ArcGIS Enterprise api, retrieving logs a page at a time until the full extent of the requested time frame is cached locally before exporting it to a local file.

This should be possible, given that the ArcGIS Enterprise api documentation specifies a "hasMore" property of the response which is intended for this exact purpose.

For bonus points, I would like to see introduced a "maxRecordsToReturn" option for the log query in the Python API. This could even default to something like 10,000, and could be overwritten to either a value the user was comfortable with or to None if they do indeed want absolutely all records. Adding an option like this with a sensible default would allay any concerns that a default query might flood a server with requests. The Python API query would simply make repeated api calls until either all records within the specified timeframe have been returned or the "maxRecordsToReturn" parameter has been reached.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 1.8.5
 - ArcGIS Pro v2.8.1

**Comment by CMPeng** [comment]
@phaakma Thanks for reporting the issue, and our developers have been actively working on it. We will give you an update when the fix is out.

**Comment by nanaeaubry** [comment]
PR was merged for this and will be in next release.
