### ISSUE TITLE
ArcPy problems with ContourList_3d return bad features

### ISSUE THREAD

**Issue by pyGisServer** [Esri/arcgis-python-api#1075]
I need to get a series of contour lines from a list of contours. The problem is that when I pass it the complete list of values, it (sometimes) returns absurd contour lines that do not correspond to the reality of the terrain, that is, the curves generated for each contour do not correspond to what should be the same curve obtained from SurfaceContour_3d. Initially I thought that it was due to a resolution issue of the input raster (since the raster is obtained from a TIN), however, the most curious thing is that recently doing tests I have been able to see that if I pass a selection on contourlist the original list, yes it works correctly and returns the curves that it should be, but when I pass it the complete list, which encompasses the previous list, the tool crashes and returns only polyline portions.

For example, if I pass you the following list of values:
`value_list = [1.50350008526267, 1.5055376478469]
arcpy.sa.ContourList(InputTIN,Output,value_list)`
![image](https://user-images.githubusercontent.com/86069813/127650449-9bb54032-20f4-4c01-bbe9-4c49acaa123d.png)

However, if I pass the following list (which includes the previous one) and therefore the result should also include the previous curves, I get:
`value_list = [1.45387599477647, 1.45820584035361, 1.46114612935297, 1.463839263108, 1.46652564051677, 1.46920531637205, 1.47187846215324, 1.4745448819629, 1.47583307604114, 1.47642781023288, 1.47702220611008, 1.47761626587378, 1.47820998674251, 1.4788033708333, 1.47925516289341, 1.47955186164705, 1.47984847245458, 1.48014499588005, 1.48044143094131, 1.4807377793336, 1.48108054277813, 1.48153796159911, 1.48199517898435, 1.48245219356185, 1.4829090085609, 1.48336562210708, 1.48390503967914, 1.48520380944726, 1.48650101929254, 1.48779667709927, 1.48909078340382, 1.49038334846949, 1.49167437276326, 1.493600261993, 1.49558747040895, 1.49757099468877, 1.49955095317015, 1.50152732682082, 1.50350008526267, 1.5055376478469, 1.50759841485483, 1.50965526715546, 1.51170821570949, 1.51375735135489, 1.51580295122513, 1.51777822449097, 1.51968918494953, 1.52159701039515, 1.52350177707478, 1.5254032568809, 1.52730137588564, 1.52928349098205, 1.5314389831327, 1.53359020088427, 1.53573716768412, 1.53787989303559, 1.54001839970148, 1.54216364234912, 1.54437493249941, 1.54658174463956, 1.54878410302166, 1.55098201680991, 1.55317560705351, 1.55536470170427, 1.56341293292356, 1.57181571050639, 1.58015832771504, 1.58844202330731, 1.59666799246023]
arcpy.sa.ContourList(InputTIN,Output,value_list)`
![image](https://user-images.githubusercontent.com/86069813/127650580-fbd790e9-6464-4c6b-9bb4-3a603bb0d4df.png)

As you can see, the last output does not make any sense, at least, the latter should include the curves shown in the first image, however, despite being many more values ​​(including those used to obtain the first output), the result is totally different, it does not cover the previous ones and it does not correspond to the outputs obtained through SurfaceContour for the same values. I understand that it is an ArcPy bug.

Below I show both results in the same image for clarity:
![image](https://user-images.githubusercontent.com/86069813/127650625-40674b86-6e0f-4c10-a760-bf147f012543.png)

**Comment by achapkowski** [comment]
@pyGisServer for `arcpy`/Pro issues, please contact Esri Support.  This is the `ArcGIS API for Python` library.
