### ISSUE TITLE
data stores with colon symbol (:) in their name

### ISSUE THREAD

**Issue by azinsharaf** [Esri/arcgis-python-api#1093]
**Describe the bug**

`gis_server.datastores.list()` doesn't list the data store item if the item includes colon symbol (:) in its name. 

**To Reproduce**

```python
for gis_server in gis_servers:
    data_store_list = gis_server.datastores.list()
```
error:
 See the screenshots below

**Screenshots**

![image](https://user-images.githubusercontent.com/10101468/132418642-c9049c6d-3c3d-4e74-9a90-5fc2fa345362.png)

![image](https://user-images.githubusercontent.com/10101468/132418771-cf1bc002-c478-425a-9802-c5194cb71dc6.png)

**Expected behavior**
I expect to see the data store properties.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` 1.8.5

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by jyaistMap** [comment]
hi @azinsharaf - I'm investigating this but am unable to create a folder with a colon in it's name directly on my windows machine. What OS is on the machine with the colon in its name?  Did you use the API to add the datastore or server manager?

**Comment by azinsharaf** [comment]
hi @jyaistMap , I think you are creating the folder in windows explorer.  I have an existing folder in windows (a shared folder) which doesn't have colon in its name (for instance \\folder1\folder2 ). Then from ArcGIS Server Manager interface, Site > Data Stores > Register Folder > name = "K: GIS" and Publisher Folder Path = "\\folder1\folder2". It adds/registers the folder in ArcGIS Server Manager and it works fine in ArcGIS Server. But when I read that through ArcGIS API for Python it doesn't recognize it because of colon in name.

**Comment by jyaistMap** [comment]
Thanks @azinsharaf -  this should be fixed at the next release. When I run a test on the latest development version I see this:
![image](https://user-images.githubusercontent.com/1399179/141214054-96822808-3644-4081-906e-2574af12aee3.png)

**Comment by azinsharaf** [comment]
thanks for checking. Are you able to reproduce it in arcgis 1.8.5?

**Comment by jyaistMap** [comment]
I'm not actually. I'm running this on a mac...let me try Windows

![image](https://user-images.githubusercontent.com/1399179/141215686-31dec581-0f37-4673-b7f4-37606ec05dc3.png)

**Comment by jyaistMap** [comment]
I'm able to get it to work in Windows, too:

![image](https://user-images.githubusercontent.com/1399179/141218443-754a759c-aaa2-4c89-a88c-060491621298.png)

**Comment by azinsharaf** [comment]
interesting. Could be an issue on my side then. Thanks for checking again.

**Comment by jyaistMap** [comment]
No problem. Let me know if you think it's the API I can retest.
