### ISSUE TITLE
How to write YOLO or U-Net Deep Learning code  which is integrated with RasterFrames? 

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [Esri/arcgis-python-api#1095]
Hi,
        I have read the RasterFrames supervised machine learning on the page of "https://rasterframes.io/supervised-learning.html", now I would like to implement Deep Learning similar to “supervised machine learning”, such as "YOLO object detection" and "U-Net semantic segmentation". 
        However, I am so confused about how to write YOLO or U-Net Deep Learning code  which is integrated with RasterFrames? So, would you pls help to give me some suggestions? Many Thanks!

**Comment by AtmaMani** [comment]
@rhea-j could you help answer this question?

**Comment by rhea-j** [comment]
@JenniferYingyiWu2020 I haven't worked with RasterFrames before, but did you try looking into this - https://rasterframes.io/unsupervised-learning.html
