### ISSUE TITLE
GeoAccessor.from_geodataframe() mangles geometries

### ISSUE THREAD

**Issue by manuela-butuc** [Esri/arcgis-python-api#1096]
**Describe the bug**
Using GeoAccessor.from_geodataframe() results in mangled geometries. It seems to happen on more complex polygons with many holes.

**To Reproduce**
```python
import geopandas as gpd
from arcgis import GIS
import requests
from arcgis.features import GeoAccessor


gis=GIS("https://arcgis.com",username, password)

base_url = 'https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/DoD_Sites_Boundaries_Public/FeatureServer/0/query'

payload = {
'f': 'geojson',
'where': "SITE_NAME='Eglin Air Force Base'",
'outSR': 4326,
'outFields': '*'
}
response = requests.get(base_url, params=payload)

gdf=gpd.GeoDataFrame.from_features(response.json()['features'], crs="epsg:4326")

sedf=GeoAccessor.from_geodataframe(gdf, column_name="geometry")

lyr = sedf.spatial.to_featurelayer('test_poly')
```

**Screenshots**
Source data:
![image](https://user-images.githubusercontent.com/62720212/134193177-34523ce6-a5d9-4134-be74-b9b14b1dbd3d.png)
After converting to a Spatially Enabled dataframe:
![image](https://user-images.githubusercontent.com/62720212/134193389-572674fa-eb36-4cd6-94e1-cc7c29e600d5.png)
A closeup:
![image](https://user-images.githubusercontent.com/62720212/134218248-630d918a-3965-4906-ad58-801d4990f5bc.png)
Result:
![image](https://user-images.githubusercontent.com/62720212/134218323-572c78b8-a4ca-4112-9818-48a7b2f6bf2d.png)

**Expected behavior**
I expect the geometries to stay the same.

**Platform:**
 - OS: Windows 10
 - Browser: Chrome
 - Python API Version: 1.8.5

**Additional context**
I tried the .buffer(0) method before converting to SEDF - didn't work. I tried the make_valid() function from shapely.validation too, same result. Filling holes before converting to a spatially enabled dataframe worked, but it is not an acceptable solution.

**Comment by davidgrubmanchoicehotels** [comment]
Having same issues with complex geometries! Thank you for looking into it.

**Comment by davidgrubmanchoicehotels** [comment]
Just for context, I have pretty much the same exact code as @manuela-butuc. Here is a screenshot of trying to upload the Census Subdivisions through a geodataframe and the sedf=GeoAccessor.from_geodataframe(gdf, column_name="geometry") command.

![image](https://user-images.githubusercontent.com/87661547/140844766-9d321086-eba6-467e-981d-7770473a7568.png)


It does look kinda cool I must say.

**Comment by manuela-butuc** [comment]
@davidgrubmanchoicehotels that is a piece of art 
Not sure what your use case it, but are looking for a workaround and just want to append to an existent feature layer in AGOL, follow this thread I opened before posting here: https://community.esri.com/t5/arcgis-api-for-python-questions/converting-geodataframe-to-spatially-enabled/m-p/1099998#M6667

**Comment by achapkowski** [comment]
We do have a solution for this in v2 coming out in January.

**Comment by achapkowski** [comment]
2.0 is release, please test.

**Comment by manuela-butuc** [comment]
I still have the same issue. 
![image](https://user-images.githubusercontent.com/62720212/156797791-6ab66d09-9204-4ec1-bd5f-c6d0377f21e5.png)

**Comment by achapkowski** [comment]
@manuela-butuc can you post your geometry for the geojson here?

**Comment by manuela-butuc** [comment]
@achapkowski The mangled one or the original? You can get both by running the snippet provided above. Are you unable to reproduce the bug?
