### ISSUE TITLE
Convert README.txt to Markdown

### ISSUE THREAD

**Issue by abxhr** [Esri/arcgis-python-api#1099]
**Is your feature request related to a problem? Please describe.**
The text information provided at `arcgis-python-api/samples/` from `README.txt`, doesn't allow user accessibility to click on each of the sample, to redirect them to that notebook. Converting the `README.txt` file to a markdown file, will allow the information to be represented better.

**Describe the solution you'd like**
Converting `README.txt` to `README.md` in `arcgis-python-api/samples/`

**Describe alternatives you've considered**

**Additional context**

**Comment by AtmaMani** [comment]
Merged, thank you.
