### ISSUE TITLE
_DeepCloner: Data error for selectors, indicators & charts when cloning a dashboard and mapping to a new source layer

### ISSUE THREAD

**Issue by andretheronsa** [Esri/arcgis-python-api#1111]
**Describe the bug**
I would like to clone a dashboard and maintain it's layout but map the data source to a new feature class (in AGOL).
When using ```clone_items``` with ```item_mapping``` The WebMap is successfully cloned and mapped to the new feature service, but selectors, indicators & charts are broken.

**To Reproduce**
```python
from arcgis.gis import GIS, Item

# Connect to your portal - you can use different source / target GIS here
# to move between portal
source_and_target_gis = GIS(client_id="")

# The Template dashboard that references the layer and webmap to clone
template_dashboard_item_id: str  = ''
# The target folder in portal to copy dashboard to
target_folder_name: str  = ''
# Map referenced item IDs from source to their new targets
# Any referenced item not mapped will be copied over
# Layer is the FC referenced by the webmap & dashboard
source_layer_item_id: str = ''
target_layer_item_id: str  = ''
source_webmap_item_id: str  = ''
target_webmap_item_id: str  = ''

# Clone the dashboard to the specified GIS & folder and map webmap and source layer there
template_dashboard_item: Item = source_and_target_gis.content.get(template_dashboard_item_id)
cloned_dash = source_and_target_gis.content.clone_items(
    items=[template_dashboard_item],
    folder=target_folder_name,
    copy_data=False,
    item_mapping={
        source_layer_item_id: target_layer_item_id,
        source_webmap_item_id: target_webmap_item_id
    }
)

```
error:
No Python exceptions - in dashboard we find "Data source error"

**Screenshots**

Working dashboard used as a template
![working_dash](https://user-images.githubusercontent.com/33958609/137714820-f1e55ab8-e5a0-4afd-8d0e-38e4b439607f.png)

Cloned dashboard with indicator, selector and chart's data source broken even though it was mapped to a new source
![broken_dash](https://user-images.githubusercontent.com/33958609/137714872-6a7cebcb-8960-4d60-909b-1142b9c0c29f.png)

The same happens to a webapp
![broken_webapp](https://user-images.githubusercontent.com/33958609/137714884-0dc0e1da-5329-4ad1-b652-02bedaec9fce.png)

**Expected behavior**
I expect a cloned dashboard/WebApp with a new data source to have working indicator, selector, infographic, charts.

**Platform (please complete the following information):**
 - Windows 10
 - Python 3.9.5
 - Browser: All (AGOL)
 - Python API Version: 1.9.1

**Additional context**
We found the same behavior when cloning a WebApp - it's infographics do not get remapped.

**Comment by achapkowski** [comment]
In regards to cloning v.2.0.0 you can custom cloner to handle the Dashboard app.  By design, we do not update the dashboard URLs.  To update manually, you can pull down the JSON by using item.get_data().  Once updated, then you can call item.update(text=<modified text>).
