### ISSUE TITLE
Getting KeyError as "assignments" when using workforce with geoprocessing tool

### ISSUE THREAD

**Issue by fatihenesusta** [Esri/arcgis-python-api#1129]
Hello,

I created a toolbox that works in local server but i could not make it work as a geoprocessing service.

My idea is that i want to be able to reach to workforce through using ArcGIS API and want to make operations over there by using the tool i created. It works without a problem on the ArcGIS Pro, but when i publish it as a geoprocessing device i get the following error.

Traceback (most recent call last): File "", line 71, in execute File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 45, in init self._assignment_schema = AssignmentSchema(self.assignments_layer) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis_impl\common_utils.py", line 158, in _lazy_property setattr(self, attr_name, fn(self)) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 233, in assignments_layer return FeatureLayer(self.assignments_layer_url, self.gis) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\apps\workforce\project.py", line 183, in assignments_layer_url return self._item_data['assignments']['url'] KeyError: 'assignments' Failed to execute (Tool). Failed to execute (Tool). Failed.

What could be the reason?

**Comment by AtmaMani** [comment]
@fatihenesusta can you share the layer using for the Workforce project and the code for your toolbox? It is difficult to debug without that info

**Comment by fatihenesusta** [comment]
`# -*- coding: utf-8 -*-

import arcpy
import pandas as pd
import arcgis



class Toolbox(object):
    def __init__(self):
        """Define the toolbox (the name of the toolbox is the name of the
        .pyt file)."""
        self.label = "Toolbox"
        self.alias = "Toolbox"

        # List of tool classes associated with this toolbox
        self.tools = [Tool]
    

class Tool(object):
    def __init__(self):
        """Define the tool (tool name is the name of the class)."""
        self.label = "Tool"
        self.description = ""
        self.canRunInBackground = True
        

    def getParameterInfo(self):
        cikti = arcpy.Parameter(
            displayName = "name of the workforce project",
            name = "cikti",
            datatype = "GPString",
            parameterType = "Derived",
            direction = "Output")
        
        params = [cikti]
        
        return params

    def isLicensed(self):
        """Set whether tool is licensed to execute."""
        return True

    def updateParameters(self, parameters):
        return

    def updateMessages(self, parameters):
        """Modify the messages created by internal validation for each tool
        parameter.  This method is called after internal validation."""
        return
    
    def execute(self, parameters, messages):
        gis = arcgis.gis.GIS("gis url", "login id ", "login pw")
        item = gis.content.get("57a0e3c7afcf4f5a977f4c64c07251b4")
        project = arcgis.apps.workforce.Project(item)
        adi = project.title
        gorevler = project.assignment_types.search()

        arcpy.SetParameter(0, gorevler)

        
        return
`

Here is the link to the project: https://www.arcgis.com/apps/workforce/projects/57a0e3c7afcf4f5a977f4c64c07251b4/dispatch/assignments

So i would like to clarify for one last time. I publish the tool from my ArcGIS Enterprise server version 10.8.1. as a geoprocessing server. It works with the ArcGIS Pro as a toolbox but when i turn it into geoprocessing server i get the error.

**Comment by fatihenesusta** [comment]
> `# -_- coding: utf-8 -_-
> 
> import arcpy import pandas as pd import arcgis
> 
> class Toolbox(object): def **init**(self): """Define the toolbox (the name of the toolbox is the name of the .pyt file).""" self.label = "Toolbox" self.alias = "Toolbox"
> 
> ```
>     # List of tool classes associated with this toolbox
>     self.tools = [Tool]
> ```
> 
> class Tool(object): def **init**(self): """Define the tool (tool name is the name of the class).""" self.label = "Tool" self.description = "" self.canRunInBackground = True
> 
> ```
> def getParameterInfo(self):
>     cikti = arcpy.Parameter(
>         displayName = "name of the workforce project",
>         name = "cikti",
>         datatype = "GPString",
>         parameterType = "Derived",
>         direction = "Output")
>     
>     params = [cikti]
>     
>     return params
> 
> def isLicensed(self):
>     """Set whether tool is licensed to execute."""
>     return True
> 
> def updateParameters(self, parameters):
>     return
> 
> def updateMessages(self, parameters):
>     """Modify the messages created by internal validation for each tool
>     parameter.  This method is called after internal validation."""
>     return
> 
> def execute(self, parameters, messages):
>     gis = arcgis.gis.GIS("gis url", "login id ", "login pw")
>     item = gis.content.get("57a0e3c7afcf4f5a977f4c64c07251b4")
>     project = arcgis.apps.workforce.Project(item)
>     adi = project.title
>     gorevler = project.assignment_types.search()
> 
>     arcpy.SetParameter(0, gorevler)
> 
>     
>     return
> ```
> 
> `
> 
> Here is the link to the project: https://www.arcgis.com/apps/workforce/projects/57a0e3c7afcf4f5a977f4c64c07251b4/dispatch/assignments
> 
> So i would like to clarify for one last time. I publish the tool from my ArcGIS Enterprise server version 10.8.1. as a geoprocessing server. It works with the ArcGIS Pro as a toolbox but when i turn it into geoprocessing server i get the error.

`# -- coding: utf-8 --

import arcpy
import pandas as pd
import arcgis

class Toolbox(object):
def init(self):
"""Define the toolbox (the name of the toolbox is the name of the
.pyt file)."""
self.label = "Toolbox"
self.alias = "Toolbox"

    # List of tool classes associated with this toolbox
    self.tools = [Tool]
class Tool(object):
def init(self):
"""Define the tool (tool name is the name of the class)."""
self.label = "Tool"
self.description = ""
self.canRunInBackground = True

def getParameterInfo(self):
    cikti = arcpy.Parameter(
        displayName = "name of the workforce project",
        name = "cikti",
        datatype = "GPString",
        parameterType = "Derived",
        direction = "Output")
    
    params = [cikti]
    
    return params

def isLicensed(self):
    """Set whether tool is licensed to execute."""
    return True

def updateParameters(self, parameters):
    return

def updateMessages(self, parameters):
    """Modify the messages created by internal validation for each tool
    parameter.  This method is called after internal validation."""
    return

def execute(self, parameters, messages):
    gis = arcgis.gis.GIS("gis url", "login id ", "login pw")
    item = gis.content.get("57a0e3c7afcf4f5a977f4c64c07251b4")
    project = arcgis.apps.workforce.Project(item)
    adi = project.title
    gorevler = project.assignment_types.search()

    arcpy.SetParameter(0, gorevler)

    
    return
`

Here is the link to the project: https://www.arcgis.com/apps/workforce/projects/57a0e3c7afcf4f5a977f4c64c07251b4/dispatch/assignments

So i would like to clarify for one last time. I publish the tool from my ArcGIS Enterprise server version 10.8.1. as a geoprocessing server. It works with the ArcGIS Pro as a toolbox but when i turn it into geoprocessing server i get the error.

**Comment by fatihenesusta** [comment]
> @fatihenesusta can you share the layer using for the Workforce project and the code for your toolbox? It is difficult to debug without that info

`# -- coding: utf-8 --

import arcpy
import pandas as pd
import arcgis

class Toolbox(object):
def init(self):
"""Define the toolbox (the name of the toolbox is the name of the
.pyt file)."""
self.label = "Toolbox"
self.alias = "Toolbox"

    # List of tool classes associated with this toolbox
    self.tools = [Tool]
class Tool(object):
def init(self):
"""Define the tool (tool name is the name of the class)."""
self.label = "Tool"
self.description = ""
self.canRunInBackground = True

def getParameterInfo(self):
    cikti = arcpy.Parameter(
        displayName = "name of the workforce project",
        name = "cikti",
        datatype = "GPString",
        parameterType = "Derived",
        direction = "Output")
    
    params = [cikti]
    
    return params

def isLicensed(self):
    """Set whether tool is licensed to execute."""
    return True

def updateParameters(self, parameters):
    return

def updateMessages(self, parameters):
    """Modify the messages created by internal validation for each tool
    parameter.  This method is called after internal validation."""
    return

def execute(self, parameters, messages):
    gis = arcgis.gis.GIS("gis url", "login id ", "login pw")
    item = gis.content.get("57a0e3c7afcf4f5a977f4c64c07251b4")
    project = arcgis.apps.workforce.Project(item)
    adi = project.title
    gorevler = project.assignment_types.search()

    arcpy.SetParameter(0, gorevler)

    
    return
`

Here is the link to the project: https://www.arcgis.com/apps/workforce/projects/57a0e3c7afcf4f5a977f4c64c07251b4/dispatch/assignments

So i would like to clarify for one last time. I publish the tool from my ArcGIS Enterprise server version 10.8.1. as a geoprocessing server. It works with the ArcGIS Pro as a toolbox but when i turn it into geoprocessing server i get the error.

**Comment by fatihenesusta** [comment]
I upgraded the server to the latest version of enterprise and i was able to overcome the issue. 

Thanks.
