### ISSUE TITLE
How to use customized CNN models by  classify-pixels-using-deep-learning tool in ArcGIS Pro?

### ISSUE THREAD

**Issue by LinoSun** [Esri/arcgis-python-api#1131]
**Is your feature request related to a problem? Please describe.**
How to use customized CNN models by  classify-pixels-using-deep-learning tool in ArcGIS Pro?

**Describe the solution you'd like**
I trained a customized CNN model and I want to use my  customized model in ArcGIS Pro.Is there any way to use customized CNN model to infer by classify-pixels-using-deep-learning tool in ArcGIS Pro? It is very imported to us, thank you very much all for any suggestions.

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
