### ISSUE TITLE
Sample for Publishing Hosted Table in ArcGIS Online

### ISSUE THREAD

**Issue by pmacMaps** [Esri/arcgis-python-api#1132]
I am trying to automate a process to do the following:

1. Add an empty hosted table with pre-defined schema to ArcGIS Online
2. Generate an ArcGIS Online credits report
3. Iterate over the generated report (CSV), and populate the empty table

I have been able to figure out no. 2 and no. 3.  However, after much searching, I can't find any samples or clear guidance on how to create/add/publish a hosted table in ArcGIS Online using the Python API.  The closest thing I found was [ArcGIS Pro help](https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/share-standalone-table.htm) for a manual process.

Having a sample for automating creating hosted tables would be very beneficial.  Thanks for the consideration.

**Comment by achapkowski** [comment]
Thank you for the suggestion, we'll take a look at adding a sample.

**Comment by achapkowski** [comment]
Here is some code to get you by until we get the sample up:

```
csv_item = gis.content.get('<some csv table item id>')
analyzed = gis.content.analyze(item=csv_item)
pp = analyzed['publishParameters']
pp['name'] = 'AVeryUniqueName' # this needs to be updated
pp['locationType'] = None # this makes it a hosted table
published_item = csv_item.publish(pp)
```

**Comment by achapkowski** [comment]
A sample usage will be on Item.publish() in v2.0.1. Thank you for reporting this.
