### ISSUE TITLE
Can't Access PortalDataStore Class

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#1135]
**Describe the bug**
First time trying to use PortalDataStore.

Using arcgis v1.9.1 I am unable to access/use the PortalDataStore class. In the documentation the stated way to access is arcgis.gis._impl._datastores.PortalDataStore(url,gis), but _datastores is not recognized. I get the error AttributeError: module 'arcgis.gis._impl' has no attribute '_datastores'.

Only methods I see available are ['APIKey', 'APIKeyManager', 'CertificateManager', 'StatusJob', '_search']

**To Reproduce**
```python
<import arcgis.gis

portal = arcgis.gis.GIS("portal site url", "admin user", "admin user password")
datastore = arcgis.gis._impl._datastores.PortalDataStore('item url of datastore item', portal)>
```
error:
```python
<AttributeError: module 'arcgis.gis._impl' has no attribute '_datastores'.>
```

**Comment by achapkowski** [comment]
use gis.datastore instead.
