### ISSUE TITLE
Export Web Map fails if print service task is not named 'Export Web Map Task'

### ISSUE THREAD

**Issue by mhogeweg** [Esri/arcgis-python-api#1138]
**Describe the bug**
If the print service has a task with name other than 'Export Web Map Task' arcgis.mapping.export_map fails with a bad URL message.

**To Reproduce**
publish a print service with a task name other than 'Export Web Map Task' (ensuring the other name is not the same length.

in _utils.py the code to get the URL of the print service to use for printing is as follows:
```
    url = gis.properties.helperServices.printTask.url[:-len('/Export%20Web%20Map%20Task')]
```
...
 _use_async, url) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\docxtpl-arcgispro-py3\Lib\site-packages\arcgis\geoprocessing\_support.py", line 360, in _execute_gp_tool resp = gptool._con.post(exec_url, gp_params, token=gptool._token) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\docxtpl-arcgispro-py3\Lib\site-packages\arcgis\_impl\connection.py", line 1177, in post self._handle_json_error(resp_json['error'], errorcode) File "C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\bin\Python\envs\docxtpl-arcgispro-py3\Lib\site-packages\arcgis\_impl\connection.py", line 1198, in _handle_json_error raise RuntimeError(errormessage) RuntimeError: Invalid URL (Error Code: 400) 
```

**Expected behavior**
If the point is to get the service URL from the task name, then there are better ways in python that do not depend on the specific name of the task. Just drop everything after and including the last /.

**Comment by AtmaMani** [comment]
@mhogeweg thanks for reporting this. It looks like a bug. I will add it to our internal repo for tracking.

**Comment by achapkowski** [comment]
@mhogeweg we are addressing this issue in v2.0.1.
