### ISSUE TITLE
Problem w/ api_key => Exception: Token Required (Error Code: 499)

### ISSUE THREAD

**Issue by micdup** [Esri/arcgis-python-api#1145]
**Describe the bug**
Different behavior between api_key/user auth against different ImageServer services:
- https://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer
  - using user/password: _ok_
  - using api_key: _ok_
- https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer
  - using user/password: _ok_
  - using api_key: **ko**

**To Reproduce**
```python
from arcgis import GIS
from arcgis.raster import ImageryLayer
from arcgis.raster.functions import extract_band

gis = GIS(api_key="<API_KEY>")
img_layer = ImageryLayer(url="https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer", gis=gis)
layer = extract_band(img_layer, None)
lon_min, lat_max, lon_max, lat_min = (1.34, 49.85, 3.34, 47.85)
layer.extent = {"ymin": lat_min, "ymax": lat_max, "xmin": lon_min, "xmax": lon_max, "spatialReference": 4326}
raster = layer.export_image(export_format="tiff")
print(raster)
```
error:
```python
Traceback (most recent call last):
  File "./arcgis/github-issue-error-499.py", line 15, in <module>
    raster = layer.export_image(export_format="tiff")
  File "./venv/lib/python3.9/site-packages/arcgis/raster/_layer.py", line 2061, in export_image
    return self._con.post(url, params, token=self._token, timeout=None)
  File "./venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 1074, in post
    return self._handle_response(
  File "./venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 625, in _handle_response
    self._handle_json_error(data["error"], errorcode)
  File "./venv/lib/python3.9/site-packages/arcgis/gis/_impl/_con/_connection.py", line 648, in _handle_json_error
    raise Exception(errormessage)
Exception: Token Required
(Error Code: 499)
```

**Platform (please complete the following information):**
 - OS: Mac+Linux
 - Python 3.9
 - Python API Version 1.9.1

**Additional context**
- similar to https://github.com/Esri/arcgis-python-api/issues/776

**Comment by micdup** [comment]
any support there?

**Comment by achapkowski** [comment]
Is the key scoped to use these services?

**Comment by micdup** [comment]
key is correctly scoped,
confirmed problem is 100% related to api by debugging and checking the exact POST request where it fails,
it doesn't reuse api token and if i force it into POST request it will work.

**Comment by micdup** [comment]
could be related: release notes for 2.0.0 mentions a fix to similar problem on FeatureLayer [https://github.com/Esri/arcgis-python-api/commit/36510942704528ae7ee38e4c018b4051c9578c7a](https://github.com/Esri/arcgis-python-api/commit/36510942704528ae7ee38e4c018b4051c9578c7a)

also, could you try running code provided in issue and share your results please?

**Comment by achapkowski** [comment]
Have you tested it in 2.0.0?

**Comment by achapkowski** [comment]
The service is not supported by API Keys: https://developers.arcgis.com/documentation/mapping-apis-and-services/service-endpoints/

**Comment by pierresouchay** [comment]
@achapkowski Not clear to me, as the endpoint works when adding the token, looks more like an API bug...
