### ISSUE TITLE
Mapping and Visualization Guide doesn't cover how to use 3rd party basemaps in MapWidget

### ISSUE THREAD

**Issue by nickpeihl** [Esri/arcgis-python-api#115]
https://github.com/Esri/arcgis-python-api/blob/master/guide/09%20Mapping%20and%20visualization/Using%20the%20map%20widget.ipynb

The last entry in this notebook shows how to search for 3rd party basemaps, but it doesn't say how to set your mapwidget basemap to one of these. I suspect it isn't possible in the `MapWidget` class since the `MapWidget.basemap` property expects a string (like 'topo', 'gray', etc) rather than a webmap `Item` class.

**Comment by achapkowski** [comment]
@nickpeihl there should be enhanced support for this in the next release.
