### ISSUE TITLE
Documentation Issue: create Groups states wrong parameter

### ISSUE THREAD

**Issue by geohaupt** [Esri/arcgis-python-api#1150]
**Describe the bug**
The documentation within arcgis.gis module -> Group Manager -> create() states the 'provider_group_name' to define the name of the domain group. When executed this parameter is ignored. This applies to create() and to create_from_dict(). 
No error or failure when executing, the parameter is ignored. 

![image](https://user-images.githubusercontent.com/3504834/150085673-450f729b-4745-4516-9160-94e701b163fd.png)

**Expected behavior**
The group should be created as a Enterprise group with links to the domain group. 

We did some digging and checked the rest call when creating the group manually. We found out that the parameter is 'providerGroupName' instead. The create_from_dict() function accepts it when used as a paremter. Therefore the documentation is wrong. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge
 - Python API Version: 1.9.1

Cheers

**Comment by nanaeaubry** [comment]
@geohaupt Hello, we will look into this thank you.

**Comment by nanaeaubry** [comment]
@geohaupt This parameter works when tested with arcgis 2.0.0.
When you specify the provider_group_name, you must also specify the provider parameter for it to be registered. If one is specified and not the other, then it gets ignored.
