### ISSUE TITLE
layer.query() with Geometry filters returns incomplete results.

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#1168]
Running a layer.query() with a Geometry filter returns only some of the expected records.
![image](https://user-images.githubusercontent.com/889468/152150402-3e983cb4-6332-4edb-bdd7-20e34213a626.png)

**To Reproduce**
Query a layer using a Geometry filter:

```python
import arcgis

# Polylines
GEOM = {"paths":[[[265091.207,6637610.73],[265066.57,6637626.64],[265058.70,6637658.92],[265051.398,6637692.902],[265048.31,6637728.14],[265045.603,6637765.623]],
[[265126.08,6637725.828],[265133.88,6637735.42],[265127.43,6637771.09]]],"spatialReference":{"wkid":25833,"latestWkid":25833}}

_gis = arcgis.GIS('pro')
_parcels = arcgis.gis.Item(_gis, '577566e7970e4f9fa53f1afb58c43178')
_myfilter = arcgis.geometry.filters.intersects(GEOM)
_res = _parcels.layers[0].query(
    geometry_filter=_myfilter,
    out_fields="kommunenr,gardsnr,bruksnr",
    geometry_precision=2,
    distance=5,
    units="esriSRUnit_Meter")

print(len(_res))
```

The problem seems to be that the API does a recordcount and uses it to set max_records in the query. After changing from record_count to max_records at line 1795 in `features/layer.py` all intersecting parcels are returned from the service.

![image](https://user-images.githubusercontent.com/889468/152154514-f7c28816-c45c-402d-84e1-871d157df997.png)

**Expected behavior**
All intersecting parcels should be returned in the result.

**Platform (please complete the following information):**
 - Python API Version: 1.9.1
 - AGE Enterprise 10.8.1

**Comment by HakonD** [comment]
The bug also applies to API 2.0.0
![image](https://user-images.githubusercontent.com/889468/152306491-d855731c-0869-4b9a-bc80-b9fb661d3c1c.png)

**Comment by achapkowski** [comment]
@HakonD thank you for reporting

**Comment by HakonD** [comment]
I've explored this a bit further, it seems it's not a bug in the Python API per se, but rather hits a known bug in the REST API. There are several bugs on this behavior, like BUG-000142440 "The Query operation on a referenced feature layer with a polygon geometry type returns unexpected results if it is not using the envelope-shaped geometry input and Result Record Count is specified." 

It only affects some services, depending of the underlying database, so services running on fgdbs or hosted feature services are not affected.

Anyway, I will suggest you don't set the feature count parameter when there are a spatial filter.

**Comment by achapkowski** [comment]
@HakonD thanks for the added information!  This will help us.

**Comment by achapkowski** [comment]
confirmed it is a server side bug, I'm going to close this issue.  Thank you for reporting this.

**Comment by HakonD** [comment]
@achapkowski Still, as long as this server side bug exists I will argue that the Python API should not add a feature count parameter when there are a spatial filter, or at least you should not override the result_record_count set by the user if any.

**Comment by chilipepperpizza** [comment]
> @achapkowski Still, as long as this server side bug exists I will argue that the Python API should not add a feature count parameter when there are a spatial filter, or at least you should not override the result_record_count set by the user if any.

I second this, it's annoying having to modify this package in order for it to work correctly. Could this issue get opened back up so  this gets corrected?
