### ISSUE TITLE
Arcgis + Python developer salary

### ISSUE THREAD

**Issue by thgbrb** [Esri/arcgis-python-api#1170]
Hi all, quick question :) what is the salary of experiencied Python developer with strong knowledge and experience within Arcgis?

**Comment by AtmaMani** [comment]
@thgbrb while this is an important question, it is outside the scope of what we use this repo for. I recommend you visit https://community.esri.com/t5/gis-jobs/gh-p/gis-jobs and post your question there. You might even find existing posts on this topic that you can use. Closing this issue.
