### ISSUE TITLE
arcgis.geometry.Geometry.from_shapely() method throws error

### ISSUE THREAD

**Issue by drclanc-oss** [Esri/arcgis-python-api#1173]
**Describe the bug**
`arcgis.geometry.Geometry` has a `.from_shapely()` method. That method is broken and throws a `NameError: name '_HASSHAPELY' is not defined` error. 

**To Reproduce**
```python
import arcgis
import shapely
from shapely.geometry import Polygon

poly = Polygon(((0., 0.), (0., 1.), (1., 1.), (1., 0.), (0., 0.)))
arcgis.geometry.Geometry.from_shapely(poly)
```
error:
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [3], in <module>
----> 1 arcgis.geometry.Geometry.from_shapely(poly)

File ~\AppData\Local\pypoetry\Cache\virtualenvs\cse-geo-helpers-kflH7NS5-py3.9\lib\site-packages\arcgis\geometry\_types.py:878, in Geometry.from_shapely(cls, shapely_geometry, spatial_reference)
    846 @classmethod
    847 def from_shapely(cls, shapely_geometry, spatial_reference=None):
    848     """
    849     Creates a Python API Geometry object from a Shapely geometry object.
    850 
   (...)
    876 
    877     """
--> 878     if _HASSHAPELY:
    879         gj = shapely_geometry.__geo_interface__
    880         geom_cls = _geojson_type_to_esri_type(gj["type"])

NameError: name '_HASSHAPELY' is not defined
```
**Screenshots**

![image](https://user-images.githubusercontent.com/62656254/152597457-50be2e20-0386-484e-aaaf-3cf806f809a6.png)

**Expected behavior**

I expect the `arcgis.geometry.Geometry.from_shapely()` method to successfully convert any shapely geometry object into an `arcgis.geometry.Geometry` object like this:

![image](https://user-images.githubusercontent.com/62656254/152597654-b07ac3af-cddc-4288-a0d3-945017b75e1b.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 91.4.1esr (64-bit)
 - Python Version: 3.9.7
 - ArcGIS Python API Version: 2.0.0

**Additional context**

The problem appears to be caused by the lack of declaration of the `_HASSHAPELY` property in `_types.py`. If you were to declare the property in the exact same way that `_HASARCPY` is declared, the `.from_shapely` method works perfectly. 

![image](https://user-images.githubusercontent.com/62656254/152598087-fc5df966-342d-47fe-99b0-45450bfb6348.png)
![image](https://user-images.githubusercontent.com/62656254/152598136-799f49be-5c3d-4f72-a0a8-c7bc5f33ac83.png)

**Comment by achapkowski** [comment]
Thanks for reporting, we'll take a look at this.

**Comment by achapkowski** [comment]
The March release will have this issue fixed.  Thank you for reporting this.
