### ISSUE TITLE
Jupyter Notebook in ArcGIS Pro has problems parsing “return”

### ISSUE THREAD

**Issue by geoli91** [Esri/arcgis-python-api#1209]
**Describe the bug**
This is a bug using Jupyter Notebook in ArcGIS Pro, but I didn't find a dedicated community for it, so I'm giving feedback here.
The crux of this issue is that ArcGIS Pro's Jupyter Notebook does not correctly parse return statements outside of functions. When we **define a “return” statement outside of a function** in another editor (such as VS Code), we get an error "SyntaxError: 'return' outside function". But in ArcGIS Pro, this will not throw an exception, but will **always run the cell blockingly**. I think this is an unexpected bug, and I hope it will be fixed.
Finally, I am not a native English speaker, so if you have any questions about the expressions, feel free to discuss them further with you.

**To Reproduce**
If we execute the following code in another editor, we will get an error `SyntaxError: 'return' outside function`. But in ArcGIS Pro, this will not throw an error, but will always run the cell blockingly. 
```python
for i in range(10):
    return i
```

**Screenshots**
In ArcGIS Pro:
![20220318160649](https://cdn.jsdelivr.net/gh/geoli91/ImageHosting/img/20220318160649.jpg)

In VS Code
![20220318160931](https://cdn.jsdelivr.net/gh/geoli91/ImageHosting/img/20220318160931.jpg)

**Expected behavior**
Throw an error  "SyntaxError: 'return' outside function" such as another editor.

**Platform (please complete the following information):**
 - OS: Windows10
 - ArcGIS version: ArcGIS Pro 2.8
 - Python API Version 1.8.5

**Comment by achapkowski** [comment]
@geoli91 `return` is a key word and should only be used as described within the python language: https://github.com/python/cpython/blob/3.10/Lib/keyword.py#L18 . This error is expected.

If you are able to use return 1 within arcgis pro notebook, I suggest you log an issue with support@esri.com.  This is a bug on Pro's end.
