### ISSUE TITLE
Typo in Geometry.get_area() documentation

### ISSUE THREAD

**Issue by jacobdadams** [Esri/arcgis-python-api#1212]
**Describe the bug**
There is a very minor typo in the `arcgis.geometry.Geometry.get_area()` method documentation. For the `method` parameter, it lists `LANAR` instead of `PLANAR`.

I know it's a very small typo and easily figured out :) 

**To Reproduce**
```
Geometry.get_area?

Signature: Geometry.get_area(self, method, units=None)

<snip>
===============     ====================================================================
**Argument**        **Description**
---------------     --------------------------------------------------------------------
method              Required String. `LANAR` measurements reflect the projection of
                    geographic data onto the 2D surface (in other words, they will not
                    take into account the curvature of the earth). `GEODESIC`,
                    `GREAT_ELLIPTIC`, `LOXODROME`, and `PRESERVE_SHAPE` measurement types
                    may be chosen as an alternative, if desired.
---------------     --------------------------------------------------------------------

```
**Screenshots**

**Expected behavior**
```python
test_geo.get_area('PLANAR')

2.250000000299451e-06
```
**Platform (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Python API Version `1.9.1`

**Additional context**
Typo is in both the online docs and the interactive REPL docs, which makes me think it's not a formatting issue

**Comment by achapkowski** [comment]
it'll be updated in the next release in Q2 of 2022.
