### ISSUE TITLE
Bulk create Groups does not add the thumbnail

### ISSUE THREAD

**Issue by bnadler** [Esri/arcgis-python-api#123]
Bulk create Groups does not add the thumbnail to the group. I see the thumbnails extracted to "Data" but is not added to a payload

![image](https://user-images.githubusercontent.com/7817862/28395654-bc6e4bcc-6cb2-11e7-99ea-6530ac9a58b9.png)

**Comment by bnadler** [comment]
for row in reader:
        **row["thumbnail"] = os.path.join("data",row["thumbnail"])**
        group = gis.groups.create_from_dict(row)
        groups.append(group)

**Comment by mateuspontesmoraes** [comment]
Hi @bnadler, I created group and add the thumbnails using code below

```
import tempfile 

GROUP_COPY_PROPERTIES = ['title', 'description', 'tags', 'snippet', 'phone',
                         'access', 'isInvitationOnly']  

for group in source_groups:
	with tempfile.TemporaryDirectory() as temp_dir:
		target_group = {}
		
		for property_name in GROUP_COPY_PROPERTIES:
			target_group[property_name] = group[property_name]


		# Handle the thumbnail (if one exists)
		thumbnail_file = None
		if 'thumbnail' in group:
			target_group['thumbnail'] = group.download_thumbnail(temp_dir)

		# Create the group in the target portal
		gis.groups.create_from_dict(target_group)
```

**Comment by bnadler** [comment]
Thanks for the info

The sample code is actually very straight forward, except that the thumbnail path was missing from the row (only the name was present)
I added an os.path.join and got it to work.

I just hope they update the sample

**Comment by rwmajor2** [comment]
@bnadler It appears since this issue was logged, we have had several releases and many updates to the samples.  It appears this sample now is working as expected when run from https://notebooks.esri.com.  If you download the samples to your local workstation, make sure the pathname to the icons are set correctly.
