### ISSUE TITLE
GIS Pro will not upgrade Python API to version 2.0.0

### ISSUE THREAD

**Issue by gocho111** [Esri/arcgis-python-api#1230]
I have upgraded the arcgis api in GIS Pro to version 2.0.0 but it still shows version 1.9.1 not matter what i do. I am using Pro 2.9.2

**Comment by achapkowski** [comment]
ArcGIS Pro pins to the major version.  In order to upgrade to v2.0.0 you need to clone the arcgispro-py3 environment and ensure you using the --no-pin option on the conda install command.
