### ISSUE TITLE
Iterate through ArcPy Charts using Search Cursor

### ISSUE THREAD

**Issue by flytheW608** [Esri/arcgis-python-api#1232]
Hello, 

I'm not sure if this is possible, but can you create an example where we create multiple figures using arcpy.Chart by iterating using the search cursor?

That way we could use an arcpy tool, such as Select, and create an iterative ArcPy chart that matches the conditional statment within an ArcGIS Notebook.

**Comment by achapkowski** [comment]
Thank you for suggesting.  We do not do ArcPy development, but we made the team aware of this suggestion.  Thank you.
