### ISSUE TITLE
Vehicle detection deep learning resources

### ISSUE THREAD

**Issue by libertadcc** [Esri/arcgis-python-api#1235]
I'm trying to reproduce the sample of "Vehicle detection and tracking using deep learning" but I can't because neither the video nor the model is available in the data folder. Could you help me? Did you move the data?

The broken links are in the tutorial: 
- "In this notebook, we'll demonstrate how we can use deep learning to detect vehicles and then track them in a video. We'll use a short [video](https://youtu.be/e8cxjNE-4_I) taken from live traffic camera feed." 

- "Prepare data that will be used for training
You can download vehicle training data from [here](https://github.com/Esri/arcgis-python-api/tree/master/samples/04_gis_analysts_data_scientists/data/vehicle_training_data.zip). Extract the downloaded file to get your training data."

Thanks!  😄

**Comment by priyankatuteja** [comment]
@libertadcc training data: https://www.arcgis.com/home/item.html?id=ccaa060897e24b379a4ed2cfd263c15f
video and csv: https://www.arcgis.com/home/item.html?id=1801dc029fed467ba67d6e39113202af

The items are provided in the sample notebook.https://developers.arcgis.com/python/sample-notebooks/vehicle-detection-and-tracking/

![image](https://user-images.githubusercontent.com/39754605/169947334-c52762ea-98a8-4c38-a5b1-7a0ffa515387.png)

**Comment by gbrunner** [comment]
@priyankatuteja I can't get to the video and data. Can you help me?

**Comment by priyankatuteja** [comment]
@gbrunner  You can push he download button after opening the item in browser. video item : video and csv: https://www.arcgis.com/home/item.html?id=1801dc029fed467ba67d6e39113202af
