### ISSUE TITLE
Adding attachments using layer.edit_features fail

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#1236]
When using `layer.edit_features()` to add attachments the method fails and returns `None`. This is caused by your requirement of one of the methods adds, deletes or updates to be part of the call.

layer.py:
![image](https://user-images.githubusercontent.com/889468/167079517-0d9b6269-ed1e-4526-b3a3-e104898a596e.png)

You should add `and "attachments" not in params` as well.

Until fixed a workaround is to add an empty `deletes=""`
```python
        _res = _layer.edit_features(deletes="", use_global_ids=True, gdb_version=_ver, attachments={'adds':[_att]})
        print(_res)
```

**Platform (please complete the following information):**
 - Python API Version: 2.0.0

**Comment by HakonD** [comment]
Sure, I trust you to find a suitable feature service and attachment file.

```python
import os
import base64
import uuid
import mimetypes
import arcgis

# File to attach
_attach = "c:/temp/test.txt"
# Create base64 string
with open(_attach,'rb') as _file:
    _data = _file.read()
    _data64 = base64.b64encode(_data).decode('ascii')

# Get a layer and a feature to attach to
_gis = arcgis.GIS('pro')
_ds = "https://your.server/server/rest/services/yourservice/FeatureServer/0"
_layer = arcgis.features.FeatureLayer(_ds, _gis)
_feat = _layer.query(result_record_count=1, return_all_records=False, out_fields='OBJECTID,GlobalID')

# Create attachment
_att = {
    'globalId': str(uuid.uuid4()),
    'parentGlobalId': _feat.features[0].attributes['GlobalID'],
    'contentType': mimetypes.guess_type(_attach)[0],
    'name': os.path.basename(_attach),
    'data': _data64
}

# Add and fail
_res = _layer.edit_features(use_global_ids=True, attachments={'adds':[_att]})
print(_res)

# Add with empty deletes
_res = _layer.edit_features(deletes="", use_global_ids=True, attachments={'adds':[_att]})
print(_res)
```

**Comment by nanaeaubry** [comment]
@HakonD 
Thanks for bringing this up. However, the REST API that we follow does ask for one of the three key parameters to be passed in: `add`, `update`, or `delete`.  You can see the documentation [here](https://developers.arcgis.com/rest/services-reference/enterprise/apply-edits-feature-service-layer-.htm) to get a more details and examples about the method.

What we suggest is to use the [`Attachment Manager`](https://developers.arcgis.com/python/api-reference/arcgis.features.managers.html?highlight=add%20attachment#attachmentmanager). This has an `add` method which adds an attachment to a Feature Layer.

Hope this helps!

**Comment by HakonD** [comment]
Hi @nanaeaubry , and sorry but this is positively wrong. The REST documentation is a bit confusing, as it only marks the attachments parameter as optional, but as you know, you don't need to send all three of adds, deletes and updates. Clearly attachments are a fourth option as you can see from the error message given if you send in an empty request:
![image](https://user-images.githubusercontent.com/889468/167178072-150028af-f484-486b-9cfc-7ca2102506a6.png)

You can easily test this yourself by applying the fix I suggested in the initial post and run my code. You will see that the "Add and fail" call attaches just fine. Or if still not convinced, test it on the REST API directly:
![image](https://user-images.githubusercontent.com/889468/167177910-0ba2f4de-688b-47c8-8778-2d2c9933acb6.png)

I'm aware of the AttachmentManager, but as it only works with DEFAULT and not with data in versions it's not an option.

**Comment by nanaeaubry** [comment]
@HakonD 

Ok I see what you are saying. We will further investigate these issues.

**Comment by nanaeaubry** [comment]
Hello, in the next release there will be an option to work with data versions and we will add better examples. Thank you for bringing this up
