### ISSUE TITLE
The Item.move() method does not have the owner parameter properly implemented

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/arcgis-python-api#1241]
**Describe the bug**
The Item.move() method (line 13139 in arcgis/gis/__init__.py) does not move items to a new owner, as stated in the documentation.
The move() method takes two parameters according to the API docs; folder and owner (default None).
The owner parameter is described as "Optional string or Owner object.  The name of the user to move to."

If I look in the code of the method, no where is the "owner" parameter used, but instead a variabel called "owner_name", which is always set to self._user_id.

Also, the underlying method move_item (line 2672 in _portalpy.py) doesn't have any code to actually change the owner of an Item.

**To Reproduce**
```python
from arcgis.gis import GIS
gis = GIS("home")
item_to_move = gis.content.get("<itemid>")
item_to_move.move(folder="new_folder",owner="new_owner")
```
error:
```python
Folder not found for given owner
```

**Expected behavior**
That the item is moved to the specified folder and ownership transfered to the specified user.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 2.0.0

**Comment by sverkerEsriSE** [comment]
As a note, I'm using the reassign_to method instead, which should be the proper method to use for my case.

**Comment by nanaeaubry** [comment]
Hello, thank you for bringing this up. You are correct that the parameter is not being used and the proper method would be the `reassign_to` method. We will make necessary changes. Thanks!
