### ISSUE TITLE
Arcgis.mapping Error - RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

### ISSUE THREAD

**Issue by canerakin111** [Esri/arcgis-python-api#1250]
Trying to get details of webmaps published by my account. I have been running this issue in my code. I've tested the sample codes, still getting the error. I am running the code below.
https://github.com/Esri/arcgis-python-api/blob/86e3a5361042b355adb4e1179e32c362870c7b93/labs/display_web_map.ipynb

- Connecting ArcGIS Online
- ArcGIS Pro 2.6.2
- Using Notebook in ArcGIS Pro

`
from arcgis.gis import GIS
import arcpy, os
gis = GIS()

webmap = gis.content.get("41281c51f9de45edaf1c8ed44bb10e30")

from arcgis.mapping import WebMap

la_parks_trails = WebMap(webmap)

`
Error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
In  [17]:
Line 3:     la_parks_trails = WebMap(webmap)

File C:\Users\cakin\AppData\Local\ESRI\conda\envs\climate_downscaling\lib\site-packages\arcgis\mapping\_types.py, in __init__:
Line 235:   self._mapview = MapView(gis=self._gis, item=self)

File C:\Users\cakin\AppData\Local\ESRI\conda\envs\climate_downscaling\lib\site-packages\arcgis\widgets\_mapview\_mapview.py, in __init__:
Line 686:   super(MapView, self).__init__(**kwargs)

File C:\Users\cakin\AppData\Local\ESRI\conda\envs\climate_downscaling\lib\site-packages\ipywidgets\widgets\widget.py, in __init__:
Line 415:   self.open()

File C:\Users\cakin\AppData\Local\ESRI\conda\envs\climate_downscaling\lib\site-packages\ipywidgets\widgets\widget.py, in open:
Line 438:   self.comm = Comm(**args)

RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
---------------------------------------------------------------------------

**Comment by achapkowski** [comment]
We cannot reproduce your issue.  Please provide more data and we'll take a look again.
