### ISSUE TITLE
inconsistency with gis.content.import_data

### ISSUE THREAD

**Issue by Jip-van-Sommeren** [Esri/arcgis-python-api#1256]
**Describe the bug**
I am importing a sdf to an online portal, and im trying to automate this process by creating a github workflow python application. When I run my code locally it uploads a feature layer to the online portal as intended, when i run the exact same code as a python application through github it also uploads a feature layer, however all the attribute field names are limited to a length of 10 characters instead of the correct full name that is in the dataframe. E.g. (it should be "Aangetroffen_situatie", it returns "aangetroff").  I guess my question is: Is there a way i can get the correct field attribute names in my feature layer?

**To Reproduce**
```python
<append_item = gis.content.import_data(
                        df= some_df,
                        
                        folder= 'some_folder',
                        title= append_item_title,
                        tags= 'Temp',
                        snippet= 'Temp',
                        
                    )>
```
error:
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**
Return correct field attribute names

**Platform (please complete the following information):**
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
Do you have arcpy in this environment?

**Comment by Jip-van-Sommeren** [comment]
I do not, I only use arcgis api python features,  both return identical feature layers. Only the field names are limited to a length of 10 characters for some reason when using the github workflow application

**Comment by achapkowski** [comment]
I'm going to close this because it's a limitation of shapefiles. We are looking to move away from shapefiles to geopackages.
