### ISSUE TITLE
Converting Pandas DataFrame to Spatially Enabled DataFrame Geometry Removes Geometry In Some Cases

### ISSUE THREAD

**Issue by picarro-awilloughby** [Esri/arcgis-python-api#1262]
**Describe the bug**
I want to convert my Pandas DataFrame with a WKT geometry column to a Spatially Enabled DataFrame (SEDF); however, sometimes the geometry column in the resulting SEDF is blank. Here is an example:

**To Reproduce**
This DF to SEDF conversion works just fine.

```python
<from arcgis.features import GeoAccessor
df = pd.DataFrame(['POLYGON ((-122.4879908428375 37.8580879209098, -122.48752841647929 37.8578624638935, -122.48727791959379 37.85818273662985, -122.487740345952 37.858408193646149, -122.4879908428375 37.8580879209098))'], columns = ['SHAPE'])
    sedf = GeoAccessor.from_df(
        df=df,
        sr=4326,
        geometry_column= 'SHAPE', )>
```
This DF to SEDF conversion appears to remove the geometries in the SHAPE column:
```python
<from arcgis.features import GeoAccessor
df = pd.DataFrame(['POLYGON ((-79.841542412627334 40.511379203842651, -79.841545978234777 40.511381914693381, -79.84155175157241 40.511385469109257, -79.841557981970013 40.511388545242923, -79.841564601166084 40.5113911093916, -79.841571536639307 40.511393133461922, -79.841578712403177 40.511394595277778, -79.84158604983854 40.5113954788232, -79.8415934685549 40.511395774417863, -79.841600887271269 40.5113954788232, -79.841608224706633 40.511394595277778, -79.8416154004705 40.511393133461922, -79.841622335943725 40.5113911093916, -79.8416289551398 40.511388545242923, -79.8416351855374 40.511385469109257, -79.841640958875033 40.511381914693381, -79.841646211898762 40.5113779209382, -79.8416508870554 40.511373531600142, -79.841654933122911 40.511368794769687, -79.841658305771759 40.511363762344573, -79.841660968050491 40.511358489461088, -79.84166289079063 40.511353033890053, -79.84166405292622 40.511347455403843, -79.841664441724674 40.511341815121511, -79.84166405292622 40.511336174839187, -79.84166289079063 40.51133059635297, -79.841660968050491 40.511325140781928, -79.841658305771759 40.51131986789845, -79.841654933122911 40.511314835473343, -79.8416508870554 40.511310098642888, -79.841646211898762 40.511305709304821, -79.841640958875033 40.511301715549642, -79.8416351855374 40.511298161133759, -79.8416289551398 40.5112950850001, -79.841622335943725 40.511292520851427, -79.8416154004705 40.5112904967811, -79.841608224706633 40.511289034965237, -79.841600887271269 40.511288151419834, -79.8415934685549 40.511287855825159, -79.84158604983854 40.511288151419834, -79.841578712403177 40.511289034965237, -79.841571536639307 40.5112904967811, -79.841564601166084 40.511292520851427, -79.841557981970013 40.5112950850001, -79.84155175157241 40.511298161133759, -79.841545978234777 40.511301715549642, -79.841540725211047 40.511305709304821, -79.841536050054415 40.511310098642888, -79.8415320039869 40.511314835473343, -79.841528631338051 40.51131986789845, -79.841525969059319 40.511325140781928, -79.841525845748663 40.511325490662813, -79.841078013264578 40.51121738182654, -79.84106219300962 40.511264926460342, -79.84105393100468 40.511313564959153, -79.8410533447901 40.511362605362, -79.841060442705725 40.5114113499902, -79.841075123772256 40.511459105372943, -79.841097179127914 40.511505192113013, -79.841126294999739 40.51154895455231, -79.841162057167566 40.511589770099711, -79.841203956856987 40.511627058088308, -79.841542412627334 40.511379203842651))'], columns = ['SHAPE'])
sedf = GeoAccessor.from_df(
    df=df,
    sr=4326,
    geometry_column= 'SHAPE', )>
```
error:
No error is thrown, the resulting SEDF just has a geometry column with blank shapes (i.e. {}).

**Expected behavior**
Before I updated to ArcGIS Pro 2.9 (and included default packages) geometries behaved similarly to the first example above.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Arcgis Python API Version 1.9.1`
 - ArcGIS Pro 2.9.3

**Comment by achapkowski** [comment]
Try using an `apply`

```
from arcgis.geometry import Geometry
df.SHAPE = df.SHAPE.apply(Geometry)
```

**Comment by picarro-awilloughby** [comment]
> df.SHAPE.apply(Geometry)

This yields a DataFrame with a SHAPE column filled with arcgis.geometry._types.Polygon data.  Do you know how to convert this DF to a featureclass?  I haven't found how to do this on the web.

**Comment by achapkowski** [comment]
Once you define your spatial column and set the geometry you can use the `to_featureclass` to write out the data to disk.

```python
df = pd.DataFrame([data], columns=[...,"SHAPE"])
df.SHAPE.apply(Geometry)
df.spatial.set_geometry("SHAPE")
fp = df.spatial.to_featureclass(r"<some output path with table name>")
print(f"your data is located: {fp}")
```

**Comment by picarro-awilloughby** [comment]
> Once you define your spatial column and set the geometry you can use the `to_featureclass` to write out the data to disk.
> 
> ```python
> df = pd.DataFrame([data], columns=[...,"SHAPE"])
> df.SHAPE.apply(Geometry)
> df.spatial.set_geometry("SHAPE")
> fp = df.spatial.to_featureclass(r"<some output path with table name>")
> print(f"your data is located: {fp}")
> ```

I had tried this but for some reason df.spatial.to_featureclass(r"<some output path with table name>") returns a "None" object.

Here's what I'm running:
`import os
import pandas as pd
from arcgis.features import GeoAccessor
from arcgis.geometry import Geometry
import arcpy

df = pd.DataFrame([1,'POLYGON ((-79.841542412627334 40.511379203842651, -79.841545978234777 40.511381914693381, -79.84155175157241 40.511385469109257, -79.841557981970013 40.511388545242923, -79.841564601166084 40.5113911093916, -79.841571536639307 40.511393133461922, -79.841578712403177 40.511394595277778, -79.84158604983854 40.5113954788232, -79.8415934685549 40.511395774417863, -79.841600887271269 40.5113954788232, -79.841608224706633 40.511394595277778, -79.8416154004705 40.511393133461922, -79.841622335943725 40.5113911093916, -79.8416289551398 40.511388545242923, -79.8416351855374 40.511385469109257, -79.841640958875033 40.511381914693381, -79.841646211898762 40.5113779209382, -79.8416508870554 40.511373531600142, -79.841654933122911 40.511368794769687, -79.841658305771759 40.511363762344573, -79.841660968050491 40.511358489461088, -79.84166289079063 40.511353033890053, -79.84166405292622 40.511347455403843, -79.841664441724674 40.511341815121511, -79.84166405292622 40.511336174839187, -79.84166289079063 40.51133059635297, -79.841660968050491 40.511325140781928, -79.841658305771759 40.51131986789845, -79.841654933122911 40.511314835473343, -79.8416508870554 40.511310098642888, -79.841646211898762 40.511305709304821, -79.841640958875033 40.511301715549642, -79.8416351855374 40.511298161133759, -79.8416289551398 40.5112950850001, -79.841622335943725 40.511292520851427, -79.8416154004705 40.5112904967811, -79.841608224706633 40.511289034965237, -79.841600887271269 40.511288151419834, -79.8415934685549 40.511287855825159, -79.84158604983854 40.511288151419834, -79.841578712403177 40.511289034965237, -79.841571536639307 40.5112904967811, -79.841564601166084 40.511292520851427, -79.841557981970013 40.5112950850001, -79.84155175157241 40.511298161133759, -79.841545978234777 40.511301715549642, -79.841540725211047 40.511305709304821, -79.841536050054415 40.511310098642888, -79.8415320039869 40.511314835473343, -79.841528631338051 40.51131986789845, -79.841525969059319 40.511325140781928, -79.841525845748663 40.511325490662813, -79.841078013264578 40.51121738182654, -79.84106219300962 40.511264926460342, -79.84105393100468 40.511313564959153, -79.8410533447901 40.511362605362, -79.841060442705725 40.5114113499902, -79.841075123772256 40.511459105372943, -79.841097179127914 40.511505192113013, -79.841126294999739 40.51154895455231, -79.841162057167566 40.511589770099711, -79.841203956856987 40.511627058088308, -79.841542412627334 40.511379203842651))']).T
df.columns = ['test','SHAPE']
df.SHAPE.apply(Geometry)
df.spatial.set_geometry("SHAPE")

project_dir = r"C:\Users\Administrator\Documents\Picarro\SE_Deep_Dives\SE_Deep_Dives\SE_Deep_Dives"
gdb_dir = project_dir + "\\test_gdb.gdb"
if not os.path.isdir(gdb_dir):
    arcpy.CreateFileGDB_management(project_dir, 'test_gdb.gdb')
            
fc_dir = gdb_dir + "\\test_fc"
fp = df.spatial.to_featureclass(fc_dir)
print(f"your data is located: {fp}")`

**Comment by picarro-awilloughby** [comment]
I found a workaround using Shapely to export to a shapefile then using arcpy to move the shapefile into my desired geodatabase. If anyone has an arcgis solution I'd love to see it.

`from osgeo import ogr, osr
from shapely.geometry import Polygon
import shapely.wkt
import arcpy

wkt_poly = 'POLYGON ((-79.841542412627334 40.511379203842651, -79.841545978234777 40.511381914693381, -79.84155175157241 40.511385469109257, -79.841557981970013 40.511388545242923, -79.841564601166084 40.5113911093916, -79.841571536639307 40.511393133461922, -79.841578712403177 40.511394595277778, -79.84158604983854 40.5113954788232, -79.8415934685549 40.511395774417863, -79.841600887271269 40.5113954788232, -79.841608224706633 40.511394595277778, -79.8416154004705 40.511393133461922, -79.841622335943725 40.5113911093916, -79.8416289551398 40.511388545242923, -79.8416351855374 40.511385469109257, -79.841640958875033 40.511381914693381, -79.841646211898762 40.5113779209382, -79.8416508870554 40.511373531600142, -79.841654933122911 40.511368794769687, -79.841658305771759 40.511363762344573, -79.841660968050491 40.511358489461088, -79.84166289079063 40.511353033890053, -79.84166405292622 40.511347455403843, -79.841664441724674 40.511341815121511, -79.84166405292622 40.511336174839187, -79.84166289079063 40.51133059635297, -79.841660968050491 40.511325140781928, -79.841658305771759 40.51131986789845, -79.841654933122911 40.511314835473343, -79.8416508870554 40.511310098642888, -79.841646211898762 40.511305709304821, -79.841640958875033 40.511301715549642, -79.8416351855374 40.511298161133759, -79.8416289551398 40.5112950850001, -79.841622335943725 40.511292520851427, -79.8416154004705 40.5112904967811, -79.841608224706633 40.511289034965237, -79.841600887271269 40.511288151419834, -79.8415934685549 40.511287855825159, -79.84158604983854 40.511288151419834, -79.841578712403177 40.511289034965237, -79.841571536639307 40.5112904967811, -79.841564601166084 40.511292520851427, -79.841557981970013 40.5112950850001, -79.84155175157241 40.511298161133759, -79.841545978234777 40.511301715549642, -79.841540725211047 40.511305709304821, -79.841536050054415 40.511310098642888, -79.8415320039869 40.511314835473343, -79.841528631338051 40.51131986789845, -79.841525969059319 40.511325140781928, -79.841525845748663 40.511325490662813, -79.841078013264578 40.51121738182654, -79.84106219300962 40.511264926460342, -79.84105393100468 40.511313564959153, -79.8410533447901 40.511362605362, -79.841060442705725 40.5114113499902, -79.841075123772256 40.511459105372943, -79.841097179127914 40.511505192113013, -79.841126294999739 40.51154895455231, -79.841162057167566 40.511589770099711, -79.841203956856987 40.511627058088308, -79.841542412627334 40.511379203842651))'

# Here's an example Shapely geometry
poly = shapely.wkt.loads(wkt_poly)
sr = osr.SpatialReference()
sr.ImportFromEPSG(4326)

# Now convert it to a shapefile with OGR    
driver = ogr.GetDriverByName('Esri Shapefile')
ds = driver.CreateDataSource('temp_data\\my.shp')
layer = ds.CreateLayer('', sr, ogr.wkbPolygon)
# Add one attribute
layer.CreateField(ogr.FieldDefn('id', ogr.OFTInteger))
defn = layer.GetLayerDefn()

# Create a new feature (attribute and geometry)
feat = ogr.Feature(defn)
feat.SetField('id', 123)

# Make a geometry, from Shapely object
geom = ogr.CreateGeometryFromWkb(poly.wkb)
feat.SetGeometry(geom)

layer.CreateFeature(feat)
feat = geom = None  # destroy these

# Save and close everything
ds = layer = feat = geom = None
 
# Set environment settings
arcpy.env.workspace = '<workspace_dir>'
 
# Set local variables
in_features = ['my.shp']
out_location = '<gdb_dir>'
 
# Execute FeatureClassToGeodatabase
arcpy.FeatureClassToGeodatabase_conversion(in_features, out_location)`

**Comment by picarro-awilloughby** [comment]
I've also noticed that converting to a SEDF warps the geometry of the shapes it doesn't fully remove.  Here is an example.  Notice that the SEDF geometry is a simple triangle.  The actual shape has many vertices and would look more like a pie slice with a rounded edge.

```
from arcgis.features import GeoAccessor
shape = 'POLYGON ((-79.837574921128578 40.520348612497742, -79.83757427285461 40.520351723925678, -79.837573884003874 40.520357364208, -79.83757427285461 40.520363004490328, -79.837575435146491 40.520368582976538, -79.837577358145182 40.52037403854758, -79.837580020781928 40.520379311431057, -79.8375833938843 40.520384343856179, -79.837587440495923 40.520389080686627, -79.837592116281243 40.520393470024693, -79.83759737001138 40.520397463779872, -79.837603144125367 40.520401018195763, -79.837609375360813 40.520404094329407, -79.837615995447 40.520406658478088, -79.837622931852863 40.520408682548407, -79.837630108581692 40.52041014436427, -79.837637447003758 40.520411027909688, -79.837644866717753 40.520411323504362, -79.837652286431748 40.520411027909688, -79.837659624853814 40.52041014436427, -79.837666801582643 40.520408682548407, -79.83767373798851 40.520406658478088, -79.837680358074692 40.520404094329407, -79.837686589310138 40.520401018195763, -79.837692363424125 40.520397463779872, -79.837697617154262 40.520393470024693, -79.837702292939582 40.520389080686627, -79.8377063395512 40.520384343856179, -79.837709712653577 40.520379311431057, -79.837712375290323 40.52037403854758, -79.837714298289015 40.520368582976538, -79.8377154605809 40.520363004490328, -79.837715849431632 40.520357364208, -79.8377154605809 40.520351723925678, -79.837714298289015 40.520346145439461, -79.837712375290323 40.520340689868434, -79.837709712653577 40.520335416984942, -79.8377063395512 40.520330384559827, -79.837702555288018 40.520325954825843, -79.838084599695648 40.520117945184623, -79.838048401401664 40.520083574597493, -79.838007575998233 40.520052343404679, -79.83796259160772 40.520024609717026, -79.8379139640413 40.520000691541433, -79.837862250884442 40.519980863134379, -79.837808045103358 40.519965351857287, -79.8377519682458 40.519954335569423, -79.837694663314139 40.519947940588438, -79.837636787392412 40.519946240242078, -79.837579004111845 40.519949254027267, -79.837521976041415 40.5199569473866, -79.837466357090534 40.519969232104557, -79.837412785011 40.51998596731908, -79.837361874084266 40.520006961136687, -79.837314208077828 40.520031972832868, -79.837270333551473 40.52006071561231, -79.837230753590177 40.520092859897431, -79.837195922035491 40.520128037107462, -79.837166238281625 40.52016584388474, -79.8371420426958 40.52020584671984, -79.837123612715445 40.520247586922331, -79.837111159666975 40.520290585880353, -79.837574921128578 40.520348612497742))'
df = pd.DataFrame([shape], columns = ['SHAPE'])
sedf = GeoAccessor.from_df(
    df=df,
    sr=4326,
    geometry_column= 'SHAPE', )
sedf['SHAPE'][0]
```

**Comment by achapkowski** [comment]
Ok it appears at the later versions of arcpy, which converts the WKT to Esri JSON doesn't apply a default spatial reference (4326).  I fixed that in the python api code.
This will be in the `2.1.0` release coming out later this year.
Thank you for reporting this.
