### ISSUE TITLE
Append only available on ArcGIS Online?

### ISSUE THREAD

**Issue by mvrtich** [Esri/arcgis-python-api#1265]
Hi,

I'm using ArcGIS Python API v2.0.0 and trying to append data to hosted feature layer in ArcGIS Enterprise v10.9.1.

It fails with a message "Append only available on ArcGIS Online".

![MatejVrtich_0-1653660440538](https://user-images.githubusercontent.com/3437056/171645366-f2aa2897-b594-42af-a821-437975266056.png)

Regarding the [documentation](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html?highlight=append#arcgis.features.FeatureLayer.append): "The append method is only available in ArcGIS Online and ArcGIS Enterprise 10.8.1+".

Am I missing something?

Thanks,

Matej

**Comment by achapkowski** [comment]
This should be resolved at 2.0.1 I believe, and 2.0.1 was released today.

**Comment by mvrtich** [comment]
Thank you for quick response.
I did try 2.0.1 and hit another issue.
`layer_item.tables[0].append(source_info = csv_info["publishParameters"],
         item_id = csv_item.id,
         upload_format = "csv",
         upsert = False,
         skip_inserts = False)`

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<timed eval> in <module>

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\layer.py in append(self, item_id, upload_format, source_table_name, field_mappings, edits, source_info, upsert, skip_updates, use_globalids, update_geometry, append_fields, rollback, skip_inserts, upsert_matching_field, upload_id, return_messages, future)
   2376         url = self._url + "/append"
   2377         del cparams
-> 2378         res = self._con.post(path=url, postdata=params)
   2379         if future:
   2380             executor = concurrent.futures.ThreadPoolExecutor(1)

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\gis\_impl\_con\_connection.py in post(self, path, params, files, **kwargs)
   1410             file_name=file_name,
   1411             try_json=try_json,
-> 1412             force_bytes=kwargs.pop("force_bytes", False),
   1413         )
   1414 

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\gis\_impl\_con\_connection.py in _handle_response(self, resp, file_name, out_path, try_json, force_bytes, ignore_error_key)
    898                     return data
    899                 errorcode = data["error"]["code"] if "code" in data["error"] else 0
--> 900                 self._handle_json_error(data["error"], errorcode)
    901             return data
    902         else:

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\gis\_impl\_con\_connection.py in _handle_json_error(self, error, errorcode)
    921 
    922         errormessage = errormessage + "\n(Error Code: " + str(errorcode) + ")"
--> 923         raise Exception(errormessage)
    924 
    925     def post_multipart(

Exception: Error downloading item from Portal.
(Error Code: 500)

**Comment by nanaeaubry** [comment]
Hello sorry for the delayed response. Can you post sample data so we can reproduce the error?

**Comment by mvrtich** [comment]
Hi,
See the attached CSV file
[test_append_data.csv](https://github.com/Esri/arcgis-python-api/files/8855529/test_append_data.csv)

The data does not include a location information and I'm appending it into a hosted feature layer (table) in ArcGIS Enterprise 10.9.1.
`layer_item.tables[0].append(source_info = csv_info["publishParameters"],
         item_id = csv_item.id,
         upload_format = "csv",
         upsert = False,
         skip_inserts = False)`

Before calling the append, a CSV file is uploaded into a portal and analyzed to fetch a publish parameters.
`csv_item = gis.content.add(item_properties = {"title": "test_append_data", "type": "CSV"}, data = csv_path)
csv_info = gis.content.analyze(item=csv_item.id, file_type="csv", location_type="none")`

The exception after calling the append is:
`Exception: Error downloading item from Portal.
(Error Code: 500)`

Thanks for any advice.

Matej

**Comment by nanaeaubry** [comment]
As of now you can append as a new Table to the item or another solution is to use the FeatureLayerCollectionManager to overwrite the table with new data.

**Comment by mvrtich** [comment]
Could you please specify what "you can append as a new Table to the item" means?
I'm doing `layer_item.tables[0].append` and it raise an exception.
The exact same method call against a data hosted in ArcGIS Online is working fine.

**Comment by nanaeaubry** [comment]
@mvrtich Ok interesting, I was able to reproduce your issue with online vs enterprise. I did not know it was going through the Feature Layer class when doing Online. 

I will reach out to see what is happening and post back with updates to this.

**Comment by mvrtich** [comment]
Hi @nanaeaubry,

It seems that `append()` method only works for ArcGIS Enterprise if using the `upload_id` parameter, not `item_id`, and it does not matter if it's a Table or Feature Layer class.
Regarding the [append sources](https://developers.arcgis.com/rest/services-reference/enterprise/append-feature-service-layer-.htm#:~:text=feature%20service%20owner.-,Append%20sources,-The%20source%20of) in a REST API reference, the item_id (appendItemId) is supported since ArcGIS Enterprise 10.9, so maybe it's not implemented in the Python API yet?

**Comment by nanaeaubry** [comment]
Hello @mvrtich ,

Thank you for looking into this as well. We were able to find differences between the way append works in online vs enterprise and our API was not handling that difference. 

We are working on a fix and the issue will be resolved at our next release (2.1.0). For now, the browser works to append to a Table in Enterprise

Thanks for bringing this to our attention
