### ISSUE TITLE
No _as_array function when calling from_table on a dbf file

### ISSUE THREAD

**Issue by namur007** [Esri/arcgis-python-api#1272]
**Describe the bug**
to_table throwing error when calling `from_table` on a `.dbf` file in arcgis pro 2.9.2.

function seems to be updated internally from `_as_array` to `_as_narray`.

Additional error when not passing a field argument as well as .da.SearchCursor doesn't expect a `None` value for the `field_names` prop.

**To Reproduce**
```python
import pandas as pd
from arcgis.features import GeoAccessor, GeoSeriesAccessor

pd.DataFrame.spatial.from_table('file.dbf', fields="*")
```
error:
```python
da.SearchCursor' object has no attribute '_as_array'
```
from fileops.py -> line 339

**Expected behavior**
table should load as a dataframe

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: ArcGIS Pro
 - Python API Version 2.0.0

**Additional context**
Resolution looks to be updating the reference from `_as_array` to `_as_narray`.
Additionally, passing `field_names=kwargs.pop("fields", "*")` instead of None to the field name prop

**Comment by nanaeaubry** [comment]
Is there a sample dbf file you can provide for us to reproduce this issue?
