### ISSUE TITLE
Exception handling advices to turn off SSL-verification

### ISSUE THREAD

**Issue by esride-jebu** [Esri/arcgis-python-api#1284]
Found in 1.9.1, still exists in 2.0.1.
In arcgis\gis\_impl\_con\_connection.py the following exception handler is implemented (3 times, once in get(), once in post() and once in post_multipart():
```
except requests.exceptions.SSLError as err:
    raise requests.exceptions.SSLError(
        "Please set verify_cert=False due to encountered SSL error: %s" % err
    )
```
This is a bad advice and leads to an security issue, if the developer using the API follows that advice.
Disabling SSL-verification should be the last thing to do and only be done if the developer really knows, why she's doing it.

**Comment by achapkowski** [comment]
Thank you for the recommendation. Advising people to ignore SSL warnings is a last case thing.  There are situations where this is valid.  

I recommend you always contact your administrator to fix the SSL problem, but many times with proxies, invalid/expired certs and other issues this is not always possible.

**Comment by spitzerr** [comment]
@achapkowski aggree on last case thing. So could you please adjust the wording of the exception a little bit. It could emphasize a little bit more the "last thing"-part as the documentation already does:
![image](https://user-images.githubusercontent.com/36198112/175311256-c350e0cc-cdec-4471-9018-ff29e22bfef4.png)

**Comment by esride-jebu** [comment]
@achapkowski What exactly do you mean by "if you enable logging"? There is no such documentation in the API.

If I simulate a MITM-attack by using Fiddler (_without_ trusting the self-generated root certificate), this is what happens:
`
import arcgis
arcgis.__version__
# --> 2.0.1

import logging
logging.getLogger("arcgis").setLevel(logging.DEBUG)
logging.getLogger("arcgis.gis").setLevel(logging.DEBUG)

# Open Connection to ArcGIS Online (which has proper certificates, of course) through our Fiddler based "MITM-Proxy"
gis = arcgis.gis.GIS(proxy={
    "http": "http://127.0.0.1:8898",
    "https": "http://127.0.0.1:8898"
})
`
..generates the following output:
`
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    699             if is_new_proxy_conn and http_tunnel_required:
--> 700                 self._prepare_proxy(conn)
    701 

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connectionpool.py in _prepare_proxy(self, conn)
    993 
--> 994         conn.connect()
    995 

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connection.py in connect(self)
    423             ssl_context=context,
--> 424             tls_in_tls=tls_in_tls,
    425         )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\util\ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    449         ssl_sock = _ssl_wrap_socket_impl(
--> 450             sock, context, tls_in_tls, server_hostname=server_hostname
    451         )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\util\ssl_.py in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    492     if server_hostname:
--> 493         return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
    494     else:

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    422             context=self,
--> 423             session=session
    424         )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
    869                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 870                     self.do_handshake()
    871             except (OSError, ValueError):

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\ssl.py in do_handshake(self, block)
   1138                 self.settimeout(None)
-> 1139             self._sslobj.do_handshake()
   1140         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    449                     retries=self.max_retries,
--> 450                     timeout=timeout
    451                 )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    825                 body_pos=body_pos,
--> 826                 **response_kw
    827             )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    825                 body_pos=body_pos,
--> 826                 **response_kw
    827             )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    785             retries = retries.increment(
--> 786                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    787             )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    591         if new_retry.is_exhausted():
--> 592             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    593 

MaxRetryError: HTTPSConnectionPool(host='www.arcgis.com', port=443): Max retries exceeded with url: /sharing/rest/portals/self (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\_impl\_con\_connection.py in post(self, path, params, files, **kwargs)
   1360                         verify=self._verify_cert,
-> 1361                         allow_redirects=allow_redirects,
   1362                     )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\auth\api.py in post(self, url, data, json, **kwargs)
    493             proxies=proxies,
--> 494             **kwargs,
    495         )

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\requests\sessions.py in post(self, url, data, json, **kwargs)
    576 
--> 577         return self.request('POST', url, data=data, json=json, **kwargs)
    578 

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         send_kwargs.update(settings)
--> 529         resp = self.send(prep, **send_kwargs)
    530 

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644         # Send the request
--> 645         r = adapter.send(request, **kwargs)
    646 

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    516                 # This branch is for urllib3 v1.22 and later.
--> 517                 raise SSLError(e, request=request)
    518 

SSLError: HTTPSConnectionPool(host='www.arcgis.com', port=443): Max retries exceeded with url: /sharing/rest/portals/self (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-17-780b815ea02c> in <module>
      1 gis = arcgis.gis.GIS(proxy={
      2     "http": "http://127.0.0.1:8898",
----> 3     "https": "http://127.0.0.1:8898"
      4 })
      5 gis

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
    505                 )
    506             else:
--> 507                 raise e
    508         try:
    509             if (

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
    467                 api_key=self._api_key,
    468                 is_hosted_nb_home=self._is_hosted_nb_home,
--> 469                 use_gen_token=self._use_gen_token,
    470             )
    471             if self._portal.is_kubernetes:

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\_impl\_portalpy.py in __init__(self, url, username, password, key_file, cert_file, expiration, referer, proxy_host, proxy_port, connection, workdir, tokenurl, verify_cert, client_id, custom_auth, token, **kwargs)
    227                 )
    228         # self.get_version(True)
--> 229         self.get_properties(True)
    230 
    231     def add_group_users(

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\_impl\_portalpy.py in get_properties(self, force)
   1289                     )  # issue seen with key, cert auth
   1290                 if not resp:
-> 1291                     raise e
   1292 
   1293             if resp:

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\_impl\_portalpy.py in get_properties(self, force)
   1269             resp = None
   1270             try:
-> 1271                 resp = self.con.post(path, self._postdata(), ssl=True)
   1272             except Exception as e:
   1273                 if (

~\AppData\Local\ESRI\conda\envs\arcgispython-2.0.1\lib\site-packages\arcgis\gis\_impl\_con\_connection.py in post(self, path, params, files, **kwargs)
   1374         except requests.exceptions.SSLError as err:
   1375             raise requests.exceptions.SSLError(
-> 1376                 "Please set verify_cert=False due to encountered SSL error: %s" % err
   1377             )
   1378         except requests.exceptions.InvalidURL as errIU:

SSLError: Please set verify_cert=False due to encountered SSL error: HTTPSConnectionPool(host='www.arcgis.com', port=443): Max retries exceeded with url: /sharing/rest/portals/self (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
`

As I just simulated the MITM attack, I had to explicetly define the proxy in the constructor. However, a real mitm scenario would not have the need for that.
