### ISSUE TITLE
Find items with exact title using content.search

### ISSUE THREAD

**Issue by richardsr-saccounty** [Esri/arcgis-python-api#129]
Is it possible to restrict search results to exact matches by title? 

My query is title:City_Boundaries and owner:username and the search is returning other "City_Boundary" matches and would like to restrict to exact matches.

**Comment by achapkowski** [comment]
Searching with the Python API is just like searching with the web browser.  See: http://doc.arcgis.com/en/arcgis-online/reference/search.htm#ESRI_SECTION1_18FD99A1020547BA864FCEBECBE267F3

**Comment by rohitgeo** [comment]
The backend API that we use - https://developers.arcgis.com/rest/users-groups-and-items/search-reference.htm - does not provide this capability and hence we wont be able to support it.
