### ISSUE TITLE
Standalone ArcPy Anaconda Distribution for ArcGIS Pro 3.0 crashes Jupyter Notebook Kernel in VSCode

### ISSUE THREAD

**Issue by FeralCatColonist** [Esri/arcgis-python-api#1298]
**Describe the bug**
After creating a new ArcPy environment within a standalone installation of Anaconda, any attempt to import ArcPy within a VSCode Jupyter Notebook crashes the kernel. This is the new distribution release on Anaconda from the ArcGIS Pro 3.0 release.

Works appropriately in a regular Jupyter Notebook. Also the distribution that comes with ArcGIS Pro 3.0 does not break the VSCode Jupyter Notebook.

**To Reproduce**
```shell
conda create -n esri
conda activate esri
conda install -c esri arcpy
```

Within a VSCode Jupyter Notebook, import ArcPy 

```python
import ArcPy
```

error:
```python
Canceled future for execute_request message before replies were done.

The Kernel crashed while executing code in the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for more details.
```
**Screenshots**
![image-1](https://user-images.githubusercontent.com/12204584/178572445-23d0928c-c3a1-44cb-8b68-5cf9d499e8ac.png)

**Expected behavior**
ArcPy should be usable within a VSCode Jupyter Notebook (when downloaded from Anaconda) as has been the behavior since ArcGIS Pro 2.7.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 2.0.1 py39_2826 esri

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by scdub** [comment]
This has been fixed with help from @FeralCatColonist and we've pushed a new build of `arcpy` 3.0 up to the Esri channel which addresses the issue.

**Comment by achapkowski** [comment]
Thank you for the fix @scdub and for the help of @FeralCatColonist, I'm closing this!
