### ISSUE TITLE
arcgis 2.0.1 won't pip install on Ubuntu 22.04

### ISSUE THREAD

**Issue by jacobdadams** [Esri/arcgis-python-api#1299]
**Describe the bug**
If I try to `pip install arcgis` on a stock ubuntu 22.04 LTS machine, github's `ubuntu-latest` image (20.04), or githubs `ubuntu-22.04` image, it fails (maybe due to a missing kerberos dependency for `gssapi`?). This is causing issues in my github CI pipeline and may cause issues down the line when deploying my code as a Google Cloud Function, which only supports pip for installing dependencies (no conda or apt-get/etc).

`conda install arcgis -c esri` installs properly.

`pip install arcgis==1.9.*` works just fine.

`pip install arcgis` works fine on windows, where a `winkerberos` package gets installed as a dependency.

After trial and error on a 22.04 VM (created using Hyper-V's Quick Create), `arcgis 2.0.1` will pip install if I first install `gcc` and `libkrb5-dev`: `sudo apt-get install gcc libkrb5-dev`.

**To Reproduce**
On an Ubuntu machine (or github's `ubuntu-latest` image): 
```
pip install arcgis
```
error:
```
< ... collecting packages ... >

 Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      In distributed package, building from C files...
      /bin/sh: 1: krb5-config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ceknmq_p/gssapi_2aa75bb70cf04f6da4585bea96eedbf3/setup.py", line 128, in <module>
          link_args = shlex.split(get_output(f"{kc} --libs gssapi"))
        File "/tmp/pip-install-ceknmq_p/gssapi_2aa75bb70cf04f6da4585bea96eedbf3/setup.py", line 41, in get_output
          res = subprocess.check_output(*args, shell=True, **kwargs)
        File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: Process completed with exit code 1.
```

**Expected behavior**
A successful `pip install arcgis` process.

**Platform (please complete the following information):**
 - OS: Ubuntu 22.04 LTS, github's 20.04 and 22.04 images
 - Python API Version: 2.0.1

**Additional context**

**Comment by achapkowski** [comment]
The python api uses `requests-kerberos` for Linux/Mac systems.  This means the system must meet the requirements to use this package.  

If you take a look at: https://github.com/requests/requests-kerberos/blob/master/ci/setup-kerb.sh from requests-kerberos, you can see how they get the package working within their pipeline. 

On Github Actions, you can add the following into your workflow:

```
  - name: Install libkrb5 for Kerberos on Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y libkrb5-dev
          pip install requests-kerberos

```

**Comment by jacobdadams** [comment]
Thanks for the info. Any info on why this is different in 2.* vs 1.9.*?

**Comment by twystd** [comment]
Trying to _pip install .._ on MacOS gives the following error:
```
pip install arcgis==2.0.1
ERROR: Ignored the following versions that require a different python version: 2.0.1 Requires-Python >=3.7, <3.10
ERROR: Could not find a version that satisfies the requirement arcgis==2.0.1 (from versions: 1.3.0, 1.3.0.post1, 1.3.0.post2, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.2.post1, 1.5.3, 1.6.0, 1.6.1, 1.6.1.post1, 1.6.2, 1.6.2.post1, 1.7.0, 1.7.1, 1.8.0, 1.8.0.post1, 1.8.1, 1.8.2, 1.8.3, 1.8.3.post1, 1.8.3.post2, 1.8.4, 1.8.5.post1, 1.8.5.post2, 1.8.5.post3, 1.9.0, 1.9.1, 2.0.0)
ERROR: No matching distribution found for arcgis==2.0.1
```

v2.0.0. installs just fine though.

**Comment by dnsohrabian** [comment]
@achapkowski Is there anything that can be done in this repo's dependencies that avoids this issue? Or if it is stemming from another package that needs attention on the matter? I'm happy to pitch in to raising the matter. 

To this day, any Ubuntu machine I attempt to install `arcgis` via `pip install arcgis` will fail because of this exact issue. I visit this issue log every couple months to remember what I need to do. The solution is always installing `libkrb5-dev` if I haven't before.

In the meantime, having that solution would be super helpful for the future and whoever else is running into this in 2024. The [official documentation for this package ](https://developers.arcgis.com/python/guide/install-and-set-up/#installation-for-arcgis-pro-30-and-later) mentions you need to install libkrb5-dev if you are installing in Google Colaboratory via `pip`. Can the _libkrb5-dev_ fix be put front and center at the top for how to install with pip with Linux?
