### ISSUE TITLE
Python from ArcGIS Server 10.9.1

### ISSUE THREAD

**Issue by Rod-Santos** [Esri/arcgis-python-api#1304]
Hey  everyone,

I don't know if this is the correct channel...
I'm having a problem installing a custom library to Python from ArcGIS Server.

**Environmental considerations:**

- Linux Operating System
- ArcGIS Enterprise 10.9.1 (was migrated from 10.8.1 recently)
- Library that will be installed: ReportLab v.2.7

**Error print**: https://prnt.sc/smYeib7kQ7JL 

**Reference documentation**: https://enterprise.arcgis.com/en/server/latest/publish-services/linux/deploying-custom-python-packages.htm
" _Start the wine explorer application. At the terminal, paste this command:
. <ArcGISServer_InstallDir>/arcgis/server/framework/etc/arcenv; wine explorer &_ "

Best Regards,

**Comment by achapkowski** [comment]
Python 2.7 is deprecated.  Use python 3 packages.
