### ISSUE TITLE
sdf to_featurelayer

### ISSUE THREAD

**Issue by hildermesmedeiros** [Esri/arcgis-python-api#1308]
**Describe the bug**
Currently we need to convert int64 to str. That is not a issue, but the lacking of warning, error causes new users to make this mistake.

**To Reproduce**
![image](https://user-images.githubusercontent.com/20046591/180495146-a6aebd64-c6e2-4fd1-b4ac-a0db8c650cdd.png)

```python
The gis module is publishing int64 columns. But if there are ints over 32 bits it the insert fails.
```

**Expected behavior**
It should warn and try to make str conversion.

**Platform (please complete the following information):**
 - windows 10
 - chrome
 - Python API Version 1.9.1

**Comment by achapkowski** [comment]
@hildermesmedeiros this is correct.  The feature class data model for shapefile and fgdb do not support int64 values for Non-OID fields.  For this issue, I would suggest you contact Esri Support and log an enhancement request.
