### ISSUE TITLE
Unable to use "CSVLayer" to return a hosted CSV in ArcGIS Online (not public) as a Pandas' DataFrame

### ISSUE THREAD

**Issue by GeeFernando** [Esri/arcgis-python-api#1311]
**Describe the bug**
Unable to use [CSVLayer](https://developers.arcgis.com/python/api-reference/arcgis.mapping.ogc.html) to return a hosted CSV in ArcGIS Online (not public) as a Pandas' DataFrame.

**To Reproduce**

```python
# Connect to AGOL
from arcgis.gis import GIS
gis = GIS("https://www.arcgis.com", username, password)

from arcgis.mapping.ogc import CSVLayer

csvItem = gis.content.get(#itemIdOfCSV)
CSVLayer(csvItem)
```

error:

```python
<CSV @ itemID of CSV>
```

Although I am able to read a hosted CSV in ArcGIS Online into Pandas' DataFrame if the hosted CSV is shared publicly, by just using the code snippet below

```python
import pandas as pd

urlCSV = "https://arcgis.com/sharing/rest/content/items/#itemIdOfCSV/data"
pd.read_csv(urlCSV)
```

**Platform (please complete the following information):**

 - ArcGIS Online Notebooks on Google Chrome, and Python API `1.9.0` on MacOS

**Comment by nanaeaubry** [comment]
Hello,

Using arcgis 2.0.1 I am unable to reproduce your issue. When I run the code you have above with a CSV item in my Online that is not shared publicly, I get these results:
![image](https://user-images.githubusercontent.com/19919283/182465220-8c1bc829-8757-4755-94b8-91003623ddcb.png)

Try to upgrade your version of arcgis and let us know if the issue persists. Thanks!

**Comment by GeeFernando** [comment]
Actually, it was my bad. Sorry.
Forgot to include the **df** property as below

CSVLayer(csvItem)**.df**

Thanks so much for the help.
Gee
