### ISSUE TITLE
Attachment Manager in ArcGIS Online Notebooks cannot add DOCX or XLSX Files

### ISSUE THREAD

**Issue by freestok** [Esri/arcgis-python-api#1315]
**Describe the bug**
Using the `add` function on the [`AttachmentManager`](https://developers.arcgis.com/python/api-reference/arcgis.features.managers.html#attachmentmanager) fails to upload Excel and Word files in the ArcGIS Online Notebook environment.  

The following files worked in the `add` function:

- JPG
- PDF
- CSV

And the following did not work:

- XLSX
- DOCX

Inserting DOCX files into the `add` function does work locally in 1.9.1 (and 2.0.1). 

**To Reproduce**

1. Manually upload a Word Document file in the `/arcgis/home` folder
2. Reference that file in the following code snippet

```python
GIS('home')
template_flayer = FeatureLayer('https://my-feature-layer-with-attachments-enabled')
dataset = '/arcgis/home/test.xlsx'
template_flayer.attachments.add(oid=new_oid, file_path=dataset)
```
error:
```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/tmp/ipykernel_21/645532613.py in <module>
      7 # dataset = '/arcgis/home/test.csv'
      8 # buf.seek(0)
----> 9 template_flayer.attachments.add(oid=new_oid, file_path=dataset)

/opt/conda/lib/python3.7/site-packages/arcgis/features/managers.py in add(self, oid, file_path, keywords)
    497 
    498         """
--> 499         return self._layer._add_attachment(oid, file_path, keywords=keywords)
    500 
    501     def delete(self, oid, attachment_id):

/opt/conda/lib/python3.7/site-packages/arcgis/features/layer.py in _add_attachment(self, oid, file_path, keywords)
    524                 attach_url = self._url + "/%s/addAttachment" % oid
    525             files = {"attachment": file_path}
--> 526             res = self._con.post(path=attach_url, postdata=params, files=files)
    527             return res
    528         else:

/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py in post(self, path, params, files, **kwargs)
   1077             file_name=file_name,
   1078             try_json=try_json,
-> 1079             force_bytes=kwargs.pop("force_bytes", False),
   1080         )
   1081 

/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py in _handle_response(self, resp, file_name, out_path, try_json, force_bytes, ignore_error_key)
    623                     return data
    624                 errorcode = data["error"]["code"] if "code" in data["error"] else 0
--> 625                 self._handle_json_error(data["error"], errorcode)
    626             return data
    627         else:

/opt/conda/lib/python3.7/site-packages/arcgis/gis/_impl/_con/_connection.py in _handle_json_error(self, error, errorcode)
    646 
    647         errormessage = errormessage + "\n(Error Code: " + str(errorcode) + ")"
--> 648         raise Exception(errormessage)
    649 
    650     def post_multipart(self, path, params=None, files=None, **kwargs):

Exception: The given key was not present in the dictionary.
(Error Code: 400)
```

**Expected behavior**
Word and Excel files should be able to be uploaded via the Attachment Manager. This is possible in 1.9.1 _locally_ and should also be functional in the ArcGIS Online Notebook environment.

**Platform (please complete the following information):**
 - OS: ArcGIS Online Notebook environment
 - Browser Chrome
 - `1.9.1`

**Comment by nanaeaubry** [comment]
Hello,

Using arcgis 2.0.1 and Notebooks I am unable to reproduce your issue. When I use your test code above with my feature layer and with a doc and excel I get a successful result:

![image](https://user-images.githubusercontent.com/19919283/182464287-0c1c66ac-b3ed-4bbd-8c22-dbd570b3750c.png)

The error you are getting is related to the oid not being correctly set. Try setting it to an existing object id value, you can use the `query()` method on the feature layer to see what that should be.

Example of code I ran:
```
template_flayer = item.layers[0]
dataset = r'C:\ipython_workfolder\Data\Excel\Leaf_Pickup_Routes.xlsx'
res = template_flayer.attachments.add(oid="3", file_path=dataset)
```

**Comment by freestok** [comment]
Hello,

Thank you for taking a look into this. Looks like you are running Notebooks locally, but I noted that I was using the Notebooks inside of **ArcGIS Online**. That environment uses 1.9.1, and I don't believe I can use 2.0.1 within **ArcGIS Online**.  

Please do another test within ArcGIS Online and see if that works. I have assured the OID exists in the dataset, and have tried converting it to a string (as the documentation says it should be), and as an integer. This issue should be reopened.

**Comment by nanaeaubry** [comment]
I am happy to check and confirm that it does not work in Online, however we do not do patches so you would have to wait for it to upgrade in Online or use it locally. 

I believe there is a way to change your version in online but I would contact the ArcGIS Online team for help with that.

**Comment by freestok** [comment]
Sounds good, thank you. Since it seems to be an environment issue, do you know who I could follow-up with on the ArcGIS Online team? Or who I could contact on switching environments in ArcGIS Online? I have not found any resources so far.

**Comment by achapkowski** [comment]
@freestok I would submit a request with support on switching underlying notebook runtimes for existing notebooks.
