### ISSUE TITLE
Add service manifest_xml as a service property

### ISSUE THREAD

**Issue by andrewrudin-austin** [Esri/arcgis-python-api#1316]
Although the service manifest.json is available, it does not include as much detail as the manifest.xml.   Most notably, I've seen that the manifest.json strips out the schema owner name for feature classes hosted in an Oracle geodatabase, and this is important for linking the service with feature classes for researching service to database object dependencies.

```python
<insert your code here>
```

**Describe the solution you'd like**
Please add manifest_xml as a separate property of a service.  It can be a separate property/method from the json one.

**Describe alternatives you've considered**
I'd much rather have each layer and table in a service have a property that tells me the feature class it's referencing and any definition query against the feature class that's been hardcoded into the service.  But I don't see anything like that in REST, and besides the database connection properties are store in the manifest at the service level.
**Additional context**

**Comment by nanaeaubry** [comment]
This has been added and will be found in the next release, thank you!
