### ISSUE TITLE
Extract email addresses for all users of a group, not just organisation users

### ISSUE THREAD

**Issue by geompc** [Esri/arcgis-python-api#1336]
I'm unable to get email addresses for external users who have been invited to an ArcGIS Online group and are a member. This makes it difficult to notify them of maintenance periods or changes related to group content etc.

I'd like to be able to extract email addresses for all users in a group, not just organisation users. I can get usernames for both internal and external users but not email addresses.

I don't appear to be the only one struggling with this [https://community.esri.com/t5/arcgis-api-for-python-questions/is-it-possible-to-get-email-addresses-for-all/m-p/776259](https://community.esri.com/t5/arcgis-api-for-python-questions/is-it-possible-to-get-email-addresses-for-all/m-p/776259)

**Comment by nanaeaubry** [comment]
We will look into this, thanks!

**Comment by nanaeaubry** [comment]
We looked with the Online team and this is on their radar and in the works. Until it is an available capability Online we are unable to get the information through the Python API. Once it is available there we will include it as well. :)
