### ISSUE TITLE
Spatial reference error

### ISSUE THREAD

**Issue by era001** [Esri/arcgis-python-api#1338]
Spatially enabled dataframe join throws error even though spatial references are the same.

**To Reproduce**
```python
sdf.spatial.sr
```
{'wkid': 2284}
```python
sdf2.spatial.sr
```
{'latestWkid': 2284, 'wkid': 102747}
```python
sj_sdf = sdf.spatial.join(sdf2)
```
error:
```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-38-9250b9e0e6db> in <module>
----> 1 sj_sdf = sdf.spatial.join(aoi_sdf)
      2 sj_sdf.head()

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py in join(self, right_df, how, op, left_tag, right_tag)
   1552             )
   1553         if self.sr != right_df.spatial.sr:
-> 1554             raise Exception("Difference Spatial References, aborting operation")
   1555         index_left = "index_{}".format(left_tag)
   1556         index_right = "index_{}".format(right_tag)

Exception: Difference Spatial References, aborting operation
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Python API Version 2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.
Changed line 1553 in ~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py
From
```python
if self.sr != right_df.spatial.sr:
```
to
```python
if self.sr.wkid not in right_df.spatial.sr.values():
```

**Comment by nanaeaubry** [comment]
Hello, I will take a look at this.

Do you have a reproducible code block or script I can use?

**Comment by nanaeaubry** [comment]
This has been addressed and will be fixed in the next release, thank you!
