### ISSUE TITLE
`as_dict` parameter name is misleading

### ISSUE THREAD

**Issue by azinsharaf** [Esri/arcgis-python-api#1339]
**Describe the bug**
The result of `gis.content.advanced_search` is always a dictionary regardless of `as_dict` parameter value.
They have different contents for sure but they are still "dictionary". The parameter name could be misleading.

**To Reproduce**
```python
from arcgis.gis import GIS

gis = GIS(url="home")
search_results = gis.content.advanced_search(query='Well', max_items=1, as_dict=False)

print(type(search_results))
print(search_results)
```
error (result):
```python
<class 'dict'>
{'query': 'Well', 'total': 10000, 'start': 1, 'num': 1, 'nextStart': 2, 'results': [<Item title:"
" type:StoryMap owner:RileyiShaw>]}
```

**Screenshots**
api reference document: 

![image](https://user-images.githubusercontent.com/10101468/187793151-be888b3c-acc2-4880-8bf8-ac5003b38cfd.png)

**Expected behavior**
Using a better name for the parameter.

**Platform (please complete the following information):**
 - OS: `Windows 10`
 - Browser `Chrome`
 - Python API Version: `1.9.1`

**Comment by nanaeaubry** [comment]
Hello,

What it is referring to is not the response of the method but the response of the rest call. As you can see in your dictionary above, the results are returned as a list of `Item` objects.
If you put as_dict = True then the results will be a list of dictionaries. 

We will add some better phrasing, thank you for bringing this up.
