### ISSUE TITLE
License information does not show in ArcGIS Pro Python Package Manager

### ISSUE THREAD

**Issue by mschenker** [Esri/arcgis-python-api#134]
When installing or selecting the ArcGIS Python API in the Python Package Manager of ArcGIS Pro (2.0.1)
 and also previous versions), the "Terms and Conditions" list the API as a third-party package where license terms were not found. This should be corrected to refer to the Apache 2.0 license.

![pythonpackagemanager_nolicense](https://user-images.githubusercontent.com/738677/29807458-6ce09ab8-8c94-11e7-9ef1-c6d656610985.PNG)

**Comment by rohitgeo** [comment]
Thanks @mschenker for reporting this. We're in touch with the Pro team to get this corrected. The license of the ArcGIS API for Python is the Esri Master License though, not Apache 2.0 (at this time).

**Comment by mschenker** [comment]
Hi @rohitgeo
Wow, fast reaction.
Regarding the license: You might want to update https://github.com/Esri/arcgis-python-api/blob/master/LICENSE then, this states the following:
"Esri/arcgis-python-api is licensed under the Apache License 2.0"

**Comment by rohitgeo** [comment]
The license for the Esri/arcgis-python-api SDK repository is Apache 2.0, so the  https://github.com/Esri/arcgis-python-api/blob/master/LICENSE file is correct. However, the license for the ArcGIS API for Python package is Esri Master License as is correctly reported on the anaconda site at https://anaconda.org/Esri/arcgis

For some reason, Pro is not picking it up, We're in touch with the Pro team about this.
