### ISSUE TITLE
Cannot create working deep learning Env in arcpro 3.0.1

### ISSUE THREAD

**Issue by Moustafa4** [Esri/arcgis-python-api#1341]
Last night, I was trying to learn about conda and environments and I did the introductory tutorial.  The biggest issue was really running the Python Command Prompt as an administrator.  So, I created a new environment from the Command Prompt using conda install --name and it appears to work just fine.  However, when I try to activate it in ArcGIS Pro, it says it is Broken environment cannot be used. 

![Capture](https://user-images.githubusercontent.com/112592160/188199395-a4e44a61-8c82-4a87-a084-37792d24986f.PNG)

I followed this steps but I still have this error" Broken environment cannot be used
is this steps Right to install new env and download Deep learning Library?  

1-I installed New OS windows
2- download arcgis pro 3.0.0
3- update it to 3.0.1
4- open CMD as administrator
5- conda create --name geoai python 3.9.12
6- conda activate geoai
7- conda install -c esri arcgis
8-conda install -c esri deep-learning-essentials
9-conda install -c esri arcgis_learn python=3.9.12

**Comment by shivanip32** [comment]
Hi Moustafa, when we create environment  using `conda install --name`  that environment doesn't have Pro Packages, so for creating a deep learning environment for Pro can you try these steps:
1. Go to search tab and type **Python Command Prompt** -> Click on **Run as administrator**
![image](https://user-images.githubusercontent.com/51908044/189817744-2b8b2074-9ee8-44f9-9d9d-7b96dfdb95f6.png)
2.  Use this command for creating a new environment : `conda create --clone arcgispro-py3 -n geoai --pinned`
In the above command we cloned the Pro default environment now you can the remaining commands.
