### ISSUE TITLE
[question] max API requests per second

### ISSUE THREAD

**Issue by wandrzejczak** [Esri/arcgis-python-api#1352]
Hello,

I cannot find in the documentation the rate limit and how many requests per second I'm allowed to send for Geocoding. 
Could anyone please let me know?

Wojtek.

**Comment by nanaeaubry** [comment]
We have this information: https://developers.arcgis.com/python/guide/part4-batch-geocoding/#Batch-sizes-(max-and-suggested-batch-sizes)

What type of geocoding are you doing since this can affect the number?

**Comment by wandrzejczak** [comment]
Hello @nanaeaubry, I've a few thousand addresses to decode, and I'd need to batch them, but my request stays unanswered; how many batch requests can I send per second? I've 10 batch requests with 150 addresses inside; what is the recommended time interval I can send them?

**Comment by nanaeaubry** [comment]
@wandrzejczak  I have asked someone on the geocoding team and once we get a reply I will post it

**Comment by nanaeaubry** [comment]
@wandrzejczak  Here is the response I got from the team:

The answer to your question is different based on the locator you're using. If you are using a locator you published/created there is no rate limit... you can send 4 batch requests simultaneously, but you'll make sure your backend geocode service is scaled up to handle that kind of load. For example, 4 simultaneous batch requests requires 4 instances to be running. You can adjust the number of instances for a service in ArcGIS Server Manager.

Generally, set the min instances = max instances = 4 (or whatever number you want), but best practice is to set them to the same value, so you know for sure how many instances are running.

Another thing to explore is best performance is generally achieved when sending less batches, but larger ones. So if you use batch size = 1000, that'll be faster than sending 6 or 7 batches of 150 addresses.

If you're sending batches to the ArcGIS World Geocoding Service, send 1 request at a time with batch size 150 or 1000. We do NOT want anyone sending more than 1 request at a time to the world service.

As far as rate limiting, sequential requests is fine. So once you submit a request, wait for it to come back, then send another one should be fine for the World Geocoding Service. For your own published geocode service, there is no limits.

**Comment by nanaeaubry** [comment]
@wandrzejczak If you need further help please reach out and we can discuss this over email so I can link you with the correct team.
