### ISSUE TITLE
Job failed when publishing JSON file

### ISSUE THREAD

**Issue by jrmyyy** [Esri/arcgis-python-api#1359]
I have a JSON file that I want to publish on a notebook (conda) used on maps.arcgis.com. As an example and for test, I replaced the JSON file directlty with a dictionnary but I have the same problem with a file.  It looks like the problem doesn't come from the data as I have tried many différent ones. 
This is my code: 
```

from arcgis.gis import GIS
    from IPython.display import display
    gis = GIS(username="XX", password="XX")
    
    data = { "type": "FeatureCollection", "features": [ { "type": "Feature", "geometry": { "type": "Point", "coordinates": [20, 10] }, "properties": { "name": "null island" } } ] }
    
    item_properties_dict = {"type": "GeoJson",
    'title': 'Test',
    'tags': 'Test',
    'snippet': 'Test',
    "text":data}
    
    item = gis.content.add(item_properties = item_properties_dict)
    item.publish()
```

When I execute this code, I have the following error:

```

    ---> 43 item.publish()
    
    File /opt/conda/lib/python3.9/site-packages/arcgis/gis/__init__.py:13921, in Item.publish(self, publish_parameters, address_fields, output_type, overwrite, file_type, build_initial_cache, item_id, geocode_service)
    13919 return Item(self._gis, ret[0]["serviceItemId"])
    13920 else:
    > 13921 serviceitem_id = self._check_publish_status(ret, folder)
    13922 return Item(self._gis, serviceitem_id)
    
    File /opt/conda/lib/python3.9/site-packages/arcgis/gis/__init__.py:14273, in Item._check_publish_status(self, ret, folder)
    14271 # print(str(job_response))
    14272 if job_response.get("status") in ("esriJobFailed", "failed"):
    > 14273 raise Exception("Job failed.")
    14274 elif job_response.get("status") == "esriJobCancelled":
    14275 raise Exception("Job cancelled.")
    
    Exception: Job failed.
```

Do you have any idea where the problem might be coming from or any solutions to solve it?

**Comment by nanaeaubry** [comment]
Hello,

GeoJson and Json are two different file types. It see in the item properties you say it is type geojson but in the description you say you are trying to upload a json file. I think you need to get this resolved and it might solve your problem.

Please let me know if this helps or if the issue continues to persist

**Comment by jrmyyy** [comment]
> Hello,
> 
> GeoJSON and JSON are two different file types. It see in the item properties you say it is type GeoJSON but in the description you say you are trying to upload a JSON file. I think you need to get this resolved and it might solve your problem.
> 
> Please let me know if this helps or if the issue continues to persist

Hello, thanks for your help. Unfortunately, changing type in the properties doesn't change anything.

**Comment by nanaeaubry** [comment]
@jrmyyy Have you tried to change the file type to a .geojson? You might have more luck with that. 

You might be able to try some online converter or if you try the solution suggested here: https://gis.stackexchange.com/questions/73756/is-it-possible-to-convert-regular-json-to-geojson

Let me know if it works after this

**Comment by jrmyyy** [comment]
Unfortunately, it is not working. Actually, even if I don't use a file but just a dictionnary like the example code above, it is not working. I don't know what to do like if the problem comes from the content of the dictionnary or the properties or something else.

**Comment by jrmyyy** [comment]
> @jrmyyy Have you tried to change the file type to a .geojson? You might have more luck with that.
> 
> You might be able to try some online converter or if you try the solution suggested here: https://gis.stackexchange.com/questions/73756/is-it-possible-to-convert-regular-json-to-geojson
> 
> Let me know if it works after this

Unfortunately, it is not working. Actually, even if I don't use a file but just a dictionnary like the example code above, it is not working. I don't know what to do like if the problem comes from the content of the dictionnary or the properties or something else.

**Comment by achapkowski** [comment]
Here is a sample on publishing geojson:

1. The first of the code downloads the geojson file
2. The second part adds and publishes the Geojson file.
3. Finally, it queries the FeatureLayer as a FeatureSet. 

```python
import os
import uuid
import tempfile
import requests
from arcgis.gis import GIS, ContentManager, Item
from arcgis.features import FeatureSet

url: str = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"
service_name: str = "Earthquake_All_day"
dl_file: str = os.path.join(
    tempfile.gettempdir(), f"{uuid.uuid4().hex[:8]}.geojson"
)  # os.path.basename(url))
with requests.Session() as session:
    session.stream = True

    with open(dl_file, 'wb') as writer:
        req: requests.Response = requests.get(url)
        for content in req.iter_content(1024):
            writer.write(content)


gis: GIS = GIS(
    profile='your_online_profile',
)
cm: ContentManager = gis.content

item: Item = cm.add(
    item_properties={
        "title": "A GeoJSON file",
        "type": "GeoJson",
        "extension": "geojson",
        "enablePublishing": True,
    },
    data=dl_file,
)

published_item: Item = item.publish(
    publish_parameters={
        "name": service_name,
        "maxRecordCount": 2000,
        "hasStaticData": True,
        "layerInfo": {"capabilities": "Query"},
    },
)

fs: FeatureSet = published_item.layers[0].query()
print(fs)
```
