### ISSUE TITLE
MapView: setting height has no effect, map centered on the left side

### ISSUE THREAD

**Issue by warmdev** [Esri/arcgis-python-api#136]
One of the sample notebooks (https://github.com/Esri/arcgis-python-api/blob/master/samples/02_power_users_developers/using_geometry_functions.ipynb) shows that map height can be changed through `map1.height = '650px'`. However, this has no effect (tested on both the Esri live demo as well as local notebooks). Furthermore, the `MapView` class (https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.widgets.html#mapview) has no `height` attribute.

Additionally, maps seem to be always centered on the left side of the screen. 

Code:

```python
from arcgis.gis import GIS
gis = GIS()
map1 = gis.map("Central Park, New York", zoomlevel=9)
map1.height = "800px"
map1
```

Result:

![arcgis_mapview_bug](https://user-images.githubusercontent.com/8269026/30090745-7586b964-9283-11e7-966b-975a71cd15b5.png)

**Comment by rohitgeo** [comment]
Due to changes in ipywidgets, the following code needs to be used to change the height of the map widget:
```map1.layout.height='600px'```

We will correct the sample code and look into the centering issue - thanks for pointing it out.

**Comment by rohitgeo** [comment]
I see the sample has been updated. Closing this issue.
