### ISSUE TITLE
show_batch module display has no attribute 'display_html

### ISSUE THREAD

**Issue by Arksi325** [Esri/arcgis-python-api#1361]
Hi all,
I am quite new to coding in general and have been working through some examples for deep learning regarding point clouds.

I am running into an error with the show_batch function(see attached). From other examples this function seems to run through arcgis Pro. 

Any suggestions will be greatly appreciated. Currently running ArcGIS Pro 3.0.2
![error](https://user-images.githubusercontent.com/115769816/195762619-295842b2-f7b8-4b2a-9bc1-e13a5ed03459.PNG)

**Comment by mcampbell1039** [comment]
I am also receiving this same error when using data.show_batch().

**Comment by priyankatuteja** [comment]
@Arksi325 Could you confirm if you are using notebook within arcgis pro?

**Comment by sledgesickle** [comment]
Yes! I was working through this Sample Tutorial:

https://developers.arcgis.com/python/samples/creating-building-models-using-point-cloud-classification/

Using cbm.ipynb Notebook provided in the following download:

https://www.arcgis.com/home/item.html?id=50390f56a0e740ac88c72ae1fb1eda7a

**Comment by priyankatuteja** [comment]
@vbhv14 Could you please look into this? I am able to reproduce the same issue. Additionally, the user has used export_point_dataset class as well. This is not covered in the sample notebook, is that missed out or there's some mistake in the user workflow?

**Comment by vbhv14** [comment]
`export_point_dataset` is not used in the sample notebook,
Pro tool should be used for exporting the data.

This function has been deprecated starting from ArcGIS API for Python version 1.9.0. Export data using Prepare Point Cloud Training Data tool available in 3D Analyst Extension from ArcGIS Pro 2.8 onwards.

**Comment by WangariKimotho** [comment]
I am getting the same error, when following [this notebook](https://geemap.org/workshops/GEE_Workshop_2022_Part2/#analyzing-global-land-cover-data)
from this code:

geemap.bar_chart(
    df,
    x='class',
    y='area',
    x_label='Land Cover Type',
    y_label='Area (km2)',
)

**Comment by priyankatuteja** [comment]
@vbhv14

**Comment by vbhv14** [comment]
`export_point_dataset` is no longer supported and its visualization is not supported.
And for pro exported datasets, this has been fixed now, for the next release of ArcGIS API for Python via PR: #11401
