### ISSUE TITLE
Installation failed in MacOs 

### ISSUE THREAD

**Issue by flaviolicorio** [Esri/arcgis-python-api#1363]
When try to ```pip install arcgis``` return error 
No module named 'setuptools.command.build'

I've tried to upgrade and update setuptools, and try to found the solution but i can't found a solution.

I'm using 
- MacOS Monterey 12.6
- Python 3.8.2
- pip 19.2.3

**Comment by nparavicini7** [comment]
Hi @flaviolicorio, have you tried changing your pip or python versions? When I try to set up an environment with the same specs, it says that pip 19.2.3 requires python 3.6.x or 3.7.x. The current version of pip is 22.2.2, I'd recommend upgrading to that unless there's a specific reason you need to use the older version. Let me know if that fixes the issue!

**Comment by jyaistMap** [comment]
closing pending further communication
