### ISSUE TITLE
Add suport to read, write TopoJson

### ISSUE THREAD

**Issue by hildermesmedeiros** [Esri/arcgis-python-api#1365]
**I'd like to have TopoJson support.
If Esri won't suport it, may be just help mere mortals to convert to json or geojson will suffice.

https://github.com/topojson/topojson-specification

**Describe the solution you'd like**
abilit to read, write topojson, helping us to convert to Spatial Data Frame

**Describe alternatives you've considered**
Installing Geopandas and topojson

**Additional context**
Some Partners companys give us topojson objects. I have a separated env to handle such files now and then.
But I'd like to see it integrated in the arcgis api (If possible in the javascript api to)

**Comment by achapkowski** [comment]
@hildermesmedeiros in what ways do you use topojson?  I've heard of it, but never used anything that really consumed it.  Could you expand why you need it?

**Comment by hildermesmedeiros** [comment]
@achapkowski 
I work at Imagem, distributor of Esri in Brazil (I'm analyst-consultant).
So, some clients just use this type of data, to use it in arcgis workflow (portal, agol, python, javascript) some just do this kind of ETL.

Imagine you have a portal, one companie you work with sends you that data. I just want people to do this ETL with python too, if possible.

topjson, to featureclass;
topojson to featurelayer, and so on.

Nevertheless, I can't explain to you in detail without arguing the collegue that asked the favor. I have no idea what so ever why people use that data.

As far I can tell, reading the file specs.... It is quite bold: 

https://github.com/topojson/topojson/blob/master/README.md

""As a result, TopoJSON is substantially more compact than GeoJSON, frequently offering a reduction of 80% or more even without simplification.""

I would test this statment, but to me now, it is an ocasional ETL.

**Comment by nanaeaubry** [comment]
Hello! We will keep this in our backlog and if we get more user requests for it we can move it up the list of tasks but for now we do not have a timeline as to when this will be implemented.
Thanks!
