### ISSUE TITLE
esridocker/arcgis-api-python-notebook doesn't load map widget

### ISSUE THREAD

**Issue by devilsgeographer** [Esri/arcgis-python-api#1371]
When pulling the current docker container esridocker/arcgis-api-python-notebook, and running per instructions here:  https://developers.arcgis.com/python/guide/install-and-set-up/#installation-as-a-docker-image

We get the error:

Error displaying widget: model not found

272.eb0d340d1eec40ac564f.js:1 Could not instantiate widget
(anonymous) @ 272.eb0d340d1eec40ac564f.js:1
272.eb0d340d1eec40ac564f.js:1 Error: Could not create a model.
Uncaught (in promise) Error: Module arcgis-map-ipywidget, semver range 2.0.1 is not registered as a widget module

**Comment by devilsgeographer** [comment]
![image](https://user-images.githubusercontent.com/17552717/198348884-6e1a6295-7998-4036-a8f4-8a165c2ee991.png)

![image](https://user-images.githubusercontent.com/17552717/198348837-37358267-35ac-4df1-87e7-0b818b6efb30.png)

**Comment by devilsgeographer** [comment]
same issue with v2.0.0 image

**Comment by devilsgeographer** [comment]
same issue with v1.9.1 image

**Comment by devilsgeographer** [comment]
Will this be resolved at some point?

**Comment by nanaeaubry** [comment]
Hello, 
I think the issue could be that you are using jupyter labs. We currently don't support for jupyter labs on only jupyter notebooks. Trying there could solve your issue

**Comment by devilsgeographer** [comment]
Super frustrating, this should be noted somewhere in the instructions.

**Comment by hildermesmedeiros** [comment]
I'm using jupyter labs, both in docker and in my on pc. 
I did the steps below:
https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/
