### ISSUE TITLE
help using oauth2 in python workflow

### ISSUE THREAD

**Issue by hildermesmedeiros** [Esri/arcgis-python-api#1374]
I'd like to suggest to some one to change the explanation on auth2 with python.
I'd like to read a better explanation, if it is for safety reasons.

![image](https://user-images.githubusercontent.com/20046591/198706176-e676b23e-447d-4f48-aab7-b48c0f04590f.png)
![image](https://user-images.githubusercontent.com/20046591/198710361-c769442f-e133-4ff4-b612-e70f335584ad.png)

One can configure the oauth2 avoid the need to create built-in user to automations, i.e, automating something to use in conjunction with geoevent or any other workflow. 

But this page will make many think  - this is not possible with python:
https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/
![image](https://user-images.githubusercontent.com/20046591/198711644-274ac84f-ae4c-4767-9a25-63f045f95b4c.png)

```diff
! Is there a particular reason to prefer bult-in over using outh2 and client_id, client_secret?
```

**Comment by Ardy-EDFRE** [comment]
@hildermesmedeiros Hey there! I would recommend not using the oauth process for any automated tasks. The best and most likely safest case is to login in using the original GIS login with user credentials.

You can setup your username and password in your System Environmental Variables so they will be hidden and not present in your code. I would suggest creating a user account that is meant for all arcgis Python connections and operations & use that for all future tasks, tools and scripts. 

``` python
import os 
from arcgis import GIS

Username = os.environ.get('GISUSER')
Password = os.environ.get('GISPASS')

 gis = GIS("https:??yourportal.playground.com?portal".replace(':??', '://').replace('?', '/'),
              Username, Password)
```

**Comment by hildermesmedeiros** [comment]
@Ardy-EDFRE, thank you, but I already do this with a mix of encryption and vault, for some bult-in . I would not advise you to save plain password on envs  always, handle it with care, well you know your stuff a guess.

IT logs, system logs, system bugs, bug report, harwadre report, etc, there are many ways that env variables could just go to some one without you knowing....

Neverteless, username, and password are fore built-in or domain users, and in some case domain users won't work. Instead of creating a built-in editor, it should be easier just to configurate the auth2, as far as I know some users have a Limited number of editors, publishers.

But it makes more sense to me publisher to config its layers acess and giving developers acess then giving devolepers bultin...
to me is not clear the safitness of the approach with oauth2 clientid, clientsecret, because of python docs.

**Comment by achapkowski** [comment]
@hildermesmedeiros have you tried using a vault to store your password then passing it along that way?  I tends to work best or using the system's credential stores?  We call them profiles in the API.

**Comment by hildermesmedeiros** [comment]
![image](https://user-images.githubusercontent.com/20046591/212067398-2e69cee1-f78b-424c-ad9b-d84c15574fc2.png)
![image](https://user-images.githubusercontent.com/20046591/212067469-adff57f9-2aa0-42a1-b7a6-69c6a709ec10.png)

@achapkowski , My point is, why doing this is not documented or it is not recommended?

**Comment by mo-sarahgeijsels** [comment]
Hello, I am looking for a solution to connect to AGOL using a script that runs in the background. To my understanding that would be an example of a "Non-Interactive Login Experience" as mentioned in the [link ](https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/#user-authentication-with-oauth-20) shared by @nanaeaubry . The link says "The recommended suggestion for non-interactive login scripts is to use the built-in identity provider instead of SAML.", but if my built-in user has MFA enabled, it won't be possible to do this non-interactively. Is it "recommended" or OK to use the OAuth method in this case? I haven't found an answer on how to create non-interactive login scripts when MFA is enabled. Any help is welcome!
