### ISSUE TITLE
ObjectId has been updated 

### ISSUE THREAD

**Issue by cyanineeee** [Esri/arcgis-python-api#1375]
When I downloaded and tried to use this file, an error occured. 
The code 
'ndvi_colorized = apply(delhi_image, 'NDVI Raw')
ndvi_colorized'
prompt a bug 
"Unable to complete operation.
Failed to open raster dataset
(Error Code: 400)"
Thus I check code which over this part, and found that the output of df showed the objectid of 2017-10-15 is defferent from the example.
changed from '2095521' to '2437835'.
Finally I reset the objectid in the error codes, this bug disapear.

**Comment by cyanineeee** [comment]
> 

I'm sorry for making a confusing problem description, 
the file I downloaded called 'How much green is Delhi as on 15 Oct 2017?' 
which address is ['arcgis-python-api/samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-15-oct-2017.ipynb '](https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-15-oct-2017.ipynb)
the error happened in the part 'Filter imageries based on cloud cover and Acquisition Date'
![8LVHA@R@(UAOD2T{$EJITWE](https://user-images.githubusercontent.com/94979331/199152950-39cf3bf0-c5a7-4267-9507-580a5fad05d9.png)
![P2)$R5QY_V_DC~{PMYC_5SE](https://user-images.githubusercontent.com/94979331/199153055-32158d14-3d01-449c-a6aa-10a16778e4b1.png)
The solution I founde was to change the code 
`delhi_image = landsat.filter_by('OBJECTID=2095521')`
to
`delhi_image = landsat.filter_by('OBJECTID=2437835')`

The result is fine:
![09UWP25PG7Q~WG4K_7R173V](https://user-images.githubusercontent.com/94979331/199153356-8b6660c5-3d10-4856-846d-a13c4b67324c.png)

**Comment by cyanineeee** [comment]
> Can you provide us with an example item so we can try this on our end and more complete code as well? thank you It is not very clear what the issue is without having a better example or some screenshots to depict the changes

I'm sorry for making a confusing problem description,
the file I downloaded called 'How much green is Delhi as on 15 Oct 2017?'
which address is ['arcgis-python-api/samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-15-oct-2017.ipynb '](https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-15-oct-2017.ipynb)
the error happened in the part 'Filter imageries based on cloud cover and Acquisition Date'
![](https://user-images.githubusercontent.com/94979331/199152950-39cf3bf0-c5a7-4267-9507-580a5fad05d9.png)
![](https://user-images.githubusercontent.com/94979331/199153055-32158d14-3d01-449c-a6aa-10a16778e4b1.png)

The solution I founde was to change the code
`delhi_image = landsat.filter_by('OBJECTID=2095521')`
to
`delhi_image = landsat.filter_by('OBJECTID=2437835')`

The result is fine:
![](https://user-images.githubusercontent.com/94979331/199153356-8b6660c5-3d10-4856-846d-a13c4b67324c.png)

**Comment by nanaeaubry** [comment]
@cyanineeee Ok thank you for the better description, @CMPeng can you help with this since it touches on the guides? 
Thanks!

**Comment by CMPeng** [comment]
Thanks @cyanineeee for reporting this issue. The object_id is the unique id that the specific image tile got stored on the cloud with, and theoretically should not change unless the backend has cleared this image out of the archive. I will check with the ArcGIS Online folks to have this straightened out. CC @nanaeaubry

**Comment by CMPeng** [comment]
Hi @cyanineeee Because the esri-living-atlas has been always updating its supported temporal range of the LandSat Data, they cannot guarantee for the `OBJECTID` being preserved or a certain set of images being archived in this particular raster datastore forever. For most cases, they usually only keep the latest 10 years of satellite data. That being said, a better way to have this `objectid` selection more automated, is to choose a narrower time range, and select the id specifically, e.g.
```
selected = landsat.filter_by(where="(Category = 1) AND (cloudcover <=0.05)",
                             time=[datetime(2017, 10, 10), datetime(2017, 10, 20)],
                             geometry=arcgis.geometry.filters.intersects(delhi_geom))

df = selected.query(out_fields="AcquisitionDate, GroupName, CloudCover, DayOfYear", 
                    order_by_fields="AcquisitionDate").sdf
df['AcquisitionDate'] = pd.to_datetime(df['AcquisitionDate'], unit='ms')
df
```
We can see that the filtered result will only have one timeframe - 2017/10/15, then we can just indicate this particular id, as in,
```
delhi_image = landsat.filter_by('OBJECTID=' + str(df['OBJECTID'][0])) # 2017-10-15 
```
This should be working regardless of how the object id changes then.
