### ISSUE TITLE
Vehicle training data not found

### ISSUE THREAD

**Issue by mhogeweg** [Esri/arcgis-python-api#1379]
**Describe the bug**
the vehicle training data cannot be found:
https://github.com/Esri/arcgis-python-api/tree/master/samples/04_gis_analysts_data_scientists/data/vehicle_training_data.zip

**To Reproduce**
- open ArcGIS API for Python page "Vehicle detection and tracking using deep learning": https://developers.arcgis.com/python/samples/vehicle-detection-and-tracking/
- scroll to section [Prepare data that will be used for training](https://developers.arcgis.com/python/samples/vehicle-detection-and-tracking/#prepare-data-that-will-be-used-for-training)
- click the link [here](https://github.com/Esri/arcgis-python-api/tree/master/samples/04_gis_analysts_data_scientists/data/vehicle_training_data.zip)

error:
- note the GitHub 404 page

**Expected behavior**
The vehicle sample dataset is downloaded

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by priyankatuteja** [comment]
https://github.com/Esri/arcgis-python-api/pull/1386 @CMPeng  This PR will fix the issue

**Comment by CMPeng** [comment]
Thanks @priyankatuteja 
Hi @mhogeweg, please revisit the page, and the link shall be restored/fixed by our colleague. Closing this issue.
