### ISSUE TITLE
Add hard date parameters to item usage method

### ISSUE THREAD

**Issue by andrewrudin-austin** [Esri/arcgis-python-api#1380]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when trying to use the item.usage method to obtain AGO item usage history data, because it only allows me to enter relative dates as parameters to filter dates.  Example '7D' for past 7 days, or '30D' for past 30 days. This makes the results different depending on when you run the query.  It's also frustrating because i cannot access the full 2 year usage history of my items, because the maximum filter I can enter for the date_range parameter is 1Y for 1 year. It would be easier for me if I could just enter 2 dates for the start and end of my filter as parameters.  

```python  (This is an example from an esri sample of how I'd use it today with just relative date filter)
gis = GIS("https://arcgis.com", "user_name")
content = gis.content.search(query="", sort_field="title", sort_order="asc", max_items=2)
for item in content:
     var_usage = item.usage ('1Y'))
     print(var_usage)
     ##at this point I'd actually be taking the results from items and writing them to a standalone table in a geodatabase or a feature service along with usage data from the other items in this loop
```

**Describe the solution you'd like**
I'd like two parameters added for me to enter start and end dates for the date range filter.  So for example, if I want to grab all usage for the 3rd quarter of 2022 (July, August, September), I'd enter a start date of 07-01-2022, and an end date of 09-31-2022).  The results would contain one row/element for each day in that range, including the start and end dates, similar to how the results are returned now.  

It would also be helpful if the end date could be optional, so if I want to grab usage from the beginning of the year until now, I just enter a parameter of start_date='2022-01-01' and then leave the end_date parameter off.  The results would hen contain one row for each day from the start date until the time I'm running my script.

**Describe alternatives you've considered**
Manually hitting the undocumented item usage REST API endpoint which I see used when the chart on the Item usage webpage is populated, and also used on the backend of the existing Python Item.Usage method.  I see the rest endpoint does provide paramters for inputing start/end dates in UNIX time, although I see it limits results to 60 days so you have to iterate to get all the history:  https://myorgname.arcgis.com/sharing/rest/portals/<orgId>/usage?f=json&startTime=1609459200000&endTime=1614470400000&period=1d&vars=num&groupby=name&etype=svcusg&name=<myItemId>

**Additional context**

**Comment by nanaeaubry** [comment]
Hello this has been added and will be in the next release of the python API. Thanks!
