### ISSUE TITLE
Plot Method does not work on point created using from_xy method

### ISSUE THREAD

**Issue by DavidAnderson-USFS** [Esri/arcgis-python-api#1390]
**Describe the bug**
The plot method does not work on point created using from_xy method.
I created a pandas dataframe from a CSV file,  converted latitude and longitude columns to a point using the from_xy method, then when I tried plot, nothing appears.

To verify no data issues, I used ArcGIS Pro to create a point layer from the CSV file, then loaded that featureclass as spatial dataframe.  The plot method works as expected on that data.

**To Reproduce**
Original:
```
import pandas as pd
from arcgis.features import GeoAccessor,GeoSeriesAccessor
df = pd.read_csv(r".\NM_PLOT.csv")
sedf = pd.DataFrame.spatial.from_xy(df=df,y_column='LAT',x_column='LON',sr=4326)
sedf[0:10].spatial.plot()
```
This produces a blank plot.

Test
```
arcpy.management.XYTableToPoint(r".\NM_PLOT.csv", r".\Default.gdb\NM_PLOT_XYTableToPoint", "LON", "LAT", None, 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision')
ap_sedf = pd.DataFrame.spatial.from_featureclass(r'.\Default.gdb\NM_PLOT_XYTableToPoint')
ap_sedf[0:10].spatial.plot()

```
This produces a map with 10 points as expected.

```python
<insert your code here>
```
error:
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**

**Platform (please complete the following information):**
 - **Windows 11**
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`
 - **1.9.1**

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
Hello I am unable to reproduce your issue: Currently running on 2.0.1 
![image](https://user-images.githubusercontent.com/19919283/204397074-fcca56de-9d95-4352-ad74-f2eea61edc9f.png)

**Comment by DavidAnderson-USFS** [comment]
Hi,
Thanks for the prompt response.

I am on 1.9.1.  So you really haven’t fully tested the issue by using the  2.0.1 version.   I ran into this while testing response to this community post, https://community.esri.com/t5/arcgis-api-for-python-questions/how-to-plot-a-specific-geometry-column-of-spatial/m-p/1235165#M8057
Thus there is one other person that can reproduce the not plotting issue.

Please send me your data so I can test on my system.





[Forest Service Shield]
David Anderson
Regional Analyst
Forest Service
Southwestern (R3) Regional Office - Planning And Watershed
p: 505-842-3217
***@***.******@***.***>
333 Broadway Blvd SE
Albuquerque, NM 87102
www.fs.usda.gov<https://www.fs.usda.gov/>
[USDA Logo]<https://usda.gov/> [Forest Service Twitter] <https://twitter.com/forestservice>  [USDA Facebook] <https://www.facebook.com/pages/US-Forest-Service/1431984283714112>
Caring for the land and serving people

**Comment by nanaeaubry** [comment]
Hello, we do not patch our versions so if you can upgrade to 2.0.1 that would be the ideal solution. 
Here is my file for reference: 
[capitals.csv](https://github.com/Esri/arcgis-python-api/files/10108619/capitals.csv)

**Comment by DavidAnderson-USFS** [comment]
Thanks for the info.  I had been wondering if the Python API could be updated outside  of the ArcGIS Pro update cycle.

The data helped.  Before updating I ran the process using the data you provided.  Which worked as expected.  I then redid with my data – same results of no plotting.
This suggests it is a data issue.  After a bit of investigation I determined that it is related to the number of data columns.  My data had 73 columns.  When I subset the data to just using 2 (latitude and longitude) the XY conversion worked fine and the data plotted just fine.
***@***.***

I have attached my data set for your own investigation into the issue.




[Forest Service Shield]
David Anderson
Regional Analyst
Forest Service
Southwestern (R3) Regional Office - Planning And Watershed
p: 505-842-3217
***@***.******@***.***>
333 Broadway Blvd SE
Albuquerque, NM 87102
www.fs.usda.gov<https://www.fs.usda.gov/>
[USDA Logo]<https://usda.gov/> [Forest Service Twitter] <https://twitter.com/forestservice>  [USDA Facebook] <https://www.facebook.com/pages/US-Forest-Service/1431984283714112>
Caring for the land and serving people

**Comment by nanaeaubry** [comment]
@DavidAnderson-USFS 

Ok I see I will investigate with your data then and update if I find anything. thank you!
