### ISSUE TITLE
Add filter parameter to the ContentManager search functions

### ISSUE THREAD

**Issue by BMannell** [Esri/arcgis-python-api#1413]
**Describe the solution you'd like**
Currently the `search` and `advanced_search` functions do not utilize the filter parameter of the search endpoint.

This is would be very useful when you want to target specific items based on tags or naming conventions.

[Filter | Search API](https://developers.arcgis.com/rest/users-groups-and-items/search.htm#:~:text=bbox%3D%2D118%2C32%2C%2D116%2C34-,filter,-Structured%20filtering%20is) 

[search | ContentManager | Python API](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.ContentManager.search)

[advanced_search | ContentManager | Python API](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.ContentManager.advanced_search)

**Describe alternatives you've considered**
The only work arounds now are to have a static list of all the items you want to target, or to write extra code to filter the search results.

[X-Posted on Community Ideas](https://community.esri.com/t5/arcgis-api-for-python-ideas/add-filter-parameter-to-the-contentmanager-search/idi-p/1245078/jump-to/first-unread-message)

**Comment by nanaeaubry** [comment]
Hello thank you for bringing this up, we will add it for the next release 
https://github.com/ArcGIS/geosaurus/pull/9452

**Comment by BMannell** [comment]
@nanaeaubry Has this been implemented yet? I don't see any filter param in the `search` or `advanced_search` docs

**Comment by nanaeaubry** [comment]
@BMannell Thanks for checking on this! You're right it was only added to Group searching. I will add it to the advanced_search as well
