### ISSUE TITLE
to_featureclass function does not convert None values to Null when exporting to featureclass

### ISSUE THREAD

**Issue by EricSamsonG2** [Esri/arcgis-python-api#1415]
**Describe the bug**
When converting a rest service to a spatial dataframe, then to a local featureclass, the text columns that contain nulls are not properly filled out. Pandas converts the nulls to a string of "None", so when we convert back to a featureclass, they are interpreted as strings. Is there currently a way around this? My current work around is to do an arcpy update cursor to replace instances of "None" with None, but it would be a nice thing to have built-in.

**To Reproduce**

I am running the below in a notebook within ArcGIS Pro. Here I used a public rest service just for example purposes.
```python
import os
from arcgis.features import FeatureLayer

us_current_wildfires = (r'https://services9.arcgis.com/RHVPKKiFTONKtxq3/'
                        r'arcgis/rest/services/USA_Wildfires_v1/FeatureServer/0')

text_field_example = ['IncidentManagementOrganization']
sdf = (FeatureLayer(us_current_wildfires)
       .query(as_df='True', out_fields=text_field_example))

out_gdb = arcpy.env.workspace
out_fc = os.path.join(out_gdb, 'test_fires')

sdf.spatial.to_featureclass(out_fc, sanitize_columns=False)
```

**Output**
![image](https://user-images.githubusercontent.com/78937033/210880229-891a8a95-e954-47cc-abb2-c0bbfe271bde.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Python API Version: 2.0.1

**Comment by nanaeaubry** [comment]
Hello, can you test this again with the new release of the Python API (version 2.1.0) and let us know if it is still occurring?

This might have been fixed in this version

**Comment by EricSamsonG2** [comment]
@nanaeaubry I am not seeing that release. When is the planned release date for that version?

**Comment by nanaeaubry** [comment]
@EricSamsonG2 Have you been able to test again? The latest version of the API is 2.1.0.2

**Comment by EricSamsonG2** [comment]
@nanaeaubry Just tested with the newest release. There is a difference now, but still not optimal. All of the null records are converted to empty string values:

![image](https://user-images.githubusercontent.com/78937033/224558762-73da6430-d909-4ab2-8459-6a2301564971.png)

It would be best if these came in as null values when converted to a feature class, to mimic what we see on the rest service.

**Comment by EricSamsonG2** [comment]
@nanaeaubry Just tested with the newest release. There is a difference now, but still not optimal. All of the null records are converted to empty string values:

![image](https://user-images.githubusercontent.com/78937033/224558762-73da6430-d909-4ab2-8459-6a2301564971.png)

It would be best if these came in as null values when converted to a feature class, to mimic what we see on the rest service.

**Comment by nanaeaubry** [comment]
@EricSamsonG2 Ok we will look at this but since it is using arcpy on the backend this might be an issue to bring to them about their convention.
