### ISSUE TITLE
How to configure proxy in API?

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#143]
Hi,

I'm having trouble using the API because my network needs to configure the proxy.
I have not found any method in the API to configure my proxy.

Has anyone else had this problem yet?

**Comment by achapkowski** [comment]
Try this:

    gis = GIS(proxy_host="127.0.0.1", proxy_port=49864)
    res = gis.content.search("Rocks")

**Comment by mateuspontesmoraes** [comment]
tks @achapkowski
