### ISSUE TITLE
Geoprocessing service results parsing

### ISSUE THREAD

**Issue by yurygeo** [Esri/arcgis-python-api#145]
If geoprocessing service/tool return results with 'value'  = 'none', then variable jsondict = None. 

if 'MapImage' in None -> TypeError occurs.

![python_api](https://user-images.githubusercontent.com/32735012/31491929-b68a859a-af51-11e7-9c73-eaa6e2497356.png)

**Comment by rohitgeo** [comment]
Thanks for reporting. This issue has been fixed in the upcoming release.
