### ISSUE TITLE
Item.Usage method returns as None when using date_range option

### ISSUE THREAD

**Issue by andrewrudin-austin** [Esri/arcgis-python-api#1456]
**Describe the bug**
For ArcGIS Online item, the item.usage() method is returning with value None when using the new date_range option and using a long date range, such as 6 months.  

**To Reproduce**
```python
import datetime
from arcgis.gis import GIS

gis = GIS('Pro')

itemid = "abc123" #Provide and itemid for an item with usage going back over a year
item = gis.content.get(itemid)

date_1 = datetime.datetime(2022,3,1)
date_2 = datetime.datetime(2022,8,31)

result = item.usage(date_range = (date_1, date_2))
result
```
error:
no error is returned.  The result variable just comes back as None

**Screenshots**

**Expected behavior**
The variable should populate with the results for each date between input date_1 and date_2, provided those dates fall in the 1 year of usage history AGO stores for each item.  Or if there is some kind of error with the python requests to the REST API, those should be displayed in python.  however, I'd expect if there is an option called '1Y' to search back exactly 1 year from today's date, then I'd be able to use the date_range option to filter on any dates in that same 1 year timeframe.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser None:  Using ArcGIS Pro Jupyter Notebook
 - Python API Version [e.g. `2.1.0`]

**Additional context**
The idea here is to loop over items in AGOL and get as much "whole month" history as possible for items.  In the example above when I use a date range of March-1-2022 to March-31-2022, it returns data fine.  I then expanded the range by 1 month until it broke at March-1-2022 to Aug-31-2022.  So about 5 months seems to break it.

**Comment by nanaeaubry** [comment]
Hello, it seems the way the calls are being sent to the server has changed server-side so we will update our code with the changes and have it for the next version of the API.

In the meantime the only workaround I can see is to get the usage in chunks. Sorry for the inconvenience

**Comment by nanaeaubry** [comment]
This has been addressed for the next release
