### ISSUE TITLE
Data historical_wildfire_analysis

### ISSUE THREAD

**Issue by libertadcc** [Esri/arcgis-python-api#1461]
I would like to test the historical_wildfire_analysis sample and for that I need to access the data from local, where can I download the GDB? In the data folder they do not appear, do they have another name?  Thank you!

(Sorry for the label: bug) I know that it's not a bug but I had to choose one of the options when I opened the issue  😅

**Comment by nanaeaubry** [comment]
@CMPeng Can you please help with this?

**Comment by CMPeng** [comment]
Hi @libertadcc have you tried downloading the zipped gdb from <a href="https://www.fs.usda.gov/rds/archive/products/RDS-2013-0009.4/RDS-2013-0009.4_GDB.zip">website</>, and then unzip to a local folder on your machine?

**Comment by libertadcc** [comment]
That's what I ned! Thank you!
