### ISSUE TITLE
Index error with Train deep learning model (spatial analyst tools)

### ISSUE THREAD

**Issue by Richard-Antwi22** [Esri/arcgis-python-api#1468]
**Hi, can you kindly help me solve this issue? I am trying to train a deep learning model using the following code**

```
witharcpy.EnvManager(processorType="GPU"):
    arcpy.ia.TrainDeepLearningModel(r"'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Balancing_Training_img_chps';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Balancing_Training_img_chps_1';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Balancing_Training_img_chps_2';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Broward_img_chps_12';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Gilchrist_img_chps_12';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Gulf_img_chps_12';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Jefferson_img_chps_12';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Miami_Dade_img_chps';'C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\All Training Data\Santa_Rosa_img_chps_12'", r"C:\Users\Richard Antwi\Desktop\Turning Lanes Detection\Turning Lane Models\Turning_lane_Model_1", 150, "YOLOV3", 64, "chip_size 224;resize_to #;monitor valid_loss;monitor average_precision", None, "DARKNET53", None, 30, "CONTINUE_TRAINING", "UNFREEZE_MODEL")
```

**However I run into this index error at epoch 63. Can you help me solve this?**

> Traceback (most recent call last):
>   File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 390, in <module>
>     execute()
>   File "c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Image Analyst Tools.tbx\TrainDeepLearningModel.tool\tool.script.execute.py", line 334, in execute
>     training_model_object.fit(
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 997, in fit
>     self.learn.fit_one_cycle(epochs, lr, callbacks=callbacks, **kwargs)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\train.py", line 23, in fit_one_cycle
>     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 200, in fit
>     fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 101, in fit
>     loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\fastai\basic_train.py", line 26, in loss_batch
>     out = model(*xb)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\learn\models\_yolov3_utils.py", line 237, in forward
>     x, y, *loss_dict = module(x, targets)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\learn\models\_yolov3_utils.py", line 552, in forward
>     obj_mask[b, a, j, i] = 1
> IndexError: index 28 is out of bounds for dimension 3 with size 28
> Failed script (null)...
> Failed to execute (TrainDeepLearningModel).
>

**Comment by priyankatuteja** [comment]
@Richard-Antwi22 Could you please share some sample data to reproduce it?

**Comment by Richard-Antwi22** [comment]
I used ArcGIS pro version 3.1. Unable to upload the file. The size is beyond 25mb. Is there an alternative?

**Comment by priyankatuteja** [comment]
@Richard-Antwi22 you could send email to ptuteja@esri.com
