### ISSUE TITLE
Updating YOLOv3 in ArcGIS Pro 

### ISSUE THREAD

**Issue by Richard-Antwi22** [Esri/arcgis-python-api#1469]
Hi, is there a way to download or add an updated version of the YOLOv3 model in ArcGIS Pro to YOLOv5 or YOLOv7? 

Kindly help.

**Comment by Richard-Antwi22** [comment]
Hi, is there any help with this? Kindly assist.

**Comment by rohitgeo** [comment]
YOLOv5, YOLOv7 and other such YOLO models have an incompatible license (GPL) and hence we cannot add them. However, you may use some other better models from the MMDetection family of models that perform better than YOLO, or alternatively use custom  python raster functions integrating your YOLO models using the documentation at https://github.com/Esri/raster-deep-learning
