### ISSUE TITLE
Change the owner of an item

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#147]
I would like do change owner of a item
I'm trying this way

```
gis = GIS(url, user, pass)

item = gis.content.get("itemid")
item.update(owner="newOwner")
```

Error: 
> update() got an unexpected keyword argument 'owner'

I also tried the following way

```
item["owner"] = "newOwner"
item.update(item_properties=item)   
```
But it did not work

Has anyone ever had to do this?

**Comment by rohitgeo** [comment]
You should use Item.reasign_to():
http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.Item.reassign_to

**Comment by mateuspontesmoraes** [comment]
Nice @rohitgeo, thank you for your help!
