### ISSUE TITLE
Installation with latest setuptools fails

### ISSUE THREAD

**Issue by nickthegroot** [Esri/arcgis-python-api#1474]
**Describe the bug**
When installing with the latest `setuptools==67.4.0`, `pip install arcgis` fails with the following message:

**To Reproduce**
```sh
pip install -U setuptools
pip install arcgis
```
error:
```sh
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in arcgis setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          keyring >=23.3.*
                  ~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Expected behavior**
`pip install arcgis` should install without errors

**Platform (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu Linux
 - Browser [e.g. chrome, safari]: N/A
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`: All 2.x versions

**Additional context**
Possibly related to #1460

**Comment by nickthegroot** [comment]
**Workaround**
Was able to workaround by downgrading to `setuptools==57.4.0`
```sh
pip install setuptools==57.4.0
pip install arcgis
```

**Comment by pierresouchay** [comment]
@nickthegroot Definitely related to https://github.com/Esri/arcgis-python-api/issues/1460 => the solution has been provided here: https://github.com/Esri/arcgis-python-api/issues/1460#issuecomment-1423420695

cc @achapkowski

**Comment by nanaeaubry** [comment]
Hello this has been fixed and will be part of the next release, thanks!
