### ISSUE TITLE
Add firstName, lastName, and userType to User.update method?

### ISSUE THREAD

**Issue by timhaverland-noaa** [Esri/arcgis-python-api#148]
Frequently our AGOL organization needs to update the user attributes firstName, lastName, and userType (enabling/disabling Esri Access). 

However, the arcgis python API's User.update method does not include parameters for these attributes. 

Looking at the code, it appears that the User.update method is based off of portalpy's update_user method. 

Can these attributes be added to the arcgis python API? If not, what would be the best way for me to extend the functionality of the arcgis python API?

Thanks!

Tim

**Comment by rohitgeo** [comment]
This has been added to the upcoming release.
