### ISSUE TITLE
UserManager module, Update won't allow user category update

### ISSUE THREAD

**Issue by MSLTrebesch** [Esri/arcgis-python-api#1482]
**Describe the bug**
using the the UserManager module with Update.
when specifying the user categories (they exist) in a list per documentation, Update throws error.

**To Reproduce**

```python
u_user = s_user.update(tags="Student Lab", categories = ['Student Lab'])
```
s_user is a created user object

error:
```python
update() got an unexpected keyword argument 'categories'
```
**Screenshots**

**Expected behavior**
expected already existing user category of "Student Lab" to be applied to the provided user object 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Python API Version '2.0.1'

**Additional context**
Running in ArcGIS Online Notebook as an admin user to my subscription

**Comment by achapkowski** [comment]
You need to use the UserManager.assign_categories method.

1). Define the categories

```
>>> category_dict = {"memberCategorySchema": [
                                               {"title": "Categories",
                                               "categories": [
                                                              {"title": "Office Location"},
                                                              {"title": "Department"}
                                                             ]
                                               }
                                             ]
                     }
>>> gis.users.categories = category_dict

```

2). Assign the categories

```
>>> gis.users.assign_categories(users=[gis.users.me], categories=['Office Location'])
```

**Comment by MSLTrebesch** [comment]
> You need to use the UserManager.assign_categories method.
> 
> 1). Define the categories
> 
> ```
> >>> category_dict = {"memberCategorySchema": [
>                                                {"title": "Categories",
>                                                "categories": [
>                                                               {"title": "Office Location"},
>                                                               {"title": "Department"}
>                                                              ]
>                                                }
>                                              ]
>                      }
> >>> gis.users.categories = category_dict
> ```
> 
> 2). Assign the categories
> 
> ```
> >>> gis.users.assign_categories(users=[gis.users.me], categories=['Office Location'])
> ```

Interesting, what if my categories are already defined via the AGOL interface?
Do I need to define the categories?

also, when calling 'assign_categories' I still get this error, when used against my user object list:
----> 1 gis.users.assign_categories(users=[gis.users.me], categories=['Student Lab'])

AttributeError: 'UserManager' object has no attribute 'assign_categories'

**Comment by achapkowski** [comment]
What version of the python API are you using?  This is newer functionality

**Comment by MSLTrebesch** [comment]
> * Python API Version '2.0.1'

What's available in our current AGOL environment

**Comment by MSLTrebesch** [comment]
> What version of the python API are you using? This is newer functionality

Can you see issue with my code/workflow?  I'd think this should be working.  Is something broken in 2.0.1
