### ISSUE TITLE
WebMap.add_layer() fails silently on raster published from local .tif in Jupyter Notebook

### ISSUE THREAD

**Issue by egorbn** [Esri/arcgis-python-api#1484]
**Describe the bug**
I am using ArcGIS API for Python to publish a local tiff raster to AGOL. I am then creating a local WebMap instance, adding the published raster item to this WebMap, and then saving this WebMap to AGOL. The issue is that the raster is not showing up in the WebMap. No errors or warning are raised in the code, but opening the WebMap in the Map Viewer in AGOL shows the following error message for the raster layer: "An error occurred loading this layer"

**To Reproduce**
* Publish a local tif raster to AGOL from a Jupyter Notebook using copy_raster()
* Add the resulting hosted item to a WebMap in a Jupyter Notebook using add_layer()
* The raster shows up in the list of layers in the WebMap, but is not displayed in the Notebook widget
* Examining the WebMap using the AGOL Map Viewer shows the following error for the raster layer: "An error occurred loading this layer"

Python notebook with full steps to reproduce:
[https://github.com/egorbn/arcgis_api_python_testing/blob/main/raster_ops.ipynb](https://github.com/egorbn/arcgis_api_python_testing/blob/main/raster_ops.ipynb)

**Screenshots**
Method 1:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/116128944/222981268-72c2898b-4e9c-4eec-a403-f719a5fc2f55.png">

Method 2:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/116128944/222981293-b2613991-93bf-46a2-9206-beef25519987.png">

Method 3:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/116128944/222992947-e09d39ec-c721-491f-b690-8f39faa9ece4.png">

**Expected behavior**
The expected behavior is that the raster item is added to the WebMap and displayed automatically

**Platform (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Firefox
 - Python API Version 2.1.0.2

**Additional context**
* The only difference I see between the manually added and saved WebMap and the WebMap saved using the ArcGIS API for Python is:
  - The map where the raster is added manually (Method 3) lists the raster layer as a "Tiled Imagery Layer"
  - The automatically generated WebMap (Methods 1 & 2) list the raster layer as an "Imagery Layer"
  - Nowhere in the documentation about [ImageryLayer](https://developers.arcgis.com/python/api-reference/arcgis.raster.toc.html#imagerylayer) or [Raster](https://developers.arcgis.com/python/api-reference/arcgis.raster.toc.html#raster) or [copy_raster()](https://developers.arcgis.com/python/api-reference/arcgis.raster.analytics.html#copy_raster) can I find how to set/change the layer type

**Comment by egorbn** [comment]
*Update:*

I found that the layerType property of the operational layer was, indeed, the issue.

Thanks to https://community.esri.com/t5/arcgis-api-for-python-blog/snippets-to-manage-a-web-map-with-the-arcgis-api/ba-p/1043716

I was able to find a workaround by setting the layer type explicitly in the item data and updating the WebMap item.

The additional code is:
```
wm1_item_text = wm1_item.get_data()
wm1_item_text["operationalLayers"][0]["layerType"]="ArcGISTiledImageServiceLayer"
wm1_item.update(item_properties={"text":json.dumps(wm1_item_text)})
```

A notebook with the workaround implemented showing the working method is here:
[https://github.com/egorbn/arcgis_api_python_testing/blob/main/webmap_text_property.ipynb](https://github.com/egorbn/arcgis_api_python_testing/blob/main/webmap_text_property.ipynb)

**Although this workaround is usable, the above bug still stands.**
add_layer() should know how to set the proper layerType, or give information about why it can't, etc.

Overwriting and updating the text based item properties manually feels like a band-aid.

**Comment by rhea-j** [comment]
@egorbn I am working on a fix for this. The workaround seems to be good. But yes, we will get the API enhanced to support this. 
Thanks for reporting.

**Comment by egorbn** [comment]
Thanks, @rhea-j ! Much appreciated. OK will use the WebMap.update() method for now.

**Comment by nanaeaubry** [comment]
This is being addressed for the next release :) Thank you for letting us know!
