### ISSUE TITLE
Wildcard character breaking Standard Geography Queries from the GeoEnrichment service

### ISSUE THREAD

**Issue by dohrenstein** [Esri/arcgis-python-api#1488]
**Describe the bug**
Cannot use wildcards with fields in standard_geography_query. This makes it impossible to efficiently collect N AreaIDs (where N is unknown) from a particular country layer.

**To Reproduce**
```python
from arcgis.geoenrichment import standard_geography_query
from arcgis import GIS
import arcgis

print(arcgis.__version__)

gis = GIS(username="",password="")

test_1 = standard_geography_query(
    source_country= 'United Kingdom',
    country_dataset= 'GBR_MBR_2022',
    layers= ['GB.Counties'],
    return_geometry= False,
    geoquery = 'ID:E06000001',
    feature_limit=5000,
    gis=gis
)

print(test_1)

test_2 = standard_geography_query(
    source_country= 'United Kingdom',
    country_dataset= 'GBR_MBR_2022',
    layers= ['GB.Counties'],
    return_geometry= False,
    geoquery = 'ID:E0600000*',
    feature_limit=5000,
    gis=gis
)

print(test_2)
```

**Expected behavior**
I expect to see the same AreaID returned with both queries since ID:E0600000* is a superset of ID:E06000001, however, nothing is returned.

**Platform (please complete the following information):**
 - OS: MS Windows 10
 - Python API Version: 1.9.0

**Additional context**
I am pretty sure this is not an issue with the Python API but rather the underlying RestAPI call.

**Comment by nanaeaubry** [comment]
Thank you for bringing this up, we will take a look at it and post any updates here

**Comment by dohrenstein** [comment]
Thanks for your help Nanae! I have been working with ESRI UK support who mentioned that a change had been made to the underlying RestAPI a couple of weeks ago (which is when we detected the breaking change). That might be a good place to investigate! 😄

**Comment by nanaeaubry** [comment]
@dohrenstein The geoenrichment team has suggested setting `use_fuzzy_search=True` in the method.

Does this work for you?

**Comment by dohrenstein** [comment]
Thanks for looking into this @nanaeaubry! However, this doesn't solve the issue. In most cases we won't know a priori the form of the AreaIDs and so would begin by searching for e.g. "a*". There is a potential overlap between "a*" and "b*" if the field is not specified as ID - this would cause very long loading times in our application due to this duplication. "ID:a*" and "ID:b*" are however mutually exclusive, so there is a clear need for this bug to be fixed. Do you have an ETA from the team for when this could be investigated?

**Comment by nanaeaubry** [comment]
I see the issue, unfortunately we are simply calling the rest service so we cannot fix it on our end. We have made the team aware and they are investigating but there is no ETA as to when it will be fixed.

If you want to speak with them directly you will have to use Esri Support since they do not have a public repo. However, if I hear anything about this I will make sure to post updates to this issue and tag you.

**Comment by dohrenstein** [comment]
Thanks, and appreciate you following up!
