### ISSUE TITLE
Change tags of the item

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#149]
I'm trying to change the tags of an item as follows

```
tags = ['tag1', 'tag2']
item["tags"] = tags
item.update(item)
```

or

```
tags = ['tag1', 'tag2']
item["tags"] = tags
item.update(item_properties=item)
```

But it does not work

**Comment by rwmajor2** [comment]
@mateuspontesmoraes try the following:
```
item.update(item_properties={'tags':'tag1,tag2'})
```
I didn't personally test this, but your syntax isn't quite right.  You can't do ```item["tags"] = tags```; it just doesn't have any affect.  You need to pass in a new key/value pair of tags.  The value for tags can either be a list or a comma-separated string.

**Comment by mateuspontesmoraes** [comment]
Hi @rwmajor2, tks that's ok now
