### ISSUE TITLE
AttributeError: 'WebMap' object has no attribute '_gallery_basemaps'

### ISSUE THREAD

**Issue by ankoure** [Esri/arcgis-python-api#1492]
**Describe the bug**
When I try to call the "gallery_basemaps" method on a WebMap object, I receive an error. Based on the error message it looks like the code is adding an "_" before the "gallery" resulting in an error as there is no "_gallery_basemaps" method. 

**To Reproduce**
```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap
gis = GIS('home')
#May need to update the id 
WebMapBaseMapToChange = gis.content.get('dcfebe1e21c3463eb3aeff999184aa2b')
changeWM = WebMap(WebMapBaseMapToChange)
changeWM.gallery_basemaps
```
error:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [31], in <cell line: 6>()
      1 #print(changeWM.gallery_basemaps)
      2 
      3 #object_methods = [method_name for method_name in dir(changeWM)
      4 #                  if callable(getattr(changeWM, method_name))]
      5 print(dir(changeWM))
----> 6 changeWM.gallery_basemaps

File /opt/conda/lib/python3.9/site-packages/arcgis/mapping/_types.py:1564, in WebMap.gallery_basemaps(self)
   1562             item_data = bm.get_data()
   1563             bm_title = bm.title.lower().replace(" ", "_")
-> 1564             self._gallery_basemaps[bm_title] = item_data["baseMap"]
   1565     return list(self._gallery_basemaps.keys())
   1566 else:

AttributeError: 'WebMap' object has no attribute '_gallery_basemaps'

```
**Screenshots**
![image](https://user-images.githubusercontent.com/50218177/225427922-89985f7b-9558-4f30-952a-f0e849c692ac.png)
**Expected behavior**
I anticipated a feature layer to be returned as a dictionary as specified on the esri documentation here: https://developers.arcgis.com/python/api-reference/arcgis.mapping.toc.html#arcgis.mapping.WebMap.gallery_basemaps

I am trying to use the basemap property to update the basemap in a map using the basemap gallery which requires this method. 

**Platform (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`
 - ArcGIS Notebook Python 3 Standard - 7.0
 - Arcgis version 2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
It seems in your org settings you don't have a group set to be your gallery basemaps group

**Comment by ankoure** [comment]
Hi nanaeaubry, 
Just checked with my AGOL org admins and we do have a group set for our Basemap gallery. I did some more testing and found that a WebMap object created from a pre-existing map returns the error. Whereas creating a webmap without an itemID allows me to access the gallery_basemaps property. 

```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap
gis = GIS("home")
```
```python
wm_item = gis.content.get('c5785bb37db34378b7b77b137086faca')
wm = WebMap(wm_item)
print(wm.gallery_basemaps)
```


    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    Input In [3], in <cell line: 3>()
          1 wm_item = gis.content.get('c5785bb37db34378b7b77b137086faca')
          2 wm = WebMap(wm_item)
    ----> 3 print(wm.gallery_basemaps)


    File /opt/conda/lib/python3.9/site-packages/arcgis/mapping/_types.py:1564, in WebMap.gallery_basemaps(self)
       1562             item_data = bm.get_data()
       1563             bm_title = bm.title.lower().replace(" ", "_")
    -> 1564             self._gallery_basemaps[bm_title] = item_data["baseMap"]
       1565     return list(self._gallery_basemaps.keys())
       1566 else:


    AttributeError: 'WebMap' object has no attribute '_gallery_basemaps'



```python
wm2 = WebMap()
print(wm2.gallery_basemaps)
```

    ['cambridge,_ma_-_cdd_basemap', 'cambridge,_ma_-_dpw_basemap', 'cambridge,_ma_-_orthophoto_basemap', 'cambridge,_ma_basemap', 'charted_territory_map', 'colored_pencil_map', 'community_map', 'dark_gray_canvas', 'firefly_imagery_hybrid', 'human_geography_dark_map', 'human_geography_map', 'imagery', 'imagery_hybrid', 'light_gray_canvas', 'mid-century_map', 'modern_antique_map', 'naip_imagery_hybrid', 'national_geographic_style_map', 'navigation', 'navigation_(dark_mode)', 'newspaper_map', 'nova_map', 'oceans', 'openstreetmap', 'openstreetmap_(blueprint)', 'outline_map', 'streets', 'streets_(night)', 'terrain_with_labels', 'topographic', 'usa_topo_maps', 'usgs_national_map']


I also have included the screenshot that they sent me and this is the link to the organization's basemap group: https://cambridgegis.maps.arcgis.com/home/group.html?id=fb8f43febf44458197a87acd2fae771b&view=list#content

![CambridgeAGOLGroup](https://user-images.githubusercontent.com/50218177/225643328-bde45c0e-c53b-49d5-8de0-b9b6368396b7.png)

Thanks,
Andrew

**Comment by nanaeaubry** [comment]
@ankoure 
Oh interesting, thank you for letting me know. I will take a look at this but in the meantime I don't have a workaround for you. I appreciate you looking into it more, I will go off of this and post any updates I have here

**Comment by nanaeaubry** [comment]
@ankoure 

I cannot reproduce this issue on my end. Can I have you try to run some lines and let me know what you get?

```
from arcgis.gis import GIS
from arcgis.mapping import WebMap

gis = GIS(profile="your_online_profile")
item = gis.content.get("81b4072380a34956a42b986c82ca3582")
wm = WebMap(item)
print(wm._gis)
bmquery = wm._gis.properties["basemapGalleryGroupQuery"]
basemapsgrp = wm._gis.groups.search(bmquery, outside_org=True)
print(len(basemapsgrp))
print(basemapsgrp[0].content())

for bm in basemapsgrp[0].content():
    print(bm.type)
```

Can you also run it without a webmap item instantiated?

**Comment by ankoure** [comment]
#### With WM item instantiated
```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap

gis = GIS("home")
item = gis.content.get("3a77d0e2b610455da1e2fc7f7b0ea019")
wm = WebMap(item)
print(wm._gis)
bmquery = wm._gis.properties["basemapGalleryGroupQuery"]
basemapsgrp = wm._gis.groups.search(bmquery, outside_org=True)
print(len(basemapsgrp))
print(basemapsgrp[0].content())

for bm in basemapsgrp[0].content():
    print(bm.type)
```

    /opt/conda/lib/python3.9/site-packages/arcgis/gis/__init__.py:597: UserWarning: You are logged on as akoure@cambridgema.gov_CambridgeGIS with an administrator role, proceed with caution.
      warnings.warn(


    GIS @ https://www.arcgis.com version:2023.1
    1
    [<Item title:"Cambridge, MA - CDD Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA - DPW Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA - Orthophoto Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA Basemap" type:Web Map owner:Cambridge_Publisher>, <Item title:"Charted Territory Map" type:Web Map owner:esri>, <Item title:"Colored Pencil Map" type:Web Map owner:esri>, <Item title:"Community Map" type:Web Map owner:esri>, <Item title:"Dark Gray Canvas" type:Web Map owner:esri>, <Item title:"Dark Gray Canvas" type:Web Map owner:esri_en>, <Item title:"Firefly Imagery Hybrid" type:Web Map owner:esri>, <Item title:"Human Geography Dark Map" type:Web Map owner:esri>, <Item title:"Human Geography Map" type:Web Map owner:esri>, <Item title:"Imagery" type:Web Map owner:esri_en>, <Item title:"Imagery Hybrid" type:Web Map owner:esri>, <Item title:"Imagery Hybrid" type:Web Map owner:esri_en>, <Item title:"Light Gray Canvas" type:Web Map owner:esri>, <Item title:"Light Gray Canvas" type:Web Map owner:esri_en>, <Item title:"Mid-Century Map" type:Web Map owner:esri>, <Item title:"Modern Antique Map" type:Web Map owner:esri>, <Item title:"NAIP Imagery Hybrid" type:Web Map owner:esri>, <Item title:"National Geographic Style Map" type:Web Map owner:esri>, <Item title:"Navigation" type:Web Map owner:esri_en>, <Item title:"Navigation (Dark Mode)" type:Web Map owner:esri>, <Item title:"Newspaper Map" type:Web Map owner:esri>, <Item title:"Nova Map" type:Web Map owner:esri>, <Item title:"Oceans" type:Web Map owner:esri_en>, <Item title:"OpenStreetMap" type:Web Map owner:esri>, <Item title:"OpenStreetMap" type:Web Map owner:esri_en>, <Item title:"OpenStreetMap (Blueprint)" type:Web Map owner:esri>, <Item title:"Outline Map" type:Web Map owner:esri>, <Item title:"Streets" type:Web Map owner:esri_en>, <Item title:"Streets" type:Web Map owner:esri>, <Item title:"Streets (Night)" type:Web Map owner:esri_en>, <Item title:"Terrain with Labels" type:Web Map owner:esri_en>, <Item title:"Topographic" type:Web Map owner:esri_en>, <Item title:"Topographic" type:Web Map owner:esri>, <Item title:"USA Topo Maps" type:Web Map owner:esri>, <Item title:"USGS National Map" type:Web Map owner:esri>, <Item title:"World Imagery" type:Map Image Layer owner:esri>]
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Map Service

#### Without WM item instantiated

```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap

gis = GIS("home")
wm = WebMap()
print(wm._gis)
bmquery = wm._gis.properties["basemapGalleryGroupQuery"]
basemapsgrp = wm._gis.groups.search(bmquery, outside_org=True)
print(len(basemapsgrp))
print(basemapsgrp[0].content())

for bm in basemapsgrp[0].content():
    print(bm.type)
```

    /opt/conda/lib/python3.9/site-packages/arcgis/gis/__init__.py:597: UserWarning: You are logged on as akoure@cambridgema.gov_CambridgeGIS with an administrator role, proceed with caution.
      warnings.warn(


    GIS @ https://www.arcgis.com version:2023.1
    1
    [<Item title:"Cambridge, MA - CDD Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA - DPW Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA - Orthophoto Basemap" type:Web Map owner:Cambridge_Data>, <Item title:"Cambridge, MA Basemap" type:Web Map owner:Cambridge_Publisher>, <Item title:"Charted Territory Map" type:Web Map owner:esri>, <Item title:"Colored Pencil Map" type:Web Map owner:esri>, <Item title:"Community Map" type:Web Map owner:esri>, <Item title:"Dark Gray Canvas" type:Web Map owner:esri>, <Item title:"Dark Gray Canvas" type:Web Map owner:esri_en>, <Item title:"Firefly Imagery Hybrid" type:Web Map owner:esri>, <Item title:"Human Geography Dark Map" type:Web Map owner:esri>, <Item title:"Human Geography Map" type:Web Map owner:esri>, <Item title:"Imagery" type:Web Map owner:esri_en>, <Item title:"Imagery Hybrid" type:Web Map owner:esri>, <Item title:"Imagery Hybrid" type:Web Map owner:esri_en>, <Item title:"Light Gray Canvas" type:Web Map owner:esri>, <Item title:"Light Gray Canvas" type:Web Map owner:esri_en>, <Item title:"Mid-Century Map" type:Web Map owner:esri>, <Item title:"Modern Antique Map" type:Web Map owner:esri>, <Item title:"NAIP Imagery Hybrid" type:Web Map owner:esri>, <Item title:"National Geographic Style Map" type:Web Map owner:esri>, <Item title:"Navigation" type:Web Map owner:esri_en>, <Item title:"Navigation (Dark Mode)" type:Web Map owner:esri>, <Item title:"Newspaper Map" type:Web Map owner:esri>, <Item title:"Nova Map" type:Web Map owner:esri>, <Item title:"Oceans" type:Web Map owner:esri_en>, <Item title:"OpenStreetMap" type:Web Map owner:esri>, <Item title:"OpenStreetMap" type:Web Map owner:esri_en>, <Item title:"OpenStreetMap (Blueprint)" type:Web Map owner:esri>, <Item title:"Outline Map" type:Web Map owner:esri>, <Item title:"Streets" type:Web Map owner:esri_en>, <Item title:"Streets" type:Web Map owner:esri>, <Item title:"Streets (Night)" type:Web Map owner:esri_en>, <Item title:"Terrain with Labels" type:Web Map owner:esri_en>, <Item title:"Topographic" type:Web Map owner:esri_en>, <Item title:"Topographic" type:Web Map owner:esri>, <Item title:"USA Topo Maps" type:Web Map owner:esri>, <Item title:"USGS National Map" type:Web Map owner:esri>, <Item title:"World Imagery" type:Map Image Layer owner:esri>]
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Web Map
    Map Service
