### ISSUE TITLE
Enhanced Logging when Row cannot be added to Spatially Enabled Dataframe

### ISSUE THREAD

**Issue by FeralCatColonist** [Esri/arcgis-python-api#1494]
**Is your feature request related to a problem? Please describe.**
When ingesting records into a spatially enabled dataframe from another source, a warning occurs stating:
```cmd
Could not insert the row because of the error message: value #XX - unsupported type: NAType. Recheck your data.
```

This warning/error would be significantly more helpful if it stated the record row number and the column/field name or index. Is the value number supposed to be the column? I don't know and the end user probably doesn't either.

![image](https://user-images.githubusercontent.com/12204584/225453354-55236124-13e7-4ad7-9f9a-e9fec0ebcab2.png)

```python
sedf = arcgis.features.GeoAccessor.from_featureclass(featureclass)
```

**Describe the solution you'd like**
Enrich the error message to include: 
- the record row's number that could not be added to the spatially enabled dataframe
    - especially an ObjectID if coming from an enterprise geodatabase or other Esri-specific format.
- the field or column name and/or index number to alert the user to the location of the error.

**Comment by nanaeaubry** [comment]
This error doesn't seem to come from our end but we will investigate. Thanks for bringing it up

**Comment by FeralCatColonist** [comment]
@nanaeaubry, yes this environment is using ArcPy in addition to the ArcGIS API for Python. I can get you that data later this evening, what's a good method for sending?

**Comment by nanaeaubry** [comment]
@FeralCatColonist Can you drop it here? or make a dropbox for it? Otherwise we can figure something out.

**Comment by FeralCatColonist** [comment]
@nanaeaubry, I was just digging into it and the issue was with `to_featureclass()` and not `from_featureclass()`; I didn't have enough signposting in my script previously and I guessed wrong on what function was to blame.
It appears to be the same issue as described here:
https://community.esri.com/t5/arcgis-api-for-python-ideas/support-a-pd-na-to-np-nan-conversion-inside-the/idi-p/1266352/

I'm running a series of data hygiene operations against the data and I've introduced some NA types as part of that process. Here's an export to parquet from that intermediate process-- --I'm unsure if this will preserve the error or not.
[dirty_addresses.zip](https://github.com/Esri/arcgis-python-api/files/10996697/dirty_addresses.zip)

**Comment by nanaeaubry** [comment]
Ok I dug a bit into it and the error message is occurring from the arcpy call being made in the method. So I will pass the message onto them but if you want tracking on progress you have to go through support unfortunately since we don't track that here.

**Comment by nanaeaubry** [comment]
> @nanaeaubry so the ArcPy would be the one to handle that NA conversion in the resources that the to_featureclass() process is calling?

Ah so you want us to fix the conversion of none types as well then?
I thought this was an enhancement for the error message only. I will talk to our team and see then

**Comment by achapkowski** [comment]
Can you post a raw rows of your data?

**Comment by achapkowski** [comment]
What version of the API are you using and what is your export format?

When I do this:
```sdf.spatial.to_featureclass(r"c:\temp\scratch.gdb\testaddress")```

I do not get an issue with the latest release.

**Comment by FeralCatColonist** [comment]
@achapkowski, I'm assuming that the problematic rows were dropped upon conversion to_parquet(). How would you recommend I post the raw rows?

**Comment by achapkowski** [comment]
Zip the raw data and send it in the issue or try and post an example with problem data.

**Comment by hannesatwork** [comment]
@nanaeaubry can we now use Arrow table to accomplish this? You have `tbl = <sedf>.spatial.to_arrow()`, then use `arcpy.management.CopyFeatures(tbl, ...)` to create the featureclass. Should be a little faster too.

**Comment by FeralCatColonist** [comment]
Thanks for being so patient everyone; here are all the records that cause errors in the transformation process. @achapkowski the total 347,087 is correct for the raw data, you can connect the error-inducing records with the unique field `["Site_NGUID"]`
Here is a listing in excel and parquet: [github.zip](https://github.com/Esri/arcgis-python-api/files/11024470/github.zip)

Further, I've isolated the intermediary step to these two functions responsible for producing the NA Type:
```python
def addresses_add_fields(sedf):
    """This subroutine adds fields from scratch or copies based on existing fields"""
    sedf["Addtl_Loc1"] = ""
    sedf["Building"] = ""
    sedf["Inc_Muni"] = ""
    sedf["NCT_Type"] = ""
    sedf["Place_Type"] = ""
    sedf["Room"] = ""
    sedf["Uninc_Comm"] = ""
    sedf["Unit"] = ""
    sedf["DiscrpAgID"] = "DENCOAREA911.DST.TX.US"
    sedf["Nbrhd_Comm"] = sedf["Alias1"].str[:100]

    return sedf

def addresses_data_hygiene(sedf):
    """This subroutine performs simple data hygiene operations"""
    sedf["Addtl_Loc2"] = (
        sedf["Alias1"]
        .str.cat(sedf[["Alias2", "Alias3", "Alias4", "Alias5"]], sep=" ", na_rep="",)
        .str.strip()
        .str[:255]
    )
    sedf["Building"].mask(
        cond=sedf["ALTUNITTYPE"] == "BLDG", other=sedf["ALTUNITID"], inplace=True,
    )
    sedf["Building"].mask(
        cond=sedf["UNITTYPE"] == "BLDG", other=sedf["UNITID"], inplace=True,
    )
    sedf["GPSX"].mask(
        cond=(sedf["GPSY"] == 0) | (sedf["GPSY"] > 40), other=0, inplace=True,
    )
    sedf["GPSX"].mask(cond=sedf["GPSX"] > 0, other=0, inplace=True)
    sedf["GPSY"].mask(cond=sedf["GPSY"] > 40, other=0, inplace=True)
    sedf["Inc_Muni"].where(
        cond=sedf["MUNICIPALITY"].str.contains("COUNTY", regex=True),
        other=sedf["MUNICIPALITY"],
        inplace=True,
    )
    sedf["Room"].mask(
        cond=sedf["UNITTYPE"] == "RM", other=sedf["UNITID"], inplace=True,
    )
    sedf["Uninc_Comm"].mask(
        cond=sedf["MUNICIPALITY"].str.contains("COUNTY", regex=True),
        other=sedf["MUNICIPALITY"],
        inplace=True,
    )
    sedf["Unit"].where(
        cond=(sedf["UNITTYPE"] == "BLDG") | (sedf["UNITTYPE"] == "RM"),
        other=sedf["UNITID"],
        inplace=True,
    )
    return sedf
```

**Comment by FeralCatColonist** [comment]
So, I think this gets to the core of the argument.
- Is it better to drop records completely or to swap out a null-ish type for another null-ish type?

If the destination format (feature class) cannot handle an NA type but it can handle a null; what's the harm in converting that? I get that from a programming perspective they are discrete units but likely that distinction doesn't matter to a large population of the user base, i.e. people shoving data into a feature class.

- What about exposing an option to sanitize those values similar to the `sanitize_columns` parameter? This would be a convenience function for a segment of the user base that are likely self-taught analysts turned programmer.

```python
df = df.replace(
    {
        pd.NA: None,
        np.NaN: None,
        np.nan: None,
        np.NAN: None,
        pd.NaT: None,
    }
)
```

**Comment by achapkowski** [comment]
The danger is that we make assumptions about your data that are incorrect and downstream we cause harm somewhere else.  In your case it might not matter, but let's say you are doing calculations about pollution measurements to detect cancer causing agents.  If we get the replacement values incorrect or make generalized assumptions, this can have a large impact on the results.

**Comment by FeralCatColonist** [comment]
@achapkowski, it seems that having a data sanitize parameter would empower users to solve both of those use-cases.

**Comment by nanaeaubry** [comment]
@FeralCatColonist 
Sorry for taking so long to get back to you. Thank you for your thoughtful comment, we have taken this into consideration for further code enhancements. Your feedback has helped us a lot.

We put in some code for type conversions and this will be reflected at our next release. Please continue to let us know if you see other issues or have other enhancement requests that we can consider.
