### ISSUE TITLE
Using assign_categories to assign an existing category to user

### ISSUE THREAD

**Issue by MSLTrebesch** [Esri/arcgis-python-api#1500]
**Describe the bug**
Using the UserManager class to assign an existing user category (already in AGOL portal,  applied in interface).  Am able to assign the category to the users object.  They are visible in the AGOL interface, but cannot be filtered in the interface.  

**To Reproduce**

Add user category "test" in AGOL interface:

![image](https://user-images.githubusercontent.com/102312546/226753494-56a589b8-3d3a-412a-b08d-8c09474dc143.png)

![image](https://user-images.githubusercontent.com/102312546/226753085-c5b8dc32-c16e-4549-a0c0-ed650d91b51b.png)

Run code from Notebook  (ArcGIS API version 2.1.0.2):
```
from arcgis.gis import GIS
gis = GIS("home")
cat_users = gis.users.search(query='username:student_user_2')
print(cat_users)
gis.users.assign_categories(users=cat_users, categories=["test"])
```

output:
```python
[<User username:student_user_2>]
[{'student_user_2': True}]
```
**Screenshots**
Observing Categories given to user in AGOL:
User shows in "test" category when accessing the member properties, "Categorize" menu option:
Notice that the category is applied, but not checked on the left side menu.
![image](https://user-images.githubusercontent.com/102312546/226754708-b0f0e676-d636-483e-8ab9-3d2dec54a87e.png)

And when attempting to filter in AGOL under the "test" category, no users show up, though the above example shows the user is assigned to the category through the API call and interface:
![image](https://user-images.githubusercontent.com/102312546/226755013-e568c2ba-d9ed-44ae-859a-30d82c656aed.png)

**Expected behavior**
The above issue doesn't happen when working exclusively with AGOL interface - only when assigning categories, from an existing category created in AGOL to the user from the API via "assign_categories"

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Python API Version: 2.1.0.2

**Comment by nanaeaubry** [comment]
Hello, we will take a look at this, thank you for bringing it to our attention

**Comment by nanaeaubry** [comment]
Hello, you can try by defining the categories as such: `["/Categories/test"]`

There was another small bug found that we fixed so it will be reflected in the next release. Thank you

**Comment by theisenm12** [comment]
I am running into this same issue. Was there a solution to this? @nanaeaubry 

Additionally,  what do you mean by defining the categories as ["/Categories/test"]?

**Comment by nanaeaubry** [comment]
@theisenm12 

Here is an example on how to use this:
```
from arcgis.gis import GIS
gis = GIS("home")
cat_users = gis.users.search(query='username:student_user_2')
print(cat_users)
gis.users.assign_categories(users=cat_users, categories=["/Categories/test"])
```
Make sure you are using the latest release of the API
