### ISSUE TITLE
cannot convert float NaN to integer - NaT does not support timestamp

### ISSUE THREAD

**Issue by r7butler** [Esri/arcgis-python-api#1504]
**Describe the bug**
All i know is i have a dataframe that im trying to use to update a feature layer, and it is telling me this

![Screenshot 2023-03-24 at 12 51 14 AM](https://user-images.githubusercontent.com/40872002/227458556-daf23ce0-dd97-4b82-99ce-0bd6573c6e2d.png)

![Screenshot 2023-03-24 at 12 51 09 AM](https://user-images.githubusercontent.com/40872002/227458554-386bb85d-d782-4223-8634-84f669946896.png)

My dataframe has one column which is a datetime field, and it has a lot of NaT values in there. I'm not exactly sure what is happening internally in the package, but if you look in the second screenshot you can see line 162 in the file called  /usr/local/lib/python3.9/dist-packages/arcgis/_impl/common/_utils.py there is the line that says 

> return int(dt.timestamp() * 1000)

which to me looks like it is converting the datetime object to a unix timestamp, but it is not liking the fact that the "dt" object is a pandas NaT object.

So to me it seems like there should be some logic in there to handle the case where it is NaT, maybe 

> return int(dt.timestamp() * 1000) if not pd.isnull(dt) else 0

Or something like that

This was happening when i was trying to print a list of records that i was going to use when updating features, and i also got it when actually calling "layer.edit_features( ... )"

The python API version is 2.1.0.3 and its running in a docker container running Debian 11

pandas version is 1.5.3 and numpy version is 1.24.2

Although with this particular issue it doesnt seem like those things will be too relevant from what i can tell based on my (maybe somewhat limited) experience  

this is the function it was crashing in, and it seems like there just needs to be a case to handle the case when the dt argument is a pandas.NaT object. I can see there is the case for NoneTypes, so maybe NaT's should just also have their own case

/usr/local/lib/python3.9/dist-packages/arcgis/_impl/common/_utils.py
![Screenshot 2023-03-24 at 1 10 58 AM](https://user-images.githubusercontent.com/40872002/227462293-cd029fa3-a48a-438c-8f76-a0acfbf34aa4.png)

**Comment by jyaistMap** [comment]
Hi @r7butler -

Can you provide a reproducible sample of the actual code with data that you're running that leads to these errors?  We'll try to reproduce the error on our end to look into it further.

**Comment by nanaeaubry** [comment]
We have made updates on datatypes used for the next release. 

The beta will be released in July please test and reopen if needed.
