### ISSUE TITLE
Input tags in create_view() from a feature layer are not honored

### ISSUE THREAD

**Issue by HRhades** [Esri/arcgis-python-api#1523]
**Describe the bug**
When creating a view from a feature layer tags can be input using the tags parameter. 
```python
view = flc.manager.create_view(
    view_name,
    capabilities="Create,Delete,Query,Update,Editing",
    tags="tag1,tag2",
)
```
These tags never end up in the created item because at the end of the view creation tags from the source item are used to overwrite the tags in the view item. 

In the feature layer collection manager class the following code is found: 
```python
class FeatureLayerCollectionManager():
    --
    def create_view():
        --
        if tags:
            params["tags"] = tags
        --
        res = gis._con.post(path=url, postdata=params)
        view = content.get(res["itemId"])
        --
        view.update(
            {
                "tags": ",".join(item.tags),
                "description": item.description or "",
                "snippet": item.snippet or "",
            }
        )
        return content.get(res["itemId"])
    --
```
In the last view.update the tags are overwritten by the original item tags

**Expected behavior**
It would be better to only use the given tags in the `create_view` method. That would mean to drop the "tag" key/value pair in the update parameters dict. Since the new tags are updated earlier on in the method.

**Platform
 - Python API Version `2.1.0`

**Comment by nanaeaubry** [comment]
Thank you we will take a look at this

**Comment by nanaeaubry** [comment]
This has been addressed for the next release
