### ISSUE TITLE
StreamLayer subscribe generates error "local variable 'WebSocketClientProtocol' referenced before assignment"

### ISSUE THREAD

**Issue by crackernutter** [Esri/arcgis-python-api#1529]
**Describe the bug**
Subscribing to a arcgis.realtime.StreamLayer published on geoevent server generates an Unbound Local Error "local variable 'WebSocketClientProtocol' referenced before assignment"

**To Reproduce**
```python
def p(event):
    pass
from arcgis.gis import GIS
from arcgis.realtime import StreamLayer
gis=GIS(profile="mygis")
sl = StreamLayer("https://geoeventarcgis.server.com:6443/arcgis/rest/services/mystream/StreamServer", gis=gis)
sl.subscribe(on_features=p)
```
error:
```python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-79-1fd7a67955cc> in <module>
----> 1 sl.subscribe(on_features=p)

~\AppData\Local\ESRI\conda\envs\eim\lib\site-packages\arcgis\realtime\stream_layer.py in subscribe(self, on_features, on_open, on_disconnect, on_error)
     93         url = "{url}/subscribe?{params}".format(url=url, params=urlencode(params))
     94 
---> 95         class StreamServiceClientProtocol(WebSocketClientProtocol):
     96             def onOpen(self):
     97                 if on_open is not None:

UnboundLocalError: local variable 'WebSocketClientProtocol' referenced before assignment
```
**Screenshots**

**Expected behavior**
No error should be generated
**Platform (please complete the following information):**
 - Chrome
 - Python API Version 2.0.1`

**Additional context**
StreamService is shared publicly / anonymously

**Comment by nanaeaubry** [comment]
Thanks for bringing this to our attention, we will take a look

**Comment by nanaeaubry** [comment]
Do you have these packages installed:

![image](https://user-images.githubusercontent.com/19919283/232857593-2980440f-7e23-4f75-8c07-883c6e892dba.png)

The print statement probably is not showing correctly so it is silently failing. We will fix this but in any case you have to have these packages installed in order to use subscribe.

**Comment by crackernutter** [comment]
Thank you I will try that and get back to you - honestly that print statement might have shown I just didn't connect the dots.
