### ISSUE TITLE
Clone_items fails with Survey123 form item types

### ISSUE THREAD

**Issue by ghost** [Esri/arcgis-python-api#1537]
**Issue**
When attempting to use clone_items on Survey123 Forms between AGOL and a Portal the process fails.

**To Reproduce**
`cloneItems = targetGIS.content.clone_items(items=[item],folder=folder,copy_data=True,owner=targetUser,preserve_item_id=True)`

**Error**
```
Exception has occurred: _ItemCreateException
('Failed to create Form MSESFO Gopher Tortoise Observation: Failed to update Form MSESFO Gopher Tortoise Observation: mismatched tag: line 5, column 543', <Item title:"MSESFO Gopher Tortoise Observation" type:Form owner:FWSGIS>)
xml.etree.ElementTree.ParseError: mismatched tag: line 5, column 543

During handling of the above exception, another exception occurred:

Exception: Failed to update Form MSESFO Gopher Tortoise Observation: mismatched tag: line 5, column 543

During handling of the above exception, another exception occurred:

  File "C:\Users\sredar\Documents\python\portal_to_portal_content_clone.py", line 88, in cloneSurvey
    cloned_items = targetGIS.content.clone_items(items=fldr_items, folder=fldr['title']+"_Python")
  File "C:\Users\sredar\Documents\python\portal_to_portal_content_clone.py", line 104, in main
    cloneSurvey('8acf403ee67f4bb4a2eb9ee005080cbf')
  File "C:\Users\sredar\Documents\python\portal_to_portal_content_clone.py", line 111, in <module>
    main()
arcgis._impl.common._clone._ItemCreateException: ('Failed to create Form MSESFO Gopher Tortoise Observation: Failed to update Form MSESFO Gopher Tortoise Observation: mismatched tag: line 5, column 543', <Item title:"MSESFO Gopher Tortoise Observation" type:Form owner:FWSGIS>)

```

**Expected behavior**
clone_items should be capable of cloning Survey123 forms across platforms since it clear has been able to in the past.

**Platform (please complete the following information):**
 - OS: Window 10
 - Python API Version: 2.1.0.2
 - Visual Studio Code IDE

**Comment by Samsetsfire** [comment]
I am using ArcGIS Pro 3.1.3. GIS object ist now on 2023.3.
Error message is:
`arcgis._impl.common._clone._ItemCreateException: ('Failed to create Form XYZ: Failed to update Form XYZ: mismatched tag: line 5, column 296', <Item title:"XYZ" type:Form owner:....>)`
I am cloning between two AGOL Subscriptions. with copy_data=False and search_for_exisitn_items=True

**Comment by Samsetsfire** [comment]
Solved by Inspection the XML Object and found that all <input> elements were not closed... So I manipulate the string until all inputs are closed correctly. Due to the api, esri is using a deprecated module to create the xml string: https://github.com/enketo/enketo-xslt
