### ISSUE TITLE
JSON formatting issue with API sample, "Publishing web maps and web scenes"

### ISSUE THREAD

**Issue by jsolly** [Esri/arcgis-python-api#154]
Here is the sample - > https://github.com/Esri/arcgis-python-api/blob/master/samples/05_content_publishers/publishing_web_maps_and_web_scenes.ipynb 
 <summary>
    
1 - Webmap Template JSON is formatted incorrectly
  </summary>
The documentation provides the following webmap template JSON:

```
{'baseMap': {'baseMapLayers': [{'id': 'defaultBasemap',
    'layerType': 'ArcGISTiledMapServiceLayer',
    'opacity': 1,
    'title': 'World Topographic Map',
    'url': 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer',
    'visibility': True}],
  'title': 'Topographic'},
 'operationalLayers': [{'itemId': '',
   'layerType': '',
   'opacity': 1,
   'title': '',
   'url': '',
   'visibility': True}],
 'spatialReference': {'latestWkid': 3857, 'wkid': 102100},
 'version': '2.5'}
```

Using this template, I get JSON parsing errors. To fix the issues, I had to change all of the single quotes to double quotes and surround the `True` values with double quotes.

#### My Fix
This is the modified webmap JSON that works for me:

```
{"baseMap": {"baseMapLayers": [{"id": "defaultBasemap",
    "layerType": "ArcGISTiledMapServiceLayer",
    "opacity": 1,
    "title": "World Topographic Map",
    "url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",
    "visibility": "True"}],
  "title": "Topographic"},
 "operationalLayers": [{"itemId": "fce0ca8972ae4268bc4a69443b8d1ef5",
   "layerType": "ArcGISMapServiceLayer",
   "opacity": 1,
   "title": "2012 USA Median Age (Mature Support)",
   "url": "http://server.arcgisonline.com/ArcGIS/rest/services/Demographics/USA_Median_Age/MapServer",
   "visibility": "True"}],
 "spatialReference": {"latestWkid": 3857, "wkid": 102100},
 "version": "2.5"}
```

**Comment by AtmaMani** [comment]
What is printed in the sample is not JSON, its a Python Dict object of a default web map. In version 1.3, to publish web maps, you no longer have to load a template JSON file. Creating an empty WebMap object will populate it with a template JSON that passes the linter.
