### ISSUE TITLE
Minimal-dependency version for serverless deployment

### ISSUE THREAD

**Issue by cgpeltier** [Esri/arcgis-python-api#1555]
**Is your feature request related to a problem? Please describe.**
I would like to use the ArcGIS Python API with AWS Lambda Functions. However, the `arcgis` library with all dependencies is very large, and over the size limit for deployment within a lambda function or as a lambda layer. There have been some threads on the Esri Community site about this, but it would be nice to get an off-the-shelf solution; maybe an official lambda layer arn or a minimal-dependency version of the library for serverless usage. 

Our serverless use case is pretty straightforward - just updating an AGOL feature layer from an SEDF.

**Comment by nanaeaubry** [comment]
@jtroe Is there something like this at the moment or in the works?

**Comment by crackernutter** [comment]
@cgpeltier I was able to figure out the minimum dependencies through some trial and error for v 2.0.1 (min dependencies might change with different versions though) and was able use the library in Lambda.  I still had to use S3 to host the zip file with the arcgis packages, but the size was hovering around 50 MB.  

I have a .bat file that creates the environment and installs everything needed.  All you need is to zip the python folder afterwards, deploy to S3, and add it as a layer to your lambda function.

`conda create --name lambda -y
CALL activate lambda
conda install python=3.9 -y
CALL mkdir "C:\Users\jay\AppData\Local\ESRI\conda\envs\lambda\python"
pip install -r arcgismindeps.txt --platform manylinux2014_x86_64 --target "C:\Users\jay\AppData\Local\ESRI\conda\envs\lambda\python" --implementation cp --python 3.9 --only-binary=:all:
pip install arcgis --no-deps --target "C:\Users\jay s gregory\AppData\Local\ESRI\conda\envs\lambda\python"`

The arcgismindeps.txt has:
ujson
requests
pandas
six
requests_toolbelt
requests_ntlm 
ntlm_auth
cachetools
lxml
requests_oauthlib
geomet

**Comment by hildermesmedeiros** [comment]
@crackernutter  For your future self happiness, I would recommend pinning yourarcgismindeps.txt (requirements.txt).

**Comment by achapkowski** [comment]
@crackernutter glad it's working. If you use an Image and register it with AWS, you can do a full install.
