### ISSUE TITLE
gis.content.deleteItems does not work for items not owned by user

### ISSUE THREAD

**Issue by philnagel** [Esri/arcgis-python-api#1572]
**Describe the bug**
Deleting an item owned by a different user fails due to the API using the wrong URL. The API attempts to delete the item using the URL for the signed in user, not the owner of the item.
eg:
`/sharing/rest/content/users/LOGGEDIN/deleteItems`
instead of:
`/sharing/rest/content/users/OWNER/deleteItems`

**To Reproduce**
If we assume that I am logged in as an administrator and try to delete an item owned by another user, I would have permissions to delete the item. This can be verified with:
```
item = gis.content.get('some-item-id')
gis.content.can_delete(item)
>>> {'itemId': 'some-item-id', 'success': True}
```

But when I actually try and delete the item, it fails:
```
gis.content.delete_items([item])
>>> False
```
error:
N/A
**Screenshots**
N/A

**Expected behavior**
The delete_items method should delete items if I have privileges to delete them.

**Platform (please complete the following information):**
 - OS: maxOS
 - Browser N/A
 - Python API Version 2.1.0.3

**Comment by nanaeaubry** [comment]
Thanks for reporting this, we will take a look
