### ISSUE TITLE
new installs of arcgis + arcpy 3.1 install urrlib3 2.0.2

### ISSUE THREAD

**Issue by HRhades** [Esri/arcgis-python-api#1574]
Creating a new environment with `arcpy=3.1` and `arcgis`, `urllib3=2.0.2` is used instead of `urllib3=1.26.15`. `urrlib3=2.0.2` is missing a whitelist_method in de Retry function which used to be present in the `1.26.15` version previously installed alongside arcgis and arcpy. This gives an error while creating a GIS Object. 

The connection part gives a custom html adaptor, in which a whitelist_method parameter is supplied to the Retry class init, which does not exist anymore in the `2.0.2` version.

This would either need to be fixed so the connection works with `urrlib3=2.0.2`
Or `1.26.15^`  needs to be set fixed in the `arcgis` dependencies for now so new installs will not be broken by this urllib3 version

**Comment by nanaeaubry** [comment]
Hello this is a known issue that has been addressed. Please see: https://github.com/Esri/arcgis-python-api/issues/1553

The best workaround is to install the version of urllib3 you need before installing arcgis.
