### ISSUE TITLE
Map cannot be displayed in Jupyter Notebook

### ISSUE THREAD

**Issue by kychanbp** [Esri/arcgis-python-api#158]
I do not have GIS desktop installed.
I used conda to install the API.
Python Version is 3.6.
OS: windows 10

I tried the follwing:
```
from arcgis.gis import GIS
my_gis = GIS()
my_gis.map()
```

No map can be displayed.

**Comment by achapkowski** [comment]
are you running this from jupyter notebooks?

**Comment by kychanbp** [comment]
Yes. I have solved this by referring to https://github.com/Esri/arcgis-python-api/issues/10.

![gis problem solved](https://user-images.githubusercontent.com/17669769/33718227-a55eb4b8-db97-11e7-92c6-7b67c59a07ec.png)

**Comment by achapkowski** [comment]
great, let me close the issue.
