### ISSUE TITLE
MapView widget does not render in ArcGIS 1.9.1

### ISSUE THREAD

**Issue by crackernutter** [Esri/arcgis-python-api#1580]
**Describe the bug**
When trying to render the mapview JavaScript widget in the arcgispro-py3 environment, or a cloned environment, it does not render

**To Reproduce**
```python
from arcgis.gis import GIS
gis=GIS()
m=gis.map()
m
```
error:
No error - it just won't render
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**
Except a javascript mapview to render

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] - Chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` 1.9.1 currently, but think it applies to others

**Additional context**
I've gotten this to work before by manually running the following two lines:
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install arcgis-map-ipywidget@1.9.1 (or whatever version)

But now it seems like jupyterlab-manager is installed, and now installing the widget is asking me to install nodejs, and when I do, and then rerun the line, the build fails.  In short - how do I get the JavaScript map widget to render in the Jupyter Lab environment.

**Comment by nanaeaubry** [comment]
Hello, 
Thanks for reporting! We are aware of the issue and trying to work on it. This is occurring due to an update in other dependencies that are no longer working with jupyter labs 2 (the recommended version for our widget). We are actively working on this but cannot provide a fix right now other than suggesting you use jupyter notebooks for any workflows needing a rendered widget.

**Comment by nanaeaubry** [comment]
Just an update that we are close to releasing a new mapping widget that will be compatible with Jupyter Labs 4! Stay tuned :)

**Comment by nanaeaubry** [comment]
@crackernutter Please use the latest install of arcgis and the new arcgis-mapping packages to try again:
conda install -c esri arcgis arcgis-mapping

Documentation should be updated shortly with the new guides on how to use this module
