### ISSUE TITLE
Group cannot be created with `membership_access=None`

### ISSUE THREAD

**Issue by philnagel** [Esri/arcgis-python-api#1581]
**Describe the bug**
In order to create a group that allows members from any org, `membershipAccess` [needs to be passed](https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm) as `None` \ `null`
When doing this with the ArcGIS API for Python, the argument is not included in the POST payload. I believe it is being filtered out in the function `_to_utf8()`:

![image](https://github.com/Esri/arcgis-python-api/assets/17130646/4c6aa0d0-99e9-471d-acef-d7c46519e259)

**To Reproduce**
```python
group = gis.groups.create(title='A test group that should allow members from any org', tags=['test'], membership_access=None)
```
error:
N/A
**Screenshots**
Fiddler payload as captured from ArcGIS API:
![image](https://github.com/Esri/arcgis-python-api/assets/17130646/280186c4-1455-431e-a763-984380358733)

Fiddler Payload as captured from AGOL UI:
![image](https://github.com/Esri/arcgis-python-api/assets/17130646/5bac0c8e-15f1-409a-9fb7-c3ad47612ca1)

**Expected behavior**
Include the parameter even with the empty value in order to create the group with the proper settings.

**Platform (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Python API Version 2.1.0.2

**Additional context**
N/A

**Comment by nanaeaubry** [comment]
Thanks for reporting this we will take a look!

**Comment by nanaeaubry** [comment]
We have fixed the issue for the next release
