### ISSUE TITLE
Python Samples "sudden ID"

### ISSUE THREAD

**Issue by amrirasyidi** [Esri/arcgis-python-api#1586]
I just read a [crime analysis sample](https://developers.arcgis.com/python/samples/crime-analysis-and-clustering-using-geoanalytics-and-pyspark/) from the arcgis python api documentation. While reading it, I found ids with no explanation where to find it like these:

```python
bigdata_fileshares = bigdata_datastore_manager.search(id='0e7a861d-c1c5-4acc-869d-05d2cebbdbee')
bigdata_fileshares
```
and
```python
illinois_blk_grps = agol_gis.content.get('a11d886be35149cb9dab0f7aac75a2af')
```

I don't quite understand how the tutorial decide which ID to use (like `id='0e7a861d-c1c5-4acc-869d-05d2cebbdbee'` and `'a11d886be35149cb9dab0f7aac75a2af'`), and where to find them?

If it requires the user/developer to go to a specific page (e.g. AGOL content page), I think it will be much clearer.

**Comment by nanaeaubry** [comment]
To find the item ids you can look at the item properties using the python API or you can also look at the item in your ArcGIS Online or Enterprise and find them in the url.

![image](https://github.com/Esri/arcgis-python-api/assets/19919283/226fcde4-6857-4cb1-ae77-fa2acf663e17)

**Comment by amrirasyidi** [comment]
Hi, thanks for the response.

My issue was about the tutorial clarity.

I think it would be helpful to add this line as a step in the tutorial, instead of suddenly bring up ids out of nowhere.
"To find the item ids you can look at the item properties using the python API or you can also look at the item in your ArcGIS Online or Enterprise and find them in the url."

Or maybe something like "to find the id go to this [page](https://developers.arcgis.com/documentation/glossary/item-id/)". Or to a more appropriate page (I found a better tutorial to find an item id than that page, but I can't remember where).
