### ISSUE TITLE
Using GIS class causes overwrite of datetime library import

### ISSUE THREAD

**Issue by cvricella2** [Esri/arcgis-python-api#1589]
**Describe the bug**
Using GIS class causes overwrite of datetime library import

**To Reproduce**
```python
from arcgis.gis import GIS
from datetime import datetime

datetime.now() # works without issue
gis = GIS("home") # assuming auth from ArcGIS Pro, not tested with user and pw
datetime.now() # throws exception, because now entire datetime module is imported
```
error:
```python
AttributeError: module 'datetime' has no attribute 'now'
```

**Expected behavior**
That the python API won't interfere with imports in my scripts

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.1.0.2

**Comment by achapkowski** [comment]
@cvricella2 this isn't a bug rather a function of the order for which python imports things.

**Comment by cvricella2** [comment]
Ah okay I was kinda thinking that after I submitted, thanks for confirming. Weird I’ve been scripting for years and I’ve never ran into that before.

Best,

Carl Vricella

**Comment by cvricella2** [comment]
> @cvricella2 this isn't a bug rather a function of the order for which python imports things.

I think this is still in fact a bug. importing Datetime before the GIS module doesn't fix the issue. Once you create the GIS object your import is over written. I've never had this issue before when using 3rd party libraries.

**Comment by hildermesmedeiros** [comment]
@cvricella2 in my env it works...
![image](https://github.com/Esri/arcgis-python-api/assets/20046591/1fae48c7-037e-470c-96d7-64a8c5507418)

I would inspect your env(s)....other packages, do some investigation.


You can do somethin like:

```python
import os
from arcgis.gis import GIS
from datetime import datetime
import inspect

print(os.path.abspath(inspect.getfile(datetime)))
gis = GIS("home") # assuming auth from ArcGIS Pro, not tested with user and pw
print(os.path.abspath(inspect.getfile(datetime)))
```
You should see the same folder....
```
C:\Users\<user>\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\datetime.py
C:\Users\<user>\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\datetime.py
```
My advices are:
 - You could try import as;
 - check youre not in lib hell cenario;
 
Any way....good luck!

**Comment by cvricella2** [comment]
Are you at the same version (2.1.0.2)? 

Can you explain the reasoning behind your suggestion/what it shows? It seems to show that before and after the creation of the `GIS` object that `datetime` is being imported from the same spot but I don't follow how that is relevant.

I'm not suspecting an environment issue but the datetime module getting imported again as `import datetime` when whatever code is ran when you create a `GIS` object.

**Comment by hildermesmedeiros** [comment]
@cvricella2 If they point to the same folder, it means that your gis datetime is the default one, and your env ArcGIS API is doing import datetime, its typical circular import

Here's an example code snippet illustrating the usage:
```
from arcgis.gis import GIS
from datetime import datetime as dtcls
import inspect

print(dtcls.now())
gis = GIS("home")
print(os.path.abspath(inspect.getfile(datetime)))
print(datetime.datetime.now())
```

Calling a function/class from a package with the same name can lead to issues, especially in larger projects where circular dependencies can arise. It's generally it isconsidered a good practice to avoid naming conflicts like this to prevent potential problems.

If you encounter circular import issues or want to avoid potential conflicts, you could try use an alias when importing the object. This way, you can differentiate between the module and the function with the same name.

But while using aliases with the as keyword can help avoid naming conflicts, it may introduce confusion or make the code less readable, especially if the alias is not intuitive or widely recognized.

read here to clarify.
https://stackoverflow.com/questions/15707532/import-datetime-v-s-from-datetime-import-datetime
https://www.askpython.com/python/built-in-methods/circular-dependencies


Any way, Typical circular problem try this
```
import builtins
import pandas as pd
import inspect
import os
old_import = __import__

def get_object_type(obj):
    obj_type = type(obj).__name__
    if inspect.ismodule(obj):
        return f"{obj_type} (module)"
    elif inspect.isclass(obj):
        return f"{obj_type} (class)"
    elif inspect.isfunction(obj):
        return f"{obj_type} (function)"
    elif inspect.ismethod(obj):
        return f"{obj_type} (method)"
    else:
        return obj_type

CHECK_DF = pd.DataFrame([])
def importWithLog(*args, **kwargs):
    global CHECK_DF
    module_name = f"{args[0]}"
    frame = inspect.currentframe().f_back
    lineno = frame.f_lineno
    called_from = frame.f_globals['__file__']
    name = frame.f_globals['__name__']
    to_check = ''
    if 'datetime' in module_name:
        if 'datetime' in globals():
            to_check = get_object_type(datetime)

        CHECK_DF = pd.concat([pd.DataFrame.from_records({'from': [called_from],
                                                         'name': [name],
                                                         'check': [to_check],
                                                         'lineno': [lineno]}),
                              CHECK_DF], ignore_index=True)
    return old_import(*args, **kwargs)

builtins.__import__ = importWithLog


from datetime import datetime
from arcgis.gis import GIS

try:
    datetime.now()
    gis = GIS("home")
    datetime.now()
except Exception:
    pass
finally:
    user_folder = os.path.expanduser('~')
    csv_path = os.path.join(user_folder, 'check.csv')
    print(f'Saving to {csv_path}')
    CHECK_DF.to_csv(csv_path, index=False)

```

If I did it right you will find the culprint doing import datetime, but a circular import with datetime it will happend once in a wile, it is better  consider other aproachs. Reading the arcgis api they do import `from datime import datime` too, quite often.
