### ISSUE TITLE
iPython/Jupyter tab completion no longer working after updating to Pro 3.1.2

### ISSUE THREAD

**Issue by jacobdadams** [Esri/arcgis-python-api#1591]
**Describe the bug**
Variable name tab completion is no longer working in jupyter notebooks or ipython after upgrading ArcGIS Pro from 3.0.x to 3.1.2 (`ipython 7.34.0`).

It still works in environments that I have not yet upgraded (`ipython 7.21.0`) or that are created without pro (`ipython 8.13.2`).

If I create an empty environment in conda and `conda install ipython`, tab completion does not work (installs packages from esri channel by default).

If I create an empty environment in conda but force the defaults channel via `conda install python=3.9 ipython=7.34 -c defaults`, tab completion does work.

**To Reproduce**

- Install ipython by cloning the default pro env or `conda create -n test`, `activate test`, `conda install ipython`
- Run ipython
- declare a variable: `foobar = 3 <enter>`
- try to tab complete variable name: `foo<tab>`

**Expected behavior**
variable/function names should tab complete.

**Platform (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: n/a

**Additional context**

I did not upgrade from 3.0.x to 3.1 until 3.1.2, so I don't know if the behavior was present in 3.1.0 or 3.1.1.1

Simplest conda env to reproduce issue:
```
(test) λ conda list
# packages in environment at C:\Users\username\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\test:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyhd3eb1b0_0
colorama                  0.4.6            py39haa95532_0
decorator                 5.1.1              pyhd3eb1b0_0
ipython                   7.34.0             pyhbfea036_1    esri
jedi                      0.18.2                   py39_0    esri
openssl                   3.0.7                         0    esri
parso                     0.8.3              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       23.1.2           py39haa95532_0
prompt_toolkit            3.0.5                      py_0    esri
pygments                  2.9.0                      py_0    esri
python                    3.9.16                        0    esri
setuptools                65.5.1                   py39_0    esri
six                       1.16.0                     py_0    esri
sqlite                    3.40.1                        0    esri
traitlets                 5.5.0                      py_0    esri
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2    esri
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.38.4           py39haa95532_0
```

**Comment by jacobdadams** [comment]
Update:

Manually doing `conda install jedi 0.18.1` (which pulls from `pkgs/main`) after cloning `arcgispro-py3` seems to fix the problem. Not sure what other side effects that may have elsewhere.

**Comment by nanaeaubry** [comment]
@jtroe FYI, not sure if this is something we are looking at

**Comment by jtroe** [comment]
ArcGIS Pro team is currently testing a fix for this

**Comment by scdub** [comment]
@jacobdadams thanks for reporting this. We've uploaded a fixed jedi build to the `esri` channel, you can either upgrade to it, or run `conda install esri::jedi` to get it, you should see `jedi 0.18.2 py_1` being installed.
