### ISSUE TITLE
gssapi error when connecting to Standalone server with AD user

### ISSUE THREAD

**Issue by adc0211** [Esri/arcgis-python-api#1593]
**Describe the bug**
I get an error when attempting to connect to a standalone (3 machine) GIS Server site, version 11.1
I have tried with the arcgis api and python installation included with ArcGIS Pro 3.1.2 and ArcGIS Server 11.1

**To Reproduce**
GIS Server site setup:
Unfederated, User store is Windows, Roles store is built-in
Authentication tier - GIS Server, Authentication mode is Token
I have verified that I can log in to the REST Admin and Manager pages with this account
```python
gis_server = Server(url="https://someurl/webadaptor/admin", username="domain\\UserInAdminRole", password="windowspass")
```
error:
```python
Traceback (most recent call last):
  File "E:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 75, in __init__
    creds = gssapi.raw.acquire_cred_with_password(
  File "gssapi\raw\ext_password.pyx", line 75, in gssapi.raw.ext_password.acquire_cred_with_password
gssapi.raw.exceptions.BadNameError: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\server\admin\administration.py", line 157, in __init__
    gis = Connection(**kwargs)
  File "E:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 344, in __init__
    self._create_session()
  File "E:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 691, in _create_session
    self._session.auth = EsriWindowsAuth(
  File "E:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\auth\_auth\_winauth.py", line 84, in __init__
    raise Exception("Please ensure gssapi is installed")
Exception: Please ensure gssapi is installed
```
**Screenshots**

**Expected behavior**
I expected to be able to successfully connect to the GIS Server site and call administrative functions/properties

**Platform (please complete the following information):**
 - OS: Windows Server 2022
 - Browser: Edge
 - Python API Version: 2.1.0.2

**Additional context**
The code below works to connect, however it fails when calling any function or properties that are for admins. I am using an account that is in an Administrator role. 
```python
gis_server = Server(url="https://someurl/webadaptor/admin", username="UserInAdminRole@domain", password="windowspass")
print(str(gis_server.properties))
```
The response is:
```
{
  "status": "error",
  "messages": [
    "Authorization failed. This user account does not have the required privileges to access this application/operation."
  ],
  "code": 498
}
```
If I request the machine property, the error will say that the 'Server' object has not attribute 'machines'. The same goes for users.

This only works if I enable the psa and use that account's credentials to log in, or change the user store to built-in users. For security reasons, I want the psa account disabled and to use the Windows user store. There is an esri community thread about this issue as well.
https://community.esri.com/t5/arcgis-api-for-python-questions/please-ensure-gssapi-is-installed/m-p/1264853#M8466

**Comment by jcguarneri** [comment]
To add to @adc0211 's post, several others of us are having this same issue while authenticating to Portal:
https://community.esri.com/t5/arcgis-api-for-python-questions/please-ensure-gssapi-is-installed/td-p/1264853
After extensive testing and tracking things down, I determined that the Exception: Please ensure gssapi is installed is being returned erroneously by Esri's code. Where that exception call is triggered, the PythonAPI code assumes that if the gssapi authentication step fails, then gssapi is missing. However, gssapi runs and returns an error message. I was able to confirm this by altering the code on a dev installation to see where the code is actually failing.

As for the larger error, I was able to get it working by hardcoding the username and password into _winauth.py and running the GIS(url,username,password) command. After that successful login, I reverted _winauth.py to it's original code and am able to login with usernames formatted as user@domain (but not as domain\user).

**Comment by achapkowski** [comment]
At 2.2.0, we added additional support for username formats.   Hopefully this will resolve these issues.  It will be in the beta release in July.
Please reopen if you encounter issues during the beta tests.
