### ISSUE TITLE
The arcgis.gis.ViewManager update method not accepting input: List of ViewLayerDefParameter objects

### ISSUE THREAD

**Issue by avstjohn** [Esri/arcgis-python-api#1596]
**Describe the bug**
The arcgis.gis.ViewManager update method is not accepting the documented input, which is a List of ViewLayerDefParameter objects.

**To Reproduce**
```python
fl_coll = gis.content.get(fl_id) 
fl_coll_related = fl_coll.related_items(rel_type="Service2Service")
if (fl_coll_related[0].type == 'Feature Service'):
  fl_vm = fl_coll.view_manager
  view_defs = fl_vm.get_definitions(item=fl_coll_related[0]) 
  
  # Make an edit: one of the fields not visible
  view_defs[0].fields[1]['visible'] = False
  
  # Feed the view_defs (list of ViewLayerDefParameter objects) to the ViewManager's update() method
  fl_vm.update(layer_def=view_defs)
```
**error:**
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_26224\1855571114.py](https://file+.vscode-resource.vscode-cdn.net/i%3A/AssetAlly_ArcGISProProjects/AssetAlly/Stormwater/~/AppData/Local/Temp/ipykernel_26224/1855571114.py) in ()
     25     # }
     26 
---> 27     fl_vm.update(layer_def=view_defs)
     28     #print(type(view_defs))
     29     #print(type(view_defs[0]))

[c:\Program](file:///C:/Program) Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py in update(self, layer_def)
  16575         for lyrdef in layer_def:
  16576             assert isinstance(lyrdef, ViewLayerDefParameter)
> 16577             layer = layer_def.layer
  16578             assert isinstance(layer, arcgis.features.FeatureLayer)
  16579             if "isView" in lyrdef.layer.properties and lyrdef.layer.properties.isView:

AttributeError: 'list' object has no attribute 'layer'
```
**Screenshots**

**Expected behavior**
 I am expecting that the list of _ViewLayerDefParameter objects_ returned by the _ViewManager get_definitions(item)_ method is usable as the input to the _ViewManager update(layer_def)_ method to apply schema edits to the hosted feature layer view.

**Platform (please complete the following information):**
 - OS: **Windows 11**
 - Browser: N/A
 - Python API Version: **2.1.0.2**
 - Python environment: **c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3** packaged with ArcGIS Pro 3.1.2
**Additional context**

**Comment by nanaeaubry** [comment]
Thanks for reporting, we will take a look at this

**Comment by avstjohn** [comment]
Great, thank you!
Was it just changing line 16577 to **layer = lyrdef.layer**?

**Comment by nanaeaubry** [comment]
@avstjohn Yes! :)

**Comment by avstjohn** [comment]
@nanaeaubry I no longer see that error, but the issue now is that the operation claims to be successful while nothing changes on the view that I am trying to update the definition of.

```python
view_items = gis_target.content.search(query=rf'title:{target_view_name}, type:"Feature Service"')

for view_item in view_items:   
    layers_in_view = view_item.view_manager.get_definitions(view_item)
    counter = 0
    for layer in layers_in_view:
        update_dict = ViewLayerDefParameter(layer=layer.layer, fields=fields_list[counter])
        print(fields_list[counter])
        view_item.view_manager.update(layer_def=[update_dict])
        counter += 1
```

**Printed output from the code above, where I want all of those "visible=false" to go through to the view definition**

>[{'name': 'OBJECTID', 'visible': True}, {'name': 'Owner', 'visible': False}, {'name': 'Status', 'visible': False}, {'name': 'YearAbandoned', 'visible': False}, {'name': 'Source', 'visible': False}, {'name': 'SourceDate', 'visible': False}, {'name': 'Notes', 'visible': False}, {'name': 'Contractor', 'visible': False}, {'name': 'ProjectNumber', 'visible': False}, {'name': 'Asset_Condition', 'visible': False}, {'name': 'Asset_Risk', 'visible': False}, {'name': 'Asset_ConsequenceOfFailure', 'visible': False}, {'name': 'Asset_ProbabilityOfFailure', 'visible': False}, {'name': 'UID', 'visible': False}, {'name': 'UserID', 'visible': False}, {'name': 'EditDate', 'visible': False}, {'name': 'Address', 'visible': False}, {'name': 'StreetName', 'visible': False}, {'name': 'CrossStreetName', 'visible': False}, {'name': 'LocationDescription', 'visible': False}, {'name': 'StructureNo', 'visible': False}, {'name': 'IsBuried', 'visible': False}, {'name': 'Rim', 'visible': False}, {'name': 'MHSize', 'visible': False}, {'name': 'Frame', 'visible': False}, {'name': 'Cover', 'visible': False}, {'name': 'Material', 'visible': False}, {'name': 'Depth', 'visible': False}, {'name': 'RingMaterial', 'visible': False}, {'name': 'SprayLined', 'visible': False}, {'name': 'YearInstalled', 'visible': True}, {'name': 'BasinID', 'visible': False}, {'name': 'ChimneyMaterial', 'visible': False}, {'name': 'ConeMaterial', 'visible': False}, {'name': 'BarrelMaterial', 'visible': False}, {'name': 'StructureType', 'visible': False}, {'name': 'YearLined', 'visible': True}, {'name': 'SurfaceType', 'visible': False}, {'name': 'CrossSection', 'visible': False}, {'name': 'LidVentHoles', 'visible': False}, {'name': 'PickHolesConcealed', 'visible': False}, {'name': 'GasketSeal', 'visible': False}, {'name': 'BoltDownLid', 'visible': False}, {'name': 'FrameGradeToGround', 'visible': False}, {'name': 'GradeAboveBelow', 'visible': False}, {'name': 'OffsetDistance', 'visible': False}, {'name': 'NoAdjRings', 'visible': False}, {'name': 'HeightAdjRings', 'visible': False}, {'name': 'SealType', 'visible': False}, {'name': 'SealPresent', 'visible': False}, {'name': 'SealDiameter', 'visible': False}, {'name': 'InternalSealOnChimney', 'visible': False}, {'name': 'InternalSealOnFrame', 'visible': False}, {'name': 'ChimneyHeight', 'visible': False}, {'name': 'FirstStepHeight', 'visible': False}, {'name': 'PipeOpenings', 'visible': False}, {'name': 'BenchPresent', 'visible': False}, {'name': 'BenchPipeConnection', 'visible': False}, {'name': 'CoverThickness', 'visible': False}, {'name': 'CoverWidth', 'visible': False}, {'name': 'FrameOpeningWidth', 'visible': False}, {'name': 'FrameDepth', 'visible': False}, {'name': 'FrameCoverDepth', 'visible': False}, {'name': 'ExternalSealOnChimney', 'visible': False}, {'name': 'ExternalSealOnFrame', 'visible': False}, {'name': 'GlobalID', 'visible': True}, {'name': 'created_user', 'visible': False}, {'name': 'created_date', 'visible': False}, {'name': 'last_edited_user', 'visible': False}, {'name': 'last_edited_date', 'visible': False}, {'name': 'YearInspected', 'visible': True}]
[{'name': 'OBJECTID', 'visible': True}, {'name': 'GlobalID', 'visible': True}, {'name': 'Owner', 'visible': False}, {'name': 'Status', 'visible': False}, {'name': 'YearAbandoned', 'visible': False}, {'name': 'Source', 'visible': False}, {'name': 'SourceDate', 'visible': False}, {'name': 'Notes', 'visible': False}, {'name': 'Contractor', 'visible': False}, {'name': 'ProjectNumber', 'visible': False}, {'name': 'Asset_Condition', 'visible': False}, {'name': 'Asset_Risk', 'visible': False}, {'name': 'Asset_ConsequenceOfFailure', 'visible': False}, {'name': 'Asset_ProbabilityOfFailure', 'visible': False}, {'name': 'UID', 'visible': False}, {'name': 'UserID', 'visible': False}, {'name': 'EditDate', 'visible': False}, {'name': 'Address', 'visible': False}, {'name': 'StreetName', 'visible': False}, {'name': 'CrossStreetName', 'visible': False}, {'name': 'LocationDescription', 'visible': False}, {'name': 'PipeID', 'visible': False}, {'name': 'PipeType', 'visible': False}, {'name': 'Diameter', 'visible': False}, {'name': 'Material', 'visible': False}, {'name': 'UpMH', 'visible': False}, {'name': 'UpInv', 'visible': False}, {'name': 'UpDir', 'visible': False}, {'name': 'DnMH', 'visible': False}, {'name': 'DnInv', 'visible': False}, {'name': 'DnDir', 'visible': False}, {'name': 'DnOD', 'visible': False}, {'name': 'DnODInv', 'visible': False}, {'name': 'YearInstalled', 'visible': True}, {'name': 'AsBuiltLength', 'visible': False}, {'name': 'YearTelevised', 'visible': True}, {'name': 'TelevisingCycle', 'visible': True}, {'name': 'Problem', 'visible': False}, {'name': 'YearCleaned', 'visible': True}, {'name': 'CleaningCycle', 'visible': True}, {'name': 'YearLined', 'visible': True}, {'name': 'YearGrouted', 'visible': True}, {'name': 'YearRootFoamed', 'visible': True}, {'name': 'PipeDepth', 'visible': False}, {'name': 'RiserPipe', 'visible': False}, {'name': 'RiserPipeHeight', 'visible': False}, {'name': 'SharedRiser', 'visible': False}, {'name': 'SharedWith', 'visible': False}, {'name': 'created_user', 'visible': False}, {'name': 'created_date', 'visible': False}, {'name': 'last_edited_user', 'visible': False}, {'name': 'last_edited_date', 'visible': False}, {'name': 'BasinID', 'visible': False}, {'name': 'Shape__Length', 'visible': False}]

**Example Fiddler output of the updateDefinition operation**
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/0d924eb2-9e9f-4e57-b8c6-27e77794c6ee)

**Comment by nanaeaubry** [comment]
@achapkowski Can you help with this?
