### ISSUE TITLE
Create a web map with my own custom layer set as Basemap

### ISSUE THREAD

**Issue by previewqueen** [Esri/arcgis-python-api#1603]
Currently code to create a web map will only allow setting the Basemap with a designated ESRI Basemap. What I would like to be able to do is create a web map and set a custom created layer as the Basemap instead. At the moment the only way to do it is manually, which is tedious when you need to create several maps with a custom Basemap. Even if a custom Basemap has been created in the Organization, it cannot be used or called. The code only allows and sees designated Esri created and owned Basemaps. 
this is a problem if your organization requires their own custom Basemap to be used or are in a disconnected environment and can’t even access the Esri basemaps at all. 
——————————————-
Use case examples:
#1 
User is setting up disconnected/highly isolated environments and would like to automate creating several custom Basemap templates that would be shared to a custom group and then set as the Basemap gallery in the organization. 

#2
User needs to create web maps reports often, but are required to use a custom Basemap per customer’s or their organizations policy/requirements. 

——————————————-
Here is the documentation of what part of the code that I am recommending to update: 

https://developers.arcgis.com/python/api-reference/arcgis.mapping.toc.html

 Scroll down to following properties:
~ basemap
~ basemap_title
~ basemap_switcher
~ basemaps

**Comment by nanaeaubry** [comment]
Hello,

Have you tried using the `move_to_basemap` method?
