### ISSUE TITLE
Unable to append to AGOL feature layer using featureCollection

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-python-api#1604]
**Describe the bug**
While submitting an `featurelayer.append()` request using python api v2.1.0.3, we get an unknown error.

**To Reproduce**
1. Create a FeatureSet.from_dict() using a list of feature objects
2. Create a FeatureCollection.from_featureset()
3. Run featurelayer.append()

error:
See screenshot below, the featureCollection gets passed as string object name instead of JSON, as seen in fiddler capture

**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/1454027/388c0370-4cbb-4d3c-a6ad-062349f52b74)

This is the response you get when you try to get status

![image](https://github.com/Esri/arcgis-python-api/assets/1454027/55fa97ba-bc3a-49dc-81bf-45af123de6fc)

**Expected behavior**
The featureCollection must be sent as json

**Comment by nanaeaubry** [comment]
Thanks for reporting this, we will take a look and post any updates

**Comment by nanaeaubry** [comment]
How are you making the append call? What parameters are you defining?

**Comment by anandak** [comment]
@nanaeaubry my apologies, I logged this issue too soon. The root cause was that some properties of the featurecollection like its name were coming from a different configuration settings module and was failing during conversion to JSON. 
I was able to get append to run successfully.

**Comment by anandak** [comment]
@nanaeaubry 
I have run into a strange issue with using append. It fails when there is date field in the feature collection and succeeds if we dont supply a date field in the feature collection. Here is the code you can use to reproduce the issue. You can either create a copy of this feature layer or use my layer as it is anonymously accessible and created only for reproducing this issue purpose.

The code below fails 
```python
from arcgis import GIS
from arcgis.features import Feature, FeatureSet, FeatureLayer, FeatureCollection
import uuid
from datetime import datetime

gis = GIS(url="https://www.arcgis.com", username="xx", password="xx")

# this layer is anonymously accessible
layer_url = "https://services1.arcgis.com/DlnuvLGpDczjeSgG/arcgis/rest/services/appendissue/FeatureServer/0"

fl = FeatureLayer(url=layer_url, gis=gis)

pt_geom = {"x":11.5, "y":20.5,"spatialReference": {"wkid":4326}}
pt_attributes = {"appendkeyfield":str(uuid.uuid4()), "nibrs_code":"345", "reported_date": datetime.now()}
feature = Feature(geometry=pt_geom, attributes=pt_attributes)
fs = FeatureSet(features=[feature])
fc = FeatureCollection.from_featureset(fs)

result = fl.append(upload_format='featureCollection',
                                edits=fc.properties,
                                upsert=True,
                                skip_inserts=False,
                                skip_updates=False,
                                update_geometry=True, 
                                use_globalids=False,
                                rollback=True,
                                upsert_matching_field="appendkeyfield",
                                return_messages=True)

print(result)
``` 
The error message is
![image](https://github.com/Esri/arcgis-python-api/assets/1454027/4097751e-67df-42e6-beda-34ee665885ae)


But, if you re-run the code after removing the date field in this line, 
`pt_attributes = {"appendkeyfield":str(uuid.uuid4()), "nibrs_code":"345"`
you will see that it succeeds with this message

![image](https://github.com/Esri/arcgis-python-api/assets/1454027/e02cafe8-6474-40c7-b7ac-45977b78049f)

**Comment by nanaeaubry** [comment]
@anandak Ok we will look at it, thanks for providing sample code!

**Comment by anandak** [comment]
Hi @nanaeaubry were you able to reproduce the issue?

**Comment by anandak** [comment]
@nanaeaubry  Thanks, will wait for next release.
