### ISSUE TITLE
Append inserts a new record even though upsert_matching_field is not present in featurecollection

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-python-api#1605]
**Describe the bug**
Not sure if this is the right place to report, but I've observed that when you use append, even though the upsert_matching_field is not present at all in the featurecollection, it still inserts a new feature into the layer. 
I expected it would throw an error, but it doesn't. In the code snippet below, you can see the `crimetype` field is used as a unique field for matching upserts, but it is not present in the input feature collection. But it still inserts a blank record with just the geometry into the layer.

**To Reproduce**
```python
featureset = {"features":[{"geometry":{"x":200000, "y":31221, "spatialReference":{"wkid":102100}}, 
                           "attributes":{"crimedesc":"robbery"}}]}
fs = FeatureSet.from_dict(featureset)
fc = FeatureCollection.from_featureset(fs)

result = layer.append(upload_format='featureCollection',
                                edits=fc.properties,
                                upsert=True,
                                skip_inserts=False,
                                skip_updates=False,
                                update_geometry=True, 
                                use_globalids=False,
                                rollback=True,
                                upsert_matching_field="crimetype",
                                return_messages=True)
```
error:

**Expected behavior**
Since the upsert_matching_field is not present in the featurecollection, we should get an error message and no records should get added to the layer

**Comment by nanaeaubry** [comment]
@anandak 
When I try I get the error message:
![image](https://github.com/Esri/arcgis-python-api/assets/19919283/a0c5e3cc-b0d5-4dd9-bb5c-2ca295298f1e)


I would suggest upgrading to the latest version of the python api (2.1.0.3 or the beta of 2.2.0)

**Comment by anandak** [comment]
@nanaeaubry, my apologies I could not respond earlier. 
Is it that in your case the field `pop2000` does not truly have a unique index? Then its logical and I see the same error.
But in my case the field `crimetype` does have a unique index, but it is not included in the feature collection. It inserts a blank record in such case.

**Comment by nanaeaubry** [comment]
@anandak Ah ok I will take a look again with someone who has a layer like this, thanks for clarifying it.

**Comment by nanaeaubry** [comment]
@anandak  Ok I reached out to find some answers and there is expected behavior. There is a parameter called `skip_inserts` and if you set it to True it will skip the insert and just do the updating. Hope this helps :)
