### ISSUE TITLE
Issue Installing ArcGIS 

### ISSUE THREAD

**Issue by ahmad2003** [Esri/arcgis-python-api#1611]
I have Python version 3.7.9. I am trying to install ArcGIS using the command '**pip install arcgis**'. However, I am getting the following error. 

 pip --no-cache-dir install arcgis
Collecting arcgis
  Downloading arcgis-2.0.0.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 949.8 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ahmad\AppData\Local\Temp\pip-install-ilm7mar0\arcgis_f2ac4677333d4648a8756e2b3455e60e\setup.py", line 193, in <module>
          _get_rel_site_packages_dir() + "arcgis/gis/_impl"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
-------------------------------------------------
I have also tried upgrading 'pip','setuptools' and installing 'ez_setup' but this didn't help. Can you please help me solve the issue? Thanks!

**Comment by nanaeaubry** [comment]
Please attempt to install the latest version and ensure you are using python version that is compatible. For 2.3.0 -> python 3.9, 3.10, 3.11
