### ISSUE TITLE
offline_areas.create() fails when web map is shared

### ISSUE THREAD

**Issue by sindresal** [Esri/arcgis-python-api#1638]
**Describe the bug**
When creating offline areas the web map has to be private . If not the below error occours. I can't find a way to specify the sharing for the created offline area (this should just follow the web maps sharing level?).

error:
```python
<{"code": 10, "messageCode": "OffPkg_ 10", "message": "Failed to add relationship source 26a13b80ea1f4365b285f6b0ca1b7b85 , destination 6d67aac3deb54d88bce7b6f89fc365cf error ERROR: code:500, The two items must be shared the same way for this Relationship Type., Internal server error.", "params": {"source": "26a13b80ea1f4365b285f6b0ca1b7b85", "destination": "6d67aac3deb54d88bce7b6f89fc365cf", "error": "ERROR: code:500, The two items must be shared the same way for this Relationship Type., Internal server error."}}>
```

**Expected behavior**
I expect to be able to set the sharing level for the offline area, or that it just inherit the sharing level of the web map.

**Platform (please complete the following information):**
 - Python API Version 2.1.0.2

**Comment by nanaeaubry** [comment]
@sindresal Thanks for reporting this, we have also noticed it failing so we will investigate and post any updates here

**Comment by sindresal** [comment]
`def execute(self, parameters):

        utils.print_parameters(parameters)

        def check_elapsed_time(start_time):

            elapsed_time = time.time() - start_time

            if elapsed_time > 60:  # 60 seconds = 1 minute

                return True

            return False

       

        # try:

        gis = GIS('pro')

        arcpy.AddMessage(gis.properties.user.username)

        wm_item = gis.content.get(parameters[0].valueAsText)

        arcpy.AddMessage(f'WebMap:{wm_item}')

        wm_objekt = WebMap(wm_item)

        # Access the geometry from the GPFeatureRecordSetLayer parameter

        polygon_layer = parameters[1].value

   

        if parameters[2].value == 0 or parameters[2].value is None:

           

            polygon_geometry= [x[0] for x in arcpy.da.SearchCursor(polygon_layer,["SHAPE@"])][0]

            boundary_poly = Polygon(polygon_geometry)

        else:

            out = r'C:\Users\sindrea\Downloads\hydrorein\Snøheia\p30\Snøheia.gdb\buffer_'+parameters[3].valueAsText

            arcpy.PairwiseBuffer_analysis(polygon_layer, out,f'{parameters[2].value} Meters')

            polygon_geometry= [x[0] for x in arcpy.da.SearchCursor(out,["SHAPE@"])][0]

            boundary_poly = Polygon(polygon_geometry)

 

 

        offline_item_properties = {"title": parameters[3].valueAsText,

                                    "tags": ["Field Maps", parameters[3].valueAsText]}

 

        arcpy.AddMessage('Starting to create offline area..')

        create_start_time = time.time()  # Record the start time of the create operation

        def create_offline_area():

            wm_objekt.offline_areas.create(area=boundary_poly,

                                            item_properties=offline_item_properties,

                                            min_scale=50000,

                                            max_scale=625,

                                            ignore_layers=None,

                                            folder=parameters[4].valueAsText)`

**Comment by sindresal** [comment]
```python

def execute(self, parameters):

        utils.print_parameters(parameters)

        def check_elapsed_time(start_time):

            elapsed_time = time.time() - start_time

            if elapsed_time > 60:  # 60 seconds = 1 minute

                return True

            return False

       

        # try:

        gis = GIS('pro')

        arcpy.AddMessage(gis.properties.user.username)

        wm_item = gis.content.get(parameters[0].valueAsText)

        arcpy.AddMessage(f'WebMap:{wm_item}')

        wm_objekt = WebMap(wm_item)

        # Access the geometry from the GPFeatureRecordSetLayer parameter

        polygon_layer = parameters[1].value

   

        if parameters[2].value == 0 or parameters[2].value is None:

           

            polygon_geometry= [x[0] for x in arcpy.da.SearchCursor(polygon_layer,["SHAPE@"])][0]

            boundary_poly = Polygon(polygon_geometry)

        else:

            out = r'C:\Users\sindrea\Downloads\hydrorein\Snøheia\p30\Snøheia.gdb\buffer_'+parameters[3].valueAsText

            arcpy.PairwiseBuffer_analysis(polygon_layer, out,f'{parameters[2].value} Meters')

            polygon_geometry= [x[0] for x in arcpy.da.SearchCursor(out,["SHAPE@"])][0]

            boundary_poly = Polygon(polygon_geometry)

 

 

        offline_item_properties = {"title": parameters[3].valueAsText,

                                    "tags": ["Field Maps", parameters[3].valueAsText]}

 

        arcpy.AddMessage('Starting to create offline area..')

        create_start_time = time.time()  # Record the start time of the create operation

        def create_offline_area():

            wm_objekt.offline_areas.create(area=boundary_poly,

                                            item_properties=offline_item_properties,

                                            min_scale=50000,

                                            max_scale=625,

                                            ignore_layers=None,

                                            folder=parameters[4].valueAsText)

**Comment by nanaeaubry** [comment]
@sindresal I think this service is down, creating offline area through the browser is also failing. We will let you know when this is working again

**Comment by nanaeaubry** [comment]
@sindresal The team reached out and said the issues have been resolved. Also if you keep seeing the same error, to check that the  layers support offline and that they are sync-enabled.

They also provided this help doc: https://doc.arcgis.com/en/arcgis-online/manage-data/take-maps-offline.htm

**Comment by sindresal** [comment]
@nanaeaubry Thanks for the quick response and fix. It is working now :)
