### ISSUE TITLE
GeoAccessor.to_featurelayer( ) numpy dependency issue

### ISSUE THREAD

**Issue by smartinez2** [Esri/arcgis-python-api#1641]
**Describe the bug**
When trying to publish a Spatially Enabled DataFrame to ArcGIS Online, np.int() is called, which is a deprecated function as of numpy 1.20. The DataFrame must contain integer columns for the error to trigger.

**To Reproduce**
```python
sdf.spatial.to_featurelayer(name)
```
error:
```python
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Expected behavior**
I would expect a new hosted feature layer to be published. 

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Python API Version: 2.1.0.3

**Additional context**
When coercing all columns in the DataFrame to string (sdf.astype(str)), the issue is resolved. I also think this issue may exist for import_pandas() when using non-spatial DataFrames.

**Comment by nanaeaubry** [comment]
Thanks for bringing this up! We fixed it and it will be reflected in the next release (2.2.0) which should occur in September :)
