### ISSUE TITLE
Remove the arcgis.gis.UserManager.send_notification() function

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#1642]
This function does not work, and in light of https://community.esri.com/t5/arcgis-enterprise-questions/quot-you-do-not-have-permissions-quot-when-trying/td-p/1106613 and https://support.esri.com/en-us/bug/when-running-the-create-notification-task-from-portal-s-bug-000143137 it never will.

**Comment by nanaeaubry** [comment]
We look at this, thanks!

**Comment by nanaeaubry** [comment]
Fixed for next version
