### ISSUE TITLE
`from_featureclass` cannot subset data with `fields`

### ISSUE THREAD

**Issue by CMPeng** [Esri/arcgis-python-api#1647]
- [ ] with parameter `fields` set, the returned SeDF should only contain the specified fields + Shape column. Instead, it is returning every column.
 - [ ] with parameter `sql_clause=(None, "ORDER BY st, pop_class")` the returned SeDF should be sorted alphabetically by `st` field, then for the same `st`, sort by the `pop_class` numerically. Instead, the test returned rows unsorted.
 - [ ] with parameter `sql_clause=("DISTINCT pop_class", "ORDER BY name")`, the returned SeDF should have a combination of different population classes, e.g. 8 or 9 rows, instead it returns all 3800+ rows.
 - [ ] with parameter `where_clause="st='ID'"` the returned SeDF should only have rows for state of Idaho. However, test returned 3800+ rows for all states.

Sample TC:
```
fcls_sql3_df = pd.DataFrame.spatial.from_featureclass(location='/arcgis/home/states/cities.shp',
                                                   fields=['st','name','pop_class','age_10_14'],
                                                   where_clause="st='ID'",
                                                   sql_clause=("DISTINCT pop_class", "ORDER BY name"))
# Check Shape
fcls_sql3_df.shape
```
For the full-fledge version of test cases, please refer to https://developers.arcgis.com/python/guide/part2-data-io-reading-data/

Same observation with arcpy or without (when without arcpy, fiona is installed)

Hi @achapkowski Would you consider this a showstopper bug? Or something we can wait for 2.3.0?

**Comment by achapkowski** [comment]
@CMPeng I'll take a look, thank you.

**Comment by achapkowski** [comment]
I think the data fields are incorrect, when I use this dataset, it works.

```
fcls_sql3_df = pd.DataFrame.spatial.from_featureclass(
    location=r'C:\GIS\cities\USA_Major_Cities.shp',
    fields=['ST', 'NAME', 'WHITE', 'POP_CLASS'],
    where_clause="ST='ID'",
[cities.zip](https://github.com/Esri/arcgis-python-api/files/12499757/cities.zip)

    sql_clause=("DISTINCT POP_CLASS", "ORDER BY NAME"),
)
```

**Comment by CMPeng** [comment]
Hi @achapkowski Turns out the mal-functioning of `fields` and `where_clause` only happens when arcpy is not installed (but shapely and fiona present), which is expected; Sorry for the mis-alarm.

However for bulletin points 2 and 3, the ordering made by `sql_clause=(None, "ORDER BY st, pop_class")` and/or the distinct + ordering made by `sql_clause=("DISTINCT pop_class", "ORDER BY name")` are not supported with arcpy as well, e.g.

```
# Postfix Sql clause - order by operation
fcls_sql1 = pd.DataFrame.spatial.from_featureclass(location='/arcgis/home/states/cities.shp',
                                                   fields=['st','pop_class', 'name'],
                                                   sql_clause=("DISTINCT POP_CLASS", "ORDER BY st, pop_class"))

fcls_sql1.tail()
```
which supposed to return SeDF entries sorted by st + pop_class, still returns the natural order:
![image](https://github.com/Esri/arcgis-python-api/assets/12433252/b4fd4ce2-6082-411e-adf3-0358563af196)

Similarly, 
```
# Prefix Sql clause - DISTINCT operation
fcls_sql1 = pd.DataFrame.spatial.from_featureclass(location='/arcgis/home/states/cities.shp',
                                                   where_clause="name='Portland'",
                                                   fields=['st','pop_class', 'name'],
                                                   sql_clause=(None, "ORDER BY st, pop_class"))
fcls_sql1.tail()
```
which is expected to return entries in a sorted order by name, and merge entries according to pop_class, still returns the same natural order, e.g.,
![image](https://github.com/Esri/arcgis-python-api/assets/12433252/17b805e7-80bc-468e-ba5c-36609b96ca27)

The `sql_clause` not being honored seems like an issue with the arcpy method itself (instead of our API), since the arcpy commands of 
```
fc = '/arcgis/home/states/cities.shp'
fields = ['st','pop_class', 'name']

# For each row, print the WELL_ID and WELL_TYPE fields, and
# the feature's x,y coordinates
with arcpy.da.SearchCursor(fc, fields, where_clause="name='Portland'", sql_clause=(None, 'ORDER BY st, pop_class')) as cursor:
    for row in cursor:
        print(u'{0}, {1}, {2}'.format(row[0], row[1], row[2]))
```
also returns a wrong ordering. 
@achapkowski Do we need to further contact this tool's product team for any follow-ups? Thanks!
