### ISSUE TITLE
batch_geocode drops geometries when first feature in response has none

### ISSUE THREAD

**Issue by cflann** [Esri/arcgis-python-api#1650]
**Describe the bug**
The `batch_geocode` function has an edge case where it will return a FeatureSet with no geometries (Shape field) for any of the input addresses. This happens when some of the addresses are empty strings, but is likely non-deterministic due to the bug being dependent on the response from the geocoding service.

**To Reproduce**
```python
from arcgis import GIS
from arcgis.geocoding import get_geocoders, batch_geocode

gis = GIS('https://www.arcgis.com', '<USERNAME_WITH_CREDITS>', '<PASSWORD>')
esri_geocoder = get_geocoders(gis)[0]

test_addrs_good = ['900 Court St NE, Salem, OR 97301'] * 5
test_addrs_bad = ['900 Court St NE, Salem, OR 97301'] + ([''] * 4)

# Has geometry:
results_good = batch_geocode(test_addrs_good, geocoder=esri_geocoder, as_featureset=True).sdf

# No geometry, despite match on OR address
results_bad = batch_geocode(test_addrs_bad, geocoder=esri_geocoder, as_featureset=True).sdf
```

I was able to track the bug down to the FeatureSet constructor: _features.py@453:464. It checks the first feature and bases the response on that alone. This may have been the intended behavior, but creates a case where users use the geocoding service **for credits**, but do not get usable results back.

**Expected behavior**
Results should contain non-null geometries for matched addresses, and null geometries for unmatched ones.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.1.0.2

**Comment by nanaeaubry** [comment]
This has been fixed for the next version! Thank you
