### ISSUE TITLE
Where are the arcpy docs?

### ISSUE THREAD

**Issue by uasdev** [Esri/arcgis-python-api#1654]
**Is your feature request related to a problem? Please describe.**
Hello, is there possibility to do a simple Sphinx like docs for the arcpy classes and functions? for example, I would like to look at all classes and functions in the `arcpy.management` module, but I am unable to locate this. Currently, I have to use python to dig through the modules and find the functions I need. I could go to the ArcGIS Pro page, but it is interweaved with the entire ArcGIS software suite.

```python
# using python to view classes and functions
print(dir(arcpy.management))
```

**Describe the solution you'd like**
Seperate docs for arcpy in Python.

**Comment by nanaeaubry** [comment]
@uasdev Thanks for sharing this but we are the ArcGIS Python API and not ArcPy. I would post this on the communities page for ArcPy if you would like someone from that team to see it! :)
