### ISSUE TITLE
Mapping Services Associated with Custom Geoprocessing Services Fail to Start

### ISSUE THREAD

**Issue by cvricella2** [Esri/arcgis-python-api#1659]
**Describe the bug**
If you have a custom gp service, like a python web tool, that has a mapping service associated with the output it won't start back up if you try to with API. Potentially an ArcGIS Server Issue (seen on 10.9.1) but the service starts/stops without an issue through the manager GUI; it's only when using the python API does this occur. 

**To Reproduce**
start/stop procedure as demonstrated in this technical article: https://support.esri.com/en-us/knowledge-base/how-to-stop-gis-services-using-arcgis-api-for-python-000019994. You need to have a python web tool published that has a map service associated with it. 

error:
No error will be thrown by the python int. You will see the mapping service as stuck stopping or starting through the manager interface. 
**Screenshots**

**Expected behavior**

**Platform (please complete the following information):**
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@cvricella2  Hello, what version of the API are you using?

**Comment by nanaeaubry** [comment]
Closed due to inactivity. Please reopen if needed
