### ISSUE TITLE
edit_features replaces dates prior to 1970 with null values

### ISSUE THREAD

**Issue by skykasko** [Esri/arcgis-python-api#1667]
**Describe the bug**
When a Spatially Enabled DataFrame with a date column that contains a date prior to 1970 is passed to the `edit_features()` method, the value `None` is actually stored instead of the date provided. If the date field does not allow null values, then the edit fails.

**To Reproduce**
Create an ArcGIS Online feature layer with a date column named "date", for example. In the code sample below, fill in the feature layer's item ID, and the username and password to connect to the GIS where the feature layer is stored.
```python
import datetime
import pandas as pd
from arcgis.gis import GIS

item_id = ""
url = "https://www.arcgis.com/"
username = ""
password = ""
gis = GIS(url, username, password)
layer = gis.content.get(item_id).layers[0]

adds = pd.DataFrame(
    [
        {
            "date": datetime.datetime(1960, 1, 1),
            "SHAPE": {
                "x": -7000000,
                "y": 5000000,
                "spatialReference": {"wkid": 102100, "latestWkid": 3857},
            },
        }
    ]
)
result = layer.edit_features(adds=adds)
print(result)
# {'addResults': [{'objectId': 1, 'uniqueId': 1, 'globalId': None, 'success': True}], 'updateResults': [], 'deleteResults': []}
print(layer.query().features[-1].attributes["date"] is None)
# True
```
The result above occurs if the date field allows null values. If null values are not allowed in the date field, the edit operation will fail with a result like:
```python
{
    "addResults": [
        {
            "objectId": 1,
            "uniqueId": 1,
            "globalId": None,
            "success": False,
            "error": {
                "code": 1000,
                "description": "Cannot insert the value NULL into column 'date', table 'db_1230.user_1230.TEST_NULLS_TEST_NULLS2'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated.",
            },
        }
    ],
    "updateResults": [],
    "deleteResults": [],
}
```
**Expected behavior**
That the date that is passed in gets stored.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API version: 2.1.0.3
 - Pandas version: 1.5.3

**Additional context**
Note that if the date value in the example above is changed to `datetime.datetime(1970, 1, 2)` or any later date, the edit succeeds as expected. Also, dates prior to 1970 work without a problem if edits are passed to `edit_features()` as a dictionary rather than as a Spatially Enabled DataFrame. For example, the following works as expected:
```python
adds = [{"attributes": {"date": datetime.datetime(1960, 1, 1)}}]
```

**Comment by nanaeaubry** [comment]
@skykasko  This is due to Linux and their definition of time. We will look into it with the feature service team to see what formats are accepted

**Comment by achapkowski** [comment]
We finished reviewing this, and we could not reproduce the issue.  Date/times are being updated for dates older than 1970 with no code modifications in version `2.2.0`.  If you need further assistance on this issue, please open an support case.
