### ISSUE TITLE
GIS Object Serialization

### ISSUE THREAD

**Issue by smartinez2** [Esri/arcgis-python-api#1673]
**Is your feature request related to a problem? Please describe.**
I am looking to geocode a large dataset using the Apache Spark distributed computing platform (specifically databricks). I want to use a custom geocoder internal to my ArcGIS Online organization to achieve this task. I was wondering if it was possible to serialize objects from the Python API such that they can be used across a distributed environment (i.e through pickle serialization or through converting to bytes). I haven't been able to find any information about this on the docs.

```python
gis = GIS()
bytes(gis)
#Returns the error:
#TypeError: cannot convert 'GIS' object to bytes

pickle.dumps(gis)
#Returns the error:
#TypeError: dict items iterator must return 2-tuples
```

**Comment by achapkowski** [comment]
The GIS object is not pickleable
