### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by modernhero666** [Esri/arcgis-python-api#1676]
Unable to display image     

![CleanShot 2023-09-28 at 23 13 43](https://github.com/Esri/arcgis-python-api/assets/66157863/e5324b7f-27a0-4bb9-ac9c-4570f29986af)

**Comment by nanaeaubry** [comment]
@modernhero666 What version of the API are you using? Is this in a local notebook or an Online, Enterprise, or Pro notebook?
Are you logged in with a gis instance or anonymous?
Please provide more information so we can properly guide you

**Comment by phuongduyta** [comment]
I experience the same, both with the original docker image here: https://hub.docker.com/r/esridocker/arcgis-api-python-notebook and also with a base jupyter data science notebook and installed "acgis api for python" package (2.2).

The error is "Error displaying widget: model not found".

In console I have got this error: _Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early_

**Comment by nanaeaubry** [comment]
@phuongduyta What kind of authentication are you using? This might be related to that.

**Comment by phuongduyta** [comment]
I use the anonymous authentication gis = GIS() as well as using a free account or my pro account. No luck at all. Really strange!

**Comment by nanaeaubry** [comment]
@phuongduyta Yes that is odd. Are you on windows?

**Comment by phuongduyta** [comment]
Yes I am, I tried on 2 different computer. The result is the same.

Could you please run this docker image to see if you experience the same?

**Comment by nanaeaubry** [comment]
@phuongduyta Spoke with our dev responsible for this and they said there is a new image coming soon. Here is the PR to keep track: https://github.com/Esri/arcgis-python-api/pull/1687

**Comment by jtroe** [comment]
Please try the new image:
`docker pull ghcr.io/esri/arcgis-python-api-notebook:latest`
`docker run -it --rm -p 8888:8888 ghcr.io/esri/arcgis-python-api-notebook:latest`
Note that the image is now hosted on ghcr.io instead of docker hub.  We will be updating documentation on the developer site shortly.

**Comment by phuongduyta** [comment]
> Please try the new image: `docker pull ghcr.io/esri/arcgis-python-api-notebook:latest` `docker run -it --rm -p 8888:8888 ghcr.io/esri/arcgis-python-api-notebook:latest` Note that the image is now hosted on ghcr.io instead of docker hub. We will be updating documentation on the developer site shortly.

It works. Thank you!

**Comment by phuongduyta** [comment]
> Please try the new image: `docker pull ghcr.io/esri/arcgis-python-api-notebook:latest` `docker run -it --rm -p 8888:8888 ghcr.io/esri/arcgis-python-api-notebook:latest` Note that the image is now hosted on ghcr.io instead of docker hub. We will be updating documentation on the developer site shortly.

Unfortunately the visualization of the sdf doesn't work as expected.

Using:
m1 = gis.map('GER')
sdf = pd.DataFrame.spatial.from_featureclass(shp)
sdf.spatial.plot(map_widget=m1)
m1

doesn't show the shapefile.

**Comment by jtroe** [comment]
<img width="1089" alt="image" src="https://github.com/Esri/arcgis-python-api/assets/2387349/f24fd9fc-14c4-4bbd-970d-422c60e3323c">
The original request snippet is working in the updated docker image.  Closing this issue.

@phuongduyta for your issue, please open a separate issue.  Please provide more context to the shapefile in your new issue (`shp` variable).
