### ISSUE TITLE
predict_las function error

### ISSUE THREAD

**Issue by ovipaul** [Esri/arcgis-python-api#1678]
Description:
The training was done smoothly without any issues on las files. But when I try to use my saved checkpoint files to predict the new data, after converting the las files to h5, it starts to give this error message. The error seems to be getting on the prediction function inside the package and it is getting the numpy array instead of the torch data type. How can I fix this?

Error:
TypeError                                 Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_17432\2894882494.py](https://file+.vscode-resource.vscode-cdn.net/d%3A/workspace/~/AppData/Local/Temp/ipykernel_17432/2894882494.py) in <cell line: 1>()
----> 1 pointcnn.predict_las(path=las_files, output_path=result_path)

[c:\Users\GSE-Linux\AppData\Local\ESRI\conda\envs\pcnn2\lib\site-packages\arcgis\learn\models\_pointcnnseg.py](file:///C:/Users/GSE-Linux/AppData/Local/ESRI/conda/envs/pcnn2/lib/site-packages/arcgis/learn/models/_pointcnnseg.py) in predict_las(self, path, output_path, print_metrics, **kwargs)
    541         """
    542 
--> 543         return inference_las(path, self, output_path, print_metrics, **kwargs)
    544 
    545     def compute_precision_recall(self):

[c:\Users\GSE-Linux\AppData\Local\ESRI\conda\envs\pcnn2\lib\site-packages\arcgis\learn\_utils\pointcloud_data.py](file:///C:/Users/GSE-Linux/AppData/Local/ESRI/conda/envs/pcnn2/lib/site-packages/arcgis/learn/_utils/pointcloud_data.py) in inference_las(path, pointcnn_model, out_path, print_metrics, remap_classes, selective_classify, preserve_classes)
   2217                 points_batch = data[[batch_idx] * batch_size, ...]
   2218                 point_num = data_num[batch_idx]
-> 2219                 predictions = get_predictions(
   2220                     pointcnn_model,
   2221                     data,

[c:\Users\GSE-Linux\AppData\Local\ESRI\conda\envs\pcnn2\lib\site-packages\arcgis\learn\_utils\pointcloud_data.py](file:///C:/Users/GSE-Linux/AppData/Local/ESRI/conda/envs/pcnn2/lib/site-packages/arcgis/learn/_utils/pointcloud_data.py) in get_predictions(pointcnn_model, data, batch_idx, points_batch, sample_num, batch_size, point_num)
   2105     indices_batch_shuffle = np.reshape(indices_shuffle, (batch_size, sample_num, 1))
   2106 
-> 2107     model_input = torch.cat(
   2108         [points_batch[i, s[:, 0]][None] for i, s in enumerate(indices_batch_shuffle)],
   2109         dim=0,

TypeError: expected Tensor as element 0 in argument 0, but got numpy.ndarray

Platform:
 - OS: [Windows]
 - Python API Version 2.1.0.2

![Screenshot (1)](https://github.com/Esri/arcgis-python-api/assets/24507771/868b7c39-7616-4b5d-bee5-0b780200b49e)

**Comment by vbhv14** [comment]
This method has been deprecated starting from ArcGIS API for Python version 1.9.0. Use Classify Points Using Trained Model tool available in 3D Analyst extension from ArcGIS Pro 2.8 onwards.
