### ISSUE TITLE
Install without anaconda?

### ISSUE THREAD

**Issue by dzackgarza** [Esri/arcgis-python-api#168]
I just wanted to see if there is any way to install this module into an existing Python environment, without pulling in an entire distribution of Anaconda. Is there a standalone package available via pip, or any other alternatives?

**Comment by rwmajor2** [comment]
You can try starting with Miniconda and install from there.  It should pick up most of the dependencies, but I am not 100% positive since I have not tried this myself.  I will try this myself and let you know what I find out.

**Comment by achapkowski** [comment]
@dzackgarza pip support is being developed.

**Comment by rohitgeo** [comment]
@dzackgarza pip support is now available. 
```pip install arcgis```
