### ISSUE TITLE
unable to upgrade arcgis package to 2.2.0 via conda

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-python-api#1682]
**Describe the bug**
unable to upgrade arcgis package to 2.2.0 via conda

**To Reproduce**
```python
conda upgrade -c esri --no-pin arcgis
```
error:
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**
In a clone environment, unable to upgrade from arcgis-2.1.0.3  to 2.2.0 

using conda upgrade -c esri --no-pin arcgis or conda install -c esri arcgis

**Platform (please complete the following information):**
 - OS: Windows 10

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@jtroe Can you advise on this?

**Comment by nanaeaubry** [comment]
Please reopen if this is still happening and provide more information on the error. Otherwise try installing 2.3.0 :) thanks!
