### ISSUE TITLE
Visualizing Spatially Enabled DataFrame from Shapefile doesn't work with the newest Docker Image

### ISSUE THREAD

**Issue by phuongduyta** [Esri/arcgis-python-api#1688]
**Describe the bug**
With the newest docker image ghcr.io/esri/arcgis-python-api-notebook:latest (ArcGIS API Python 2.2), the Visualizing of Spatially Enabled DataFrame from Shapefile doesn't work as expected.

**To Reproduce**
from arcgis.gis import GIS
import pandas as pd

gis = GIS()
shp = ".../test_point_shp.shp"
sdf = pd.DataFrame.spatial.from_featureclass(shp)
sdf.head()
m1 = gis.map('GER')
sdf.spatial.plot(map_widget=m1)
m1
```
error:
```python
There is no error code, the points are just not added.
```

**Expected behavior**
The points should be added to the map

**Additional context**
test_point_shp.shp is provided.
[test_point_shp.zip](https://github.com/Esri/arcgis-python-api/files/12829479/test_point_shp.zip)

**Comment by nanaeaubry** [comment]
What version of Python are you using?

**Comment by jtroe** [comment]
This docker image uses python 3.9

**Comment by nanaeaubry** [comment]
New docker image available, closing this. Feel free to reopen if needed
