### ISSUE TITLE
Add support for bulk updating organization's content to use HTTPS

### ISSUE THREAD

**Issue by cwwhitmore** [Esri/arcgis-python-api#169]
It is becoming increasingly important that organizations use HTTPS only for their content. However, this can be challenging for organizations that have been using HTTP or a mix of both.

The December release of ArcGIS Online introduced the ability to update HTTP layers in a web map to use HTTPS on a per map basis. There are also several tools available for updating HTTP layers in web maps - ago assistant and geojobe. Geojobe has the capability to do this in bulk for web maps I believe (not positive, but believe it's only web maps).

It would be ideal if there's a way to perform a bulk HTTP -> HTTPS update of an organization's content. There are many item types / organization resources that could have HTTP references that would need to be updated.  I think this is something that could be built / evolved over time based on feedback, etc.

A good first stab might be update web maps (and any layer items referenced in the web maps). From there could expand to include apps (configurable apps, story maps, etc).

Any update functionality should also include a reporting mechanism so that the org admin can identify what needs to be updated before proceeding. Would also need to check for the validity of the HTTPS endpoint for any HTTP resources (all Esri hosted offerings support HTTPS. Same with most on-prem AGS instances now. Problematic areas are typically things like references to multimedia, OGC, CSV, etc).

cc @AtmaMani

**Comment by rohitgeo** [comment]
The API now provides a programmatic way of updating web maps - see https://developers.arcgis.com/python/sample-notebooks/using-and-updating-gis-content/#Fix-errors-in-web-map. Additionally, other types of content can also be updated.
