### ISSUE TITLE
When converting a data frame with multiple date columns to a feature set, the dates fields all have the same value

### ISSUE THREAD

**Issue by justingreco** [Esri/arcgis-python-api#1693]
**Describe the bug**
When converting a spatially enabled data from to a feature set using df.spatial.to_featureset() with multiple date fields, all of the dates are being set to the value in the last date column.

**To Reproduce**
```python
from arcgis import pd
data = [[datetime(2023, 1, 1), datetime(2023,7,1), datetime.now()]]
df = pd.DataFrame(data, columns=['date1', 'date2', 'date3'])
fs = df.spatial.to_featureset()
print(fs.features)
```
error:
No error, but this is what the resulting feature set looks like.
```python
[{"attributes": {"date1": 1697111406380, "date2": 1697111406380, "date3": 1697111406380, "OBJECTID": 1}}]
```
**Screenshots**

**Expected behavior**
The feature set should return the same dates as in the dataframe.  I am able to bypass this issue by converting straight to a feature class instead of converting to a featureset then to a feature class

**Platform (please complete the following information):**
 - OS
 RHEL 8
    N/A
 - Python API Version
    2.2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@justingreco Thanks for reporting this, I found the problem and work on a fix. For some reason it is not iterating through all the datetime rows correctly.

**Comment by justingreco** [comment]
Thanks @nanaeaubry.  I did notice that features.FeatureSet.from_dataframe() results in the correct dates, so I have switched my code to use that.

**Comment by nanaeaubry** [comment]
This was fixed but won't be reflected until the next version is released. That is a good workaround for now! Thanks again for reporting this
