### ISSUE TITLE
spatial.to_featurelayer returns FeatureCollection

### ISSUE THREAD

**Issue by SPhillips2022** [Esri/arcgis-python-api#1697]
spatial.to_featurelayer returns FeatureCollection

Online Notebook sedf spatial.to_featurelayer returns FeatureCollection not feature layer - any thoughts?
```
both2a_fl = both2a_df.spatial.to_featurelayer(title="both2a_fl")
both2a_fl
out[] <FeatureCollection>

**Comment by nanaeaubry** [comment]
@SPhillips2022 
Is your `both2a_fl` a table by chance?

**Comment by SPhillips2022** [comment]
Hi !

Why yes, yes it was a table!  I had created a spatial data frame and then I created a new dataframe from it with a subset of columns – and didn’t include the geometry!  Funny how spatial data needs geometry.  And do you know what helped ring a bell for me – I found the sample in the esri notebook samples and the error it throws was to make sure it was an sedf – I was created it in Pro without the exception handling and it just spits out the FeatureCollection without the handy error message.

I will update it on GitHub.

I have a handful of other questions I am running into on this little project – like – I have a feature class that I can turned into a dataframe, did some manipulations and then created a feature layer without any problems in Pro – but, when I do the same thing in AGOL notebook – it throws the cannot convert string to double error.  So, I dropped the double fields – and now it just says “job failed” when converting to feature layer in AGOL notebook…same feature class…it’s weird.

Is there anyway we could set up a time to talk?

Thank you -

STEPHANIE PHILLIPS
DESIGN TECHNOLOGY SPECIALIST - GIS 

Team D3
O: 207.827.7758 EXT 1164
***@***.******@***.***>

***@***.***<https://www.facebook.com/TeamD3Coalition>  ***@***.*** ***@***.***>   ***@***.*** <https://www.linkedin.com/company/team-d3/>   ***@***.*** <https://www.d3tech.net/blogs/>

**Comment by nanaeaubry** [comment]
@SPhillips2022 

Happy to help.

If you are having other issues the best thing to do is to go through your Esri Representative and discuss with them. You can also reach out to support and they are happy to assist.

If you have any small questions or you come across bugs or enhancement requests feel free to keep posting here!
