### ISSUE TITLE
Downloading CSV files via arcgis.gis.Item.download() failing with unexpected permission error

### ISSUE THREAD

**Issue by knoopum** [Esri/arcgis-python-api#1701]
Downloading CSV files via arcgis.gis.Item.download() failing with unexpected permission error.

First noticed this when downloading an Administrative Report item in an ArcGIS Online Notebook (runtime Standard - 8.0; ArcGIS API for Python version 2.1.0.2.) The issue began occurring after the October 2023 ArcGIS Online update. The code had been running fine before this as a daily scheduled task. Seems to impact any downloading any CSV file though.

One way to reproduce the issue is to generate an Administrative Report, such as a daily-scoped Item report, via the ArcGIS Online GUI. From the report's item detail page, you can successfully down the CSV using the Download button. However, attempting to programmatically retrieve the same report via the ArcGIS API for Python using arcgis.gis.Item.download() generates a CSV which contains a JSON error message (e.g., Error: You do not have permissions to access this resource or perform this operation.)

Updating the ArcGIS Online Notebook to the latest version of the runtime, ArcGIS Notebo0k Python 3 Standard - 9.0, does not fix the issue.

**Comment by nanaeaubry** [comment]
@knoopum Thanks for reporting this. We investigated and confirmed it is a backend problem and not an issue with the Python API. Please open an issue with support to track when this will be fixed on their end.
