### ISSUE TITLE
View Manager update method not working

### ISSUE THREAD

**Issue by avstjohn** [Esri/arcgis-python-api#1704]
**Describe the bug**
I am not able to update a view's definition. 
I am working on a script to read a hosted view's definition, store the definition, delete the view, overwrite the hosted feature layer, recreate the view, and, lastly, update the view's definition with the stored one.

**To Reproduce**
```python
...
for view_item in view_items:
    title = view_item.title
    layer = view_item.view_manager.get_definitions(view_item)[0].layer
    query_definition = view_item.view_manager.get_definitions(view_item)[0].query_definition
    fields = view_item.view_manager.get_definitions(view_item)[0].fields
...
update_dict = ViewLayerDefParameter(layer=layer, query_definition=query_definition, spatial_filter=None, fields=fields)
for new_view_item in new_view_items:
    new_view_item.view_manager.update(layer_def=[update_dict])
```
error:
```python
AttributeError                            Traceback (most recent call last)
In  [152]:
Line 13:    new_view_item.view_manager.update(layer_def=[update_dict])

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py, in update:
Line 16577: layer = layer_def.layer

AttributeError: 'list' object has no attribute 'layer'
```
**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/6b54ac48-d59b-4d16-bba0-b66f082378e0)

**Expected behavior**
At the error's location, line 16577, **layer = layer_def.layer** should read **layer = lyrdef.layer**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser: N/A
 - Python API Version: 2.1.0.2

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@avstjohn Yep, this got fixed already please upgrade to the latest version: 2.2.0

**Comment by avstjohn** [comment]
My apologies. Thank you.

That was feeling very familiar to write the bug report but I had the issues list filtered for only open issues and missed that we've been through this already.

I didn't know we could separately update the Python package, outside of a Pro update, but that makes sense, since it is a Python package!

I am having some trouble updating the _arcgis_ package with conda:
`(arcgispro-py3-clone) C:\Users\AStJohn\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone>conda install -c esri arcgis`
Which upgraded from 2.1.0.2 to 2.1.0.3

And then I try to go to 2.2.0.1, but get this error
`
(arcgispro-py3-clone) C:\Users\AStJohn\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone>conda install -c esri arcgis=2.2.0.1
Collecting package metadata (current_repodata.json): done
Solving environment: \ WARNING conda.core.solve:_add_specs(648): pinned spec arcgis=2.1.0 conflicts with explicit specs.  Overriding pinned spec.
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - WARNING conda.core.solve:_add_specs(648): pinned spec arcgis=2.1.0 conflicts with explicit specs.  Overriding pinned spec.
failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - WARNING conda.core.solve:_add_specs(648): pinned spec arcgis=2.1.0 conflicts with explicit specs.  Overriding pinned spec.
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | WARNING conda.core.solve:_add_specs(648): pinned spec arcgis=2.1.0 conflicts with explicit specs.  Overriding pinned spec.
failed

SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs:
    - arcgis=2.2.0.1
    - esri/win-64::arcpy-base==3.1=py39_41759
    - esri/win-64::arcpy==3.1=py39_arcgispro_41759
  pinned specs:
    - mkl==2020.0=arcgispro_167
    - numpy=1.20
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
`

Does arcgis 2.2.0.1 depend on those two pinned packages being updated as well?

**Comment by nanaeaubry** [comment]
@avstjohn No worries :) 

To upgrade I think there is a --no-pin tag to use. Otherwise the latest version of Pro should release any day now and it will have the latest version included.

**Comment by avstjohn** [comment]
I got a much longer, much scarier error message when I tried the _--no-pin_ option. I think I will wait for the Pro release.

This is the start of the error, followed by 5800 lines of every package's conflicts with every other package:

> (arcgispro-py3-clone) C:\Users\AStJohn\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone>conda install -c esri arcgis=2.2.0.1 --no-pin
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: -
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> Examining conflict for arcpy nbconvert jsonschema pyjwt jupyter_client keyring sqlalchemy jupyterlab_server entrypoints importlib_metadata: :Examining conflict for arcpy nbconvert jsonschema pyjwt jupyter_client keyring sqlalchemy jupyterlab_server entrypoints importlib_metadata: :Examining conflict for numpy-base mkl_fft mkl_random: : 269it [29:17,  1.90s/it]
> failed
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
