### ISSUE TITLE
Improve content.search by making query accept dictionary 

### ISSUE THREAD

**Issue by astrong19** [Esri/arcgis-python-api#171]
Currently the query argument accepts search sting (e.g., GIS.content.search(query='owner:astrong_pnw AND type:Feature Service')). I think this would work a lot better as a dictionary (e.g., GIS.content.search(query={'owner': 'astrong_pnw', 'type': 'Feature Service'}). 

Advantages:

* More flexible if certain item fields are not included in the query (i.e., dictionaries can support None type, search stings cannot)

* Can support lists that are important for item fields like tags (e.g., GIS.content.search(query={'tags': ['tag1', 'tag2', 'tag3']})

* Generally more pythonic 

Search string documentation: http://resources.arcgis.com/en/help/arcgis-rest-api/#/Search_reference/02r3000000mn000000/

**Comment by rwmajor2** [comment]
@astrong19 I agree that JSON is always a better mechanism than building a string.  However, the search capability within Portal allows AND/OR and also the ability to not search for certain features, e.g. ```-tags:roads```, which means find items that do not have the tag ```roads```.  It may be challenging to build a JSON structure that then ultimately ends up building the proper string query in the end.

Just my thought.

**Comment by astrong19** [comment]
@rwmajor2 thanks for the tip! I wasn't aware that query strings support the ability to NOT search for certain items. That's useful. Appreciate the feedback. 

Cheers!
