### ISSUE TITLE
Help Installing Neural Network Package

### ISSUE THREAD

**Issue by Gitminorkes** [Esri/arcgis-python-api#1710]
I tried to install a neural network for generating images, but when installing such an error comes out, what is the problem?

![image](https://github.com/Esri/arcgis-python-api/assets/149723970/7551078d-ee53-443b-9cf0-c924ef0df7c5)
![image](https://github.com/Esri/arcgis-python-api/assets/149723970/7dd5a2a8-bf64-4265-b925-456ebb3764db)

**Comment by nanaeaubry** [comment]
@Gitminorkes 

Hello we are going to need a bit more information. 
What command are you trying to execute? Do you have the api already installed or is this a fresh environment?

**Comment by nanaeaubry** [comment]
This doesn't seem to have anything to do with the arcgis python api. Closing. Feel free to reopen if needed
