### ISSUE TITLE
content metadata property returns html error message instead of None when content doesn't have metadata

### ISSUE THREAD

**Issue by nakamura2000** [Esri/arcgis-python-api#1713]
**Describe the bug**
content metadata property returns html error message instead of None when content doesn't have metadata.
if I switches to arcgis pyton api 1.6.2 , it returns None.
document describes , " metadata returns None if the item does not have metadata."

**To Reproduce**
```python
from arcgis.gis import GIS
gis = GIS('https://www.arcgis.com','user','password')
item = gis.content.get('content_item_id')
item.metadata
```
error:
```python
>>> item.metadata
'\n\n\n\n\n\n\n\n<html>\n\n\n\n\n\n\n<head>\n<title>\nError: Metadata for item not found</title>\n<link href="/sharing/rest/files/gw.css" rel="stylesheet" type="text/css"/>\n</head>\n\n<body>\n\n<table width="100%" class="topTable">\n<tr valign="top">\n<td>\n<b>ArcGIS Portal Directory</b>\n\n</td>\n<td align="right">\n\n</td>\n</tr>\n</table>\n\n<table class="navTable" width="100%"><tr><td class="breadcrumbs">Error</td></tr></table>\n\n<div class="gwDiv">\n\n<h3>Metadata for item not found</h3><br/>\n\n<b>Error: </b>400<br/><br/>\n\n\n\n</div>\n\n</body>\n\n</html>\n'
```
**Screenshots**
n/a

**Expected behavior**
f.metadata returns None

**Platform (please complete the following information):**
 - OS: windows
 - Browser : N/A
 - Python API Version 2.2.0 

**Additional context**
N/A

**Comment by achapkowski** [comment]
We'll take a look, thank you for reporting this.

**Comment by nanaeaubry** [comment]
This was fixed and will be in the next release
