### ISSUE TITLE
Hosted downloads(Arcgis Hub) not working

### ISSUE THREAD

**Issue by spalrobert** [Esri/arcgis-python-api#1719]
Hi there,
I am trying to set hosted downloads for my hosted feature services in AGOL using ArcGIS API for Python like this:
![image](https://github.com/Esri/arcgis-python-api/assets/33999971/2935e900-6198-4fdd-a18a-c1284c49e19e)

No matter what I try I get True message but my service doesn't have checked Hosted downloads in ArcGIS Hub content management:
![image](https://github.com/Esri/arcgis-python-api/assets/33999971/5d7b43b2-7168-4eab-a58b-09e4c06fef27)

Thanks a lot!

**Comment by nanaeaubry** [comment]
@ManushiM This was the issue we discussed. 

@spalrobert Did you message the Hub team via email as well?

**Comment by spalrobert** [comment]
Hi @nanaeaubry, yes, I did. I also sent them a link on this issue. Thank you very much for taking an interest in this 👍 .

**Comment by achapkowski** [comment]
Please verify that you followed these instructions: https://community.esri.com/t5/arcgis-hub-blog/an-upgrade-to-arcgis-hub-s-hosted-service-download/ba-p/1370544

and reopen if this is still an issue.
