### ISSUE TITLE
Readability and navigability of the API reference

### ISSUE THREAD

**Issue by avstjohn** [Esri/arcgis-python-api#1720]
**Is your feature request related to a problem? Please describe.**
It is difficult to navigate the API reference and to know what are all of the methods and properties available to a class.
For example, in the image below, I can search for the FeatureLayer class and it would be extremely helpful if there were an additional submenu in the left panel or some kind of summary of methods and properties. 

![image](https://github.com/Esri/arcgis-python-api/assets/24692437/0a3b2021-849f-4113-963f-cb978307968d)

The module page is not granular or navigable enough (very long web page) to efficiently show methods and properties available to a class.

Thanks!

**Comment by nanaeaubry** [comment]
@avstjohn Hello, this is an ongoing effort in our team. Unfortunately it's not as straightforward as we would like but this is constantly being worked on to the best of our ability and we hope to have an update with this notation in the future.

**Comment by avstjohn** [comment]
Thank you @nanaeaubry for the note and apologies if it is a very redundant message at this point.

**Comment by nanaeaubry** [comment]
@avstjohn Not redundant at all! It's good to know what we have requests for this and that you care! Always happy for the feedback :)

We can keep this issue open so other documentation enhancement requests can be made and we will update with any progress we make!

**Comment by jyaistMap** [comment]
@avstjohn To elaborate just a bit, the system we use to build the API Reference doesn't currently provide the output the website publishing application needs to provide for expanding the classes to see the properties and methods. Admittedly, the navigation on the site is frustrating - we experience it, too. As @nanaeaubry mentioned, we're actively researching it and investigating alternatives. When we find one, we can all rejoice together. Until then, bear with us.

**Comment by avstjohn** [comment]
Thanks for the elaboration!

**Comment by sverkerEsriSE** [comment]
To add to this; the version selector (which was available before) was really useful, since many times, you're not coding against the latest version of the API, and cannot upgrade easily.

**Comment by esride-jts** [comment]
We should invest into this. Especially our graduates and data science teams getting their hands dirty would highly appreciate this enhancement. Furthermore, we need more type definitions regarding return types, and also possible exception which can be raised. We know this is a huge investment, but we should invest into clean type declarations for every class, method, function which can be analyzed by the intelli-sense capabilities of the IDEs.

**Comment by nanaeaubry** [comment]
Hello, the documentation team has made some great updates to help with the nagability of the reference. 
Please check it out and if you have any feedback we also have a 'submit feedback' link directly in the documentation. 

Thank you!
