### ISSUE TITLE
Server LogManager fail

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#1722]
**Describe the bug**
The server LogManager fails in version 2.1.0.2 ->

**To Reproduce**
Steps to reproduce the behavior shown here from notebook server:
![image](https://github.com/Esri/arcgis-python-api/assets/889468/e1eef17c-9ed0-4a48-ac0c-097949f0343f)

Looks like it is caused by a change in `__init__`. Here is `self._con == connection == gis`
Guess it should be `connection = gis._con`

```python
    def __init__(self, url: str, gis: GIS, initialize: bool = False):
        """Constructor."""
        connection = gis
        super(LogManager, self).__init__(gis=gis, url=url)
        self._url = url
        self._con = connection
        if initialize:
            self._init(connection)
```

**Expected behavior**
Expect to get logs.

**Platform (please complete the following information):**
 - Python API Version 2.1.0.2 ->

**Comment by nanaeaubry** [comment]
@HakonD What version of Enterprise are you on?

**Comment by HakonD** [comment]
This is a Enterprise 11.1 deployment.
Querying the same server using arcgis API 2.2.0.1 returns logs.
![image](https://github.com/Esri/arcgis-python-api/assets/889468/286ddf8a-67f5-46f3-8437-95d66f70fb3c)

**Comment by nanaeaubry** [comment]
We made a fix for this for the next release. Unfortunately we don't have a workaround for the call that is not working as of now.
