### ISSUE TITLE
Create webhook on hosted feature service gives KeyError: 'globalId'

### ISSUE THREAD

**Issue by EliseTegner** [Esri/arcgis-python-api#1725]
**Describe the bug**
When creating a Feature Service webhook (arcgis.features.managers.WebHookServiceManager.create()) in ArcGIS Enterprise v 11.1, the response from ArcGIS Server contains a json, with the newly created webhook id, stored in the json under the key "id". The ArcGIS API tries to extract "globalId" from this response json, to obtain the webhook ID, which does not exist in the reponse.

**To Reproduce**
```python

 _wh_manager = WebHookServiceManager(
     url=<webhook url from ArcGIS Server admin API>,
     fc=<FeatureLayerCollection object>,
     gis=<URL to arcgis.gis.GIS object>
 )
 _webhook = _wh_manager.create(
     name=_webhook_name,
     hook_url=<url to webhook receiver>,
     change_types="AttachmentsCreated",
     active=True
 )
```
error:
```python

Exception has occurred: KeyError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
'globalId'
  File "C:\arcgispro-31\Lib\site-packages\arcgis\features\managers.py", line 1677, in create
    hook_url = self._url + f"/{resp['globalId']}"
  File "C:\git\arcgis-louvre-initialization\tools.py", line 140, in create_webhook
    _webhook = _wh_manager.create(
  File "C:\git\arcgis-louvre-initialization\main.py", line 65, in main
    _item.create_webhook()
  File "C:\git\arcgis-louvre-initialization\main.py", line 72, in <module>
    main()
  File "C:\arcgispro-31\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\arcgispro-31\Lib\runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
KeyError: 'globalId'
```
**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/57002426/becf7884-5644-4e17-8398-8b90acc3633f)

**Expected behavior**
The ArcGIS API should look for "id" in the response json if "globalID" is not found.

**Platform (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Visual Studio Code 1.84.2
 - Python API Version 2.1.0.2
 - ArcGIS Enterprise 11.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
We cannot reproduce the issue, please ensure that your data has the following properties defined:

```python
{
            "hasStaticData": False,
            "capabilities": "Query,Editing,Create,Update,Delete,ChangeTracking",
            "editorTrackingInfo": {
                "allowAnonymousToDelete": True,
                "allowAnonymousToUpdate": True,
                "allowOthersToDelete": True,
                "allowOthersToQuery": True,
                "allowOthersToUpdate": True,
                "enableEditorTracking": False,
                "enableOwnershipAccessControl": False,
            },
        }
```

We tested this on AGOL, Enterprise 11.1 and 11.2

**Comment by achapkowski** [comment]
@EliseTegner is the issue continues, I recommend you contact Esri support.

**Comment by EliseTegner** [comment]
I contacted support. This issue is now registered as BUG-000164125.

**Comment by achapkowski** [comment]
@EliseTegner thank you!
