### ISSUE TITLE
sdf.spatial.to_featurelayer ‎before creates "File geodatabase" and, now, ShapeFile

### ISSUE THREAD

**Issue by geografiadascoisas** [Esri/arcgis-python-api#1730]
Before the update in ArcGIS Pro, my ArcGIS API for Python behaved as follows:

When I used the sdf.spatial.to_featurelayer to "send" a Spatial Enabled DataFrame to ArcGIS Online, I had a FeatureLayer + File Geodatabase. Now, the same code creates a FeatureLayer + Shape file in ArcGIS Online.

With that, the names of my columns are changed, even using sanitize_columns=False, which seems to have no effect.

# Publish the SpatialDataFrame as a feature layer
item = sd.spatial.to_featurelayer(
    title='New Error',
    gis = GIS,
    tags=['bug', 'error'],
    folder='new_behavior', 
    sanitize_columns=False,
    service_name='newerror'
)

Current version of ArcGIS API for Python: 2.1.0.3 / Python 3.11.1

**Comment by geografiadascoisas** [comment]
Thanks, I hadn't found anything about this in the documentation, I apologize for reporting it as _bug_. However, I imagined that this function was available without the need for ArcPy.

**Comment by nanaeaubry** [comment]
@geografiadascoisas It is available but creates a Shapefile in that case. FileGeodatabase is only created with the use of arcpy. 

@jyaistMap Maybe we can add a note in the doc about this or into one of the SeDF guides ?
