### ISSUE TITLE
documentation refers to a list of values for the privileges parameter that doesn't seem to exist 

### ISSUE THREAD

**Issue by leeberryman** [Esri/arcgis-python-api#1737]
**Screenshots**

https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#apikeymanager
![privileges-list-that-doesnot-exist](https://github.com/Esri/arcgis-python-api/assets/23552439/4d9174a0-b267-438b-8027-c3e6e1d7e140)

**Comment by achapkowski** [comment]
Check out: https://developers.arcgis.com/rest/users-groups-and-items/set-role-privileges.htm

**Comment by leeberryman** [comment]
Thanks
