### ISSUE TITLE
WebMap object move_to_basemap() method will not move the layer to the basemap

### ISSUE THREAD

**Issue by Clubdebambos** [Esri/arcgis-python-api#1739]
**Describe the bug**
WebMap object move_to_basemap() method will not move the layer to the basemap and results in an error. Using the Map Viewer (no tested with Map Viewer Classic)

The layer is a VectorTileLayer. It is a layer that was moved_from_basemap() in the first place but cannot be moved back to basemap using the move_to_basemap() method.

```python
{
      "id": "dark-gray-base-layer",
      "opacity": 1,
      "title": "Dark Gray Base",
      "visibility": true,
      "layerType": "VectorTileLayer",
      "styleUrl": "https://www.arcgis.com/sharing/rest/content/items/5e9b3685f4c24d8781073dd928ebda50/resources/styles/root.json"
   }
```

**To Reproduce**

Move basemap to layer with move_from_basemap() method.

```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap

## Access AGOL
agol = GIS("home")

## get webmap item
wm_item = agol.content.get("WM_ITEM_ID")

## create WebMap object
webmap = WebMap(wm_item)

## get basemap definition
basemap_lyr = webmap.definition["baseMap"]["baseMapLayers"][0]

## call move_from_basemap
webmap.move_from_basemap(basemap_lyr)

## update basemap
webmap.update()
```

Attempt to use move_to_basemap() methos to move layer to basemap.

```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap

## Access AGOL
agol = GIS("home")

## get webmap item
wm_item = agol.content.get("WM_ITEM_ID")

## create WebMap object
webmap = WebMap(wm_item)

## get layer definition
basemap_lyr = [lyr for lyr in webmap.layers if lyr.title == "Dark Gray Base"][0]

## move to basemap
webmap.move_to_basemap(basemap_lyr)

## update webmap
webmap.update()
```
error:
```python
arcgis.gis.Error: This layer type cannot be added as a basemap. See method description to know what layer types can be moved to basemap.
```
**Screenshots**

**Expected behavior**
Expect the layer to be moved to basemap as a reference layer or as the basemap layer.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Python API Version: 2.2.0.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
@Clubdebambos What is the layer type? Only certain layer types can be moved to basemap

**Comment by nanaeaubry** [comment]
@Clubdebambos Ok thanks I will take a look!

**Comment by nanaeaubry** [comment]
@Clubdebambos The `to` and `from` methods did not handle moving basemaps of type 'VectorTileLayer' only 'ArcGISVectorTileLayer'. So it did not account for basemaps that are esri owned and only for layers a user would want to add and remove from the basemap layers. I put in a fix so that these can now be moved back.

I don't have a workaround as of now but will let you know if I find one, I did put in a fix for this and it will be in the next release once merged

**Comment by Clubdebambos** [comment]
Thank you @nanaeaubry 
I have made a workaround for now, you can see here in [Esri Communities](https://community.esri.com/t5/arcgis-api-for-python-questions/webmap-object-move-to-basemap-method-will-not-move/m-p/1369907#M9517)
