### ISSUE TITLE
ArcGIS API for Python WebMap method to combine layers into a Group Layer and also the ungroup.

### ISSUE THREAD

**Issue by Clubdebambos** [Esri/arcgis-python-api#1741]
**Is your feature request related to a problem? Please describe.**
I can workaround by manipulating the JSON from the operationalLayers to create a Group Layer in the WebMap. It can be quite cumbersome and you need to have in-depth knowledge of the JSON required and how to remove your layers as single layers and add as a Group Layer.

Current Solution...

```python
from arcgis.gis import GIS
from arcgis.mapping import WebMap

## Access AGOL
agol = GIS("home")

## access webmap item
wm_item = agol.content.get("WM_ITEM_ID")

## create WebMap object
webmap = WebMap(wm_item)

## layers to group
lyr1 = webmap.get_layer(title="Layer 1")
lyr2 = webmap.get_layer(title="Layer 2")
lyr3 = webmap.get_layer(title="Layer 3")
lyr4 = webmap.get_layer(title="Layer 4")

## create a list of group layers
group_lyrs = [
        lyr1,
        lyr2,
        lyr3,
        lyr4
]

## get a list of layer names to be groupes
lyr_names = [lyr.title for lyr in group_lyrs]


## create the group layer JSON
group = {
    "title" : "NPWS Designated Boundaries",
    "layers" : group_lyrs,
    "layerType": "GroupLayer",
    "visibilityMode": "independent"
}

## we will use this list to overwrite current operationalLayers JSON
new_ol = [group]

## append all other layers into the list
for lyr in webmap.definition.operationalLayers:
    if lyr.title not in lyr_names:
        new_ol.append(lyr)

## update the operationalLayers list
webmap.definition.operationalLayers = new_ol

## update the properties and webmap
item_properties = {"text":webmap.definition}

wm_item.update(item_properties=item_properties)

```

**Describe the solution you'd like**
a method for the WebMap object called group_layers() that takes in a list of layer names or layer ids from the operationalLayer.
```python
layer_ids = [1,2,5]
webmap.group_layers(layer_ids)
webmap.update()
```

Building on from this is would be good to be able to remove a single layer or all layers (ungroup all) from a Group Layer, possible method names from_group_to_layer() or clear_group_layer()

**Describe alternatives you've considered**
Shown in the python code further up.

**Additional context**

**Comment by nanaeaubry** [comment]
@Clubdebambos 
We are working on major mapping module updates and this will be in there. We don't have a set release date but I will keep you updated when we have one.

**Comment by JesseKHall** [comment]
@nanaeaubry, Any update on this?

**Comment by nanaeaubry** [comment]
This will be in our Fall release :)

**Comment by stfran22** [comment]
@nanaeaubry did this actually come out? If so, can you let me know which release it was? Thanks!

**Comment by nanaeaubry** [comment]
@stfran22 You can test with the latest release of arcgis and arcgis-mapping (2.4.2 and 4.33)

We are also working on a patch to support subtypegrouplayers and subtypegrouptables. This is available with the pre-release tag

**Comment by stfran22** [comment]
@nanaeaubry Thanks for the quick response! I don't see the method in the docs that adds a new GroupLayer, just the ability to instantiate the class on an existing one. I am trying to build a core web map with hundreds of layers that need to be grouped and this is proving to be near impossible in the GUI.

**Comment by nanaeaubry** [comment]
@stfran22 

To add a group layer using the new mapping you simply add using the `add` method.

Some pseudo code:
```
from arcgis.mapping import Map
from arcgis.gis import GIS

gis = GIS(<your login>)
m = Map()

# Get your layers
layer1 = gis.content.get(<item_id_1>).layers[0] 
            OR
from arcgis.layers import Service
layer1 = Service("<url_to_layer>")

layer2 = ...
layer3 = ...

group_layer = [layer1, layer2, layer3...]
m.content.add(group_layer)

m.content.layers
>>> [GroupLayer]
```

**Comment by nanaeaubry** [comment]
@stfran22 If the layers are already on a map and need to be grouped I realize there is actually no way to do that without a group layer already existing. 

In that case you need to create at least one group layer by adding multiple layers as a group (code shown in comment above).

Then you can use the `move` method to move the other layers into the group. https://developers.arcgis.com/python/latest/api-reference/arcgis.map.toc.html#arcgis.map.map_widget.MapContent.move


```
m = <existing map>

all_layers = m.content.layers

group_layer = all_layers[0] #if group is the first layer in your list

m.content.move(1, group_layer) #moves the second layer into the group
```


I realize now that this is not super straight forward. I will work on improving the workflow but the basis is there.
