### ISSUE TITLE
FeatureLayerCollection.manager.create_view() does not correctly handle the view_layers parameter(?)

### ISSUE THREAD

**Issue by avstjohn** [Esri/arcgis-python-api#1743]
I am developing scripts to manage views in Online Portal. 
I use the create_view() method and give it a value for the view_layers parameter.
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/98f33b5d-89aa-4241-8e3a-ef727e5d723c)

It creates the view, but hits an error when I try to open the view in the Map Viewer or view the Data/Fields on the item page.
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/9b6f48b5-9502-48df-969d-c2603619c981)

Note that the URL is looking for layer ID 3 in the view that I just created "Sanitary_Pipes_View", but the ID=3 refers to layer ID in the parent hosted feature layer, from which I created the view
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/1917c76b-66be-4a75-80b2-9845d49df4ba)

 - OS: Windows 11
 - Browser: Chrome
 - Python API Version: 2.2.0.1

**Comment by avstjohn** [comment]
Also, it looks like the view automatically inherits the tags of the parent hosted feature layer, but they are not fully parsed:
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/71f4336d-7b8d-46d1-b344-4e23282f9eb2)

**Comment by nanaeaubry** [comment]
@avstjohn 
Are you able to open the layer in the original parent? I am unable to reproduce this so I wonder if it is specific to the layer.

Does this also occur for your first view you create: "Sanitary Structures View"?
