### ISSUE TITLE
Dependency conflict between arcgis and mage-ai due to jupyter-client version requirements

### ISSUE THREAD

**Issue by adelorean** [Esri/arcgis-python-api#1748]
### Environment
- Operating System: Debian GNU/Linux 12 (bookworm)
- Python Version: 3.10.13

### Issue Description
There is a dependency conflict in the arcgis package that is causing issues when trying to use it alongside mage-ai.

`arcgis` specifies:
```
arcgis==2.2.0.2 depends on jupyter-client<=6.1.12
```

Meanwhile, `mage-ai` specifies:
```
mage-ai==0.9.60 depends on jupyter-client==7.3.4
```

### Impact
This makes it challenging to use the two packages in the same environment, as they have incompatible version requirements for `jupyter-client`. 

### Steps to Reproduce
This can be reproduced by attempting to install both packages in the same Python environment:
```
pip install arcgis==2.2.0.2
pip install mage-ai==0.9.60
```

### Request
Can the requirements for `jupyter-client` in `arcgis` be relaxed to allow for newer versions of the `jupyter-client`, or is there a known workaround for this issue?

Thank you for looking into this matter.

**Comment by jinanyi** [comment]
Now that Fiona is testing @adelorean, maybe it will not be a problem anymore?

**Comment by adelorean** [comment]
Centralizing the pipeline in Mage work better if there is any dependency on between the pipelines. Would be great if we can get some feedback from the Arcgis maintainers team on what it will take to resolve the conflict.
