### ISSUE TITLE
Argispro python Kernel crash in visual studio code

### ISSUE THREAD

**Issue by Pragati2** [Esri/arcgis-python-api#1749]
I was trying to run python code using Argispro python.exe as interpreter, it crashed after some time. What could be possible reason for it and how to fix this?

![Screenshot 2024-01-29 100337](https://github.com/Esri/arcgis-python-api/assets/53491243/404fe3d9-3810-423e-a873-d9f0be996c2b)

**Comment by nanaeaubry** [comment]
@Pragati2 
We cannot reproduce this. I suggest you go to support as it may have to do with your environment setup
