### ISSUE TITLE
Doc - remove reference to "PlacesAPI (beta)"

### ISSUE THREAD

**Issue by nginer316** [Esri/arcgis-python-api#1750]
In the "Find Places" guide, we have a reference to the Places API beta.  This feature is no longer in beta so we can remove reference to it in the guide.  We can simply refer to it as "Places service".

https://developers.arcgis.com/python/guide/find-places/

![image](https://github.com/Esri/arcgis-python-api/assets/149705448/1dea6e9a-53da-47a8-9a10-bc3621b37c35)

**Comment by tarunkukreja003** [comment]
its fixed, currently in the production site the Beta isn't there

![fixed-places-api-doc](https://github.com/Esri/arcgis-python-api/assets/21152323/55bce4c8-1428-4167-9ced-25a23cb530e8)
