### ISSUE TITLE
Error displaying widget: model not found for arcgis 2.1.0

### ISSUE THREAD

**Issue by timhaverland-noaa** [Esri/arcgis-python-api#1755]
**Describe the bug**
When installing arcgis=2.1.0, jupyterlab=2 and nodejs=18.16.0=ha637b67_1, get an "error displaying widget: model not found" error when trying to display a map.
**To Reproduce**
```python
#I have the esri channel in my conda channel list
conda create -n arcgis210env python=3.8
conda activate arcgis210env
conda install -c esri arcgis=2.1.0
conda install jupyterlab=2
conda install nodejs=18.16.0=ha637b67_1
jupyter labextension install @jupyter-widgets/jupyterlab-manager@2
jupyter labextension install arcgis-map-ipywidget@2.1.0
#run jupyter lab, I've been using the following command but there may be a better way
jupyter lab --ip 0.0.0.0 --no-browser --allow-root
```
error:
```python
Error displaying widget: model not found
```
**Screenshots**

**Expected behavior**
interactive map should display
**Platform (please complete the following information):**
 - OS: [e.g. iOS] linux x64
 - Browser [e.g. chrome, safari] chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` 2.1.0

**Additional context**
Add any other context about the problem here, attachments etc.
Using the same kind of commands, I can install arcgis=2.0.0, jupyterlab=2 and nodejs=18.16.0=ha637b67_1 and the map widget displays. I installed nodejs=18.16.0=ha637b67_1 because that was the highest version that still used openssl=1.1.1. If I installed a nodejs with higher version, openssl 3.x was installed, and my jupyterlab builds would fail.
![modelnotfound](https://github.com/Esri/arcgis-python-api/assets/11637032/09586662-b48c-4257-854d-ace7ca450f45)

**Comment by nanaeaubry** [comment]
@timhaverland-noaa Our widget is not currently supported in Jupyter Lab only in Jupyter Notebook.

This support is being added soon...

**Comment by timhaverland-noaa** [comment]
That's good news to hear that better support is coming, but I was following this page that explicitly mentions JupyterLab
https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/ and shows how to install the arcgis-map-ipywidget. Doesn't that page imply support?

**Comment by nanaeaubry** [comment]
@timhaverland-noaa 
Yes, it does imply that but we are working on removing it and then updating with the new information. Sorry for the confusion.

When we do have support for Jupyter lab it will be Jupyter Lab 4

**Comment by tatornator12** [comment]
@nanaeaubry I know this is an old/closed thread, but looking to see if anything has changed/updated on supporting Jupyter Lab 4?

**Comment by achapkowski** [comment]
@tatornator12 the newer versions of the API support jupyter labs.
Try version 2.4.0 or 2.4.1

**Comment by nanaeaubry** [comment]
@tatornator12 
We have tested in Colab, MyBinder, and Notebook 7.x
Azure Databricks has an unofficial workaround one of our users found to get the widget to render.
