### ISSUE TITLE
Feature Layer Collection query_domains() returns and empty list from a Feature Layer in ArcGIS Online

### ISSUE THREAD

**Issue by Clubdebambos** [Esri/arcgis-python-api#1760]
**Describe the bug**
As per the documentation [here](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#arcgis.features.FeatureLayerCollection.query_domains). The query_domains() method should return a list of dictionaries, instead it returns an empty list. The documentation used to state that this only worked for Portal. This has been removed. The query_domains used to throw the error below with Online, but now it returns an empty list, all indicating it should work in Online now, but doesn't.

```python
The requested layer (layerId: queryDomains) was not found.
(Error Code: 400) 
```

**To Reproduce**
```python
from arcgis import GIS
from arcgis.features import FeatureLayerCollection

agol = GIS("home")

item = agol.content.get("FS_ITEM_ID")
flc = FeatureLayerCollection(item.url, agol)
domains = flc.query_domains(layers=[0])

print(domains)
```

error:
No error, returns empty list when it should return a dictionary describing the domains.

**Screenshots**

**Expected behavior**
Should return a list of dictionaries with domain information

**Platform (please complete the following information):**
 - OS: Windows 11 Home
 - Browser Chrome
 - Python API Version: 2.2.0.1

**Additional context**
Domains exist in my example, I can use a workaround as per below.

```python
from arcgis import GIS
from arcgis.features import FeatureLayerCollection

agol = GIS("home")

item = agol.content.get("FS_ITEM_ID")

 list to hold the domain information
domains_list = []

 get domains for specific layer
for fld in item.layers[0].properties.fields:
    if fld.domain:
         append each domain into the list
        if fld.domain not in domains_list:
            domains_list.append(fld.domain)

print(domains_list)
```

**Comment by nanaeaubry** [comment]
@Clubdebambos 

Can you check in the FeatureLayerCollection if `supportsQueryDomains` is in the properties?
And if so, is it set to True?

If this is not the case then an empty list is returned

**Comment by Clubdebambos** [comment]
Thanks for the reply @nanaeaubry ,
There is no property called supportsQueryDomains and when I attempt to add one, although I get an indication that the addition was successful, when I access the flc properties, the property does not exist. Why wouldnt this property be automatically added when you add a domain?

```python
from arcgis.gis import GIS
from arcgis.features import FeatureLayerCollection

"""Access AGOL"""
agol = GIS("home")

item = agol.content.get("051cfbc792854a44b4502000ba839f30")

add_dict = {
    "supportsQueryDomains": True
}

flc = FeatureLayerCollection.fromitem(item)

"""Update the JSON definition"""
status = flc.manager.add_to_definition(update_dict)
print(status)
```


```python
from arcgis import GIS
from arcgis.features import FeatureLayerCollection

## connect to agol
agol = GIS("home")

## get feature service as an item object
item = agol.content.get("051cfbc792854a44b4502000ba839f30")

## create a flc object from item object
flc = FeatureLayerCollection(item.url, agol)

## print properties
print(flc.properties)`
```

**Comment by nanaeaubry** [comment]
@Clubdebambos Interesting, I will reach out to the Online team and see what is happening. The REST documentation implies that this property still exists: https://developers.arcgis.com/rest/services-reference/enterprise/query-domains-feature-service-.htm
Not sure why it would not show up when adding a domain.

I will keep you updated on what I find

**Comment by nanaeaubry** [comment]
@Clubdebambos 
I got a reply from the team that implements this:
`queryDomains` is not implemented by all feature service implementations. 
At this time only arcobjects FS supports it.

Users do not set supports properties - they are indicators to clients of when something is supported - when a service adds support it with advertise with a supports property. That way clients that look for the support property will just start to work with the new feature is supported. A false for a supports property (or not listing it which means false) indicates it is not supported

So it is only for arcobjects FS and hosted FS in enterprise and online will not support it.


---
We will better document this in the API as well but hope this clears it up for you
