### ISSUE TITLE
GeoAccessor.compare incorrectly shows every row as modified

### ISSUE THREAD

**Issue by skykasko** [Esri/arcgis-python-api#1766]
**Describe the bug**
When using `compare()` to compare Spatially Enabled DataFrames that were loaded from different sources (one from an ArcGIS online layer and one from a geodatabase feature class), I'm getting a result showing that every single row has been modified, when in reality they should be identical.

**To Reproduce**
My scenario is a bit involved to reproduce, since it seems to be caused by loading the DataFrames from different kinds of sources. However, one thing I noticed was that the `GeoSeriesAccessor.JSON` attributes of both DataFrames were equal, whereas calling the Pandas `to_json()` method showed small floating point differences in the numbers in the geometry field. The code below reproduces that behavior, by starting out with geometries that have those small floating point differences I was seeing:
<details>
<summary>Expand example code</summary>

```python
import pandas as pd
from arcgis.features import GeoAccessor, GeoSeriesAccessor

line1 = [[[-7813752.429099999, 5438372.717100002], [-7813761.6741, 5438384.995700002]]]
line2 = [[[-7813752.4291, 5438372.7171], [-7813761.6741, 5438384.9957]]]
spatial_reference = {"wkid": 102100, "latestWkid": 3857}
df1 = pd.DataFrame(
    [
        {
            "unique_column": 0,
            "SHAPE": {"paths": line1, "spatialReference": spatial_reference},
        }
    ]
)
df2 = pd.DataFrame(
    [
        {
            "unique_column": 0,
            "SHAPE": {"paths": line2, "spatialReference": spatial_reference},
        }
    ]
)

print(df1[df1.spatial.name][0].JSON)
# {"paths":[[[-7813752.4290999994,5438372.7171000019],[-7813761.6741000004,5438384.9957000017]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}
print(df2[df2.spatial.name][0].JSON)
# {"paths":[[[-7813752.4290999994,5438372.7171000019],[-7813761.6741000004,5438384.9957000017]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}
print(df1.SHAPE.to_json())
# {"0":{"paths":[[[-7813752.4290999994,5438372.7171000019],[-7813761.6741000004,5438384.9957000017]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}}
print(df2.SHAPE.to_json())
# {"0":{"paths":[[[-7813752.4291000003,5438372.7171],[-7813761.6741000004,5438384.9956999999]]],"spatialReference":{"wkid":102100,"latestWkid":3857}}}
print(df1[df1.spatial.name][0].JSON == df2[df2.spatial.name][0].JSON)
# True
print(df1[df1.spatial.name][0].equals(df2[df2.spatial.name][0]))
# True
print(df1.SHAPE.to_json() == df2.SHAPE.to_json())
# False
print(df1.spatial.compare(df2, match_field="unique_column")["modified_rows"])
#    unique_column                                              SHAPE
# 0              0  {"paths": [[[-7813752.4291, 5438372.7171], [-7...
```

</details>

**Expected behavior**
Comparing DataFrames which are loaded from different copies of the same dataset should not show every row as modified. In particular, if `GeoSeriesAccessor.equals()` returns `True` when comparing two rows' geometries, as in the example above, those geometries should not cause the row to be listed as modified in the comparison result.

If there's no way to avoid issues with floating points numbers in geometry comparisons, perhaps the ability to specify a spatial tolerance for the comparison could be added.

**Platform:**
 - OS: Windows 10
 -  Python API version: 2.2.0.1

**Comment by nanaeaubry** [comment]
@skykasko 
How are you getting the JSON for the GeoAccessor? `df1.spatial.json`? 

The compare method uses a panda's merge method so if you are seeing difference in the panda's to_json then that would explain the fact that difference are found when merging. 

I would do some data manipulation on the data and make sure they are rounded to the same decimal place. It seems the issue might arise to how the data is stored in Online vs the other source.

@achapkowski do you have any input?

**Comment by nanaeaubry** [comment]
@skykasko 
Creating a custom round method is the way to go. Otherwise you can look into other libraries that have some methods such as `almost_equals` in the Shapely library or if you have arcpy you can use the generalize operation or boundary.

https://stackoverflow.com/questions/63402333/how-does-almost-equals-function-of-shapely-treat-the-starting-point-and-errors
https://pro.arcgis.com/en/pro-app/latest/tool-reference/editing/generalize.htm

You can also post on the Esri Community forum to see if other users have come across this or have suggestions.
