### ISSUE TITLE
edit_features does not set NaT dates to null in version 2.2

### ISSUE THREAD

**Issue by skykasko** [Esri/arcgis-python-api#1768]
**Describe the bug**
After updating to version 2.2.0.1 of the API, when using `FeatureLayer.edit_features()` to update an ArcGIS Online feature with a date value of `pandas.NaT`, the date column's value is set to 0 (which is displayed as 1/1/1970) instead of null, even if the field is nullable.

**To Reproduce**
Create an ArcGIS Online feature layer with a nullable date field named "date_field", for example, and add a single feature with some date value. In the code sample below, fill in the feature layer's item ID, and the username and password to connect to the GIS where the feature layer is stored.

```python
import pandas as pd
from arcgis.gis import GIS

item_id = ""
url = "https://www.arcgis.com/"
username = ""
password = ""
gis = GIS(url, username, password)
layer = gis.content.get(item_id).layers[0]

print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': 1709283600000}
updates = pd.DataFrame(
    [
        {
            "OBJECTID": 1,
            "date_field": pd.NaT,
            "SHAPE": {
                "x": -7000000,
                "y": 5000000,
                "spatialReference": {"wkid": 102100, "latestWkid": 3857},
            },
        }
    ]
)
print(layer.edit_features(updates=updates))
# {'addResults': [], 'updateResults': [{'objectId': 1, 'uniqueId': 1, 'globalId': None, 'success': True}], 'deleteResults': []}
print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': 0}
```

Running the exact same code in version 2.1.0.2 of the API (with Pandas version 1.4.4) yields the expected final result:
```python
print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': None}
```

**Screenshots**
Initial state
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/a18f891b-33b8-4b73-a926-7acc18aa6384)
State after running the example code above with version 2.2.0.1 of the API
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/2dd4b927-e108-4ea6-b2fe-fde94221db74)
State after running the same code with version 2.1.0.2 of the API instead
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/13c0ff66-ad75-47bf-8a8d-98ce523fe902)

**Expected behavior**
Sending an update with a `pandas.NaT` value in a nullable date field should result in a null value being stored, like it did prior to version 2.2 of the API.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.2.0.1
 - Pandas version: 2.0.2

**Comment by achapkowski** [comment]
This will be resolved in v2.3.0, which should be released in April 2024
