### ISSUE TITLE
edit_features sets all dates to the same value in version 2.2

### ISSUE THREAD

**Issue by skykasko** [Esri/arcgis-python-api#1769]
**Describe the bug**
After updating to version 2.2.0.1 of the API, when using `FeatureLayer.edit_features()` to update values in multiple date fields of an ArcGIS Online feature, all but one of the supplied values are ignored, and the same date value is stored in each date field.

**To Reproduce**
Create an ArcGIS Online feature layer with a two date fields named "date_field" and "date_field_2", for example, and add a single feature. In the code sample below, fill in the feature layer's item ID, and the username and password to connect to the GIS where the feature layer is stored.
```python
import datetime
import pandas as pd
from arcgis.gis import GIS

item_id = ""
url = "https://www.arcgis.com/"
username = ""
password = ""
gis = GIS(url, username, password)
layer = gis.content.get(item_id).layers[0]

print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': 1709283600000, 'date_field_2': 1667664000000}
updates = pd.DataFrame(
    [
        {
            "OBJECTID": 1,
            "date_field": datetime.datetime(1999, 6, 15, 1),
            "date_field_2": datetime.datetime(2005, 12, 1, 8),
            "SHAPE": {
                "x": -7000000,
                "y": 5000000,
                "spatialReference": {"wkid": 102100, "latestWkid": 3857},
            },
        }
    ]
)
print(layer.edit_features(updates=updates))
# {'addResults': [], 'updateResults': [{'objectId': 1, 'uniqueId': 1, 'globalId': None, 'success': True}], 'deleteResults': []}
print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': 1133424000000, 'date_field_2': 1133424000000}
```

Despite being provided completely different dates, "date_field" and "date_field_2" end up storing identical values after the update.

Running the exact same code in version 2.1.0.2 of the API (with Pandas version 1.4.4) yields the expected final result:

```python
print(layer.query(object_ids="1").features[0].attributes)
# {'OBJECTID': 1, 'date_field': 929422800000, 'date_field_2': 1133442000000}
```

**Screenshots**
Initial state
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/d38b9308-4910-4b8d-beb6-6a6ef335f0e6)
State after running the example code above with version 2.2.0.1 of the API, showing the incorrect outcome
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/f1af9c41-e18c-4c27-a4c7-7d442c388cf1)
State after running the same code with version 2.1.0.2 of the API instead, showing the expected outcome
![image](https://github.com/Esri/arcgis-python-api/assets/88055150/f598fa67-7402-4b7b-9826-0cd7d4ce97a7)

**Expected behavior**
Each date field should be updated with the value provided for it, which was the behavior prior to version 2.2 of the API.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.2.0.1
 - Pandas version: 2.0.2

**Comment by achapkowski** [comment]
@skykasko we cannot reproduce your bug.  Please try updating to version 2.2.0.3.

**Comment by skykasko** [comment]
@achapkowski, I updated to version 2.2.0.3 and am still experiencing the same bug. To make what's hopefully a completely isolated, reproducible example, I've created a repo at https://github.com/skykasko/arcgis-python-api-date-example with a `requirements.txt` file for creating an isolated Python environment based on only the arcgis and pandas dependencies, and a `run_example.py` script that creates a new hosted ArcGIS Online feature layer with a single feature with two date fields, and then attempts to update the date values using `edit_features()`.

I'd greatly appreciate it if you could try to reproduce the bug again using this example repo. See below for more details on running the example:

---

First create a virtual environment and install the dependencies from `requirements.txt`. (`requirements.txt` was compiled from `pyproject.toml`; if you prefer to use a tool to install the dependencies directly from `pyproject.toml`, it should yield the same
results.) Then run the `run_example.py` script. The following steps worked for me on Windows:

```ShellSession
git clone https://github.com/skykasko/arcgis-python-api-date-example
cd arcgis-python-api-date-example
py -3.9 -m venv .venv
.venv\Scripts\activate
py -m pip install -r requirements.txt
py run_example.py
```

`run_example.py` will prompt you to enter a username and password to login to ArcGIS Online. (To skip this, edit lines 11 and 12 of `run_example.py` and enter the username and password directly in the code.) It then creates a hosted ArcGIS Online feature layer with a single feature based on the contents of `layer_source.csv`, which contains two different date values in two date fields. Finally, it attempts to update the date fields with two new, distinct date values.

Below is the output I saw from running the code.

```
INFO:2024-03-05 13:06:25,350:Created CSV item '65116ea32f8c49f99d8c85e17186f410'
INFO:2024-03-05 13:06:38,148:Created Date Example Feature Layer '983a470c9faf4a82b68e0f216279b87c'
INFO:2024-03-05 13:06:39,974:Initial state: {'date_field': 1709283600000, 'date_field_2': 1667664000000, 'x': -68.7, 'y': 46.5, 'ObjectId': 1}
INFO:2024-03-05 13:06:40,218:Edit results: {'addResults': [], 'updateResults': [{'objectId': 1, 'uniqueId': 1, 'globalId': None, 'success': True}], 'deleteResults': []}
INFO:2024-03-05 13:06:40,396:Final state: {'date_field': 1133424000000, 'date_field_2': 1133424000000, 'x': -68.7, 'y': 46.5, 'ObjectId': 1}
```

Below is a screenshot of the ArcGIS feature layer after the run, showing that both fields ended up with the date value intended for date_field_2.

![image](https://github.com/Esri/arcgis-python-api/assets/88055150/8ab50d1f-890f-4bd6-81e9-c219f16871ea)

**Comment by skykasko** [comment]
Update: I was able to reproduce what I believe to be the same issue in a much simpler example that doesn't involve updating a feature layer. I've found that calling `spatial.to_featureset()` on a Spatially Enabled DataFrame with multiple date fields returns a feature set with features that have identical values in each date field:

```python
import datetime
import pandas as pd
from arcgis.features import GeoAccessor

df = pd.DataFrame(
    [
        {
            "OBJECTID": 1,
            "date_field": datetime.datetime(1999, 6, 15, 1),
            "date_field_2": datetime.datetime(2005, 12, 1, 8),
            "SHAPE": {
                "x": -7000000,
                "y": 5000000,
                "spatialReference": {"wkid": 102100, "latestWkid": 3857},
            },
        }
    ]
)
attributes = df.spatial.to_featureset().features[0].attributes
print(attributes)
# {'OBJECTID': 1, 'date_field': 1133424000000, 'date_field_2': 1133424000000}
print(datetime.datetime.utcfromtimestamp(attributes["date_field"] / 1e3))
# 2005-12-01 08:00:00
print(datetime.datetime.utcfromtimestamp(attributes["date_field_2"] / 1e3))
# 2005-12-01 08:00:00
```

I got the above result running in the same Python environment specified in the [GitHub repo](https://github.com/skykasko/arcgis-python-api-date-example) I mentioned in my previous comment, with version 2.2.0.3 of the ArcGIS API for Python.

**Comment by achapkowski** [comment]
Ok, I'll take a look, thank you

**Comment by nanaeaubry** [comment]
I cannot reproduce this with the most recent code you provided with 2.3.0 (coming soon):
![image](https://github.com/Esri/arcgis-python-api/assets/19919283/58d369e7-d43c-4cb8-b12b-2ac365cc30b5)


With 2.2.0.3 this does occur:
![image](https://github.com/Esri/arcgis-python-api/assets/19919283/de9f4b46-35be-4d62-a151-93a0b9cb5923)



So it has been fixed for the next release
