### ISSUE TITLE
take layer offline devlab

### ISSUE THREAD

**Issue by mpayson** [Esri/arcgis-python-api#177]
Creating a devlab per:

| Lab | Description|
| ----- | --------- |
| Take data offline using spatial dataframe | Show how to query feature layers into a dataframe and then write to a shape file or fgdb. Converse of import data |

A few questions:

1. Should I skip the dataframe since the `save` function is on a `feature_set`? We could then leave it as a challenge to create the dataframe and maybe a simple operation on that dataframe?
2. Can I save to a shape file or fgdb on a Mac, it says `ArcPy` is required for shape files?
3. Should the initial service query return all features or only a subset?

[Pushing here](https://github.com/mpayson/arcgis-python-api/blob/mp-df-offline/labs/take_layer_offline.ipynb)

Thanks!

@AtmaMani @jyaistMap

**Comment by AtmaMani** [comment]
@mpayson 
1. yes, showing `save` functionality is appropriate
2. You can save on OSX, Linux. We need `pyshp` for IO with shape files and `fiona` for fgdb. The fiona part is still under dev, not available in production at 1.3. So you might want to show saving to shape file now and update it to fgdb later
3. I think it is save to query a subset, this way we don't run out of memory and is generally a good pattern to show case. Additionally, the sample teaches how to specify queries.

**Comment by rohitgeo** [comment]
There are multiple ways to export feature data to shp or fgdb:
- [Item.export()](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html?#arcgis.gis.Item.export) - by owner or admin
 - [extract_data()](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.features.manage_data.html#extract-data)
 - [FeatureLayer.query()](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.features.toc.html#arcgis.features.FeatureLayer.query) -> FeatureSet ->(optonally) SpatialDataFrame. These can be saved to shapefiles but need arcpy or pyshp. PyShp doesnt currently support projections though.

I think we should promote the first two approaches for exporting to shp and fgdb as they don't need pyshp or arcpy on the client. The third approach is mainly to get data into a SpatialDataFrame. Saving the spatial dataframe to a file could be a separate lab.

I find getting a dataframe out of a layer the most valuable for analysis.

The simplified code could be:
```from arcgis.gis import GIS
from arcgis.features import SpatialDataFrame

gis = GIS(username="<USERNAME>")

items = gis.content.search(query='Griffith', 'Feature Layer')
feature_layer_item = items[0]
feature_layer = feature_layer_item.layers[0]

sdf = SpatialDataFrame.from_layer(layer)
sdf.head()
```

**Comment by mpayson** [comment]
appreciate the feedback @rohitgeo @AtmaMani ! Should I change this lab to just get a dataframe per Rohit's snippet?

**Comment by rohitgeo** [comment]
Yes, let's do that. We can then write the SpatialDataFrame to disk using the to_featureclass() method.
