### ISSUE TITLE
InsecureRequestWarning when initializing GIS with client_id and client_secret

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-python-api#1770]
**Describe the bug**
When initializing a GIS object using client_id and client_secret, we see the following messages logged in console ```C:\Miniconda3\envs\unitylite\lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.arcgis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings```

Initializing the GIS using username and password works fine as expected and does not print any `InsecureRequestWarning` messages.

**To Reproduce**
```python
gis = GIS(url="https://www.arcgis.com", client_id=<client_id>, client_secret=<client_secret>)
# tried setting verify_cert = True, but it does not help, it still prints InsecureRequestWarning messages    
gis = GIS(url="https://www.arcgis.com", client_id=<client_id>, client_secret=<client_secret>, verify_cert=True) 

```
**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.2.0.3 with Python 3.9.18

**Comment by nanaeaubry** [comment]
This has been fixed for the next release of the API
