### ISSUE TITLE
Need help with Web Maps

### ISSUE THREAD

**Issue by LillyDHS** [Esri/arcgis-python-api#1771]
If I create a feature layer in python AGOL using gis.content.add, publish the item , then add the layer to a webmap. At what point in the process can I set or change the symbols on the map? What specific code do I use?

**Comment by nanaeaubry** [comment]
@LillyDHS 
We have some guides:
https://developers.arcgis.com/python/guide/working-with-web-maps-and-web-scenes/#adding-layers-to-a-web-map
https://developers.arcgis.com/python/guide/using-the-map-widget/#adding-layers-with-custom-symbology
https://developers.arcgis.com/python/guide/smart-mapping/
https://developers.arcgis.com/python/guide/advanced-cartography-part1/


Check these out and see if it can help answer your question.
If not feel free to describe with a bit more detail/reproducible code what you are trying to achieve.

**Comment by LillyDHS** [comment]
Hello,

This is the code I am using:

#Create df
details = {
    'Name' : ['Dot1', 'Dot2'],
    'Longitude' : [-110.972895, -110.971250],
    'Latitude' : [32.126740, 32.170415]
}

#define renderer
rend = {
    "type": "simple",
    "symbol": {
        "type": "esriSLS",
        "color": [200, 50, 0, 250],
        "width": 20,
        "style": "esriSLSSolid"
    }
}


# creating a Dataframe object
df = pd.DataFrame(details)
sdf = pd.DataFrame.spatial.from_xy(df=df,
                                   x_column='Longitude',
                                   y_column='Latitude')


#Create Feature Set
df2FeatureSet = FeatureSet.from_dataframe(sdf)

#Create webmap
wm = WebMap()


#Add layer
wm.add_layer(df2FeatureSet, {'title':'Test',
                             'renderer':rend
                            })
wm

Loris Williams
Business Analyst
Systems & Information Integration Office
Office of the Chief Readiness Support Officer
Department of Homeland Security
***@***.******@***.***>
_______________________________________
Leading the way with Affordable Readiness
***@***.***

**Comment by LillyDHS** [comment]
Thanks. I figured it out.
