### ISSUE TITLE
Append job gets stuck in pending state indefinitely

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-python-api#1775]
**Describe the bug**
While appending a featurecollection to an ArcGIS Online hosted feature layer, the append job sometimes gets stuck in `pending` state and the script does not progress further. It remains stuck at that moment and there is no way out but to kill it. 
When I looked at the fiddler log I was able to see that job status was continuously getting queried as expected, but it kept returning `pending` until eventually I killed it. 

I am appending data in batches of 500 features, so its not a lot of data being pushed and the layer too does not have more than couple of hundred features. But after a couple of batches, it will suddenly get stuck and not move forward. The job status keeps getting returned as `pending`.

Please see the attached har and fiddler saz dump file which shows the first couple of append jobs succeed and then get stuck.

[append-stuck-at-pending.zip](https://github.com/Esri/arcgis-python-api/files/14607513/append-stuck-at-pending.zip)

**Platform:**
 - OS: Windows and Ubuntu 22.04
 - Python API Version 2.2.0.3

**Comment by achapkowski** [comment]
@anandak it seems to be an issue on online, can you reach out to them.
