### ISSUE TITLE
Python Bypasses User Credit Allotment in AGOL

### ISSUE THREAD

**Issue by kphaneuf** [Esri/arcgis-python-api#1776]
When I publish a table from a csv item with no params and there is a field called "Address" it automatically geocodes the table and publishes as a feature layer. It also does not present an error if the credit usage passes what the connected user is allowed.  Allowed a user with only 100 credits allotted to use 2,700 credits. And in the AGOL Org it still showed that user had 100 credits left.  When I try in the AGOL GUI, I get a credit usage error.
```
gis = GIS("Pro")
csv_properties={"title":"TableTest"}
csv_item = r"C:\FLTest.csv"
table = gis.content.add(item_properties=csv_properties, data=csv_item)
###publish csv item as table with no params creates FL and sees location and zip fields and uses credits to geocode####
item= table.publish()
```

**Comment by nanaeaubry** [comment]
@kphaneuf 

Thanks for bringing this up. To publish as a table and not a feature layer you can set the locatioType to None in the publish parameters

Here is an example :
```
file_item= gis.content.add(item_properties=csv_properties, data=csv_item)
analyzed = gis.content.analyze(item=file_item)
pp = analyzed['publishParameters']
pp['name'] = 'MyTable'
pp['locationType'] = None
table_item= file_item.publish(pp)
```

**Comment by achapkowski** [comment]
@kphaneuf for the credit issue, please contact support to log a support requests for ArcGIS Online.
