### ISSUE TITLE
clone_items() with item_mapping parameter misses group layers in the web map

### ISSUE THREAD

**Issue by avstjohn** [Esri/arcgis-python-api#1779]
**Describe the bug**
I found that group layers in a web map are missed by the _item_mapping_ procedure in the _clone_items()_ method.

**To Reproduce**
Create a web map with group layers.
Run the clone_items() method.

```python
gis_target.content.clone_items(items=[wm_item], # list of items to clone
            folder="TARGET FOLDER NAME", 
            item_extent=None, 
            use_org_basemap=False, # basemap does not change
            copy_data=False, # do not copy HFL to target Portal 
            copy_global_ids=False, # features not copied, so does not matter
            search_existing_items=True, # check whether item already exists in target
            item_mapping={
                "source HFL item id":"target HFL item id",  # hfl
                "source view item id":"target view item id"  # view
            }, # {source itemid: target itemid} 
            group_mapping={
                "source group id":"target group id"
            }, # key=source groupid; value=target groupid; 
            owner="TARGET OWNER USERNAME", 
            preserve_item_id=False)
```
error:
```python
No error upon execution, just in web map: see screenshots.
```
**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/24692437/1fbb919b-4569-41d0-9ae8-5f1eb5ed715b)

**Expected behavior**
I identified this as a bug when I separated all of the group layers in my web map into individual layers. All of my layers' data sources, whether sourced by hosted feature layers, tables, or views, were then properly mapped by the _item_mapping_ parameter.

**Platform (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Python API Version: 2.2.0.1

**Additional context**
I verified that both the feature layer item URL and the ID are untouched in the content JSON of the new target web map.

**Comment by nparavicini7** [comment]
Addressed this for next version
