### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by addiercv** [Esri/arcgis-python-api#1786]
**Describe the bug**
Newer versions of Numpy (1.24.4) doesn't have float attribute. 
The error is occurring at line 138 ...\AppData\Roaming\Python39\site-packages\arcgis\_impl\common\_utils.py where numpy.float is used to compare data types when features are edited (features.edit_features(updates=[array of dicts])) on an arcgis online feature layer. 

**To Reproduce**
Edit features/attributes where at-least one attribute is of numpy.float64 type on the arcgis online feature layer. 
```python
feature_layer = gis.content.get(feature_layer_id).layers[0] 
update_result = feature_layer.edit_features(updates=updated_features) 
```
error:
```python
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Expected behavior**
Feature should be updated on the online feature layer. Even when datatype to be edited to changed to float(), the error continues. 

**Platform (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser: NA 
 - Python API Version: 2.1.0.3 

**Additional context**
Error is resolved when numpy.float is changed to numpy.float_ at line 138 of ...\AppData\Roaming\Python39\site-packages\arcgis\_impl\common\_utils.py

**Comment by nanaeaubry** [comment]
@addiercv Please update to the latest release, this was normally fixed at a later version. 

If you see this persist at a later version let us know!
