### ISSUE TITLE
Efficient way to identify ArcGIS Online Named User Pro licenses that have been taken offline

### ISSUE THREAD

**Issue by knoopum** [Esri/arcgis-python-api#1798]
I need to be able to identify the group of users in our ArcGIS Online organization who have taken their ArcGIS Pro license offline. 

One reason for generating such a list is to monitor how our users are using offline Named User licensing over time. Another is to identify who to contact with specific messaging related to offline licensing at various times throughout the year.

If I use user_entitlement() for the Pro license to check the disconnected property for a user, then that takes a number of seconds to return. In an ArcGIS Online organization with over 11,000 users, that adds up days!

My 'best" workaround so far is to loop through all the users using check() to get their list of entitlements, and then assign() to set them the same, but catching the exception that occurs when a user has their Pro license offline (i.e., 'None of the specified users can be disconnected.\n(Error Code: 400)'. That only takes ~4-hours for our org, but even that is long enough to present a challenge for something we hope to monitor daily

Perhaps there is a quicker way to do this already that I've missed, however, if not I would like to see one implemented.

While our initial focus is on Pro, we would like to be able to do this for any offline Named User license (e.g., Drone2Map, CityEngine.)

Thanks!

**Comment by nanaeaubry** [comment]
Thanks for the suggestion, we will look into this!

**Comment by knoopum** [comment]
Thanks! Works like a charm as of API 2.4.0, for both Pro and Drone2Map offline licensing, see [arcgis.gis.admin.License.offline_report](ga-usecpam).
