### ISSUE TITLE
Why is the Folders class not named FolderManager?

### ISSUE THREAD

**Issue by BMannell** [Esri/arcgis-python-api#1799]
The new `Folders` class is described as being a helper class. The naming convention of this module has been to end helper classes with _Manager_. i.e. ContentManager, UserManager, GroupManager etc..

https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#folders

Is this an indication of future changes? Will the `ContentManager` be re-named `Contents` at some point?

**Comment by achapkowski** [comment]
The introduction of 'Folders' and 'Folder' classes is to help users better organize data.  

Think of it like this: Imagine your laptop overflowing with GIS data – rasters, roads, parcels, water lines, all spread across different regions.   Would you just toss everything in the root directory (like C:)?  Of course not! We naturally organize things into folders based on topic or project.  That's the power of Folders and Folder classes – you can now manage your content within the API just like you would on your local machine, with the added bonus of ArcGIS functionality at your fingertips.


In terms of changing ContentManager to Content, we haven't thought about that at the moment.  Currently, the content manager is accessible via the gis.content property, so in a way, it is using 'content' already.  It's an interesting thought, thank you for suggesting it.

With a strong foundation of over seven years, our API is constantly evolving alongside Python and the ArcGIS product suite.  

Let us know what you think of the release!

**Comment by BMannell** [comment]
@achapkowski 

Thanks, I understand how folders operate in AGOL and Portal.

My main question is why the `Folders` class not named `FolderManager`? The naming convention of this module has been to end helper classes with Manager. i.e. ContentManager, UserManager, GroupManager etc..

Why the change to a the pluralized name of the managed resource? 
Is the `Folders` class inherently different than the other manager classes?

**Comment by achapkowski** [comment]
It is different because it just doesn't manage multiple folders.
