### ISSUE TITLE
Publish function for shapefile items create duplicate indexes for area and length

### ISSUE THREAD

**Issue by BMannell** [Esri/arcgis-python-api#1809]
**Describe the bug**
For a Shapefile item, calling `publish(overwrite=True)` multiple times results in duplicate indexes for the `Shape__Area` and `Shape_Length` fields.

**To Reproduce**
```python
import arcgis

gis = arcgis.GIS("home")

# Shapefile that has already been published as a feature service
shapefile_item = gis.content.get("e9a63b122c26484aa62cb1f2a74572fe")
# Republish shapefile multiple times
for i in range(0,5):
	shapefile_item.publish(overwrite=True)
```
**Screenshots**
Indexes after initial publish:
```json
  "indexes" : [
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "PK__SAMPLEDA__C1BEA5A2CDFFF3A9", 
      "fields" : "FID", 
      "isAscending" : true, 
      "isUnique" : true, 
      "description" : "clustered, unique, primary key", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "user_144.SAMPLEDATA_SAMPLEDATA_Shape_sidx", 
      "fields" : "Shape", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "Shape Index", 
      "indexType" : "Spatial"
    }
  ]
```

Indexes after calling re-publish 5 times:

```json
  "indexes" : [
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "PK__SAMPLEDA__C1BEA5A27BE7D6DD", 
      "fields" : "FID", 
      "isAscending" : true, 
      "isUnique" : true, 
      "description" : "clustered, unique, primary key", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "user_144.SAMPLEDATA_SAMPLEDATA2_Shape_sidx", 
      "fields" : "Shape", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "Shape Index", 
      "indexType" : "Spatial"
    }, 
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Area_Index", 
      "fields" : "Shape__Area", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }, 
    {
      "name" : "Shape__Length_Index", 
      "fields" : "Shape__Length", 
      "isAscending" : true, 
      "isUnique" : false, 
      "description" : "", 
      "indexType" : "Attribute"
    }
  ]
```

**Expected behavior**
Expecting no duplicates of indexes

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Python API Version: 2.1.0.4

**Additional context**
I've only tried this on Shapefiles, not sure if this happens for other file types. 
This doesn't seem to effect the performance of the layer. This is somewhat concerning as we have clients that will be using this function daily. What happens when there are 50, 100, 200 indexes for the feature service? If anything this will add credit usage for storing the extra index data.

[Shapefile](https://arcgis.com/home/item.html?id=e9a63b122c26484aa62cb1f2a74572fe)
[Feature Layer](https://arcgis.com/home/item.html?id=4f8415302c8f41f0945d5ca628dade02)

**Comment by nanaeaubry** [comment]
@BMannell We will take a look thanks for reporting this

**Comment by nanaeaubry** [comment]
@BMannell 
I am not able to reproduce with my shapefile using the latest version of the python API and ArcGIS Online.
Are you using ArcGIS Online or Enterprise?
Also try to update the version of the Python API you are using to see if this issue is still there at the latest release.

**Comment by BMannell** [comment]
@nanaeaubry 
Thanks! I figured that may be the case, didn't see anything in the release notes though.
I will update my version of _arcgis_ and try again.

**Comment by BMannell** [comment]
> Are you using ArcGIS Online or Enterprise?

AGOL

**Comment by nanaeaubry** [comment]
> @nanaeaubry Thanks! I figured that may be the case, didn't see anything in the release notes though. I will update my version of _arcgis_ and try again.

Since we didn't know it was an issue it might have been resolved through other changes that were made. If you see this still occurring at 2.3.0 can you provide a sample shapefile that we can use to attempt to reproduce since it might be data driven? Or still an issue.

**Comment by BMannell** [comment]
@nanaeaubry 
I just tested with version 2.3.0 and I'm still seeing the duplicate indexes. Here's a link to the Shapefile I used:
https://arcgis.com/home/item.html?id=e9a63b122c26484aa62cb1f2a74572fe

**Comment by BMannell** [comment]
@nanaeaubry 
No it's not the fields being duplicated, it's the indexes for those fields.

**Comment by nanaeaubry** [comment]
@BMannell We were able to confirm that this is a bug in ArcGIS Online and not with the Python API. I would contact support to get follow up on the issue, we have reported it to the team as well.

**Comment by BMannell** [comment]
Thanks @nanaeaubry!
