### ISSUE TITLE
Feature Layer query() using return_all_records does not return all records

### ISSUE THREAD

**Issue by dnsohrabian** [Esri/arcgis-python-api#1823]
**Describe the bug**
When using the `.query()` method on a Feature Layer, it returns the max record count (1000 in my case) even if you pass `return_all_records=True` to the method. It should be returning all records.

**To Reproduce**
```python
# Living Atlas USA 2020 Census Population Characteristics
census_ago_id = 'ebeb65deb5c14f4d8849fd68944b7ee6'
census_item = gis.content.get(census_ago_id)
blockgroup_census = census_item.layers[4] # The fourth feature layer is block groups
blockgroup_fs = blockgroup_census.query(where="County = 'Cuyahoga County'", return_all_records=True)
```
error:
blockgroup_fs FeatureSet only has 1,000 records, which is not the full set according to where clause.

**Screenshots**

**Expected behavior**
The query returns everything the where clause specifies, no matter how many records.
It should return 1,184 features in the query.

**Platform (please complete the following information):**
 - OS: Linux, WSL 2
 - Browser: Chrome
 - Python API Version: 2.3.0.1

**Additional context**
This only started happening after updating to 2.3.0.1. Using 2.2 does not cauase this bug.

**Comment by nanaeaubry** [comment]
@dnsohrabian Thanks for reporting we will take a look!

**Comment by dnsohrabian** [comment]
Thank you for looking at this one. @achapkowski Can you please offer any details for why this was closed? Is this something that's already fixed? Was it not reproducible?

**Comment by dnsohrabian** [comment]
Hi @nanaeaubry, can you clarify if this wasn't reproducible or if something is wrong with my submission?

**Comment by nanaeaubry** [comment]
@dnsohrabian We were able to reproduce and it has been fixed for the next release.

From above you can see an issue was opened on our side and a PR was made and merged in for the next version:
![image](https://github.com/Esri/arcgis-python-api/assets/19919283/0488d5be-4fed-46b5-bc3f-be1a694399ec)


Hope that helps!

**Comment by dnsohrabian** [comment]
@nanaeaubry Thank you, that's great to hear. Appreciate the update! Will look forward to next release.
