### ISSUE TITLE
Exception: Enter only compatible datasets from Labeled_Tiles, MultiLabeled_Tiles

### ISSUE THREAD

**Issue by Daremitsu1** [Esri/arcgis-python-api#1830]
**Describe the bug**
Getting the error Exception: Enter only compatible datasets from Labeled_Tiles, MultiLabeled_Tiles while trying to run a `FeatureClassifier` model on the NWPU-RESISC45 data.

**To Reproduce**
```
import os, json
from arcgis.learn import prepare_data, FeatureClassifier

data_path = os.path.join(os.getcwd(), "NWPU-RESISC45")

data = prepare_data(
    path=data_path, dataset_type="Imagenet", batch_size=32, val_split_pct=0.2
)

model = FeatureClassifier(data, oversample=True)

```
error:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_21316\2252118473.py in <module>
----> 1 model = FeatureClassifier(data, oversample=True)

D:\Python Projects\Honda-Invoice\app\lib\site-packages\arcgis\learn\models\_classifier.py in __init__(self, data, backbone, pretrained_path, mixup, oversample, backend, *args, **kwargs)
    136                 raise Exception (f"Enter only compatible backbones from {', '.join(self.supported_backbones)}")
    137 
--> 138             self._check_dataset_support(self._data)
    139 
    140             self._code = feature_classifier_prf

D:\Python Projects\Honda-Invoice\app\lib\site-packages\arcgis\learn\models\_arcgis_model.py in _check_dataset_support(self, data)
    468         if hasattr(data, 'dataset_type'):
    469             if getattr(data, 'dataset_type') not in self.supported_datasets:
--> 470                 raise Exception(f"Enter only compatible datasets from {', '.join(self.supported_datasets)}")
    471 
    472     def _arcgis_init_callback(self):

Exception: Enter only compatible datasets from Labeled_Tiles, MultiLabeled_Tiles
```
**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/54842807/ab80a4d6-a951-47da-ad51-33b89c5ede32)

**Expected behavior**
The model should have started training. 
I followed the steps exactly outlined in this notebook:
https://github.com/Esri/arcgis-python-api/blob/master/samples/04_gis_analysts_data_scientists/image_scene_classification_using_feature_classifier.ipynb

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome
 - Python API Version [e.g. `1.6.2`] 1.8.4

**Additional context**
The data is [RESISC45 Dataset](https://arxiv.org/abs/1703.00121) outlined in the notebook.

Kindly help.

**Comment by Daremitsu1** [comment]
Any update? Could you guys specify the deep learning libraries for the python versions > 3.7? There in lies the problem since there are conflicting versions resulting in most of the errors.

**Comment by priyankatuteja** [comment]
@Daremitsu1 The version of python api you're trying to use is quite old. I just tested this workflow with python api release 2.3.0 and it works.

Command to install:
conda install arcgis_learn=2.3.0 python=3.11 -c esri

**Comment by Daremitsu1** [comment]
@priyankatuteja Thank you! Yes python api needed to be changed to `2.3.0` with python3.11.

Additionally, for people wanting to download the deep-learning libraries please refer to the link below:
https://github.com/Esri/deep-learning-frameworks

For pip installation, I would suggest `torch==2.0.1 torchvision==0.15.2 fastai==1.0.61 timm==0.4.12 optuna==3.0.4(optional)`.

If there are any ModuleNotFound error just go through the link above and install the version dependencies.
