### ISSUE TITLE
create_view method does not work on hosted feature layers if layer ids are not in sequential order.

### ISSUE THREAD

**Issue by ramcgreg** [Esri/arcgis-python-api#1841]
**Describe the bug**
create_view method does not work on hosted feature layers whose layer ids are **not** in sequential order. (ie unique layer ids has been enabled and layers were moved, EVEN IF YOU REALIZE YOU DID THIS AND TURN OFF ASSIGN UNIQUE IDS (pardon all caps)).
**To Reproduce**
```python
source_search = gis.content.search("hosted feature service with layer ids NOT in sequential order")[0]
source_flc = FeatureLayerCollection.fromitem(source_search)

new_view = source_flc.manager.create_view(name="output view name")
```
error:
```python
<copy the full error message here>
```
The resulting view has layers with differently ordered layer ids. When opened in map viewer, layers are out of order and often their type (point line polygon) is altered. Resulting view is completely unusable. See link to geonet post below.
**Screenshots**
![image](https://github.com/Esri/arcgis-python-api/assets/74867122/88cc515a-8189-4133-a895-3934452387e9)

**Expected behavior**
A normal feature service view is created.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windwos 11
 - Browser [e.g. chrome, safari] Chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` Most recent verson on AGOL.

**Additional context**
Add any other context about the problem here, attachments etc.
https://community.esri.com/t5/arcgis-api-for-python-questions/create-view-does-not-work-with-non-sequential/m-p/1487937#M10144

**Comment by nanaeaubry** [comment]
@ramcgreg 

There is a parameter on the create view called `preserve_layer_ids` where the default is False. Have you tried with this set to True?

**Comment by ramcgreg** [comment]
I have not. I did not know about that. I will try that and definitely give
you credit if that works. Thanks

**Comment by nanaeaubry** [comment]
@ramcgreg Did this work?
