### ISSUE TITLE
item.usage() returns None when using a custom date range longer than 6 months

### ISSUE THREAD

**Issue by jcrawford85** [Esri/arcgis-python-api#1843]
**Describe the bug**
item.usage() returns None when using a custom date range longer than 6 months

**To Reproduce**
Following the Usage Example 2: Custom Date Range from the ArcGIS API for Python reference page:
https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Item.usage

Choose a date range longer than 6 months from now.  I chose the beginning of FY 2024, 10-01-23.

```python
import datetime as dt

flyr_item = gis.content.get("00d79cc145144b44883b4f22563aa547")
date_1 = dt.datetime(2023,10,1)
date_2 = dt.datetime.now()

# Early value, later value
result = flyr_item.usage(date_range = (date_1, date_2), as_df=True)
result
```
error:
```python
The notebook cell runs without giving an error, but no results are returned.  If you choose a date sooner than 6 months ago, results will be returned.
```
**Screenshots**

**Expected behavior**
It would be nice to have custom date ranges beyond 6 months return their results.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox, edge
 - Python API Version 1.9.1

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by nanaeaubry** [comment]
Please update to the latest version of the API this was fixed
