### ISSUE TITLE
How to determine successful authentication?

### ISSUE THREAD

**Issue by ruckc** [Esri/arcgis-python-api#1844]
**Describe the bug**
Trying to login to an enterprise portal, PropertyMap instance has no attribute 'user'

**To Reproduce**
```python
from arcgis.gis import GIS
gis = GIS(url, username, password)
print("Logged in as: ", gis.properties.user)
```
error:
```python
AttributeError: 'PropertyMap' instance has no attribute 'user'
```
**Screenshots**
The environment is airgapped.

**Expected behavior**
I expect a better process to determine if authenticated or not, with ideally a reason.  The username and password work when logging in directly to portal, it's configured directly to Active Directory.

**Platform (please complete the following information):**
 - OS: Windows 10/Python 3.9.19
 - Python API Version: 2.3.0.2

**Comment by ruckc** [comment]
So... using username@DOMAIN works for the username, but not DOMAIN\\username... so stupid

**Comment by nanaeaubry** [comment]
You can use: gis.users.me to see if you are logged in

**Comment by ruckc** [comment]
@nanaeaubry the documentation should reflect that.

**Comment by nanaeaubry** [comment]
@ruckc 
Sure here are the places you can refer to in our doc:
https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/
https://developers.arcgis.com/python/guide/accessing-and-managing-users/

**Comment by ruckc** [comment]
That first page doesn't mention the .me key at all.

**Comment by nanaeaubry** [comment]
@ruckc True but it shows ways to verify your authentication and there are several ways to do this shown in our doc. Hope it helps!
