### ISSUE TITLE
Specify type in item_properties

### ISSUE THREAD

**Issue by ruckc** [Esri/arcgis-python-api#1845]
**Describe the bug**
Following examples on adding content doesn't work

**To Reproduce**
```python
gis = GIS(...)
properties = {'title': 'some title', 'description': 'some description', 'tags': 'a, b, c'}
path = 'path/to/file.csv'
item = gis.content.add(item_properties=properties, data=path)
```
error:
```python
RuntimeError: Specify type in item_properties
```

**Expected behavior**
The documentation to have steps that work.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 2.3.0.2

**Comment by achapkowski** [comment]
Title and type are the only requirements to add an item besides your data.  
This isn't a bug.

**Comment by ruckc** [comment]
@achapkowski - then why does the documentation https://developers.arcgis.com/python/guide/import-data/ not show a "type" field.

This is the 2nd major breaking deficiency I've found in the python documentation.
