### ISSUE TITLE
User' object has no attribute 'availableCredits'

### ISSUE THREAD

**Issue by MSLTrebesch** [Esri/arcgis-python-api#1846]
**Describe the bug**
User object is not providing "AvailableCredits" or "AssignedCredits", for **some** users in AGOL, though the user clearly has credits in AGOL assigned and available to them.

**To Reproduce**
```python
from arcgis.gis import GIS

gis = GIS("home")
userid = 'xxx@mt.gov_montana'
user = gis.users.get(userid)

print(user.availableCredits)
```
error from 2.3.0:
```python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
In  [27]:
Line 7:     print(user.availableCredits)

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py, in __getattr__:
Line 10980: raise AttributeError(

AttributeError: 'User' object has no attribute 'availableCredits'
---------------------------------------------------------------------------

```
**Screenshots**

**Expected behavior**
I've successfully obtained the available credits and assigned credits attributes from the user class numerous times.  This error is happening now from AGOL Notebooks (ArcGIS Notebook Python 3 Standard - 9.0) and from a local notebook using arcgis API 2.2.01

**Platform (please complete the following information):**
 - OS:Windows 11
 - Browser: Edge
 - Python API Version 2.2.03 and online w/ 2.3.0   (errors fpriv

**Additional context**
This might be an AGOL issue...  but, thought I'd bring it up here.

**Comment by nanaeaubry** [comment]
@MSLTrebesch This is a property that comes back directly from a Rest call to get the user information and not something we are setting up. (As you suspected it seems)
I would open an issue with support for ArcGIS Online and we will see if we can find out any information on our end in the meantime :)

**Comment by nanaeaubry** [comment]
@MSLTrebesch Just an FYI that we have tested and cannot reproduce this on our Online Orgs. So I would reach out to support since it might be an issue with your org configuration or an Online issue we just aren't able to reproduce. Good luck!
