### ISSUE TITLE
- [checked] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?

### ISSUE THREAD

**Issue by ethiclegacy** [Esri/arcgis-python-api#1852]
- [checked] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [checked] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

_Originally posted by @Areebey in https://github.com/github/opensource.guide/pull/3223_

**Comment by nanaeaubry** [comment]
@ethiclegacy The issues you have opened do not make sense to us. Please provide more context and better explanation

**Comment by ethiclegacy** [comment]
### https://ds7ci3976lwlh.cloudfront.net/tophatch/a7d6175a-e32c-4cf4-b6e0-d6e47b1dd258.txt?Expires=1719291716&Signature=pJpBbY-xD21x~CRHsv5N2Fi2rKEWb5uXdG2q4X2FjLUjjayp6~UyY6WN0xt4te~Uz0gO8~HjiWhw2Kn2URb08O5yzlFzOMoNDXzWJ~ShQMHH0PX70E~Qv~~kSwJAN~IMt95dPM2CQ1yY-P5WDUwqX~rnwCzf-h1ZzA3Q5wPZ63XmFjFRtAhIYNL8ih4QMybNLRN0wuGmDfdWHzglch2bMw5kmu9hsM-RLFhsY4QFpmqPSXMBVxSRYTdvjckojdlrGeyATt9FCVhffugEQ1rYUtleTLiM1gpq25IPwA2aH8LXZc7-0x8ImxPLE0gX-5OqbCEee6IZ3-QaJjcSK6yYuQ__&Key-Pair-Id=K3TWGX9UIYEXH4
