### ISSUE TITLE
Unable to create user

### ISSUE THREAD

**Issue by rdw4nau** [Esri/arcgis-python-api#1879]
When trying to migrate users using the example code here:
https://developers.arcgis.com/python/samples/move-existing-user-content-to-a-new-user/
I am unable to create the user, and receive a generic response, thus unable to troubleshoot.

I am making use of the API endpoint:  "https://www.arcgis.com/sharing/rest"

**To Reproduce**
```python

new_userid = "TESTING1234XYZ"
givenName = "*********"
sn = "*********"
mail = "*********@nau.edu"

gis = GIS(profile="*********")

newuser = gis.users.create(username = new_userid,
                        password = 'pwdNotUsed3453435',
                        firstname = givenName, 
                        lastname = sn, 
                        email = mail, 
                        description = 'testing migration',
                        role = 'Default SAML user',
                        provider = 'enterprise',
                        idp_username = None,
                        user_type = None)
```
error:
```python
Unable to create TESTING1234XYZ
ERROR:arcgis.gis:Unable to create TESTING1234XYZ
```

- Changing various things like password length or removing provider does not change behavior.
- The user attempting to create the account is an 'Administrator' in our instance and a 'Professional Plus' user type.

**Platform (please complete the following information):**
 - OS: MacOS
 - Browser: None, running CLI
 - Python API Version `print(arcgis.__version__)` 2.3.0.3

I was requested by B Baldwin to post this here as a bug for support.

**Comment by jyaistMap** [comment]
Hi @rdw4nau - It looks like from your code, you're trying to create a user with a SAML identity provider.  When you use the provider argument of `enterprise`, the `idp_username` argument is documented as required.  Can you provide an argument for that parameter and see if that works?  The `user_type` argument might also be necessary to assign licensing - I'll research into this today to verify.

**Comment by rdw4nau** [comment]
@jyaistMap Thanks for the response. I have tried a large number of iterations (suggested and unsuggested) for the variable values. This example it is set to 'None' but multiple other attempts included a corresponding value for our IdP (in our ORG's case a unique 9 digit value.) ie "001234567" etc. This produced similar 'Unable to create' results with the following:  
```
newuser = gis.users.create(username = new_userid,
                        password = 'pwdNotUsed3453435',
                        firstname = givenName, 
                        lastname = sn, 
                        email = mail, 
                        description = 'testing migration',
                        role = 'Default SAML user',
                        provider = 'enterprise',
                        idp_username = '001234567',
                        user_type = None)
```

**Comment by jyaistMap** [comment]
@rdw4nau - I'll look into this and test internally and get back to you when I have some information.

**Comment by jyaistMap** [comment]
Hi @rdw4nau -

Here is Python API code that works in an ArcGIS Online org configured for SAML Login. 

```python
new_user = gis.users.create(
    username="firstinitial_lastname@company.com_production",
    password=None,
    firstname="Newuserfirst",
    lastname="Newuserlast",
    email="valid_user_email@your_domain.com",
    provider="enterprise",
    idp_username="username@domain.com"
)
``` 

- This organization has [_New Member Defaults_](https://doc.arcgis.com/en/arcgis-online/administer/configure-new-member-defaults.htm) configured for the _user_type_ and _role_ parameters, so those arguments are not necessary.  If you do not have default values configured for those, the values will need to be valid _user_type_ and _role_ values in your organization
- The password must be set to _None_
- The _idp_username_ argument must match the value configured by the identity provider (IdP) for the _NameID_ attribute For SAML logins. That value comes from the SAML configuration.

**Comment by rdw4nau** [comment]
@jyaistMap 
The only thing I had not tried was changing password to None. Doing this did not change behavior (same error response and no user created.) I've even tried running the same code as posted, which also resulted in the same response. Is there any way to get someone to enable debug logging on our instance?

**Comment by achapkowski** [comment]
@rdw4nau I recommend reaching out to support, who can do a more indepth look at your system to see what is going on.
