### ISSUE TITLE
Adding assignment to workforce does not work

### ISSUE THREAD

**Issue by arpasuyu** [Esri/arcgis-python-api#1881]
We are using some automated scripts to add assignments to the Workforce project since 11.1 of ArcGIS Enterprise. We have updated to 11.3 last week and everything stopped working.  There are just a few lines of code. 

This the part that is giving an error. We are trying to add a single assignment.
![cap3](https://github.com/user-attachments/assets/7fc2857b-ccdc-4be6-96a6-6ca153cf80c7)

This is the geometry that we add :
![cap2](https://github.com/user-attachments/assets/bc426e46-a642-4251-be13-f4013cadb723)

And this is the error:
![cap1](https://github.com/user-attachments/assets/c069730a-a34a-4a46-abb3-292b0528c029)

**Comment by nanaeaubry** [comment]
This has been fixed at the latest release, thanks!
