### ISSUE TITLE
Failed to create Service: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

### ISSUE THREAD

**Issue by bootrider** [Esri/arcgis-python-api#193]
Hello fellows, 

Trying to create a service using the GIS.content.add method in AGOL, I am receiving the following response:
`Failed to create Service: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
`

The issue here is: using an unrestricted account in the computer, I have no trouble creating the service, if I try to run the script using a windows account that has several restrictions regarding internet access, the exception is raised. So far the account with internet restriction has been granted connection to AGOL using port 80 and 443, more over it has permission to access the domain *.maps.arcgis.com.

Maybe you know if there is another requirement regarding firewall in order to avoid this issue?

thanks in advance

**Comment by achapkowski** [comment]
Please verify the following:

- The network link between server and client may be temporarily going down.
- running out of system resources.

Beyond that it is extremely difficult to troubleshoot this issue.  I recommend running fiddler or some other network monitor to see where the calls are going.
