### ISSUE TITLE
map.export_to_html broken

### ISSUE THREAD

**Issue by bjfultn** [Esri/arcgis-python-api#1977]
**Describe the bug**
Using the export_to_html method of the GIS.map() object does not create a functional stand-alone html page.

**To Reproduce**
```python
from arcgis.gis import GIS

gis = GIS("https://www.arcgis.com")
m = gis.map()

m.export_to_html("tmp.html", title="Interactive Map")

```

**Screenshots**
![Screenshot 2024-08-28 at 12 56 28 PM](https://github.com/user-attachments/assets/d93bf6c8-b9d3-49f1-aefb-70ae01f6a9fc)

**Expected behavior**
I expect to be able to see a map when I open tmp.html

**Platform (please complete the following information):**
 - OS: Mac OS 14.6.1
 - Browser: Chrome
 - Python API Version: 2.3.1

**Additional context**
- Same bug reported in the Esri community forums over a year ago. https://community.esri.com/t5/python-questions/arcgis-python-export-map-to-html-is-blank/td-p/1280483
- The Export live map in a separate HTML file section of this tutorial does not work as written https://developers.arcgis.com/python/guide/part5-saving-updating-and-embedding-map-widget/#embedding-a-live-map

**Comment by nanaeaubry** [comment]
@bjfultn Hi thank you for reporting this! We are making some major improvements to the mapping module and have updated this method. You can expect a fix in the next version which will be released end of September

**Comment by nanaeaubry** [comment]
@bjfultn Please use the latest install of arcgis and the new arcgis-mapping packages to try again:
`conda install -c esri arcgis arcgis-mapping`
