### ISSUE TITLE
Get all groups of a content

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#200]
I'd like to know if is possible to get all groups from a content.

**Comment by rwmajor2** [comment]
@mateuspontesmoraes Thanks for the feedback.  This was a slight oversight in the Python API.  We have addressed this in the API and will be available next release (v1.4.1 ?).  There will be a new method on an item called
```python
print(item.shared_with)
```

The output of this will be a dictionary that looks something like:
```json
{"private": false, "everyone": true, "org": true, "groups": [<Group title:"My Shared Group Name" owner:myuser>]}
```
