### ISSUE TITLE
Create_view Not honoring set_item_id

### ISSUE THREAD

**Issue by stevewayuk** [Esri/arcgis-python-api#2030]
**Describe the bug**

I discovered this bug when trying to work around the inability for swap_view to work with multiple layers.

I need my ItemIDs to be stable so consuming systems do not break.  One option, was to delete the view, and recreate using create_view:

https://developers.arcgis.com/python/api-reference/arcgis.features.managers.html#arcgis.features.managers.FeatureLayerCollectionManager.create_view

This does exactly what I want....except, when I pass the ItemID I would like my view to be using set_item_id, it does not work, and a system generated itemid is created.

**To Reproduce**

```
service = gis.content.get('itemIDofService')
flc = FeatureLayerCollection.fromitem(service )
flc.container.manager.create_view(name='View Name Here', set_item_id='ItemIdOfDeletedViewToReuse')

```
error:
`No Error - Resulting View has system generated ItemID`

**Expected behavior**
Resulting View should use the specified item id.

**Platform (please complete the following information):**
 - OS: Widnows
 - Browser Chromium
 - Python API Version 2.3.1

**Comment by achapkowski** [comment]
Is this online or enterprise?  If enterprise what version of enterprise do you have?

**Comment by stevewayuk** [comment]
> Is this online or enterprise? If enterprise what version of enterprise do you have?

Apologies, for missing this information out.
This is with Online.

**Comment by achapkowski** [comment]
@stevewayuk on enterprise, where this is supported, it works:

```
gis = GIS(profile='your_eneterprise_profile')
item = gis.content.get("<some item id>")
flc = FeatureLayerCollection.fromitem(item=item)
item_id_set = uuid.uuid4().hex
view_item = flc.manager.create_view(
    name='ViewNameHere',
    set_item_id=item_id_set,
)
assert view_item.id == item_id_set
```

This is not supported on online.
