### ISSUE TITLE
ModuleNotFoundError: No module named 'arcgis.map' for version 2.4.0

### ISSUE THREAD

**Issue by Clubdebambos** [Esri/arcgis-python-api#2096]
**Describe the bug**
installed version 2.4.0 expecting access to the new arcgis.map module but it is not available. 

**To Reproduce**
```python
from arcgis.map import Map 
```
error:
```python
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
ModuleNotFoundError: No module named 'arcgis.map'
```
**Screenshots**
![image](https://github.com/user-attachments/assets/0eb4e6b9-f2b3-47e1-8b1b-fc096a6a2a38)

**Expected behavior**
arcgis.map to be imported successfully

**Platform (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: Chrome
 - Python API Version 2.4.0

**Additional context**
Installed using pip install arcgis from command prompt

the arcgis.mapping module is still present but no WebMap to import
![image](https://github.com/user-attachments/assets/26d7207e-6f7f-4811-9637-23a5ffe40de6)

**Comment by achapkowski** [comment]
For 2.4.0: conda install -c esri arcgis arcgis-mapping or pip install arcgis arcgis-mapping
see: https://developers.arcgis.com/python/latest/guide/install-and-set-up/anaconda/
