### ISSUE TITLE
Typo error. "lateste" should be changed to "latest"

### ISSUE THREAD

**Issue by rkraujutis** [Esri/arcgis-python-api#2140]
https://github.com/Esri/arcgis-python-api/blob/4a7cf4852eadcd3e87cc3cc0078cf650cf0e035d/guide/04-feature-data-and-analysis/part2_branch_versioning_with_parcel_fabrics.ipynb#L356C54-L356C61

**Comment by nanaeaubry** [comment]
Thanks we will update this!
