### ISSUE TITLE
Unable to get arcgis.mapping to work

### ISSUE THREAD

**Issue by gv2325** [Esri/arcgis-python-api#2149]
**Describe the bug**
Unable to use the arcgis mapping module

error:
```python
Import Error: Cannot import WebMap from arcgis.mapping
```
**Screenshots**
<img width="1394" alt="Screenshot 2024-10-29 at 2 30 09 PM" src="https://github.com/user-attachments/assets/4174f044-8c1c-4d0d-8c35-5a81e3f2859d">

**Platform (please complete the following information):**
 - OS: [Docker] https://github.com/Esri/arcgis-python-api/pkgs/container/arcgis-python-api-notebook/283262919?tag=latest
 - Browser [Chrome]
 - Python API Version [`2.4.0`]

**Additional context**
I used the docker availble on the repo, the same is reproducible if using it in a conda environment or on Google Colab with `!pip install arcgis`

**Comment by achapkowski** [comment]
You need to install Arcgis-mapping.

See: https://developers.arcgis.com/python/latest/guide/install-and-set-up/anaconda/

**Comment by gv2325** [comment]
is the recommendation to create an entirely new environment for arcgis 2.4.0?

**Comment by achapkowski** [comment]
Did you try using this? https://github.com/Esri/arcgis-python-api/blob/master/docker/NotebookImage.Dockerfile

**Comment by jtroe** [comment]
@gv2325 please see the updated documentation for v2.4.0 on using the map widget at developers.arcgis.com/python
----
The `arcgis.mapping` namespace has been deprecated in v2.4.0 and we have released a new Jupyter Lab based package to provide the widgets.   You will now use the `arcgis.map` namespace for mapping widgets.  An even simpler way of accessing this is to just call `.map()` on your `GIS` object.

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/8b6ed9f8-3f76-4026-bea0-5bb2102c5a15">

If you wish to interact directly, you may use: 

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/06e1bab2-66c4-4237-970b-2b72e57c7fcb">

Please make sure your docker image is up to date.  Thank you!

**Comment by gv2325** [comment]
Hi @jtroe and @achapkowski,

Thanks for the update, I just went through the whats new in `2.4.0` and have understood what the refactor does. I have switched to using an environment.yml for binder but stil getting errors on Google Colab. Thanks again!

**Comment by jtroe** [comment]
@gv2325 please open a separate issue for Colab.
