### ISSUE TITLE
raise "string" inside the API

### ISSUE THREAD

**Issue by Miralupa** [Esri/arcgis-python-api#2166]
**Describe the bug**
There are several occurences of omission of the word 'Exception' inside the code of the arcgis python API when wanting to raise an exception. (I counted 4 occurences in the 2.3.0 version of the API). For example, in the _version.py file line 1079 : 

```python
raise ("Version must be in edit mode to run post.")
```

This leads to the following error when the code is reached :

```python
TypeError: exceptions must derive from BaseException
```

Thus, the original error message is hidden to the user.

**Expected behavior**
Please fix the API code in order to raise an exception object and not a string.

**Platform:**
 - Python API Version `2.3.0`

**Comment by nanaeaubry** [comment]
@Miralupa Thanks we will take a look!

**Comment by nanaeaubry** [comment]
@Miralupa We put in a fix and only found the 4 occurrences as you stated. Thanks for catching this! It will be fixed at the next release (Spring 2025)

**Comment by Miralupa** [comment]
Great ! Thank you for your quick fix.
