### ISSUE TITLE
gis.content.add() does not accept a URL for data parameter

### ISSUE THREAD

**Issue by felnne** [Esri/arcgis-python-api#2175]
## Describe the bug

I am trying to upload a GeoJSON file as an item in AGOL. The GeoJSON to be added is available remotely via a URL.

If I set the `data` parameter of `gis.content.add() ` to a URL I get an error:

```
File ".../.venv/lib/python3.11/site-packages/arcgis/gis/__init__.py", line 6750, in add
    elif _geo._is_geoenabled(data) and hasattr(data, "spatial"):

AttributeError: module 'arcgis.features.geo' has no attribute '_is_geoenabled'
```

## To Reproduce

```python
gis.content.add(
    item_properties=item.item_properties,
    data=item.data_href,
)
```

Where `item.item_properties` is a ItemProperties object with the `title`, `item_type` and `file_name` properties set, and `item.data_href` is a valid URL string.

error:

```
File ".../.venv/lib/python3.11/site-packages/arcgis/gis/__init__.py", line 6750, in add
    elif _geo._is_geoenabled(data) and hasattr(data, "spatial"):

AttributeError: module 'arcgis.features.geo' has no attribute '_is_geoenabled'
```

## Screenshots

N/A.

## Expected behaviour

I expect the URL to the data file to be uploaded as part of creating the item.

The comment for the `content.add` method describes the `data` property as:

> Optional string, io.StringIO, or io.BytesIO. Either a path or URL to the data or an instance of `StringIO` or `BytesIO` objects.

So I assume URLs are intended to work for this method.

I can see in the underlying `self._portal.add_item()` method references to a `_is_http_url()` method which suggests that does support URLs but there's no equivalent method in this `add()` method.

The underlying HTTP API method also suggests a URL can be used: https://developers.arcgis.com/python/latest/api-reference/arcgis.gis.toc.html#arcgis.gis.ContentManager.add

Am I misunderstanding how this is intended to work? I would rather not have to download the file first and pass as bytes, etc.

**Platform (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Python API Version 2.4

## Additional context

N/A.

**Comment by achapkowski** [comment]
Have you tried using the folder.add method? 

```python
from arcgis.gis import GIS, ItemProperties,  ItemTypeEnum

gis = GIS(profile='your_enterprise_profile')
folder = gis.content.folders.get()
ip = ItemProperties(**{'title' : 'datafromurl', 'item_type': ItemTypeEnum.SHAPEFILE,})
result = folder.add(item_properties=ip, data_url="https://www2.census.gov/geo/tiger/GENZ2010/gz_2010_09_170_00_500k.zip")
item = result.result()
print(item)
```

**Comment by felnne** [comment]
@achapkowski, ah yes that works.

Thanks!
