### ISSUE TITLE
Cannot visualize a spatial dataframe in 1..4.1

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/arcgis-python-api#241]
After I upgraded to 1.4.1 I noticed that I cannot visualize a spatial dataframe the same way I could in 1.4.0.

When I try to add the sdf to the map using this `sdf.plot(kind='map', map_widget=m)` I get this error:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-45a8b8c0c0d8> in <module>()
----> 1 sdf.plot(kind='map', map_widget=m)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\demo\lib\site-packages\arcgis\features\_data\geodataset\geodataframe.py in plot(self, *args, **kwargs)
   1146                      colors=kwargs.pop('cmap', None) or kwargs.pop('colors', None) or kwargs.pop('pallette', 'jet'),
   1147                      alpha=kwargs.pop('alpha', 1),
-> 1148                      **kwargs)
   1149                 return True
   1150             else:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\demo\lib\site-packages\arcgis\features\_data\geodataset\viz\mapping.py in plot(df, map_widget, name, renderer_type, symbol_type, symbol_style, col, colors, alpha, **kwargs)
    168         map_widget = MapView()
    169 
--> 170     fc = df.to_feature_collection(name=name)
    171     if renderer_type in [None, 's']:
    172         renderer_type = 's' # simple (default)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\demo\lib\site-packages\arcgis\features\_data\geodataset\geodataframe.py in to_feature_collection(self, name, drawing_info, extent, global_id_field)
   1524             ext = self.geoextent
   1525             extent = {
-> 1526                 "xmin" : ext[0],
   1527                 "ymin" : ext[1],
   1528                 "xmax" : ext[2],

TypeError: 'NoneType' object is not subscriptable`

Here is the same code in 1.4.0:

![sdf](https://user-images.githubusercontent.com/7396398/39581715-d793d30e-4eb1-11e8-8d54-a180a13b8f42.PNG)

**Comment by achapkowski** [comment]
Can you post your test data? So I can try and reproduce this.

**Comment by PerAkeMattias** [comment]
This is a simple shapefile that I was using, just a few random points.
[test_data.zip](https://github.com/Esri/arcgis-python-api/files/1971448/test_data.zip)

**Comment by achapkowski** [comment]
@PerAkeMattias we have a fix in, it will be in the  early June Release

**Comment by PerAkeMattias** [comment]
Awesome!  Thank you.

On May 17, 2018, at 11:38 AM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


@PerAkeMattias<https://github.com/PerAkeMattias> we have a fix in, it will be in the early June Release
