### ISSUE TITLE
Problem to create a new Feature Service Hosted

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#243]
I'm trying to create a new Feature Service Hosted using the following properties

```
properties={'title':'myTitle',
                'type': 'Feature Service',
                'url': 'myurl',
                'description':'mydscription',
                'typeKeywords': 'Hosted Service,Layer,providerSDS',
                'tags':'arcgis, python, earthquake, natural disaster, emergency'}

item = gis.content.add(item_properties=properties)
```

The item was created with success, but i realized that the "**typeKeywords**" property haven't the key "**Hosted Service**"

![image](https://user-images.githubusercontent.com/11629395/39602874-d67cec26-4efc-11e8-954f-898dbe160919.png)

![image](https://user-images.githubusercontent.com/11629395/39602688-4e848c66-4efc-11e8-928c-72fec632926a.png)

I'd like to know if this is an issue or i'm doing something wrong to created a new Feature Service Hosted

**Comment by achapkowski** [comment]
Are you adding a service by reference? or are you adding a service from some dataset like a file geodatabase or shapefile?

**Comment by rwmajor2** [comment]
@mateuspontesmoraes the type keyword "Hosted Service" can't be added to an Item; that's only managed by the backend Sharing API.  If you try to assign like above, it will discard it.

**Comment by mateuspontesmoraes** [comment]
@rwmajor2 and @achapkowski I have created a new Feature Service using the backend Sharing API.
Tks
