### ISSUE TITLE
Problem to add new layer using FeatureLayerManage update_definition

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#247]
Hello,

I have a Feature Service Hosted and I need to add a new layer.
I'm trying to add using this code:

`
featureLayer = FeatureLayerCollection.fromitem(feature)
`

I created a new object layers that contains two layers

![image](https://user-images.githubusercontent.com/11629395/40185948-4c9035da-59ca-11e8-94b0-d9c56fa936c7.png)

![image](https://user-images.githubusercontent.com/11629395/40185962-55605b22-59ca-11e8-88fb-c956649e0697.png)

The attribute **description** has changed with success, but the attribute **layer** keeps unchanged, with just one layer.

![image](https://user-images.githubusercontent.com/11629395/40186487-98c6f82a-59cb-11e8-8824-3f182e2066b8.png)

**Comment by achapkowski** [comment]
If you go to the FeatureService endpoint, so you see the layer?

**Comment by achapkowski** [comment]
You need to use `add_to_definition` to add a new **layer** to the hosted feature layer.

Here is a sample of adding a statept feature to a feature layer.  

```
lyr2add = {'layers': [{'currentVersion': 10.6,
   'name': 'statepts',
   'parentLayerId': -1,
   'defaultVisibility': True,
   'minScale': 0,
   'maxScale': 288895,
   'type': 'Feature Layer',
   'geometryType': 'esriGeometryPoint',
   'description': '',
   'copyrightText': '',
   'editFieldsInfo': None,
   'syncCanReturnChanges': True,
   'relationships': [],
   'isDataVersioned': False,
   'supportsRollbackOnFailureParameter': True,
   'supportsStatistics': True,
   'supportsAdvancedQueries': True,
   'supportsValidateSQL': True,
   'supportsCalculate': True,
   'advancedQueryCapabilities': {'supportsReturningQueryExtent': True,
    'supportsStatistics': True,
    'supportsDistinct': True,
    'supportsPagination': True,
    'supportsOrderBy': True,
    'supportsQueryWithDistance': True,
    'supportsLod': False,
    'supportsPaginationOnAggregatedQueries': True,
    'supportsQueryWithResultType': True,
    'supportsCountDistinct': True,
    'supportReturningGeometryCentroid': True},
   'extent': {'xmin': -19839092.30428812,
    'ymin': 2145729.67991779,
    'xmax': -7454985.146516735,
    'ymax': 11542624.916041076,
    'spatialReference': {'wkid': 102100, 'latestWkid': 3857}},
   'hasM': False,
   'hasZ': False,
   'allowTrueCurvesUpdates': False,
   'onlyAllowTrueCurveUpdatesByTrueCurveClients': True,
   'hasAttachments': False,
   'supportsApplyEditsWithGlobalIds': False,
   'htmlPopupType': 'esriServerHTMLPopupTypeAsHTMLText',
   'objectIdField': 'objectid',
   'globalIdField': None,
   'displayField': 'state_name',
   'typeIdField': '',
   'fields': [{'name': 'objectid',
     'type': 'esriFieldTypeOID',
     'alias': 'objectid',
     'domain': None,
     'nullable': False,
     'editable': False,
     'sqlType': 'sqlTypeInteger'},
    {'name': 'state_name',
     'type': 'esriFieldTypeString',
     'alias': 'STATE_NAME',
     'domain': None,
     'editable': True,
     'nullable': True,
     'length': 25,
     'sqlType': 'sqlTypeVarchar'}],
   'indexes': [],
   'dateFieldsTimeReference': {'timeZone': 'UTC',
    'respectsDaylightSaving': False},
   'types': [],
   'templates': [],
   'useStandardizedQueries': True,
   'supportedQueryFormats': 'JSON, geoJSON',
   'maxRecordCount': 2000,
   'allowGeometryUpdates': True,
   'capabilities': 'Query',
   'enableZDefaults': False,
   'allowUpdateWithoutMValues': True,
   'supportsCoordinatesQuantization': False,
   'supportsAttachmentsByUploadId': False,
   'hasStaticData': False}]}

```
 
So now we have a **new** layer defined per the spec for a feature layer.  See the REST API help to see what that looks like for a Feature Layer.  
Now we can go ahead and use the `add_to_definition` off the Feature Layers' container (AKA the Feature Service).  

```
mgr = somefeaturelayer.container.manager
mgr.add_to_definition(lyr2add)

```

The result is something like this (depends on the number of layers that exist in the Feature Service):

`{'layers': [{'name': 'statepts', 'id': 1}], 'success': True}`

If you don't believe the result, you can then go back to the original layer and double check:

`lyr.container.layers`

results in:

```
[<FeatureLayer url:"http://mysite/server/rest/services/Hosted/United_States/FeatureServer/0">,
 <FeatureLayer url:"http://mysite/server/rest/services/Hosted/United_States/FeatureServer/1">]
```

We have success!

So going back to what you saw.  Updating updates existing items in a service, and will **NOT** add new stuff.  So what you saw is expected.  For new things: indexes, layers, etc... you need to `add_to_definition`. 

Hope this helps

**Comment by mateuspontesmoraes** [comment]
@achapkowski works fine!

Tks so much
