### ISSUE TITLE
Clone items

### ISSUE THREAD

**Issue by yurygeo** [Esri/arcgis-python-api#250]
When i try to clone item from one org to another (both arcgis.com), runtime error occurs

![default](https://user-images.githubusercontent.com/32735012/40659614-6b8a8ecc-6357-11e8-9060-ca08925f0bd8.png)

Operation system: Windows 7, ArcGIS Pro installed.

Python API version: 1.4.1 (1.4.0 - same error)

**Comment by achapkowski** [comment]
@yurygeo please post your full code so we can reproduce it (minus passwords/usernames). Also, what items are failing to clone? 


Thanks

**Comment by yurygeo** [comment]
@achapkowski 

```python
import arcgis
from IPython.display import display
import pandas as pd
import keyring
import json

gis1 = arcgis.gis.GIS(username=keyring.get_password(...), password=keyring.get_password(...))
gis2 = arcgis.gis.GIS(username=keyring.get_password(...), password=keyring.get_password(...))

item = gis2.content.search('USA States')[0]

gis1.content.clone_items([item])
```

"item" is a copy of layer: http://www.arcgis.com/home/item.html?id=99fd67933e754a1181cc755146be21ca

Python version - 3.6.5

This code works fine in Python API version 1.3.

**Comment by apulverizer** [comment]
@yurygeo 

Try running the same code without the Jupyter Notebook, just as a Python script. 
There seems to be an issue with the Jupyter/Tornado that affects asyncio operations. 

Try downgrading tornado `pip3 install tornado==4.5.3`

https://github.com/jupyter/notebook/issues/3397
