### ISSUE TITLE
Detecting map extent change

### ISSUE THREAD

**Issue by maherkarim** [Esri/arcgis-python-api#251]
HI,
I am working with the API to perform analytics based on map extent, I was looking around the documentation to find how we can listen to map (basemap) extent change so I can issue a callback request.
can you help please on this.
The scenario is the following:
MapView show the basemap -> user change the map extent -> listen to change -> query database based on the new extent -> display the return geometry on top of the map as a new layer

Regards
Maher

**Comment by AtmaMani** [comment]
@maherkarim the map widget inherently performs this operation (fetching features for current / new extent). Is there a different / additional reason for which you need to listen to extent change events?
