### ISSUE TITLE
Mismatch between Python and Java

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#252]
https://developers.arcgis.com/python/sample-notebooks/clone-portal-users-groups-and-content/

Usernames that are observed as different in python but not in Java.  Source lists username as JonnyD27, but target is Jonnyd27, so for the following snippet:

for source_user in source_users:
    try:
        target_user = target.users.get(source_users.username)
        if target_user is not None:
            print('Deleting user: ' + target_user.fullName)
            target_user.reassign_to(target_admin_username)
            target_user.delete()
    except:
        print('User {} does not exist in Target Portal'.format(source_user.username))

User JonnyD27 does not exist in Target Portal

but then getting to:
for user in source_users:
    print("Creating user: " + user.username)
    copy_user(target, user, 'TestPassword@123')

Creating user: JonnyD27

java.lang.Exception: The server at 'https://TESTINGMAPS.ASRCLKREC.ORG:7443/arcgis/sharing/rest/community/createUser' returned an error. The user already exists.  Please check the username and try again. []

**Comment by achapkowski** [comment]
@guyn2gis i cannot reproduce this error at 1.5.2 are you still getting this?
