### ISSUE TITLE
Role Reversal

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#253]
Using the https://developers.arcgis.com/python/sample-notebooks/clone-portal-users-groups-and-content/

When I run:

#!esri_ & !admin
source_users = source.users.search('JonnyD27')
for user in source_users:
    print(user.username + "\t:\t" + str(user.role))

the result is JonnyD27	:	org_admin
This user has a custom role of Analyst, why does it show org_admin?

When I run:
for user in source_users:
    print("Creating user: " + user.username)
    copy_user(target, user, 'TestPassword@123')

Which not only comes back with:

Creating user: JonnyD27
HTTP Error 404: Not Found
Unable to create user JonnyD27

but does create the user but as an org_admin.

![image](https://user-images.githubusercontent.com/3903420/40810897-11a3942e-64e4-11e8-9477-fd0dcd0c2c93.png)

**Comment by rwmajor2** [comment]
@guyn2gis This is a perculiar situation that we are aware of and need to update this sample documentation.  Can you try `user.roleId` instead?  If a user has a custom role, it will actually report a strange id, which is the id of that custom role.

**Comment by guyn2gis** [comment]
I can try roleID.  I wound up just going with it and manually changing to Analyst, but still trying to finish the underlying script.
