### ISSUE TITLE
ipywidgets version bump request

### ISSUE THREAD

**Issue by xliiv** [Esri/arcgis-python-api#260]
Any plans to update ipywidgets version to 0.7 or higher?
Now it must be lower according to [this](https://github.com/Esri/arcgis-python-api/blob/master/environment.yml#L7)?

```bash
$ pipenv --python 3.6
$ pipenv install arcgis==1.4
$ pipenv graph
arcgis==1.4.0
  - ipywidgets [required: <7,>=5.2.2, installed: 6.0.1]
# cut rest of deps.
```

**Comment by DavidJVitale** [comment]
Hi @xliiv , The newest version of the ArcGIS API for Python (v1.4.1 and v1.4.2) actually requires >= v 7.0 of ipywidgets, and upon install with pip or conda will automatically include that dependency (See https://developers.arcgis.com/python/guide/system-requirements/ for more information). Older version had that version stipulation.

The environment.yml in this repository serves a different purpose, but it should be updated for parity. Thanks for catching that!

**Comment by xliiv** [comment]
I've just read that I did this issue on wrong repo. That explains why I couldn't find `setup.py` :)
However I installed again on blank env (see code from my first message) and I'm still getting:
```
arcgis==1.4.0
  - ipywidgets [required: <7,>=5.2.2, installed: 6.0.1]
    - ipykernel [required: >=4.5.1, installed: 4.8.2]
```
Maybe it's something related to `pipenv`?
I'll check regular `pip`.

**Comment by xliiv** [comment]
Evertything works. False alarm :)

I misunderstood this
`pipenv install arcgis==1.4`
which means
`pipenv install arcgis==1.4.0`
whereas in `rust` programming language (in which I recently spent more time) it would mean
`pipenv install arcgis==1.4.*`

I'm closing, sorry for this mess :)
