### ISSUE TITLE
copy_feature_layer_collection doc

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#265]
Argument | Description
-- | --
service_name | Required string. It is the name of the service.
layers | Optional list/string. This is **a** either a list of integers or a comma **seperated** list of integers as a string. Each index value represents a layer in the feature layer collection.
tables | Optional list/string. This is **a** either a list of integers or a comma **seperated** list of integers as a string. Each index value represents a table in the feature layer collection.
folder | Optional string. This is the name of the folder to place in. The default is None, which means the root folder.
description | Optional string. This is the Item description of the service.
snippet | Optional string. This is the Item’s snippet of the service. It is no longer than 250 characters.
owner | Optional string/User. The default is the current user, but if you want the service to be owned by another user, pass in this value.

Consider removing the letter **a** for readability above as it is unneeded in the layers and tables arguments, as well as spelling for **separated**

**Comment by guyn2gis** [comment]
Would be great to have a little snippet for the layers and or tables.  What is a list of integers or a comma separated list of integers as a string?
I am thinking -  [0 1 2 3] or [0,1,2,3]  or ["0,1,2,3"]

**Comment by guyn2gis** [comment]
In fact, thinking there needs to be lots of python snippets for everything, beyond just samples, something more akin to arcpy doc

**Comment by AtmaMani** [comment]
@guyn2gis yes, I agree. We (Python API team) have started to prioritize this and you should see more examples in the API ref doc as well. We will fix this issue as well.

**Comment by guyn2gis** [comment]
Thank you.  I would think with more samples, not necessarily more notebooks will bring more users to use the api.  I have been struggling, but then I used to do that with arcpy.  On the notebooks side for doc, it makes sense at least to me to have focused admin capabilities on different tools like copy groups, then copy  users as separate notebooks not duplicate notebooks with the same action, like currently there is a create groups, and then another for create groups, users, etc.  A sample notebook for CloneItems would be great too, but I am now using Collaboration to handle that side as I was unable to figure out the items list parameter.  JupyterLab is working great so far, but not using widget

**Comment by achapkowski** [comment]
we resolved the issue. Thank you for reporting.
