### ISSUE TITLE
SpatialDataFrame.from_featureclass()... generalizes polygons

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/arcgis-python-api#279]
When I convert a polygon featureclass to a spatial dataframe in 1.4.2, it generalizes the geometries.  This is quite a problem especially when I save the spatial dataframe back to a featureclass.

I have attached an image of the problem.  I add a featureclass that comes from Esri and I know there is no slivers in the data, anyways, its census blockgroups for the state of Pennsylvania in this case.  As you can see there is slivers everywhere.

Is there a limit on datasize, a setting I can change, or is this a real issue?

Thanks.

![arcgispythonapi](https://user-images.githubusercontent.com/7396398/43557261-6e703408-95c9-11e8-8266-8a9419d77128.PNG)

**Comment by achapkowski** [comment]
We have fixed this issue and it will be in the next release.
