### ISSUE TITLE
New Feature:  Add support for Databricks

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/arcgis-python-api#280]
I cannot visualize geographic data with the API using Databricks "notebooks".  Would you consider adding support for Databricks in upcoming releases?

Thanks.

**Comment by nshampur** [comment]
@PerAkeMattias . could you clarify what you mean by support for Databricks.

**Comment by PerAkeMattias** [comment]
[Databricks](https://databricks.com/) is our chosen data science platform at work- the API seems to work for spatial dataframes etc...  However, I cannot visualize even the simplest map and I don't get an error either.

I have attached an image of what happens when I try to draw a map.

So, to clarify, I want to be able to draw maps with the API when I use it in Databricks notebooks.

![arcgis in databricks](https://user-images.githubusercontent.com/7396398/43606691-b6909f00-9661-11e8-981b-0c3d7f53bb8f.PNG)

**Comment by nshampur** [comment]
Databricks notebooks use a different notebook format which is distinct from Jupyter notebooks.
The MapView widget was built to integrate with Jupyter notebooks.

I'll defer to the experts on the form on how it could work in data brick notebooks.

**Comment by DavidJVitale** [comment]
@PerAkeMattias the map widget incorporated with the ArcGIS API for python is built using the  [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/) javascript libraries, which is unfortunately not compatible with databricks notebooks. To my knowledge, databricks notebooks do not offer as rich of a custom widget experience, so I am not sure it is even possible to port the widget to databricks.

**Comment by PerAkeMattias** [comment]
Thank you for looking into it.

On Aug 2, 2018, at 6:56 PM, David Vitale <notifications@github.com<mailto:notifications@github.com>> wrote:


@PerAkeMattias<https://github.com/PerAkeMattias> the map widget incorporated with the ArcGIS API for python is built using the ipywidgets<https://ipywidgets.readthedocs.io/en/stable/> javascript libraries, which is unfortunately not compatible with databricks notebooks. To my knowledge, databricks notebooks do not offer as rich of a custom widget experience, so I am not sure it is even possible to port the widget to databricks.
