### ISSUE TITLE
Documentation Issue for Webscene Update

### ISSUE THREAD

**Issue by mschenker** [Esri/arcgis-python-api#283]
The 1.5 API reference for Webscene (in apidoc/arcgis.mapping.html) contains some code/text that does not belong there, see [here](https://esri.github.io/arcgis-python-api/apidoc/html/beta/arcgis.mapping.html?highlight=webscene#arcgis.mapping.WebScene.update)

**Comment by DavidJVitale** [comment]
Thanks for bringing this up @mschenker : When we do the public v1.5 release (It is still in beta now), we will go through all sample, guide, and API ref pages that use the WebScene and make sure they are up to date!

**Comment by DavidJVitale** [comment]
@mschenker v1.5 of the API has been released publicly: we changed the WebScene functionality a bit from the beta release, all the documentation for `arcgis.mapping.WebScene` should be updated: Please comment on this issue if you find any problems, thanks again for bring this to our attention!
