### ISSUE TITLE
Ports along the west coast.

### ISSUE THREAD

**Issue by werkwijzer** [Esri/arcgis-python-api#284]
I know this isn't exactly in the repository but.

When using the the guide to update features...
guide/04-feature-data-and-analysis/updating-feature-layer-properties.ipynb
There is a reference to a map/dataset of ports along the west coast.
It's no longer there. which makes using the guide tricky.

Could this be restored?

Thanks in advance.

**Comment by achapkowski** [comment]
@jyaistMap can we publish this data set?

**Comment by achapkowski** [comment]
Service can be found here: https://pythonapi.playground.esri.com/portal/home/item.html?id=6a8766e14d3d41cfb8fc8d4d8974f16d
CSV: https://pythonapi.playground.esri.com/portal/home/item.html?id=5a185ae26bab43f3abb12750966330c3
