### ISSUE TITLE
Offline Map Area Creation produce error

### ISSUE THREAD

**Issue by MuhammadYasirAlikhan** [Esri/arcgis-python-api#289]
I m trying to create offline map areas using python API. It's working perfectly when I run the 'create' method outside of any class. But when I include this method inside a class with exactly the same arguments it produces the following error;
 TypeError: Object of type 'set' is not JSON serializable.
This is how i m calling it:
Test_offline_item = wm.offline_areas.create(area = extent, item_properties = offline_item_properties, min_scale = 73957191, max_scale = 70)
where  offline_item_properties = {'title': title,
							'tags': ['Python', 'Automation', 'Offline'],
							'snippet': {'Area created for Offline Use'}}
and extent = {'xmin': extnt[0], 'ymin': extnt[2], 'xmax':extnt[1], 'ymax': extnt[3], 'spatialReference': {'wkid': 102100}}

**Comment by MuhammadYasirAlikhan** [comment]
This is the method inside my class which is used to call the "create" method of offline maparea manager.
	def MapArea(self, R, C, Z, wm_id, extnt):
		"Creates Map Area at provided Details"
		#new_wm = self.WebMap(R, C)
		wm_item = gis.content.get(wm_id)
		wm = WebMap(wm_item)
		title = 'Z'+str(Z)+'R'+str(R)+'C'+str(C)
		offline_item_properties = {'title': title,
							'tags': ['Python', 'Automation', 'Offline'],
							'snippet': {'Area created for Offline Use'}}
		extent = {"xmin": extnt[0], "ymin": extnt[2], "xmax":extnt[1], "ymax": extnt[3], "spatialReference": {"wkid": 102100}}
		print(extent)
		layer_size, layer_name, layer_id = [], [], []
		lst = {'area' : extent, 'item_properties' : offline_item_properties, 'min_scale' : 73957191, 'max_scale' : 70}
		Test_offline_item = wm.offline_areas.create(area = extent, item_properties = offline_item_properties, min_scale = 73957191, max_scale = 70)
		area_id = Test_offline_item.id

And here is how I m calling the above function:
area.MapArea(x, y, z, new_wm, extnt) 
where area is an instance of my class.
Below is the response output of above call:
--------------------------
TypeErrorTraceback (most recent call last)
<ipython-input-10-d046a4011d24> in <module>()
     13             layers = layerdata.loc[x,y]
     14             new_wm = area.WebMap(x, y, layers)
---> 15             maparea = area.MapArea(x, y, z, new_wm, extnt)
     16 
     17 

<ipython-input-9-6805fb49f852> in MapArea(self, R, C, Z, wm_id, extnt)
    105                 print("Arguments =", lst)
    106                 #print(argmts)
--> 107                 Test_offline_item = wm.offline_areas.create(area = extent, item_properties = offline_item_properties, min_scale = 73957191, max_scale = 70)
    108                 print("Happy")
    109                 area_id = Test_offline_item.id

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\mapping\_types.py in create(self, area, item_properties, folder, min_scale, max_scale, layers_to_ignore)
    843         from arcgis.geoprocessing._tool import Toolbox
    844         pkg_tb = Toolbox(url=self._url, gis=self._gis)
--> 845         oma_result = pkg_tb.create_map_area(self._item.id, _bookmark, _extent, output_name=output_name)
    846         # endregion
    847 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\geoprocessing\_tool.py in create_map_area(self, map_item_id, bookmark, extent, output_name)
     95         #    print(k + " => " + str(v))
     96 
---> 97         return self._execute(kwargs)
     98 
     99     code = call.__code__

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\geoprocessing\_tool.py in _execute(self, params)
    987             task_url = "{}/{}".format(self.url, task_name)
    988             submit_url = "{}/submitJob".format(task_url)
--> 989             job_info = self._con.post(submit_url, gp_params, token=self._token)
    990             job_id = job_info['jobId']
    991             try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\_impl\connection.py in post(self, path, postdata, files, ssl, compress, is_retry, use_ordered_dict, add_token, verify_cert, token, try_json, out_folder, file_name, force_bytes, add_headers)
   1086             encoded_postdata = None
   1087             if postdata:
-> 1088                 postdata = {k: jsonize_dict(v) for k, v in postdata.items()}
   1089                 encoded_postdata = urlencode(postdata)
   1090             if self._referer:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\_impl\connection.py in <dictcomp>(.0)
   1086             encoded_postdata = None
   1087             if postdata:
-> 1088                 postdata = {k: jsonize_dict(v) for k, v in postdata.items()}
   1089                 encoded_postdata = urlencode(postdata)
   1090             if self._referer:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\arcgis\_impl\connection.py in jsonize_dict(val)
    198 def jsonize_dict(val):
    199     if isinstance(val, (dict, list)):
--> 200         return json.dumps(val)
    201     else:
    202         return val

~\AppData\Local\Continuum\anaconda3\lib\json\__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

~\AppData\Local\Continuum\anaconda3\lib\json\encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~\AppData\Local\Continuum\anaconda3\lib\json\encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

~\AppData\Local\Continuum\anaconda3\lib\json\encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'set' is not JSON serializable

**Comment by achapkowski** [comment]
We believe this issues related to map area creation packages are resolved, please retest with 2.0.0.
