### ISSUE TITLE
Smart Mapping.ipynb uses non-existent library

### ISSUE THREAD

**Issue by henrymartin1** [Esri/arcgis-python-api#292]
Smart Mapping.ipynb from samples\02 Power Users & Developers 

Cell number 5 imports the lyr module:
```
import arcgis.lyr
freeway_feature_service = arcgis.lyr.FeatureService(freeway_item.url, gis)
```
Which results in the following error:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-5-1974c4b5e829> in <module>()
> ----> 1 import arcgis.lyr
>       2 freeway_feature_service = arcgis.lyr.FeatureService(freeway_item.url, gis)
> 
> ModuleNotFoundError: No module named 'arcgis.lyr'

arcgis.lyr seems not to exist anymore... See the link: https://developers.arcgis.com/python/guide/release-notes/

**Comment by AtmaMani** [comment]
@henrymartin1 this has been fixed. Thanks for reporting

**Comment by Sudeepa14** [comment]
@AtmaMani Hi, Still there are imports in the sample files given. Can you mention a fix?

**Comment by AtmaMani** [comment]
@Sudeepa14 could you point me to the location where you still find it?

**Comment by Sudeepa14** [comment]
Sorry I think That was found in a different different example. (Not from the samples.)
