### ISSUE TITLE
add_layer ability to copy symbology configuration from layer

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#294]
I recently made this as an ArcGIS Idea and I figured I'd ask here if it's already possible or if it will ever be. Link to ArcGIS Idea: https://community.esri.com/ideas/15457-addlayer-ability-to-copy-symbology-configuration-from-layer 

Essentially trying to use arcgis.mapping add_layer to completely copy a layer from 1 webmap and place it in another. I can do everything but symbology because it is pulling the symbology from the REST and not the copied layer.

**Comment by achapkowski** [comment]
You can copy symbology from layers using Spatially Enabled DataFrames at ArcGIS API for Python v1.8 and beyond.  

```python
sdf = gis.content.get("<some item id>").layers[0].query(as_df=True)
print(sdf.spatial.renderer) # should match the renderer of the Feature Layer.
```
