### ISSUE TITLE
conda create -n newenvname

### ISSUE THREAD

**Issue by VidyaSamadi** [Esri/arcgis-python-api#299]
Guys; Jupyter Notebook throwing below error. I did create a new environment in conda and install the new package, but didnot help. How to fix it?

File "<ipython-input-2-26e935956df4>", line 43
    conda create -n newenvname python=3.6
               ^
SyntaxError: invalid syntax

**Comment by scw** [comment]
@samadi57 if you're running this from within a notebook, you'll need to prefix the command with an exclamation point:
    
    !conda create -n newenvname python=3.6

But probably it's best to run this outside of the notebook if you have access.
