### ISSUE TITLE
ValueError: The truth value of a SpatialDataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/arcgis-python-api#305]
Many times when I save a spatial dataframe to a featureclass I get this error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\a\lib\site-packages\pandas\core\generic.py in __nonzero__(self)
   1574         raise ValueError("The truth value of a {0} is ambiguous. "
   1575                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
-> 1576                          .format(self.__class__.__name__))
   1577 
   1578     __bool__ = __nonzero__

ValueError: The truth value of a SpatialDataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
---------------------------------------------------------------------------
In this specific case I had 392,953 features in my spatial dataframe and I got the error 3 times when I used this code:
sdf.to_featureclass(FGDB, fc, overwrite=True, skip_invalid=True)

It still saved all features to the new featureclass with valid geometries so I'm not sure why this is happening.

**Comment by achapkowski** [comment]
We are looking into this.

**Comment by achapkowski** [comment]
This issue is resolved with the release of ArcGIS Pro 2.5.
