### ISSUE TITLE
Example that demonstrates item.usage, please?

### ISSUE THREAD

**Issue by BC89** [Esri/arcgis-python-api#308]
At 1.5 it was stated that a usage property was added on Item class to inspect individual statistics but i can't get this ti work for the life of me. An example would be great help.

**Comment by achapkowski** [comment]
You can get the help for the method by doing the following:

```

from arcgis.gis import Item
help(Item.usage)

```

From Jupyter Notebook: `item.usage?`

Usage Example:

```
gis = GIS(username='AGOL ACCOUNT', password='****')
item = gis.content.get("SOME ITEM ID")
df = item.usage('30D', True) # Item Stats as a Pandas' DataFrame for the last 30 days
raw_data = item.usage('30D', False) # Item Stats as dictionary for the last 30 days

```

Hope this helps.

**Comment by BC89** [comment]
thanks for the reply. still not having any luck, however.


import sys
import matplotlib
import numpy
import scipy
import arcgis
import pandas
from arcgis.gis import Item
from arcgis.gis import GIS

print(sys.version)
print(matplotlib.__version__)
print(numpy.__version__)
print(scipy.__version__)


gis = GIS("real", "real", "real")

#help(Item)

item = gis.content.get('dc706efee1cf4e8dabddf95b21057aac')

print (item)

df = item.usage('30D', True)





<Item title:"Deer Kills and Bear Encounters 2014-2017-backupBeforeFinal" type:Web Map owner:lensminger@CENTRAL>




---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py in __getattr__(self, name)
   5024         try:
-> 5025             return dict.__getitem__(self, name)
   5026         except:

KeyError: 'usage'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-21-6ba451bd47d0> in <module>()
----> 1 df = item.usage('30D', True)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py in __getattr__(self, name)
   5025             return dict.__getitem__(self, name)
   5026         except:
-> 5027             raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, name))
   5028
   5029     def __getitem__(self, k): # support item attributes as dictionary keys on this object

AttributeError: 'Item' object has no attribute 'usage'

________________________________

**Comment by achapkowski** [comment]
Are you using AGOL?

**Comment by achapkowski** [comment]
This works on AGOL only at this time.

**Comment by BC89** [comment]
Funny, not sure I saw that anywhere in the docs.
