### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by PerAkeMattias** [Esri/arcgis-python-api#309]
With the new 1.5.0 and JupyterLab I can now finally visually my local Portal content- however, not until I had to use [this ](https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present)workaround (chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security).  Do you have any suggestions of any setting I can pass along to the Portal Admin for them to change on the server so I don’t have to use the workaround?

Thanks.

**Comment by DavidJVitale** [comment]
Thanks for bringing this up @PerAkeMattias , happy to try to help you debug: A few things:
- When did you start seeing this behavior? Was it around today or did you see it a week or so ago?
- Can you run Chrome without the `--disable-web-security` flag, try to draw the map widget, and then copy and paste all your Browser Console content onto this issue?

**Comment by PerAkeMattias** [comment]
Well, today was the first time I tried to visualize something using the local Portal with 1.5.0 so I have no idea if the error was present prior to today.

The log I attached is from when I logged onto the portal until I tried to draw a basic map
[localhost-1538422487466.log](https://github.com/Esri/arcgis-python-api/files/2435369/localhost-1538422487466.log)

![simplemap](https://user-images.githubusercontent.com/7396398/46311761-d2f07c00-c588-11e8-98d6-ca715ce9624d.PNG)

**Comment by DavidJVitale** [comment]
Thanks for the info @PerAkeMattias . I am seeing a similar error on some machines, but am having a hard time to get a reproducible case. To my knowledge, the JavaScript API should do all the CORs configuration needed to where this error shouldn't appear: i.e., you shouldn't need to configure your portal in any special way. I will be looking into it and will update you on my progress. You might want to try these workarounds in the mean time:

- Set up your notebook server to serve over https
- Try clearing your cache and/or opening in an incognito mode
- Try a different browser
- Try updating your browser and launching your browser in a 'Safe Mode' (i.e. no addons)

**Comment by PerAkeMattias** [comment]
I don’t think this is related to my problem- only because when I looked at our Portal there is no restrictions.

On Oct 1, 2018, at 8:26 PM, Rohit Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


http://enterprise.arcgis.com/en/portal/latest/administer/windows/restrict-cross-domain-requests-to-your-portal.htm might be related to this.

**Comment by PerAkeMattias** [comment]
David,

So I tried all your suggestions except a different browser (Chrome is the only one we have available) with the same problem.

For now, the workaround I found is manageable.

Thanks.

On Oct 1, 2018, at 6:52 PM, David Vitale <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the info @PerAkeMattias<https://github.com/PerAkeMattias> . I am seeing a similar error on some machines, but am having a hard time to get a reproducible case. To my knowledge, the JavaScript API should do all the CORs configuration needed to where this error shouldn't appear: i.e., you shouldn't need to configure your portal in any special way. I will be looking into it and will update you on my progress. You might want to try these workarounds in the mean time:

  *   Set up your notebook server to serve over https
  *   Try clearing your cache and/or opening in an incognito mode
  *   Try a different browser
  *   Try updating your browser and launching your browser in a 'Safe Mode' (i.e. no addons)

**Comment by irisevenstar** [comment]
I'm able to duplicate this issue myself in version 1.5.2. I'm using an IWA Portal and getting cross domain issues in Chrome. When I run with --disable-web-security, I can display maps, but not otherwise. I have not been able to try updating my local notebook server to run over https. Do you have any good documentation on doing this?

**Comment by DavidJVitale** [comment]
@irisevenstar This page is useful information for how to configure it from a Jupyter standpoint:

https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication

You basically need to generate the certs (either self-sign or get one from a source like `Let's Encrypt`), then configure Jupyter to use those certs files and server over https. Let me know if you run into issues, happy to help!

**Comment by PerAkeMattias** [comment]
I don't see this problem in newer releases.

**Comment by runneals** [comment]
This issue still persists in 10.8.1. I'm trying to hit Portal Health Check (/portal/portaladmin/healthCheck) using a simple fetch and it's not returning either the Access-Control-Allow-Origin or Access-Control-Allow-Credentials like ArcGIS Server does. I can't set this at the IIS application level, as it's already set within Portal and will break applications. Likewise, what do I do when ArcGIS Server or Portal are down and their rules don't get applied? Why can't this just be set at the IIS level so it's always applied whether or not the server or portal application server is up or down.
