### ISSUE TITLE
User Provider Inconsistency

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#310]
Starting a few weeks ago one of my scheduled scripts stopped working and it was not obvious what was happening right away. Turns out something changed with how a user object sees its provider detail. Below I describe the inconsistency. I'm wondering if this was a mistake or intentional. If it is intentional then I will have to start using the get() function for every thing instead of just search().

When I use a user object from a search() and try to look at provider it shows all my users as "None". (See code example below)

AGOusers = ago_connection.users.search(query='', max_users=1000)
for AUser in AGOusers:
         print(AUser.provider)

When I use the get() function instead of search for a user object the provider shows the proper provider as "Enterprise". ( See code example below)

AGOusers = ago_connection.users.search(query='', max_users=1000)
for AUser in AGOusers:
      AUser_get = api.UserManager(ago).get(AUser.username)
      print(AUser_get.provider)

**Comment by BrettFrahm** [comment]
That is correct. This was with version 1.4.1.

**Comment by achapkowski** [comment]
@BrettFrahm can you update to v1.5 and see if the issue still exists?

**Comment by BrettFrahm** [comment]
Hello achapkowski,

Sorry for the delay. I recently upgraded to the new version of ArcGIS Pro, which updated my python API to v1.5. Search without the query parameter now works, but now I have another problem. On v1.5, the search() function does not work at all if I included the query parameter with query=''. I need my scripts using python api to be sustainable for me and my team, which is why I'm taking the time bring up this issue. 

See below for the new error I'm experiencing (User does not exist or is inaccessible.)

Code:
--------
try:
    AGOuser = ago_connection.users.search(query='', max_users=1)
    print(AGOuser)
except:
    AGOuser = ago_connection.users.search(max_users=1)
    print(AGOuser)

Results:
---------
User does not exist or is inaccessible.
[<User username:107378@trpd>]

**Comment by iceaxe** [comment]
FYI, I was using GIS.users.search(query='query_string') and was also getting "User does not exist or is inaccessible." with arcgis v1.5.1 (which came with Pro v2.3.2).  I upgraded my arcgis module to v1.6.1 and it looks like it's fixed there.
