### ISSUE TITLE
Map Legend

### ISSUE THREAD

**Issue by simoxu001** [Esri/arcgis-python-api#316]
I've raised this in [Geonet](https://community.esri.com/ideas/15551-map-legend-for-map-widget-in-arcgis-api-for-python), but it hasn't got much attention from other peers. I feel this is a very important issue the developers need to be aware of.

Like charts built using python matplotlib library have legend, maps built using ArcGIS Python API should have legend too. 

After all,  what's the point of using sophisticated ArcGIS map rendering technology when the audience can not understand what the symbols and colors mean? ---- A map showing data analysis result with colors and symbols is nothing more than a meaningless noisy picture without a legend or map key on the side.

Currently I am working around this by using matplotlib to built make-shift legend, but it's not very convenient and very limited. it will be nice to see a built-in legend in the WebMap widget.

**Comment by achapkowski** [comment]
@simoxu001, good news, it is something we are already identified and are actively working on for a future release.

**Comment by simoxu001** [comment]
@achapkowski Thanks, Good to know, and looking forward to it.

**Comment by DavidJVitale** [comment]
The newest version of the Python API contains the `mapview.legend` boolean to toggle the legend on and off. See [here](https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.widgets.html#arcgis.widgets.MapView.legend) for more info. 

Closing.
