### ISSUE TITLE
enhancement: add changelog

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-python-api#317]
a short synopsis of what bugs have been fixed and what new features have been added in each release would be **super** useful 🍰!

bonus points for adhering to https://keepachangelog.com/en/1.0.0/

**Comment by achapkowski** [comment]
We provide release notes.

https://developers.arcgis.com/python/guide/release-notes/

**Comment by jgravois** [comment]
wow. thanks for pointing me to that!

i expected to find it under `Getting Started`, but i _swear_ i looked in `API Overview` too.
