### ISSUE TITLE
Is this an issue for Spatially Enabled DataFrame (SEDF)?

### ISSUE THREAD

**Issue by simoxu001** [Esri/arcgis-python-api#319]
I understand SEDF is using  a [Registering Custom Accessors](https://pandas.pydata.org/pandas-docs/stable/extending.html#registering-custom-accessors) approach to extend the Pandas dataframe. This will leave all the non-spatial functions (e.g. merge, join, concatenate and other popular function) for Pandas class itself to handle. The problem is, the returned objects of those standard DataFrame functions are Pandas DataFrames rather than SEDF despite the spatial information are intact in the DataFrame. So you'll have to manually spatial-enable the resultant object every time before you want to use any SEDF specific functions. It's not hard to do though. Currently, I simply use set_geometry() to specify the column(s) holding the spatial information.

I know this is not a big issue if it is one at all. but it is a nuisance making the coding experience not as seamless as it should be in object-oriented programming. I have a feel that this is something to do with the Accessor approach which seems very different from sub-classing.

In contrast to SEDF, the deprecated SpatialDataFrame, which is a subclass of the Pandas DataFrame class, will always return a SpatialDataFrame (arcgis.features._data.geodataset.geodataframe.SpatialDataFrame) after using its merge and join methods. (I am sure other functions will behave the same).

Any comments?

**Comment by achapkowski** [comment]
The internals of the SeDF call `df.spatial.name`, which if the `set_geometry()` has not been called will assume `SHAPE` is the spatial column and set it for the user to account for these situations.

**Comment by simoxu001** [comment]
Ok, when I call a function on SeDF using df.spatial.fun(), it would be good if SeDF can figure out the geometry column (SHAPE), but my experience is different. I have to manually call set_geometry() to make it happen.
Think about the scenario:  You are joining SeDF to another DataFrame, you would expect it to return an SeDF keeping all the spatial information, but the resultant DataFrame is not spatially enabled. This will leave you puzzled at the beginning although you can work around it once you understand the situation.
 
Here are some codes to support my point:
![image](https://user-images.githubusercontent.com/1132496/47538083-ffda4980-d910-11e8-92ee-8cf22edfd6a9.png)

**Comment by achapkowski** [comment]
@simoxu001 

I added additional checks based on your feedback.  This will be included in the November release.

```
sdf = (
    pd
    .DataFrame
    .spatial
    .from_featureclass(os.path.join(gdb,"city"))
    .head()
    .copy()
) # Copy First 5 Rows
data = [[1,'a'],
        [2,'b'],
        [3,'c'],
        [4,'d'],
        [5,'e']]
df = pd.DataFrame(data=data, 
                  columns=["OBJECTID", 
                                   "FAKECITYCLASS"])
res = pd.merge(sdf,df)
print(res.spatial.bbox)

```

Result:

```
{'rings': [[[-12609547.622000001, 4466288.306199998], [-12609547.622000001, 4470640.231600001], [-12595519.862399999, 4470640.231600001], [-12595519.862399999, 4466288.306199998], [-12609547.622000001, 4466288.306199998]]], 'spatialReference': {'wkid': 102100}}
```

A pd.merge creates a new dataframe, so it makes sense that `set_geometry` needs to be called.  In order to assist you and other users, I now also check for the name `SHAPE` in any casing.

**Comment by simoxu001** [comment]
@achapkowski Thank you Andrew. I believe this will make the user experience better, particularly for ArcGIS users without comprehensive Pandas background knowledge.
