### ISSUE TITLE
list index out of range error when using Content_Manager.import_data

### ISSUE THREAD

**Issue by dkoerner** [Esri/arcgis-python-api#322]
I try to publish a featurelayer from a `SpatialDataFrame` using `GIS.content.import_data`. I get the following error:
```
~\AppData\Local\Continuum\anaconda3\lib\site-packages\shapefile.py in record(self, *recordList, **recordDict)
   1067         fieldCount = len(self.fields)
   1068         # Compensate for deletion flag
-> 1069         if self.fields[0][0].startswith("Deletion"): fieldCount -= 1
   1070         if recordList:
   1071             record = [recordList[i] for i in range(fieldCount)]

IndexError: list index out of range
```

The offending line (1069) assumes the presence of at least one field which is not the case in this simple example. Here is the code which reproduces the problem:
```
import os
import json
from IPython.display import display
from arcgis.gis import GIS
from arcgis.geometry import Point, Geometry
from arcgis.features import SpatialDataFrame

# Create an anonymous connection to ArcGIS Online  =========================
gis = GIS()

# create geometry ================================================================
geo = [Point({"x" : -118.15, "y" : 33.80, "spatialReference" : {"wkid" : 4326}})]

# create spatialdataframe ========================================================
df = SpatialDataFrame(geometry=geo);

# create and publish feature layer from spatialdatafrme ======================================
gis.content.import_data(df)
```

NB: I am aware that I dont have publishing rights on GIS()

**Comment by dkoerner** [comment]
Switching to the spatially extended dataframe:
```
# create geometry ========================================================
geo = [Point({"x" : -118.15, "y" : 33.80, "spatialReference" : {"wkid" : 4326}})]

# create dataFrame ===================================
d = {'col1':["abc"], 'col2':[123], 'geometry' : geo }
df = pd.DataFrame(d)

# spatially enable dataframe by specifying the columen which holds the spatial information
# (will interally add a SHAPE column)
df.spatial.set_geometry( "geometry" )

# publish dataframe as featurelayer =====================================
test = df.spatial.to_featurelayer("publishing test", gis)
```

When calling `to_featurelayer` I get some errors in `...\anaconda3\Lib\site-packages\arcgis\features\geo\_io\fileops.py`. In line 611 the function call to `shapefile.Writer` seems to be wrong. Maybe I am using a different version of `pyshp`? The error is fixed by changing the function call accordingly.

Further the index received by `df[c].first_valid_index()` in line 616 can be `None` which produces the following error in line 617:
```
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

After fixing this the code on these lines looks like this:
```
        shpfile = shapefile.Writer(out_fc, GEOMTYPELOOKUP[geom_type])
        shpfile.autoBalance = 1
        dfields = []
        cfields = []
        for c in df.columns:
            idx = df[c].first_valid_index()
            if not idx is None and idx > -1:
```

This makes it work! 👍

**Comment by dkoerner** [comment]
I tried adding a `spatiallyEnabled` dataframe with different spatialReferences like this:
```
geo_wkid4326 = [Point({"x": -118.5, "y": 33.80, "spatialReference":{"wkid":4326}})]
geo_wkid102100 = [Point({"x": -118.5, "y": 33.80, "spatialReference":{"wkid":102100}})]

core_df_wkid4326 = pd.DataFrame(geo_wkid4326)
fc_wkid4326 = gis.content.import_data(core_df_wkid4326)

core_df_wkid102100 = pd.DataFrame(geo_wkid102100)
fc_wkid102100 = gis.content.import_data(core_df_wkid102100)

m = gis.map()
m.add_layer(fc_wkid4326)
m.add_layer(fc_wkid102100)
```

The two point features appear at the same location on the map. Is this to be expected? I would have thought that different spatialReferences for the same `x`/`y` coordinates produce different locations on the map.

**Comment by achapkowski** [comment]
@dkoerner you are passing a list of dictionaries.  When you do that in pandas, it will create an column for each key.  This will get you your results:

```python
core_df_wkid4326 = pd.DataFrame([], columns=['SHAPE', "OID"])
core_df_wkid4326['SHAPE'] = geo_wkid4326
core_df_wkid4326['OID'] = [1]
```

**Comment by dkoerner** [comment]
Thanks for getting back to me on this. So this is what I try:
```
geo_wkid4326 = [Point({"x": -118.5, "y": 33.80, "spatialReference":{"wkid":4326}})]
geo_wkid102100 = [Point({"x": -118.5, "y": 33.80, "spatialReference":{"wkid":102100}})]

core_df_wkid4326 = pd.DataFrame([], columns=['SHAPE', "OID"])
core_df_wkid4326['SHAPE'] = geo_wkid4326
core_df_wkid4326['OID'] = [1]
fc_wkid4326 = gis.content.import_data(core_df_wkid4326)

core_df_wkid102100 = pd.DataFrame([], columns=['SHAPE', "OID"])
core_df_wkid102100['SHAPE'] = geo_wkid102100
core_df_wkid102100['OID'] = [2]
fc_wkid102100 = gis.content.import_data(core_df_wkid102100)
```

It produces points at the same location on the map which I would not expect due to the use of two different spatial reference frames.

**Comment by achapkowski** [comment]
I am able to get two separate points on the map.

![image](https://user-images.githubusercontent.com/5131271/54375012-9c9a4b00-4656-11e9-9bde-f21b96bd82ec.png)

**Comment by dkoerner** [comment]
Hm. I am using arcgis for python verison `1.6.0`. Could that be related? 

One layer has a negative id. Could that indicate a problem?
![](https://i.gyazo.com/10c1c1daf31d5fe5955362d054e0c03c.png)

**Comment by achapkowski** [comment]
@dkoerner I still can't reproduce your issue:

![image](https://user-images.githubusercontent.com/5131271/54377452-82af3700-465b-11e9-941f-667d0b0955a7.png)

I used the exact some code as you.  Can you dump your environment to a text file?

```
     conda env create -f environment.yml
```

**Comment by dkoerner** [comment]
I ran `conda env export > environment.yml`:
[Uploading environment.zip…]()

As I mentioned above, I had to fix some issue with the call to `shapefile.Writer()` constructor in `...\anaconda3\Lib\site-packages\arcgis\features\geo\_io\fileops.py` (line 611) which may hint at some issues with using the wrong pyshape library or something.

**Comment by achapkowski** [comment]
Try doing the following:

```
conda install pyshp=1.2.11
```

**Comment by dkoerner** [comment]
That didnt solve the problem. I checked the temporary shape files which were created by `import_data` and they have the correct spatialReferences (I see the two points at the correct locations when opening both shapefiles in ArcGISPro). So the problem seems to not be with pyshp but somewhere during publishing into FL.

**Comment by dkoerner** [comment]
I think I found the problem. The problematic code is in `fileops.py` at the bottom:
```
            url = 'http://epsg.io/{}.esriwkt'.format(wkid)

            opener = request.build_opener()
            opener.addheaders = [('User-Agent', 'geosaurus')]
            resp = opener.open(url)

            wkt = resp.read().decode('utf-8')
            if len(wkt) > 0:
                prj = open(prj_filename, "w")
                prj.write(wkt)
                prj.close()
```

It turns out the url is empty for `wkid=102100` and it is not writing the`.prj` file.
http://epsg.io/4326.esriwkt
http://epsg.io/102100.esriwkt

**Comment by dkoerner** [comment]
This fixes the problem:
```
            url = 'http://epsg.io/{}.esriwkt'.format(wkid)

            opener = request.build_opener()
            opener.addheaders = [('User-Agent', 'geosaurus')]
            resp = opener.open(url)

            wkt = resp.read().decode('utf-8')

            if wkid == 102100:
                wkt = 'PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mercator_Auxiliary_Sphere"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",{Central_Meridian}],PARAMETER["Standard_Parallel_1",0.0],PARAMETER["Auxiliary_Sphere_Type",0.0],UNIT["Meter",1.0]]'

            if len(wkt) > 0:
                prj = open(prj_filename, "w")
                prj.write(wkt)
                prj.close()
```

**Comment by dkoerner** [comment]
-Im surprised it worked for you. Why is http://epsg.io/102100.esriwkt empty? Would be nice to get this fixed.
-Also: I think it there needs to be a check in the code that the pyshp version is 1.2.11. After a clean install of conda and arcgis my environment was configured to use pyshp 2.1 which produced errors when using the code

**Comment by achapkowski** [comment]
Thanks for the heads up about this wkid.

**Comment by dkoerner** [comment]
Thanks for helping me out. Much appreciated! 👍
