### ISSUE TITLE
Point.buffer(1) returns None

### ISSUE THREAD

**Issue by jmcbroom** [Esri/arcgis-python-api#330]
Here's my code, I'm on 1.5.1:

Trying to do a point-in-polygon on an AGO feature layer.

```
from arcgis.features import FeatureLayer
from arcgis.geometry import Point, filters

l = FeatureLayer("https://services2.arcgis.com/qvkbeam7Wirps6zC/arcgis/rest/services/DEGC_Bounds/FeatureServer/1")
p = Point({"x":-83.01642613, "y":42.33625507})

l.query(returnGeometry=False, outFields='*', geometry_filter=filters.intersects(p, sr=4326))
```

returns `'geometryType' parameter is invalid`

upon further inspection,

```
p = Point({"x":-83.01642613, "y":42.33625507})
print(p.buffer(1))
```

returns None which causes a problem for arcgis/geometry/_types.py line 357

**Comment by achapkowski** [comment]
@jmcbroom Thanks for reporting this.  In regards to the None part of your issue, do you have arcpy installed?

**Comment by jmcbroom** [comment]
Nope, I am running anaconda 3.6, no arcpy.

**Comment by achapkowski** [comment]
do you have any geometry engine installed?

**Comment by DanCranford** [comment]
Hey all - i just ran into this after updating too.  I can create an intersect filter (arcgis.geometry.filters.intersect()) using a feature.geometry and an input spatial reference, but I'm getting that same error.  I was able to fix it by editing the geometry type of the filter.  This is what my filter looked like 
{'geometry': {'x': 629569.1300565653, 'y': 4274855.026780627},
 'geometryType': 'esriGeometrypoint',
 'inSR': {'latestWkid': 26910, 'wkid': 26910},
 'spatialRel': 'esriSpatialRelIntersects'}

If you modify the filter change the 'geometryType' parameter to 'esriGeometryPoint' with a capital P, it functions normally.  This is new behavior after the update though.

**Comment by jmcbroom** [comment]
I'm not quite sure if I have a geometry engine installed. I know I have `geos`.

@DanCranford can you paste code? I don't understand whether that should be a string or a Python dictionary. Neither seem to work for me.

**Comment by DanCranford** [comment]
Hey - Looks about right.  so your point object there is a geometry filter dictionary.  I just added a few lines of code to fix the problem after i created my geometry filter.

`    geomFilter = arcgis.geometry.filters.intersects(feature.geometry,sr)
    if geomFilter['geometryType']=='esriGeometrypoint':
        geomFilter['geometryType']='esriGeometryPoint'`

I think it's an issue with the filter creation.  I haven't checked any other geometry types though.
