### ISSUE TITLE
Server.services.list fails if serviceName contains non ascii characters.

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#333]
List services fails if one or more serviceName contains international characters like ÆØÅ.
Bug found in version 1.5.2 and older.

```python
from arcgis import GIS
from arcgis.gis import server

_gis = GIS(profile=....)
_server = server.Server("https://someurl/server/admin", _gis)

_services = _server.services.list("Hosted")
print(len(_services)
```

Quoting serviceName at line 210 in "\\Lib\\site-packages\\arcgis\\gis\\server\\admin\\_services.py" fixes the issue.

Add import at line 9:
`from six.moves.urllib_parse import quote`

And quote at line 210 (211 after added import):
`u_url = self._currentURL + "/%s.%s" % (quote(s['serviceName']), s['type'])`

**Comment by achapkowski** [comment]
This should be resolved in v1.8.x of the ArcGIS API for Python.  Thank you for reporting.
