### ISSUE TITLE
Improper formatting in geometry.project documentation

### ISSUE THREAD

**Issue by cmosnick** [Esri/arcgis-python-api#334]
**Current behavior:**
` in_sr` parameter is not on new line and highlighted like other parameters

**Steps to reproduce:**
Go to https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html#project and look at `in_sr` parameter

**Expected or desired behavior:**
` in_sr` parameter should be on a new line and highlighted like the other parameters

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Screenshot:**

![bug](https://user-images.githubusercontent.com/6201681/49884368-5258c200-fdfa-11e8-9bcf-ca4dedc2dae9.PNG)

I am unfamiliar with the build process and the source files, but I can see that the issue is on [this line](https://github.com/Esri/arcgis-python-api/blob/master/apidoc/arcgis.geometry.html#L3234) after the build.

**Comment by nanaeaubry** [comment]
This has been addressed and can now be seen : https://developers.arcgis.com/python/api-reference/arcgis.geometry.html#project
