### ISSUE TITLE
API for Python 1.5.1 & 1.5.2: arcgis.geometry.Polygon.is_valid() method for polygons does not work

### ISSUE THREAD

**Issue by lukasbug** [Esri/arcgis-python-api#335]
Hello,
we use ArcGIS API for Python in a project and encountered the following problem:

In ArcGIS API for Python 1.5.1 the boolean type property "is_valid" of geometries of type Polygon was removed and replaced by a method. This method is_valid() does not work like the boolean property in the previous versions. It throws an error for valid Polygon geometries as shown below:
![image](https://user-images.githubusercontent.com/45874502/50005935-54fb1900-ffac-11e8-8cf2-ed59e7530505.png)

In ArcGIS API for Python 1.5.0 the boolean type attribute worked well:
![image](https://user-images.githubusercontent.com/45874502/50006018-a4414980-ffac-11e8-91a3-2b7f93f8deb2.png)

Do you have an idea how to work around this problem ?

Best regards,
Lukas Bug
Student assistant at Esri Deutschland

**Comment by lukasbug** [comment]
I prepared two jupyter notebooks to be able to reproduce this issue. You will find them in the following zip file (Unfortunately Jupyter Notebooks are not supported as a file type on Git):

[is_valid_issue.zip](https://github.com/Esri/arcgis-python-api/files/2680245/is_valid_issue.zip)

**Comment by lukasbug** [comment]
Dokumentation mentions it in the GeoSeriesAccessor section and return type should be boolean True or False:

https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.features.toc.html?highlight=is_valid#arcgis.features.GeoSeriesAccessor.is_valid

**Comment by achapkowski** [comment]
@lukasbug I'll take a look today.

**Comment by lukasbug** [comment]
@achapkowski Have you any news on this issue ?

**Comment by bixb0012** [comment]
@achapkowski , look at lines 22, 64, 79, and 80 in `geometry/_types.py`.  Someone wrote bad type checks involving variables that are never defined in the module:  `list_types`, `number_type` .

**Comment by achapkowski** [comment]
It will be fixed in the next release.
