### ISSUE TITLE
Module arcgis-map-ipywidget, semver range 1.5.2 is not registered as a widget module

### ISSUE THREAD

**Issue by 57ar7up** [Esri/arcgis-python-api#336]
Jupyter Notebook / Lab 0.34.9

```
from arcgis.gis import GIS
gis = GIS()
map = gis.map()
```

**Comment by DavidJVitale** [comment]
Hi @57ar7up , are you using Jupyter Lab? Can you run this command for me and paste the output?

`jupyter labextension list`

JupyterLab functions a bit differently than jupyter notebook, you must manually install the `arcgis-map-ipywidget` extension separately, and you must make sure that your widget extension version is the __exact__ same as the python API version. [This page](https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/) should have more information

**Comment by 57ar7up** [comment]
Thanks, suspected I missed something, now displays map

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install arcgis-map-ipywidget
```
