### ISSUE TITLE
add 'num' parameter to item.dependent_upon()

### ISSUE THREAD

**Issue by maartentromp** [Esri/arcgis-python-api#337]
item.dependent_upon() returns a maximum of 10 dependent items. The REST API has the parameter 'num' to get more results. Please implement the option to get more than 10 dependent items.
example REST request:
<servername>portal/sharing/content/items/89473a1awegg40b2af939agagb09/dependencies?f=pjson&num=10000

Sample request:
item.dependent_upon(num=1000)

**Comment by achapkowski** [comment]
Can you please post a fully reproducible code to show your issue?  Is this on ArcGIS Online or Portal?

**Comment by maartentromp** [comment]
This is a request for an extra parameter currently does not exist. reproducible code is not available. I will add a Pull request.

**Comment by daraobeirne** [comment]
Has this been addressed? I'm running into a situation where I pass a web map item to dependent_upon() and it only returns the first ten layers:

 for item in folder_items:
            if item.type == "Web Map" and item.title == "OneMapWebMap":
                print(item.title)
                print(item.dependent_upon())

returns

{'total': 37, 'start': 1, 'num': 10, 'nextStart': 11, 'list': [{'dependencyType': 'url', ........ 

Any parameters available that aren't in the docs?


https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html?highlight=dependent_upon#arcgis.gis.Item.dependent_upon

**Comment by achapkowski** [comment]
is this on AGOL or Portal?  What version of Portal if portal?

**Comment by daraobeirne** [comment]
This is on Portal 10.6

**Comment by maartentromp** [comment]
My temporary quickfix fix was to change some python code in a **!!Clone!!** of the API.
Default returned items is 10, if you want more you can then use the optional 'num' parameter.

```
## in ...\arcgispro-py3-clone\Lib\site-packages\arcgis\gis\__init__.py change existing dependent_to(self) and dependent_upon(self):
    def dependent_to(self,num=10):
        """ Returns items, urls, etc that are dependent to this item. This capability (item dependencies)
        is not yet available on ArcGIS Online. Currently it is available only with an ArcGIS Enterprise."""
        return self._portal.get_item_dependents_to(self.itemid,num)

    def dependent_upon(self,num=10):
        """ Returns items, urls, etc that are dependent to this item. This capability (item dependencies)
        is not yet available on ArcGIS Online. Currently it is available only with an ArcGIS Enterprise."""
        return self._portal.get_item_dependencies(self.itemid,num)

```

```
## in ...\arcgispro-py3-clone\Lib\site-packages\arcgis\_impl\portalpy.py replace get_item_dependents_to(self,itemid) and get_item_dependencies(self,itemid)  to:
    def get_item_dependencies(self, itemid,num=10):
        postdata = self._postdata()
        postdata['num'] = num
        return self.con.post('content/items/' + itemid + '/dependencies', postdata)

    def get_item_dependents_to(self, itemid,num=10):
        postdata = self._postdata()
        postdata['num'] = num
        return self.con.post('content/items/' + itemid + '/dependencies/listDependentsTo', postdata)
```
Regards, Maarten

**Comment by maartentromp** [comment]
Good to hear @magr665! Unfortunately this important num-parameter is still not in the latest release of the ArcGIS Python API.

**Comment by maartentromp** [comment]
In the latest version this is unfortunately still not fixed. Every time I have to change the above code to get valid results of e.g. the # of services in a webmap.

**Comment by laurenskusse** [comment]
Hope this gets fixed soon, because now I can just get a maximum of 10 services used in a WebMap. 
But why not add the 'start' parameter to item.dependent_upon() ? That way I can use a loop until nextStart = -1. And every loop gives me the next 10 results when I increase the 'start' parameter by 10 every loop.  
The 'start' parameter is used in other places in the api, e.g. advanced_search().
