### ISSUE TITLE
User search is terribly slow

### ISSUE THREAD

**Issue by guus-stedin** [Esri/arcgis-python-api#338]
Ever since the release of 1.5.0 the search action of users on our Enterprise 10.6.1 (using a 'profile' based signin with an internal user, the users typically are SAML) is terribly slow. We currently have roughly 1050 users.

A line such as:
```python
agssite = GIS(profile="gis-prod")
print(agssite.properties.user.username + " on " + agssite.properties.name + " " + agssite.properties.platform)
gebruikerslijst = agssite.users.search(query='!esri', max_users=15000)
```
used to take mere seconds (if even...), now takes upwards of five minutes, breaking several of our 'poll and forget' scripts; eg: relating to automatically adding new users depending on their domain to appropriate groups.

**Comment by achapkowski** [comment]
@guus-stedin can you please try updating to 1.5.2 and re-running your code?

**Comment by guus-stedin** [comment]
Hello @achapkowski ; we're already running 1.5.2:
Requirement already satisfied: arcgis in python\envs\arcgispro-py3\lib\site-packages (1.5.2.post1)

**Comment by achapkowski** [comment]
@guus-stedin we added an `advanced_search` method which greatly improved speed and performance over the simple search.  Please check that out.
https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.ContentManager.advanced_search
