### ISSUE TITLE
Documentation for geometry.filters() is confusing

### ISSUE THREAD

**Issue by gBushong** [Esri/arcgis-python-api#341]
The geometry.filters documentation is confusing because it does not show that for each function on the page (intersects, contains, crosses, etc.), the first argument should be geometry [ex: filters.intersects(geometry, sr=None)]. Right now it just shows that the only argument to each function is the spatial reference [ex. filters.intersects(sr=None)]. 

My guess is that there's some formatting code somewhere that translates the function's arguments from the actual api code and doesn't show the first argument because it is usually self. Not sure if that's what's actually going on but it would be nice for users if these sections could be clarified!

**Comment by nanaeaubry** [comment]
The documentation will be edited and reflected in 2.0.1, thank  you for bringing this up
