### ISSUE TITLE
Service Manifest

### ISSUE THREAD

**Issue by gaj995** [Esri/arcgis-python-api#342]
Hi, 

Is there a way to access service manifest? 

I had no luck in finding a method. So I tried to do the following:

for folder in folders: 
    services = server1.services.list(folder=folder)
    for service in services:
         manifest_URL =  (service.url+"iteminfo/manifest/manifest.xml")
         response = requests.get(manifest_URL)
         print (response.text)

It goes to the login page for server. Any idea on dealing with this token based on GIS connection? 

Thanks

**Comment by achapkowski** [comment]
Assuming you have administrator access you can get the file information as such:  

```python
gis = GIS(profile='admin_login')
for server in gis.admin.servers.list():
    print(server)
   
    services = server.services
    service = services.list()[0]
    print(service._service_manifest())
    break
```

XML was dropped, and only JSON is supported now.

**Comment by gaj995** [comment]
That worked like a charm!

Thanks Andrew!

**Comment by gaj995** [comment]
One thing I am noticing is that from the "databases", the onPremisePath is always empty ("onPremisePath":"")

Do you know why this is?

**Comment by achapkowski** [comment]
I do not. I'm closing this issue since the initial question was answered.
