### ISSUE TITLE
Bug in Item.copy_feature_layer_collection

### ISSUE THREAD

**Issue by jrmatchett** [Esri/arcgis-python-api#343]
There appears to be a bug in `Item.copy_feature_layer_collection` in which the copied item's service name is not correctly set. Say I have a feature service named "fs_x" and try to make a copy named "fs_y". Executing `fs_y = fs_x.copy_feature_layer_collection('fs_y', layers=[0])` generates the error `RuntimeError: Service name 'fs_x' already exists for '0123456789ABCDEF'`. I receive this error on my enterprise portal, however not on ArcGIS Online.

The bug seems to be in lines 6390–6396 of `gis/__init__.py` (version 1.5.2). Lines 6392–6393 set the feature service name to the new service name, but line 6396 overwrites the name to the original. I suggest replacing lines with 6392–6396 with:
```
if k.lower() == 'name':
    params['name'] = service_name
elif k.lower() == '_ssl':
    params['_ssl'] = False
else:
    params[k] = v
```
Lines 6398–6400 seem unnecessary since the above will correctly set the name and _ssl params. Also, `serviceItemId` in the list of `allowed` parameters (line 6340) doesn't seem to be needed since a new ID is going to be assigned to the copy.

**Comment by carstenpiepel** [comment]
FYI - This is reproducible on ArcGIS Enterprise 10.6.1 but not on 10.8.1. I didn't test versions in between.

**Comment by achapkowski** [comment]
We have tested at multiple versions and cannot reproduce. 10.6.1 is very very old and in mature support, we recommend updating to a newer portal and trying again.
