### ISSUE TITLE
Bug in arcgis.gis.server.Server 

### ISSUE THREAD

**Issue by spiskula** [Esri/arcgis-python-api#345]
There appears to be a dodgy code that is error prone depending on how the Server class and publish_sd method is used.

If you initiate the Server class and proceed to publish_sd right away:
`
 server = Server(
        url=args.server_url,
        username=args.ags_admin,
        password=args.ags_pass
    )
server.publish_sd(sd_file=args.sdfile)
`
Then in the publish_sd method there is an attempt to extract
`
        catalog = self._catalog
        if 'System' not in catalog.folders:
`
But `self._catalog` is `None` in this scenario, hence attempt to read `catalog.folder` crashes the API.
As such i think there should be a call to `self.content` which assures all is initiated as it should and prevents returning `None`

"site-packages\arcgis\gis\server\admin\administration.py"
![image](https://user-images.githubusercontent.com/6223455/51760518-7cbcc100-20c2-11e9-85fd-fa22b6ca82ab.png)

**Comment by achapkowski** [comment]
please post a fully reproducible example and what version you are using.
Thank you

**Comment by spiskula** [comment]
Hello,

arcgis 1.5.2

full repro case:
```
from arcgis.gis.server import Server
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
server = Server(
    url="https://localhost:6443/arcgis",
    username="siteadmin",
    password="site!admin",

)
result = server.publish_sd(sd_file="dummy.sd")
print("Success")
```
Running the above results in:
![image](https://user-images.githubusercontent.com/6223455/51772159-36c42500-20e3-11e9-99aa-c2cd03aa9943.png)

**Comment by spiskula** [comment]
Hello,

arcgis 1.5.2

full repro case:
```
from arcgis.gis.server import Server
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
server = Server(
    url="https://localhost:6443/arcgis",
    username="yyy",
    password="xxxx",

)
result = server.publish_sd(sd_file="dummy.sd")
print("Success")
```
Running the above results in:
![image](https://user-images.githubusercontent.com/6223455/51773170-e69a9200-20e5-11e9-935b-b0d20287449b.png)

**Comment by achapkowski** [comment]
I've gone through your workflow and tested it, and at the latest release I cannot reproduce this error.  

Instead of accessing the Server directly, have you tried accessing it through the portal's admin?

**example**

```python
gis = GIS(mysite creds)
server = gis.admin.servers.list()[0]
```

**Comment by dizietz** [comment]
I've had the same issue with 1.4.2.

achapkowski's example worked for me but also doing it the way I show below did not work. Btw, the not working version works fine to list existing services/folders, it just won't publish.

Working:

from arcgis.gis import GIS

gis = GIS(mysite creds)
server = gis.admin.servers.list()[0]
svcs = server.services
svcs.publish_sd(sd_file= 'dummy/path', 
                        folder='dummyFolder')


Not Working:

from arcgis.gis import server

gis = GIS(mysite creds)
server = server.Server(baseurl="https://mysite.com:6443/arcgis",
                                  url="https://mysite.com:6443/arcgis/admin"
                                  gis=gis
                                  username="yyy",
                                  password="xxxx",
                                  verify_cert=False,
                                  all_ssl=True)
svcs = server.services
svcs.publish_sd(sd_file= 'dummy/path', 
                        folder='dummyFolder')

**Comment by alexkemp94** [comment]
![image](https://user-images.githubusercontent.com/33670839/62686302-5e624700-b9bc-11e9-9661-2040e67e77db.png)
 Same issue for me
