### ISSUE TITLE
Type error when creating a Spatialy Enabled Data Frame from Feature Layer with date fields

### ISSUE THREAD

**Issue by Ben-Sperry** [Esri/arcgis-python-api#353]
When I try to create a spatially enabled data frame (SEDF) using Hosted Feature Layers with date fields I get the following error:

`Exception: Could not load the dataset: dtype '<class 'datetime.datetime'>' not understood`

I don't encounter the problem with hosted feature layers that don't have date fields but as soon as I add a date field it gives me that error. I copied the code directly from the guide.

`flayer = item.layers[0]

sdf = pd.DataFrame.spatial.from_layer(flayer)
sdf.head()`

I am using ArcGIS API for Python 1.5.3 and Pandas 0.24.1

Many thanks

**Comment by achapkowski** [comment]
@Ben-Sperry can you provide a link to the FeatureLayer you are using?

Thank you

**Comment by Ben-Sperry** [comment]
Hello @achapkowski,

Here you go:
https://services8.arcgis.com/ZbDl0kmn9FILhh7J/arcgis/rest/services/Py_Thing/FeatureServer

**Comment by achapkowski** [comment]
Try:

```python
from arcgis.gis import GIS
from arcgis.features import FeatureLayer
import pandas as pd
from arcgis.features import GeoAccessor, GeoSeriesAccessor

fl = FeatureLayer(url="https://services8.arcgis.com/ZbDl0kmn9FILhh7J/ArcGIS/rest/services/Py_Thing/FeatureServer/0")

df = pd.DataFrame.spatial.from_layer(fl)
```

**Comment by Ben-Sperry** [comment]
I get the same error.

**Comment by Ben-Sperry** [comment]
It appears that it was a problem with pandas in my environment. I downgraded pandas to a previous version and it worked. When I upgraded again to the current version it still worked.

**Comment by achapkowski** [comment]
@Ben-Sperry what version was giving you issues?

**Comment by Ben-Sperry** [comment]
Pandas 0.24.1
arcgis 1.5.3
