### ISSUE TITLE
Synchronize Replica parameter issue

### ISSUE THREAD

**Issue by fallomj** [Esri/arcgis-python-api#369]
I'm attempting to use the synchronize method in the arcgis.features.managers.SyncManager class and I'm seeing an issue where the parameters passed are "scrambled" such that they become invalid. Here are the parameters I'm using:

![image](https://user-images.githubusercontent.com/22376581/53670831-f0f20380-3c30-11e9-9d46-be627b0451f1.png)

Stepping through this in the managers.py module:

![image](https://user-images.githubusercontent.com/22376581/53671651-3f54d180-3c34-11e9-9726-ca792c362bc9.png)

Stepping through the code then jumps to the layers module, and these parameters are not valid:

![image](https://user-images.githubusercontent.com/22376581/53671698-732ff700-3c34-11e9-91ad-2ad630613158.png)

Here is the traceback:

File "C:\ProgramData\Anaconda3\lib\site-packages\arcgis\features\managers.py", line 270, in synchronize
    rollback_on_failure)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arcgis\features\layer.py", line 1508, in _synchronize_replica
    res = self._con.post(path=url, postdata=params, token=self._token)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arcgis\_impl\connection.py", line 1129, in post
    self._handle_json_error(resp_json['error'], errorcode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\arcgis\_impl\connection.py", line 1149, in _handle_json_error
    raise RuntimeError(errormessage)
RuntimeError: 
'async' parameter is invalid
'editsUploadFormat' parameter is invalid
'dataFormat' parameter is invalid
(Error Code: 400)

I'm using version 1.4.1 of the arcgis module

**Comment by DanCranford** [comment]
I ran into the same thing last year.  I think this has been fixed in versions 1.5+.  The code below works for sure on the current version of the api.
![image](https://user-images.githubusercontent.com/38766170/55973851-2f6cdc00-5c3b-11e9-8cde-e3672f99fa2d.png)
