### ISSUE TITLE
can't connect through ArcGIS Pro

### ISSUE THREAD

**Issue by simoxu001** [Esri/arcgis-python-api#372]
My pro was running when the script is executed.
And the active portal is pointing to the my enterprise portal
My enterprise portal is using IWA authentication
I tried to switch the active portal to AGOL, same error:
The error is as below:

> ---------------------------------------------------------------------------
GSSError                                  Traceback (most recent call last)
<ipython-input-12-493b7b5e9d31> in <module>
----> 1 dcsiportal=GIS("pro")

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\gis\__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
    450         if self._product_version is None:
    451             self._is_agol = self._portal.is_arcgisonline
--> 452             self._product_version = [int(i) for i in self._portal.get_version().split('.')]
    453     #----------------------------------------------------------------------
    454     def _pfx_to_pem(self, pfx_path, pfx_password):

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\portalpy.py in get_version(self, force)
   2244         # forcing a check of the server, then check the server
   2245         if not self._version or force:
-> 2246             resp = self.con.post('', self._postdata())
   2247             if not resp:
   2248                 old_resturl = _normalize_url(self.url) + 'sharing/'

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\connection.py in post(self, path, postdata, files, ssl, compress, is_retry, use_ordered_dict, add_token, verify_cert, token, try_json, out_folder, file_name, force_bytes, add_headers)
   1105             opener.addheaders = headers
   1106             #print("***"+url)
-> 1107             resp = opener.open(url, data=encoded_postdata.encode())
   1108             resp_data, is_file = self._process_response(resp,
   1109                                                out_folder=out_folder,

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\urllib\request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\urllib\request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\urllib\request.py in error(self, proto, *args)
    562             http_err = 0
    563         args = (dict, proto, meth_name) + args
--> 564         result = self._call_chain(*args)
    565         if result:
    566             return result

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in http_error_401(self, req, fp, code, msg, headers)
     34         _log.info('Using NTLM handler')
     35         url = req.full_url
---> 36         response = self.http_error_ntlm_auth_reqed(url, req, headers, 'WWW-Authenticate', 'Authorization', fp)
     37         return response
     38 

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in http_error_ntlm_auth_reqed(self, host, req, headers, authenticatehdr, authhdr, fp)
     55         if ntlmsig in str(headers):
     56             fp.close()
---> 57             return self.retry_http_ntlm_sspi_auth(host, req, authenticatehdr, authhdr)
     58 
     59     def retry_http_ntlm_sspi_auth(self, host, req, authenticatehdr, auth_header):

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in retry_http_ntlm_sspi_auth(self, host, req, authenticatehdr, auth_header)
     66 
     67         headers["Connection"] = "Keep-Alive"
---> 68         headers[auth_header] = "NTLM " + self.get_auth_req()
     69 
     70         h.request(req.get_method(), req.selector, req.data, headers)

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in get_auth_req(self)
     43 
     44     def get_auth_req(self):
---> 45         return self.sspiauth.create_auth_req()
     46 
     47     def create_challenge_response(self, input_buffer):

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in create_auth_req(self)
     17 
     18     def create_auth_req(self):
---> 19         return self.create_challenge_response('')
     20 
     21     def create_challenge_response(self, challenge):

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\_impl\common\_iwa.py in create_challenge_response(self, challenge)
     20 
     21     def create_challenge_response(self, challenge):
---> 22         status = kerberos.authGSSClientStep(self.ctx, challenge)
     23         auth_req = kerberos.authGSSClientResponse(self.ctx)
     24         return auth_req

GSSError: SSPI: InitializeSecurityContext: The handle specified is invalid

**Comment by simoxu001** [comment]
My ArcGIS Python API is 1.5.3
ArcGIS Pro is at version 2.3.1
and Portal is at 10.6.1

**Comment by achapkowski** [comment]
Open Pro and see if you are still logged into your portal.

**Comment by simoxu001** [comment]
It's working now after upgrading to API Version 1.6.0
this latest version also fixed my IWA authentication problems, although it's not mentioned in the release note.
