### ISSUE TITLE
'Item' object has no attribute 'register'

### ISSUE THREAD

**Issue by gaj995** [Esri/arcgis-python-api#384]
![image](https://user-images.githubusercontent.com/13633898/54540465-70404080-496e-11e9-918b-a3b43f34de98.png)

Trying to register my app, but the function does not exists. 

![image](https://user-images.githubusercontent.com/13633898/54540599-a2ea3900-496e-11e9-9b80-770d06375abb.png)

Any idea why?

**Comment by achapkowski** [comment]
This works for me.  What version of the API are you using?

```python
application = gis.content.add(item_properties={"type": "Application",
                                 "title" : "DummyApplication2",
                                 "name" : "DummyApplication_1553009254509",
                                 "tags":  ["application", 'oauth']})
print(application)
reg = application.register("multiple", redirect_uris=["https://app.example.com", "urn:ietf:wg:oauth:2.0:oob"])
print(reg)
print(application.app_info)
```

**Comment by gaj995** [comment]
I was on 1.4.1. After updating the latest, it worked. 

Thanks alot!
