### ISSUE TITLE
Register App (#384)

### ISSUE THREAD

**Issue by gaj995** [Esri/arcgis-python-api#387]
This is a continuous from #384. 

After the update I am able to see the register function, but it doesn't register. 

![image](https://user-images.githubusercontent.com/13633898/54634328-5f6bf980-4a58-11e9-8b98-d5d6fc491eab.png)

The function run's without any error, but when I check the app, it hasn't been registered.

**Comment by ATL2001** [comment]
gaj995, what is the "type" property of your item?  I was running into this exact same issue a few days ago, and when i dug into the source code, I noticed that the register function returns None if the item's type is anything besides "Application".  My item had a type of "Web Mapping Application".  When I changed it to "Application" the register function worked perfectly!  (the code should probably allow the type of "Web Mapping Application", but changing the type got my webapp registered)

**Comment by gaj995** [comment]
Thank you so much! I did the same thing and had the type as Web Mapping Application and I just tested it with Application and it worked!

Thanks for letting me know.
