### ISSUE TITLE
Error in gis content search in "2 - Intersection Detection.ipynb"

### ISSUE THREAD

**Issue by mssudarsan** [Esri/arcgis-python-api#389]
![Capture](https://user-images.githubusercontent.com/40969919/54660644-394c6500-4afd-11e9-95c5-3c1fbf91db62.JPG)

IndexError : Traceback (most recent call last)
<ipython-input-36-780819fc8068> in <module>
----> 1 object_point_srvc = gis.content.search("JHWY_ML_Detection_02")[1]
         2 object_point_srvc

IndexError: list index out of range

Could you please help me on this, Thank you.

**Comment by JanineCHEN** [comment]
I am having similar error while trying to run one of the provided example ipynb, detecting_swimming_pools_using_satellite_image_and_deep_learning.ipynb to be specific

![image](https://user-images.githubusercontent.com/37527041/66379106-6bfd7280-e9e7-11e9-99cb-11f203771e3a.png)

![image](https://user-images.githubusercontent.com/37527041/66379278-b7178580-e9e7-11e9-8622-b30a6ca746b4.png)

Can anyone shed some light on this issue, many thanks!
