### ISSUE TITLE
Problem with integration with ArcGIS Pro 

### ISSUE THREAD

**Issue by dainius-kavoliunas** [Esri/arcgis-python-api#398]
Hi,

I am trying to integrate the model with ArcGIS Pro with .emd file, but I fail to do it. Can you add more information how to use trained deep learning model directly in ArcGIS Pro?

Thanks

**Comment by AtmaMani** [comment]
@dainius-kavoliunas we are working on authoring guide chapters for Deep Learning which talks about the emd files and related concepts. We plan to release that for the next version. Meanwhile, please look at https://pro.arcgis.com/en/pro-app/help/analysis/image-analyst/deep-learning-in-arcgis-pro.htm for help about using this in Pro.
