### ISSUE TITLE
Overwrite Python API

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-python-api#40]
Hi there!
It's [Raul, from Esri Spain](https://twitter.com/hhkaos). I have received a [question in Geonet](https://geonet.esri.com/thread/184410-ejemplo-overwrite-python-api) and I need some help.

A customer is trying to use [the API](https://developers.arcgis.com/python/) to overwrite the content of a feature service using a shapefile. We tried to do that using the **Item.Update** ([1](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.html#arcgis.gis.Item.update),[2](https://developers.arcgis.com/python/guide/class-gis-Item/#update(item_properties=None,-data=None,-thumbnail=None,-metadata=None))) function but it didn't work. It updates the metadata but not the content itself, the function even returns `True` as you can see here:

![pythonapi](https://cloud.githubusercontent.com/assets/826965/20666670/c287f68e-b565-11e6-8e34-a91d38c3a0ec.JPG)

Do you have any thoughts on that? Is this a bug? Should we use any other function? [Item.publish](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.html#arcgis.gis.Item.publish) maybe?

They can not use [ArcREST](https://github.com/Esri/ArcREST) because they have no ArcPy installed in the machine which is going to run the script.

Thanks in advance,
Raul

**Comment by achapkowski** [comment]
@hhkaos you do not need arcpy to use ArcREST.

**Comment by hhkaos** [comment]
Ups!, you are right Andrew! hehe... ^_^'', last time I checked (2014?) I didn't realise that you could use it without arcpy 

Well, in this case, I can not find an overwrite function. Should we follow the [update_features.py](https://github.com/Esri/ArcREST/blob/master/samples/update_features.py) approach? (or maybe the @phpmaps at [developer-support repo](https://github.com/Esri/developer-support/blob/gh-pages/python/general-python/overwrite-feature-service-with-editor-tracking/OverWriteWIth%20EditorTracking.py)?), what about the [Item.publish](https://developers.arcgis.com/python/guide/class-gis-Item/#update(item_properties=None,-data=None,-thumbnail=None,-metadata=None)) function on the [Python API](https://developers.arcgis.com/python/), should that work?

Thanks one more time!! :dancer: :smile:

**Comment by rohitgeo** [comment]
@hhkakos, the hosted feature service is not a file based item like the shapefile. You could update the shapefile and re-publish the feature service. Alternatively, you could update features that have changed using [edit features](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.lyr.html#arcgis.lyr.FeatureLayer.edit_features) in combination with arcpy that this aspect of the API depends upon..

Sample code below:
```python
from arcgis.gis import *
from arcgis.tools import *
from arcgis.lyr import *

gis = GIS("OrganzationURL", "UserName", "Password")
svc = FeatureService("Url to Feature Service", gis)

layer = svc.layers
print ("Service contains {0} layers".format(len(layer)))

fl=layer[0]
print ("First layers url is: {0}".format(fl.url))

oidQResults = fl.query(returnIDsOnly=True)
if len(oidQResults['objectIds']) > 0:
    print ("Service contain {0} features".format(len(oidQResults['objectIds'])))
    oidString = ','.join(str(x) for x in oidQResults['objectIds'])
    fl.edit_features(deletes=oidString)
else:
    print ("Service does not contain any features")

feat = Feature()
features = feat.fc_to_features(r'Path to GDB Layer')

featDict = [feat.as_dict for feat in features]

if len(features) > 0:
    addresult = fl.edit_features(adds=featDict)
    print (addresult)
else:
    print ("The layer does not contain any features")
```

**Comment by hhkaos** [comment]
Thanks @rohitgeo !! Let us try that and we'll be back to you :clap: :smiley_cat:
