### ISSUE TITLE
ItemManager.share() ignores allow_members_to_edit arg

### ISSUE THREAD

**Issue by philnagel** [Esri/arcgis-python-api#417]
When sharing an item with a group that has editing capabilities, it is necessary to specifically allow this. The `Item.share()` method has the keyword argument `allow_members_to_edit` for this, but in the newest version (1.6), this argument, which was working previously, is now ignored.
When watching the request in Fiddler, the `confirmItemControl`, which should result from this argument being set to `True`, never gets passed.

**Comment by AtmaMani** [comment]
@philnagel thanks for bringing this to our attention. We will fix this in the next release. Meanwhile, you can use `ContentManager.share_items()` where this works as designed

**Comment by sirws** [comment]
I am an administrator and I am trying to share someone elses item and I get a 500 error when trying the workaround:
f=gis.content.get('abdd407fb1fc469580718341acf01732')
f
gis.content.share_items([f], groups='7662fadb041e47d6bee00564b8b1e622',allow_members_to_edit=True)

{'results': [{'itemId': 'abdd407fb1fc469580718341acf01732',
   'success': False,
   'notSharedWith': [],
   'error': {'code': 500,
    'message': 'Item does not exist or is inaccessible'}}]}

**Comment by Biboba** [comment]
Hello,

I have the same issue using arcgis version "1.8.5.post3".

Using an administrator account, I would like to share an item that belongs to another user to a group with editing capabilities.
While it is working on the Portal web interface, it does not work with ArcGIS API for Python.
Debugging it, I noticed that the parameter 'confirmItemControl' is only sent if the item is owned by the user:

Extract from: 'arcgis\gis\\\__init___.py'
```python
if self.owner == self._gis.users.me.username:

            url = "{resturl}content/users/{owner}/shareItems".format(resturl=self._gis._portal.resturl,
                                                                      owner=self.owner)
            params = {
                'f' : 'json',
                'items' : self.id,
                "groups": group_ids,
                "everyone": everyone,
                "account": org
            }
            if allow_members_to_edit:
                params['owner'] = self.owner
                params['confirmItemControl'] = allow_members_to_edit  # True
        else:
            url = "{resturl}/content/items/{itemid}/share".format(resturl=self._gis._portal.resturl,
                                                                  itemid=self.itemid)
            params = {
                'f' : 'json',
                "groups": group_ids,
                "everyone": everyone,
                "account": org
            }
```

If I add manually the parameter confirmItemControl, it works.
Could  you please fix it ? 
Any workaround in the meantime ?

Thanks

**Comment by nanaeaubry** [comment]
This has been fixed and the error no longer occurs at version 2.0.0
