### ISSUE TITLE
Unable to view Web Map in collector gallery after adding map via API

### ISSUE THREAD

**Issue by SergStol** [Esri/arcgis-python-api#42]
The code I wrote to create copies of the existing map, successfully creates new copies which I can see in My Contents tab in ArcGIS Online. However, I am unable to view those in the Collector App Map Gallery (Collector v10.3.5 running on iOS) Would anyone have a clue why? Something I am missing in the json? 

If I manually "Save As" using the same title format as in the script, within the web map viewer, the map is visible in the Map Gallery of Collector app. So its the script copy process that is wrong I think.

```
webmap = gis.content.search(query = 'title:PC_Test', item_type=None, sort_field='numViews', sort_order='desc', max_items=9999)

testmap = webmap[0]

web_map_dict = testmap.get_data(try_json=True)

x = 0
while x <= 5:
    title = "PC_Test_" + str(x)
    web_map_properties = {'title': title,
                         'type':'Web Map',
                         'snippet':'This web map copied from template',
                         'tags':'ArcGIS Python API PC Test',
                         'text':json.dumps(web_map_dict)}

    web_map_item = `gis.content.add(web_map_properties)`

    x += 1
```

**Comment by MikeMillerGIS** [comment]
There is a typekeyword collector is expecting, did you copy all these over too?

**Comment by SergStol** [comment]
Thanks! Is there a way to "get" the web map description json which includes those? Similar to get_data for example? Manually putting those did the trick though!

**Comment by SergStol** [comment]
However, the final json of the web map looks a bit odd:

`  "typeKeywords": [
    "'Collector'",
    "'Data Editing'",
    "'Explorer Web Map'",
    "'Map'",
    "'Offline'",
    "'Online Map'",
    "'Web Map']",
    "['ArcGIS Online'",
    "ArcGIS Online",
    "Explorer Web Map",
    "Map",
    "Online Map",
    "Web Map"
  ],`

**Comment by AtmaMani** [comment]
@SergStol the TypeKeywords are not part of webmap JSON, instead its a property on the webmap item. When you are publishing a new webmap for using with collector app, you can write the code as following
```PYTHON
web_map_properties = {'title': 'New Web Map for Collector',
                                  'type': 'Web Map',
                                  'snippet': 'an appropriate description',
                                  'tags': 'appropriate tags',
                                  'typeKeywords' : "Collector, Explorer Web Map, Web Map, Map, Online Map",
                                  'text': json.dumps(your_web_map_dict)}
#Publish
web_map_item = gis.content.add(web_map_properties)
```

**Comment by SergStol** [comment]
@AtmaMani Thanks for this!
