### ISSUE TITLE
Add support for pagination to ContentManager.search()

### ISSUE THREAD

**Issue by bjdemers** [Esri/arcgis-python-api#420]
As a developer searching a Portal, I would like to be able to retrieve the results of my search query over multiple requests/pages so that I can be confident that I've reviewed all items.

Currently, the way to search through a large number of Portal items seems to be to call the ContentManager.search() function with a large value for its "max_items" parameter.  However, if this limit is exceeded, there is no way to use the API to get the second, third, etc. page of results.

The documentation for the Portal's REST search capability (https://developers.arcgis.com/rest/users-groups-and-items/search.htm) appears to support pagination via it's "start" parameter.

**Comment by AtmaMani** [comment]
@bjdemers thank you. We will consider this request for enhancement for the upcoming versions of the API

**Comment by achapkowski** [comment]
This has been resolved.  You can do this by using `advanced_search` on the ContentManager.

https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.ContentManager.advanced_search

**Comment by simongis** [comment]
Would be great to see a snippet of how to paginate using the advanced_search.  Struggling a bit!
