### ISSUE TITLE
Reduce import size by moving visualization to separate package

### ISSUE THREAD

**Issue by philnagel** [Esri/arcgis-python-api#430]
This API is a rather large import, which makes it difficult to use in some production environments where performance and user experience is impacted by this.
I wonder if it would be possible to move some parts of it, like the Jupyter Notebooks related items that do not get used by all users, to a separate package to help reduce import size?

**Comment by AtmaMani** [comment]
@philnagel we support a lite install as documented here: https://developers.arcgis.com/python/guide/install-and-set-up/#Install-without-Dependencies

Closing issue, please reopen if this does not suit your requirements

**Comment by philnagel** [comment]
@AtmaMani Thanks for the tip! While that is not entirely what I was looking for (in some specific situations in our environment, we cannot control what packages are installed), it did lead me in the right direction. One can modify the import of arcgis as follows to avoid the heavy imports that are not typically used in a programmatic-only use scenario (our scripts run headless or are called through Flask endpoints, no need for jupyter, for example).

``` python
import sys
# block certain imports before importing arcgis
removals = ['ipywidgets', 'widgetsnbextension', 'jupyterlab', 'arcpy']
for rem in removals:
    sys.modules[rem] = None
import arcgis

# restore sys.modules to previous state
for rem in removals:
    del sys.modules[rem]

```

**Comment by philnagel** [comment]
Hi @AtmaMani it seems the solution you posted above has been removed from the docs. Is this no longer supported? I am unable to import `arcgis` without import errors now.
