### ISSUE TITLE
Having a percent in your password with profile='profilename' throws error

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-python-api#431]
If you have a percent character in your password it throws an error while trying to log in to GIS and save to a profile.

**Comment by achapkowski** [comment]
We will review this issue and let you know what the outcome is.  Thank you for reporting.

**Comment by achapkowski** [comment]
@roemhildtg What version of the Python API are you using?

I cannot reproduce the issue:

```python
from arcgis.gis import GIS
gis = GIS(username='somerandomaccount', password='123%abCdDF', profile='test_profile')
```

Then closed and ran a new python file:

```python
from arcgis.gis import GIS
gis = GIS(profile='test_profile')
print(gis.users.me)
```

and it resulted in a successful login.  

@DavidJVitale

**Comment by roemhildtg** [comment]
I'm using the version that comes with arcgis pro - v 1.5.1.

**Comment by roemhildtg** [comment]
Huh. I can't seem to reproduce it anymore either. Sorry about this!
