### ISSUE TITLE
Geometry.centroid returns None

### ISSUE THREAD

**Issue by roemhildtg** [Esri/arcgis-python-api#432]
I copied the example from the docs into a jupyter notebook and I am seeing this issue:

![image](https://user-images.githubusercontent.com/5471079/57489675-60f9b700-727c-11e9-88c5-cec5a2e14561.png)

Any tips?

**Comment by achapkowski** [comment]
What geometry engine are you using? ArcPy or Shapely?

**Comment by roemhildtg** [comment]
I'm not sure - I'd assume arcpy since its running in the ArcGIS pro jupyter install?

**Comment by achapkowski** [comment]
Can you clone the environment and upgrade the Python API?

**Comment by roemhildtg** [comment]
I'm wondering if maybe I'm using the wrong environment. Like maybe when I'm running jupyter its not activating the Pro env and there's no Arcpy or Shapely available. I'm a bit of a noobie with conda.

**Comment by achapkowski** [comment]
If you don't have a geometry engine, then this is expected.

**Comment by roemhildtg** [comment]
Gotcha. I am definitely learning a lot. Thanks for the info!

**Comment by scdub** [comment]
@achapkowski Perhaps raising a warning would be useful if no geometry engine is found?
