### ISSUE TITLE
.Validate() and .Join() Spatially Enabled DataFrame Methods Failing With Cast Array DataType Type Error

### ISSUE THREAD

**Issue by PatrickFlynn** [Esri/arcgis-python-api#434]
Problem:
-----------------------------------------
I am attempting to take two spatially enabled DataFrames and spatially join them using the DF1.spatial.join(DF2) syntax. I thought perhaps it was my environment so I created a new environment (see .YAML attached) with only Arcgis package and its dependencies installed.  The failure linked below is the same in my normal environment. 

Notebook and YAML zipped files:
[arcgis Python API Spatially Enabled Dataframe Error.zip](https://github.com/Esri/arcgis-python-api/files/3174242/arcgis.Python.API.Spatially.Enabled.Dataframe.Error.zip)

Package version available further below.

Link to Example ESRI Notebook:
-----------------------------------------------

[ESRI Spatially Enabled DataFrame Advanced Topics - Spatial Joins ](https://github.com/Esri/arcgis-python-api/blob/master/guide/05-working-with-the-spatially-enabled-dataframe/spatially-enabled-dataframe-advanced-topics.ipynb)

Code:
------------------------------------------------
`from arcgis.gis import GIS`
`import pandas as pd`
`from arcgis.features import GeoAccessor, GeoSeriesAccessor`
`g2 = GIS("https://pythonapi.playground.esri.com/portal", "arcgis_python", "amazing_arcgis_123")`
`import os`
`data_pth = r'/path/to/your/data/census_2010/example'`
`cities = r"cities.shp"`
`states = r"states.shp"`
`sdf_target = pd.DataFrame.spatial.from_featureclass(os.path.join(data_pth, cities))`
`sdf_target.spatial.validate()`

Fails with this warning:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a6b07dd6c095> in <module>
----> 1 sdf_target.spatial.validate()

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\arcgis\features\geo\_accessor.py in validate(self, strict)
   1013         else:
   1014             q = self._data[self.name].notna()
-> 1015             return all(pd.unique(self._data[q][self.name].geom.is_valid))
   1016         return True
   1017     #----------------------------------------------------------------------

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2916         # Do we have a (boolean) 1d indexer?
   2917         if com.is_bool_indexer(key):
-> 2918             return self._getitem_bool_array(key)
   2919 
   2920         # We are left with two options: a single key, and a collection of keys,

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\frame.py in _getitem_bool_array(self, key)
   2967         key = check_bool_indexer(self.index, key)
   2968         indexer = key.nonzero()[0]
-> 2969         return self._take(indexer, axis=0)
   2970 
   2971     def _getitem_multilevel(self, key):

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\generic.py in _take(self, indices, axis, is_copy)
   3357         new_data = self._data.take(indices,
   3358                                    axis=self._get_block_manager_axis(axis),
-> 3359                                    verify=True)
   3360         result = self._constructor(new_data).__finalize__(self)
   3361 

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\internals\managers.py in take(self, indexer, axis, verify, convert)
   1348         new_labels = self.axes[axis].take(indexer)
   1349         return self.reindex_indexer(new_axis=new_labels, indexer=indexer,
-> 1350                                     axis=axis, allow_dups=True)
   1351 
   1352     def merge(self, other, lsuffix='', rsuffix=''):

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\internals\managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy)
   1233             new_blocks = [blk.take_nd(indexer, axis=axis, fill_tuple=(
   1234                 fill_value if fill_value is not None else blk.fill_value,))
-> 1235                 for blk in self.blocks]
   1236 
   1237         new_axes = list(self.axes)

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\internals\managers.py in <listcomp>(.0)
   1233             new_blocks = [blk.take_nd(indexer, axis=axis, fill_tuple=(
   1234                 fill_value if fill_value is not None else blk.fill_value,))
-> 1235                 for blk in self.blocks]
   1236 
   1237         new_axes = list(self.axes)

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\pandas\core\internals\blocks.py in take_nd(self, indexer, axis, new_mgr_locs, fill_tuple)
   1776         # if its REALLY axis 0, then this will be a reindex and not a take
   1777         new_values = self.values.take(indexer, fill_value=fill_value,
-> 1778                                       allow_fill=True)
   1779 
   1780         if self.ndim == 1 and new_mgr_locs is None:

~\Documents\Code\Anaconda\envs\TestPythonAPI\lib\site-packages\arcgis\features\geo\_array.py in take(self, indexer, allow_fill, fill_value)
    170     def take(self, indexer, allow_fill=True, fill_value=None):
    171         mask = indexer == -1
--> 172         result = self.data.take(indexer)
    173         result[mask] = self.dtype.na_value
    174         return type(self)(result, copy=False)

TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'

Environment and Package Info:
------------------------------------------
arcgis=1.6.0=py37h62639d4_1
attrs=19.1.0=py37_1
backcall=0.1.0=py37_0
blas=1.0=mkl
bleach=3.1.0=py37_0
ca-certificates=2019.1.23=0
certifi=2019.3.9=py37_0
colorama=0.4.1=py37_0
cycler=0.10.0=py37_0
decorator=4.4.0=py37_1
defusedxml=0.6.0=py_0
entrypoints=0.3=py37_0
freetype=2.9.1=ha9979f8_1
icc_rt=2019.0.0=h0cc432a_1
icu=58.2=h3fcc66b_1
intel-openmp=2019.3=203
ipykernel=5.1.0=py37h39e3cac_0
ipython=7.5.0=py37h39e3cac_0
ipython_genutils=0.2.0=py37_0
ipywidgets=7.4.2=py37_0
jedi=0.13.3=py37_0
jinja2=2.10.1=py37_0
jpeg=9b=he27b436_2
jsonschema=3.0.1=py37_0
jupyter_client=5.2.4=py37_0
jupyter_core=4.4.0=py37_0
jupyterlab=0.35.4=py37hf63ae98_0
jupyterlab_server=0.2.0=py37_0
keyring=18.0.0=py37_0
kiwisolver=1.1.0=py37ha925a31_0
libpng=1.6.37=h2a8f88b_0
libsodium=1.0.16=h9d3ae62_0
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
markupsafe=1.1.1=py37he774522_0
matplotlib=3.0.3=py37hc8f65d3_0
mistune=0.8.4=py37he774522_0
mkl=2019.3=203
mkl_fft=1.0.12=py37h14836fe_0
mkl_random=1.0.2=py37h343c172_0
msys2-conda-epoch=20160418=1
nbconvert=5.5.0=py_0
nbformat=4.4.0=py37_0
notebook=5.7.8=py37_0
numpy=1.16.3=py37h19fb1c0_0
numpy-base=1.16.3=py37hc3f5095_0
openssl=1.1.1b=he774522_1
pandas=0.24.2=py37ha925a31_0
pandoc=2.2.3.2=0
pandocfilters=1.4.2=py37_1
parso=0.4.0=py_0
pickleshare=0.7.5=py37_0
pip=19.1.1=py37_0
prometheus_client=0.6.0=py37_0
prompt_toolkit=2.0.9=py37_0
pygments=2.4.0=py_0
pyparsing=2.4.0=py_0
pyqt=5.9.2=py37h6538335_0
pyrsistent=0.14.11=py37he774522_0
pyshp=2.1.0=py_0
python=3.7.3=h8c8aaf0_1
python-dateutil=2.8.0=py37_0
pytz=2019.1=py_0
pywin32=223=py37hfa6e2cd_1
pywinpty=0.5.5=py37_1000
pyzmq=18.0.0=py37ha925a31_0
qt=5.9.7=vc14h73c81de_0
send2trash=1.5.0=py37_0
setuptools=41.0.1=py37_0
sip=4.19.8=py37h6538335_0
six=1.12.0=py37_0
sqlite=3.28.0=he774522_0
terminado=0.8.2=py37_0
testpath=0.4.2=py37_0
tornado=6.0.2=py37he774522_0
traitlets=4.3.2=py37_0
vc=14.1=h0510ff6_4
vs2015_runtime=14.15.26706=h3a45250_4
wcwidth=0.1.7=py37_0
webencodings=0.5.1=py37_1
wheel=0.33.2=py37_0
widgetsnbextension=3.4.2=py37_0
wincertstore=0.2=py37_0
winkerberos=0.7.0=py37_1
winpty=0.4.3=4
zeromq=4.3.1=h33f27b4_3
zlib=1.2.11=h62dcd97_3

**Comment by PatrickFlynn** [comment]
**Update** - Upgrading arcgis to 1.6.1 did not resolve this issue.

**Comment by PatrickFlynn** [comment]
Failure occurs because a GIS object is not passed to Spatial Enabled Data Frame Object. This can be overcome by passing a GIS object as below:

`gis = GIS("https://your_gis__here", username=user, password=password)
sdf = arcgis.features.SpatialDataFrame(gis=gis)
sdf = sdf.from_xy(df, 'x', 'y')
sdf.spatial.join(layer_to_join)
`

Documentation/examples likely need to be updated to avoid confusion.

**Comment by achapkowski** [comment]
`arcgis.features.SpatialDataFrame` is deprecated.  You should get the accessor pattern instead.
