### ISSUE TITLE
pd.DataFrame.spatial.from_featureclass() UnboundLocalError: local variable 'cursor_fields' referenced before assignment

### ISSUE THREAD

**Issue by ATL2001** [Esri/arcgis-python-api#436]
While using ArcGIS module versions 1.5.2 and 1.6.0 using the pd.DataFrame.spatial.from_featureclass() function and specifying a list of fields in the fields paramater, an error occurs:

> import pandas as pd
import arcgis
test_fc = r"C:\Temp\test.gdb\test_fc"
field_list = ["valid_field_name_one", "valid_field_name_two"]
test_df = pd.DataFrame.spatial.from_featureclass(test_fc, fields=field_list)

> --> 340         shape_field_idx = cursor_fields.index("SHAPE@JSON")
    341         with da.SearchCursor(filename,
    342                              field_names=cursor_fields,
UnboundLocalError: local variable 'cursor_fields' referenced before assignment

If lines 336 and 337 in arcgis\features\geo\_io\fileops.py are unindented one level, the issue is resolved.  I'd put in a pull request, but the code isn't in the repository, so I can't make the change myself.

**Comment by AtmaMani** [comment]
@ATL2001 thanks! This looks like a bug, we will take a look.

**Comment by AtmaMani** [comment]
@ATL2001 a fix for this will be available in the next release of Python API.

**Comment by ATL2001** [comment]
excellent news! much appreciated
