### ISSUE TITLE
SpatialDataframe 'to_featuresclass' method, Fill np.nan values will ArcGIS 'null' values, not 0

### ISSUE THREAD

**Issue by nick-romano-kci** [Esri/arcgis-python-api#439]
I'd like to be able to place null values within float32/float64 columns of the dataframe.

Currently if a value is np.nan or 'None', the resulting feature class will fill those values with 0. I think they should fill with <NULL>, similar to how arcpy fills None with <NULL> in their cursors.

**Comment by achapkowski** [comment]
@nick-romano-kci can you post your code where you see this occurring?

**Comment by achapkowski** [comment]
closing due to no response.
