### ISSUE TITLE
Error in RasterManager.add() service_url parameter

### ISSUE THREAD

**Issue by earlmedina** [Esri/arcgis-python-api#444]
There's a minor error in the source code that causes RasterManager.add() to fail when using a service url.

**Example Script:**
```
from arcgis import GIS
conn = GIS("https://machine.domain.com", "admin", "password")
img = conn.content.search("imageservice")[0]
img_lyr = img.layers[0]
content = arcgis.raster.RasterManager(img_lyr)
content.add(service_url="https://sampleserver6.arcgisonline.com/arcgis/rest/services/CharlotteLAS/ImageServer", raster_type="Image Service")
```

**Fails with:**
RuntimeError: Invalid or missing input parameters.
(Error Code: 400)

**Cause:**
Slight mistake in source code for arcgis/raster/_layer.py.
On line 1623 in the __add_rasters_ function, service_url is set to a list:
`service_url = [service_url]`

This causes the function to fail. The line needs to be changed to:
`service_url = service_url`

After making that change the function works as expected.

**Comment by AtmaMani** [comment]
@earlmedina thanks for reporting, we will take a look at this.

**Comment by achapkowski** [comment]
@earlmedina this issue was addressed in the latest release. Thank you for reporting this.
