### ISSUE TITLE
map.draw create polygon from coordinates

### ISSUE THREAD

**Issue by gismcieri** [Esri/arcgis-python-api#446]
Hi,

I have tried various different formats to draw a polygon from coordinates and it keeps failing and saying its asking for a unicode string not a list but the help says to make a list of coordinate pairs.  Is it possible to get some assistance with the correct format.  

Fyi my over all goal is to draw the box get its centroid.

I most recent attempt is:
```
polygon = [[42.384623,-82.992670],[42.385585,-82.991273],[42.379144,-82.988897],[42.380106,-82.987500]]
map.draw(polygon)
```
Error:
```
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-8-c91a94b25397> in <module>()
----> 1 map2.draw(polygon)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\widgets\_mapview.py in draw(self, shape, popup, symbol, attributes)
   1230         else: # User passed in a string for interactive draw mode
   1231             self._trigger_interactive_draw_mode_for = ""
-> 1232             self._trigger_interactive_draw_mode_for = shape
   1233 
   1234     def _draw_featureset(self, fset, popup, symbol):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\traitlets\traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\traitlets\traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\traitlets\traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\traitlets\traitlets.py in validate(self, obj, value)
   2052                 msg = "Could not decode {!r} for unicode trait '{}' of {} instance."
   2053                 raise TraitError(msg.format(value, self.name, class_of(obj)))
-> 2054         self.error(obj, value)
   2055 
   2056 

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\traitlets\traitlets.py in error(self, obj, value)
    623             e = "The '%s' trait must be %s, but a value of %r was specified." \
    624                 % (self.name, self.info(), repr_type(value))
--> 625         raise TraitError(e)
    626 
    627     def get_metadata(self, key, default=None):

TraitError: The '_trigger_interactive_draw_mode_for' trait of a MapView instance must be a unicode string, but a value of [[42.384623, -82.99267], [42.385585, -82.991273], [42.379144, -82.988897], [42.380106, -82.9875]] <class 'list'> was specified.
```

Thanks,
Matt

**Comment by DavidJVitale** [comment]
Hi @gismcieri , try the following code to explicitly define a `Geometry` object and a `symbol` to draw it:

```
from arcgis.geometry import Geometry
from arcgis.mapping import create_symbol
```

```
from arcgis.gis import GIS
gis = GIS()
map = gis.map()
map
```

```
geom = Geometry({'spatialReference': {'latestWkid': 4326,
       'wkid': 4326},
      'rings': [[[-72.48642904188986, 26.14669683070787],
        [-72.48642904188986, 40.73987910899463],
        [-45.50400716689704, 40.73987910899463],
        [-45.50400716689704, 26.14669683070787],
        [-72.48642904188986, 26.14669683070787]]]})
symbol = create_symbol(geometry_type='polygon', cmap='Greens_r')
```

```
map.draw(geom, symbol=symbol)
```

![Screen Shot 2019-05-29 at 3 47 05 PM](https://user-images.githubusercontent.com/18691334/58596488-34a4db00-8229-11e9-8fc5-25c0aa2d41e0.png)

----

You can try substituting your own points into the JSON, but I'm not sure your points are a valid geometry object. A `Geometry` object has a `is_valid` function, and your polygon looks invalid:

![Screen Shot 2019-05-29 at 3 51 41 PM](https://user-images.githubusercontent.com/18691334/58596633-af6df600-8229-11e9-9be7-6f8d310588c2.png)

Let me know if you still can't figure it out, hope this helps!

**Comment by gismcieri** [comment]
Hi,

I still can't figure out why my polygon doesn't draw even when the geometry is valid.  

I have attached my note book.  I was able to create a point for each of the vertices and they all draw but i don't see why the polygon won't draw.

FYI i am parsing some XML to get the coordinates , The polygon vertices make a detailed polygon but the 
upper through lower lat long seem to form a box so those 4 points should be valid.
```
    <polygon_vertices>42.380564/-82.987816 42.380439/-82.987750 42.380172/-82.987723 42.379917/-82.987835 42.379714/-82.988070 42.379593/-82.988392 42.379572/-82.988752 42.379656/-82.989095 42.379830/-82.989370 42.384168/-82.992356 42.384426/-82.992454 42.384560/-82.992450 42.384815/-82.992338 42.384925/-82.992233 42.385091/-82.991949 42.385139/-82.991780 42.385160/-82.991420 42.385077/-82.991077 42.384902/-82.990803 42.380564/-82.987816</polygon_vertices>
    <upper_left_latitude>42.384623</upper_left_latitude>
    <upper_left_longitude>-82.992670</upper_left_longitude>
    <upper_right_latitude>42.385585</upper_right_latitude>
    <upper_right_longitude>-82.991273</upper_right_longitude>
    <lower_left_latitude>42.379144</lower_left_latitude>
    <lower_left_longitude>-82.988897</lower_left_longitude>
    <lower_right_latitude>42.380106</lower_right_latitude>
    <lower_right_longitude>-82.987500</lower_right_longitude>

```
Thank you for your assistance,
Matt
[MakeMap.zip](https://github.com/Esri/arcgis-python-api/files/3235164/MakeMap.zip)

**Comment by gismcieri** [comment]
Hi David,  

On a side question.  I don't think i am going to be able to make a map the way i was hoping but i did find a work around for what i need.  The map was just icing on the cake i would still like to know why it isn't working for me though.  

What i really need is the centroid of the polygon which i can get now (manually) thanks to you but i  need to do it programmatically.    

How do i get a variable in to the geometry function?
polygonvert = [[[42.380564,-82.987816],[42.380439,-82.987750],[42.380172,-82.987723],[42.379917,-82.987835],[42.379714,-82.988070],[42.379593,-82.988392],[42.379572,-82.988752],[42.379656,-82.989095],[42.379830,-82.989370],[42.384168,-82.992356],[42.384426,-82.992454],[42.384560,-82.992450],[42.384815,-82.992338],[42.384925,-82.992233],[42.385091,-82.991949],[42.385139,-82.991780],[42.385160,-82.991420],[42.385077,-82.991077],[42.384902,-82.990803],[42.380564,-82.987816]]]

That string works if i paste it in but not when i use the variable. I have tried a few different thing i have used in the past but it keeps coming back as invalid geometry type. Also please not the line below isn't all that a tried it just shows what i am trying to do the best.

geom = Geometry({'spatialReference': {'latestWkid': 4326, 'wkid': 4326}, 'rings': polygonvert})

Thanks again i am so close to what i need to do.
Matt

**Comment by achapkowski** [comment]
See: https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html#arcgis.geometry.Geometry.centroid
