### ISSUE TITLE
Using the API without having to install ArcPro

### ISSUE THREAD

**Issue by gaj995** [Esri/arcgis-python-api#448]
Hi, 

Is it possible to run the API without having to install ArcPro on the same machine? I want to utilize the API on a server which has python 3x and I can use pip to setup the API, but is the API similar to arcpy where you require the desktop for licensing or can you by pass this with the GIS connection to your portal/agol environment? 

Thanks

**Comment by achapkowski** [comment]
@gaj995 you do not need arcpy or arcgis pro to run the api.
