### ISSUE TITLE
Connection to GIS with proxy

### ISSUE THREAD

**Issue by geompc** [Esri/arcgis-python-api#455]
Working in a corporate environment with a proxy and the following code throws an error:
`source_gis = gis.GIS(source_gis_url, username, password, verify_cert=False, proxy_host='https://user:@pwd@proxyserver.domain.co.nz', proxy_port=8080)`

If I specify the proxy, prior to calling the GIS module using the following code, and removing the proxy parameters from the GIS call, it works fine:
`os.environ['https_proxy'] = "https://user:@pwd@proxyserver.domain.co.nz:8080"`

I'm trying to clone an item from ArcGIS Online to an internal Portal which is proving problematic as I need the proxy for external URLs but not for the internal Portal. I'm using v1.5.3 of the API.

**Comment by achapkowski** [comment]
For the proxy host, do not put the `https://` infront of the proxy URL.

**Comment by geompc** [comment]
Thanks, working now 👍
