### ISSUE TITLE
Clone_Items failing due to JSONObject Error

### ISSUE THREAD

**Issue by Bkella** [Esri/arcgis-python-api#458]
_**JSONObject["globalId"] not found.
_ItemCreateException: ('Failed to create Feature Service Leases: ERROR: Inconsistency in the Field Definitions found.\n(Error Code: 500)', <Item title:"Leases" type:Feature Layer Collection owner:bkeller>)**_

I am receiving this error for some feature layers and also a feature collection within a web map while cloning. Other feature layers and collections clone just fine when I try everything solo. To reproduce error, see these web services: 

https://services.arcgis.com/LkFvjvW56uBq4pMv/ArcGIS/rest/services

Specifically Facilities and Leases.

Thanks.

**Comment by achapkowski** [comment]
I was able to clone using ArcGIS API for Python v2.0.0, please retest and try again.  I also ensure I set copy_data=True.
