### ISSUE TITLE
arcgis.geometry.buffer: 'Unit' argument not honored

### ISSUE THREAD

**Issue by earlmedina** [Esri/arcgis-python-api#461]
There are a couple of problems with the arcgis.geometry.buffer function:
1. Unit values are not honored
2. The optional 'buffer_sr' parameter is required because of #1 (due to the order of operations for performing a buffer described here: https://developers.arcgis.com/rest/services-reference/buffer.htm). If 'buffer_sr' is not supplied you will encounter this error: 

> Unable to complete operation. Wrong unit type (expected linear unit, got angular unit, or vice versa)

The source of the problem is a very minor error in the 1.6.1 source code for the _buffer_ function in /arcgis/_impl/tools.py. On line 5559:
`params['units'] = unit`

Should be corrected to:
`params['unit'] = unit`

This update resolves the aforementioned problems and requests to /geometry are properly handled.

**Comment by achapkowski** [comment]
@earlmedina thank you for reporting the issues.  We have already caught these issues and are in the process of being put into a future release!
