### ISSUE TITLE
Can't overwrite a feature layer with new data in portal

### ISSUE THREAD

**Issue by billxu2007** [Esri/arcgis-python-api#462]
I tried to overwrite the feature layer data, failed. I tried both CSV published layer or GDB published layer.
items2 = gis.content.search('BST Données sur les événements de transport ferroviaire Tout', 'Feature Service')
myItem = items2[0]
display(myItem)
<Item title:"BST Données sur les événements de transport ferroviaire Tout" type:Feature Layer Collection owner:tc.smart.maps>

myItem_flayer_collection = FeatureLayerCollection.fromitem(myItem)
myItem_flayer_collection.manager.overwrite('TSBRailOccFre_all.csv')
{'error': 'Cannot find related data item used to publish this feature layer'}

**Comment by anthonyljones** [comment]
Any update on this?

**Comment by achapkowski** [comment]
I tried to reproduce your error using a CSV file I had and it worked without issue.  

The biggest gotcha with overwrite:

1. The file name needs to be exactly the same as the original file name
2. Ensure you can geocode locations.

```
gis = GIS(profile='your_online_profile')
item = gis.content.get("97c4e15a627d4cb79c205c93450b2e54") # Hosted Feature Layer Published from CSV file
fs = item.layers[0].container # Get the container.
fs.manager.overwrite(r"./nyc_musaems.csv") # Overwrite the CSV file
```

**Comment by anthonyljones** [comment]
Still not able to get this to work.

I'm also trying it with Jupyter notebook and am not having success.

https://developers.arcgis.com/python/sample-notebooks/overwriting-feature-layers/

Can you get the above example to work?

**Comment by cflann** [comment]
I have been unable to get this to work. I've ensured that the update file (feature class in gdb) has the same name as original. The overwrite returns "success", but the data does not change. I can get around this by using edit_features to delete and then add, but it's a clunky workaround.

**Comment by achapkowski** [comment]
@cflann please  open a new issue and post a reproducible sample, also include what version of the API, OS information, and arcgis software versions.
