### ISSUE TITLE
Notebook does not lead to try it live page

### ISSUE THREAD

**Issue by shub8703** [Esri/arcgis-python-api#468]
@AtmaMani @DavidJVitale 
The 'Try it live' link does not work on this notebook:
https://developers.arcgis.com/python/sample-notebooks/finding-routes-for-appliance-delivery-with-vrp-solver/

**Comment by achapkowski** [comment]
We will take a look. Thank you for reporting this.

**Comment by mohi9282** [comment]
@shub8703 - Given the number of samples we have on the developers' website, unfortunately, we have decided to include "Try it Live" buttons on specific samples that demonstrate the diverse functionalities of our api. To try the sample, please download the notebook, the data and try it on your machine.
