### ISSUE TITLE
Move talks folder to gh-pages branch

### ISSUE THREAD

**Issue by AtmaMani** [Esri/arcgis-python-api#473]
We need to shed some weight from the master branch of the repo. Currently, it is about `800`mb in size and `talks` folder alone is `~500`mb. As we keep giving more talks, this folder will only grow in size. 

What if we move the talks to the gh-pages branch? Since it is in the `gh-pages`, the GitHub server will give it a URL and users can download the talk - its pdf and notebooks directly without having to clone the full repo.  To help, we can make a simple HTML landing page inside the talks folder (which gets hosted) and list each talk.

We can zip up each talk so there aren't too many files to list in the HTML file. What are your thoughts?

**Comment by DavidJVitale** [comment]
@AtmaMani I think this is a great idea to move things out of master, this repo is getting too large. A few thoughts:

1) Do we move all talks, or only old talks to a new location? (uc2018 and uc2017, old dev summit talks, etc.)

2) We need to keep in mind users that have bookmarked URLs on github to a specific talk on master. Moving a talk will make these URLs invalid. Maybe we replace every file in the talks/ folder on master with a lightweight text document that points to the new branch location where the talk is? That way the URLs will still be valid, and will point the users to the new location.

3) As for the branch itself, I vote we move it to a new branch titled "conference_talks". In my view, hosting the `.ipynb` files on github-pages it outside of the scope of what github-pages is used for. Most users download or clone the talks to their computer, or preview the file itself in a browser.

**Comment by AtmaMani** [comment]
@DavidJVitale we can move all talks to `conference_talks` branch. Regarding (2), we could create a README file on the root talks folder on master saying that it is moved and a hyperlink. Do we need for each sub folder?

**Comment by DavidJVitale** [comment]
@AtmaMani Sounds good. I think we might need one for each sub-folder, or find a way to redirect URLs to that root README.md file. The end goal should just be a user that has this URL saved:

https://github.com/Esri/arcgis-python-api/blob/master/talks/uc2018/AnalysisAndDataScience/FindingCriticalBridges.ipynb

should not 404, but have some way of finding out where that talk is. I'll have to think about what's the best way to solve this problem.

**Comment by rohitgeo** [comment]
Also, GitHub renders notebooks in the repo and users need not download and launch these notebooks with the current way. This won't work with the gh-pages branch being served out over http(s).

**Comment by rwmajor2** [comment]
@AtmaMani @DavidJVitale I think @rohitgeo point is valid, although that hasn't been working for me lately (not sure why).  Another idea is to move most of this content to an S3 bucket and then reference the links in a Wiki page.

**Comment by achapkowski** [comment]
How about we create a new repository to hold the talks? LIke `arcgis-python-talks`?

**Comment by AtmaMani** [comment]
@rohitgeo posting notebooks to `conference_talks` would still have the same benefit (previewing without downloading)
@rwmajor2 I think an S3 bucket might be an overkill for this, but that is a good option to keep in mind. Likewise, @achapkowski a new repo might also be overkill. We like pointing users to a single repo to get all their SDK content.

**Comment by jyaistMap** [comment]
Closing this issue as the #478 has been merged.
