### ISSUE TITLE
New feature and functionality of 1.6.2 ?

### ISSUE THREAD

**Issue by Hiromu-Nakamura** [Esri/arcgis-python-api#475]
Hi,

Not sure if here is the right place to ask, so please tell me if there is another appropriate one. 
Currently, the release note is not updated after 1.6.1. It is helpful if we could know what feature and functionality have been added to the API.

Thank you,

**Comment by DavidJVitale** [comment]
Thanks for reporting @Hiromu-Nakamura , we will look into adding the release notes for v1.6.2. Sorry for any inconvenience.

**Comment by Hiromu-Nakamura** [comment]
@DavidJVitale Thank you very much for your response. Looking forward to see updated one.

**Comment by DavidJVitale** [comment]
@Hiromu-Nakamura the v1.6.2 release notes are live: https://developers.arcgis.com/python/guide/release-notes/

Sorry again for the inconvenience! Closing this issue.

**Comment by Hiromu-Nakamura** [comment]
@DavidJVitale Thank you so much for dealing with it so quickly!
