### ISSUE TITLE
Problem uploading file using absolute path (with workaround and code fix)

### ISSUE THREAD

**Issue by eykamp** [Esri/arcgis-python-api#481]
I found a bug in gis.content.add().  The particular code:

    if not os.path.isfile(os.path.abspath(data)): 
        raise RuntimeError("File("+data+") not found.")
  
What's happening here is the code is preparing to upload a file, and wants to make sure it exists before proceeding.  That's great when it works.

The data var contains the path to the file to be uploaded.  Unfortunately, abspath prepends the current working folder, which is often the folder where the local environment is based.  
This prepending only occurs when checking the existence of the file, and fails if you provide an absolute path to your data.  The fix would be to add "and not os.path.isfile(data)" to the end of the if statement.  

I do have a workaround, which is to replace the drive letter with  "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\" in data, which fools abspath into recognizing that the file exists.  This workaround is pretty lame, and should be fixed.

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.

**Comment by eykamp** [comment]
Reopening; this is a pretty specific and reproducible bug, which fails when using data with an absolute path.  There is an easy (albeit lame) fix.  If you want to close the issue, please fix the bug, or declare it isn't a bug, or something other than "it's old".

**Comment by nanaeaubry** [comment]
Ok thank you for reopening, we will take a look

**Comment by nanaeaubry** [comment]
A suggested fix for your issue is to use: f"./<file name>"
this will fix the issue. Thank you!

**Comment by eykamp** [comment]
I'm not going to reopen this, but this solution completely misses the point.  The code does not work with absolute paths, and telling me to just use a relative path does not fix the problem.  It's your code, and if you want to leave an obvious bug in it that is easy to fix, that helps explain why ESRI code is chronically buggy.

A proper solution would make the code work with absolute paths, even if it's just using the hacky solution I offered.
