### ISSUE TITLE
Performing-route-analyses (Solve Route) returns ALWAYS geometry with spatialRefernce = 4326 ,even though ouput_sr is set to WebMercator.

### ISSUE THREAD

**Issue by chritomix** [Esri/arcgis-python-api#487]
Issue:
 - when solving route where output spatial refernce is set to WebMercator, the output geometry contains wrong spatialRefernce = 4326 (or is not shown) , instead of 3857. But coordinates are correct.

Details
- If you run performing-route-analyses.ipynb, go to line "Drawing the result route on a web map as a layer"
- add to solve command "spatial reference" and set it to WebMercator
   result = route_layer.solve(….., out_sr = 3857)
 - check the result's geometry:
    result['routes']['features'][0]['geometry']
You will notice that spatialRefernce is either missing or is set to 4326(WGS84), though coordinates will be in WebMercator. This is wrong. This disables to show results on the map . Is that behaviour normal?
(the workaround is to create polyline feature and set correctly the spatial refernce)

[performing-route-analyses_modifiedWebMercator.zip](https://github.com/Esri/arcgis-python-api/files/3482214/performing-route-analyses_modifiedWebMercator.zip)

**Comment by chritomix** [comment]
Issue:
 - when solving route where output spatial refernce is set to WebMercator, the output geometry contains wrong spatialRefernce = 4326 (or is not shown) , instead of 3857. But coordinates are correct.

Details
- If you run performing-route-analyses.ipynb, go to line "Drawing the result route on a web map as a layer"
- add to solve command "spatial reference" and set it to WebMercator
   result = route_layer.solve(….., out_sr = 3857)
 - check the result's geometry:
    result['routes']['features'][0]['geometry']
You will notice that spatialRefernce is either missing or is set to 4326(WGS84), though coordinates will be in WebMercator. This is wrong. This disables to show results on the map . Is that behaviour normal?
(the workaround is to create polyline feature and set correctly the spatial refernce)

[performing-route-analyses_modifiedWebMercator.zip](https://github.com/Esri/arcgis-python-api/files/3482214/performing-route-analyses_modifiedWebMercator.zip)

**Comment by Yongyao** [comment]
@chritomix May I ask what is the spatial reference for your input stops: `stops = '''-3.203062,55.906437; -3.190080,55.935570'''` ? WebMercator?

**Comment by Yongyao** [comment]
@chritomix We did some debugging and confirmed this is a bug in our source code. Thanks for reporting this. The issue is that there are two inconsistent spatial reference in the solve result which confuses the map widget. A quick fix/workround is shown below. Feel free to let us know if there is any other questions.

![image](https://user-images.githubusercontent.com/5552606/63185598-42d7eb80-c00f-11e9-9663-f77d608258dc.png)

**Comment by chritomix** [comment]
Yongyao, thank you for letting me know, together with the snipet for workaround. Concerning your previous question I assume I dont need to anwser to it anymore as you confirm the bug.
Personally, in my opinion, the value of output SR should be depending on SR of network dataset (so no default value). Regards,
