### ISSUE TITLE
Create User Doesn't Send Email

### ISSUE THREAD

**Issue by nfink-nlt** [Esri/arcgis-python-api#492]
ArcGIS Python API v1.6.2

gis = GIS(portal=org.maps.arcgis.com, username=username, password=password)
gis.users.create(username='john.doe_ORG',password='password',firstname='John',lastname='Doe', email='john.doe@domain.com')

User is created, but no email is sent.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Pretty sure create sends user emails.  Create is actually used to pre-create accounts.  You would have to use arcgis.gis.invite to send an email I think

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Pretty sure create doesn't send user emails.  Create is actually used to pre-create accounts.  You would have to use arcgis.gis.invite to send an email I think

https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.UserManager.invite

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
When my admin account was created I never got an invite link. I was simply told about it.

**Comment by nfink-nlt** [comment]
Previously user creation generated an email, as noted in this issue: https://github.com/Esri/arcgis-python-api/issues/329

The code to send the email after creating the account is also present in the library at arcgis\gis\__init__.py at line 1931.

**Comment by nanaeaubry** [comment]
Is this for an Online or Enterprise account? An email text is only created for use with Online and will not be sent if using Portal.

**Comment by filipworksdev** [comment]
@nanaeaubry  This was an enterprise account and we had our ArcGIS enterprise server install. This was not using portal but ArcGIS does have it's own "portal" component even as enterprise server in which you create accounts. The accounts created would automatically email users but would not get invite links just told that someone created an account for them with no information. But the reply is way too late. I am no longer doing that job and no longer have access to that account. Was done back in May 2020.
