### ISSUE TITLE
The raster and polygon outputs of the model are inverted relative to each other.

### ISSUE THREAD

**Issue by rfairhurst** [Esri/arcgis-python-api#493]
The illustrations of the raster output of the model and the polygon output of the modelbuilder process are inverted vertically relative to each other.  I assume that is not actually what happened and that the orientations of the output raster and output polygons matched each other.  Please correct the images so that they both show the buildings oriented the same way.

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
