### ISSUE TITLE
Advanced Search Doesn't Work

### ISSUE THREAD

**Issue by nfink-nlt** [Esri/arcgis-python-api#499]
**Describe the bug**
Advanced search returns an error seeking more parameters.

**To Reproduce**
```python
gis = GIS(portal=portal, username=username, password=password)
search = gis.content.advanced_search(query='', max_items=100, start=x, as_dict=False, bbox=None, categories=None)

```
error:
```python
RuntimeError: Unable to perform search.
'q', 'bbox' or categories parameter must be specified.
(Error Code: 400)
```

**Expected behavior**
Return a list of items

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 1.6.2

**Comment by nanaeaubry** [comment]
Upgrading to arcgis 2.0.0, you can use: `search = gis.content.advanced_search(query='*', max_items=100)` without getting an error

**Comment by mtgovjesse** [comment]
The error still happens with an empty query string, like in the example above. I don't know if that's necessarily a bug or if empty query strings just aren't supported by advanced_search, but maybe this issue needs to be re-opened.

**Comment by mtgovjesse** [comment]
How do you query all items in your server, with advanced_search so that you can use pagination?

**Comment by nanaeaubry** [comment]
@mtgovjesse 
You're right you have to do "1=1" not "*". This is a convention from the REST API
