### ISSUE TITLE
GeoAnalyticsTools Invalid URL path to BigData features

### ISSUE THREAD

**Issue by mindzia** [Esri/arcgis-python-api#5]
Set up Portal 10.5 Beta with ArcGIS Python API on the same machine.
Trying to test GeoAnalyticsTools BigData sample on Jupyter Notebook
Configured BigData NYCTaxi data. URL: https://mportal.hnit-baltic.lt/arcgis/rest/services/DataStoreCatalogs/bigDataFileShares_bdfs2/BigDataCatalogServer/NYCTaxi

from arcgis.gis import GIS
from arcgis.viz import MapView
from arcgis.tools import GeoAnalyticsTools

gis = GIS("https://mportal.hnit-baltic.lt/arcgis/", "admin_user", "admin_pass")
gae = GeoAnalyticsTools("https://mportal.hnit-baltic.lt/arcgis/rest/services/System/GeoAnalyticsTools/GPServer", gis)
maxTip = gae.aggregate_points_by_bins("https://mportal.hnit-baltic.lt/arcgis/rest/services/DataStoreCatalogs/bigDataFileShares_bdfs2/BigDataCatalogServer/NYCTaxi", None, "5 Kilometers", "1 Weeks", "1 Months", "1/1/2014", "tip_amount MAX")

Returns: Invalid URL
See attached image.

Have tried other tools: describe_dataset, list_bigdata_datasets. 
What is correct parameters in gae.aggregate_points_by_bins(in_points...., )?

![jupyter_notebook_geoanalyticstools](https://cloud.githubusercontent.com/assets/12560743/18081792/9ac49006-6ea4-11e6-9404-410d54baff69.jpg)

Regards,
Mindaugas

**Comment by rohitgeo** [comment]
@mindzia thank you for reporting this - this issue has been resolved in v0.3-beta released last week.
