### ISSUE TITLE
Unable to launch jupyter lab/notebook off python command prompt

### ISSUE THREAD

**Issue by kamosuela** [Esri/arcgis-python-api#502]
I followed the steps in https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/ and still, the command "jupyter lab" and "jupyter notebook" produces nothing, i.e. the command prompt pauses for a while and then just goes to another line without any comments or evidence that anything has run.

**Comment by PerAkeMattias** [comment]
@kamosuela try starting Jupyter using one of these commands instead:
`python -m jupyter lab`
or 
`python -m jupyter notebook`
