### ISSUE TITLE
No way to update_group fields to empty strings "" or spaces "    "

### ISSUE THREAD

**Issue by ghost** [Esri/arcgis-python-api#510]
**Describe the bug**

`gis._portal.update_group(id, description="") ` will not update the description because an empty string "" is same as None making the code ignore 

Additionally
`gis._portal.update_group(id, description="       ") ` will also fail probably because space is trimmed in the url 

**To Reproduce**
use the function passing an empty string to any field see if the groups update

error:
no error. It simply doesnt do what is supposed to do

**Expected behavior**
There should be a way to update a field to empty string or strings with spaces.

**Platform (please complete the following information):**
 - Python API Version   1.6.2-post1

**Comment by achapkowski** [comment]
Have you tried doing group.update?  Is this on Portal or ArcGIS Online?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@achapkowski  Hi, thank you for your reply. Yes I have tried using group.update and exact same issue. 

See the anim below for proof
![proof](https://user-images.githubusercontent.com/36826319/65261179-a99c6900-dad5-11e9-8d97-43a98b4b5f35.gif)

Ignore the multiple true values. Is part of a script that changes every entry so it literally does that script 7 times for each entry in a csv. Regardless. Is not setting empty string "" and same issue with "    " strings with spaces. 

```
g = arcgis.gis.Group(gis, arcgis_group["id"])
res = g.update(description="")
print(res)
```

returns true not nothing is changed

```
g = arcgis.gis.Group(gis, arcgis_group["id"])
res = g.update(description="a")
print(res)
```

returns true and description is now "a"

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
My guess is that function was over-optimized to update ONLY the appropriate fields ignoring None positional values but seems case of the empty string "" was never considered. It appears in Python "" is None.  I cannot explain why " " is also not working but I see there is a trim function in the api url backend call which would mean the issue is the server or portal itself treats empty strings as no update.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
A coworker has informed me there are many other functions that ignore  "" or " " but has found sometimes `None` appears to work. I have tried `gis._portal.update_group(id, description=None) ` still doesn't work.

**Comment by achapkowski** [comment]
```group.update(description="", clear_empty_fields=True)```
will set it to empty string.
