### ISSUE TITLE
'portalName' error

### ISSUE THREAD

**Issue by CheckMinus** [Esri/arcgis-python-api#517]
If you try to connect to an ArcGIS Server using GIS from arcgis.gis you get an error regarding the ‘portalName’ key doesn’t exist.  

It appears that when you attempt to connect to an ArcGIS Server the _product_version is None so the 'portalName' key doesn't exist.

Our temporary fix was to comment out lines 451-453 
…\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\arcgis\gis\__init__.py.  It appears the _product_version is only called here and never used again in the code.

**Comment by CheckMinus** [comment]
https://github.com/Esri/arcgis-python-api/issues/440

**Comment by achapkowski** [comment]
You do not connect to a server using the GIS object.
