### ISSUE TITLE
publish_sd() results in "AttributeError: 'NoneType' object has no attribute 'folders'"

### ISSUE THREAD

**Issue by 2Dews** [Esri/arcgis-python-api#519]
I have a valid sd file that I can publish manually from ArcMap and from the web interface. When I try and publish via the arcgis version 1.6.2 (as well as 1.6.2.post1) I get an error. 

```python
from arcgis.gis.server import Server
serverUrl = "http://ourserver.com/arcgis"
mapServiceSDFilePath = "C:/Users/me/important/surface_query.sd"
server = Server(url="{}/admin".format(serverUrl), 
                tokenurl="{}/rest/generateToken".format(serverUrl),
                username="superdooper", password="password1")
server.publish_sd(mapServiceSDFilePath, "importantservice")
```
error:
```python
AttributeError                            Traceback (most recent call last)
c:\users\thing.py in ()
----> 1 server.publish_sd(mapServiceSDFilePath, "importantservice")

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\arcgis\gis\server\admin\administration.py in publish_sd(self, sd_file, folder)
    159             return False
    160         catalog = self._catalog
--> 161         if 'System' not in catalog.folders:
    162             return False
    163         if folder and \

AttributeError: 'NoneType' object has no attribute 'folders'
```

**Expected behavior**
The connection is good, I can create a folder with 
```python
server.services.create_folder(serviceFolder, description="")
```  
so I know the connection is good. Since the sd file can be published manually 
I would expect the map service to be published via the api. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Python API Version 1.6.2 and 1.6.2.post1

**Additional context**
The SD file can be published from the web interface. I also tried various flavors of the sd file including not putting the service in a folder all returned the same error.

**Comment by achapkowski** [comment]
this has been addressed in a future release (v1.8.0)
