### ISSUE TITLE
Updating services - JSON or Object?

### ISSUE THREAD

**Issue by m1ckr1sk** [Esri/arcgis-python-api#520]
## Description
When updating services (for our example we are adding and enabling extensions) the edit function requires the json representation of the service.  However, the only way to get this is to use the private _json property.  

```python
workflow_server = get_workflow_server(my_gis, workflow_url)
workflow_service_folders = workflow_server.services.folders
for workflow_service_folder in workflow_service_folders:
  workflow_services_in_folder = workflow_server.services.list(workflow_service_folder)
  for workflow_service in workflow_services_in_folder:
    jsonString = workflow_service._json
    serviceJson = json.loads(jsonString)
    
    # is extension present? 
    if hasExtension(serviceJson["extensions"]):
      for i in range(len(serviceJson["extensions"])):
        if serviceJson["extensions"][i]["typeName"] == extIName:
          # Switch between false/off 
          if serviceJson["extensions"][i]["enabled"] == 'false':
            serviceJson["extensions"][i]["enabled"] = 'true'
            break
            serviceJson["extensions"][i]["enabled"] = 'false'
            break
         else:
           # Append extension object to it
           serviceJson["extensions"].append(extensionJson)
 
        # Convert service json back to string
       newServiceJson = json.dumps(serviceJson)
       
       # Execute edit. 
       workflow_service.edit(newServiceJson);
```

## Possible resolution
Could the access to the json representation of the service be a public property?

## Alternatives
Instead of passing the json object into edit function, pass the entire service object in.  However, to do this a number of other methods would need to be added to allow easier editing of the service object, such as access to add,/remove/update extensions.

## Notes
Tested on 1.6.2

**Comment by CMPeng** [comment]
@m1ckr1sk Can you please try replacing these three lines -
```
for workflow_service in workflow_services_in_folder:
        jsonString = workflow_service._json
        json.loads(jsonString)
```
with 
```
    for workflow_service in workflow_services_in_folder:
        serviceJson = workflow_service.properties
```
Instead of getting the hidden JSON representation of the server properties, you want to get the dict object directly. Please let us know how it works, thanks!
