### ISSUE TITLE
IndexError: list index out of range while using gis.content.search

### ISSUE THREAD

**Issue by JanineCHEN** [Esri/arcgis-python-api#522]
**IndexError: list index out of range**
I am encountering  IndexError while trying to run gis.content.search in one of the provided samples, to be specific:
_detecting_swimming_pools_using_satellite_image_and_deep_learning.ipynb_

**To Reproduce**
```python
from arcgis import GIS
user_name = 'arcgis_python'
password = 'P@ssword123'
gis = GIS('https://www.arcgis.com', user_name, password)
pool_bb = gis.content.search("SwimmingPoolLabels", item_type='Feature Layer Collection')[0]
pool_bb
```
**Error:**
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-20-6beaf1e7bdf6> in <module>
----> 1 pool_bb = gis.content.search("SwimmingPoolLabels", item_type='Feature Layer Collection')[0]
      2 pool_bb

IndexError: list index out of range
```
**Screenshots**
![image](https://user-images.githubusercontent.com/37527041/66379106-6bfd7280-e9e7-11e9-99cb-11f203771e3a.png)

![image](https://user-images.githubusercontent.com/37527041/66379278-b7178580-e9e7-11e9-8622-b30a6ca746b4.png)

**Platform:**
 - OS: [Windows]
 - Browser [chrome]
 - Python API Version [`1.6.2-post1`] 

Can anyone shed some light on this issue, many thanks!

**Comment by kohn1001** [comment]
Experiencing the same issue on Mac

**Comment by achapkowski** [comment]
It has nothing to do with the OS, the item can't be found, just print out the results without the index value.

**Comment by achapkowski** [comment]
@AtmaMani can you please look at the data and ensure it's on the test site?

**Comment by FarFromBoston** [comment]
Did you ever find a solution?
im trying to do the tutorial here:
https://developers.arcgis.com/python/sample-notebooks/land-cover-classification-using-unet/

and when you do the first bit :
--------------------------------------------
label_layer = gis.content.search("title: Kent_county_full_label_land_cover owner:api_data_owner", 
                                 "Map Image Layer")[0] # the index might change
label_layer
--------------------------------------------

you immediately get:       IndexError: list index out of range

**Comment by nanaeaubry** [comment]
Tested and works, the data is up to date and shows the correct output:
![image](https://user-images.githubusercontent.com/19919283/162471912-8dc94aa3-00b3-4c38-a613-d2c9c61c6a7c.png)
