### ISSUE TITLE
geometry.buffer malfunctioning

### ISSUE THREAD

**Issue by DanCranford** [Esri/arcgis-python-api#523]
I'm getting errors with geometry functions (buffer, generalize) after upgrading to version 1.6.2.  The following code will work on version 1.6.1, but returns a RuntimeError on version 1.6.2.

**To Reproduce**
```python
import arcgis
point = arcgis.geometry.Point({'x': '768727.2590672647',
                               'y': '4165411.8416050677'})
buffer = arcgis.geometry.buffer([point],
                                26910,
                                unit = 'METERS',
                                distances = 200)
```
error:
```python
RuntimeError: Unable to complete operation.
The operation cannot be performed on a non-simple geometry.
(Error Code: 400)
```

I'm running this on windows in an environment with version 1.6.2 of the arcgis api.  I have a different environment with version 1.6.1 that will return buffered geometry with this code.  This behavior seems to be consistent across geometry types.

I'm getting a similar error with the geometry.generalize tool

**Comment by achapkowski** [comment]
I'll take a look. thanks

**Comment by achapkowski** [comment]
You need to change the `unit` value from `meters` to 9001.
See: http://resources.arcgis.com/en/help/arcobjects-cpp/componenthelp/index.html#/esriSRUnitType_Constants/000w00000042000000/
