### ISSUE TITLE
gis.admin.system.properties setter bug

### ISSUE THREAD

**Issue by nfink-nlt** [Esri/arcgis-python-api#524]
**Describe the bug**
Code uses 'get' instead of 'post'

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version 1.6.2

**Additional context**
Begins at line 122 in arcgis\gis\admin\system.py, correct code should be:
`
url = "%s/properties/update" % self._url
params = {"f" : "json", "properties" : properties}
self._con.post(path=url, postdata=params)
`

**Comment by AtmaMani** [comment]
@nfink-nlt I don't think this is a bug. Setters typically use POST and Getters use GET. Can you elaborate more?

**Comment by nfink-nlt** [comment]
The production code uses GET at version 1.6.2 when it should be using POST.

**Comment by AtmaMani** [comment]
You are right, this was fixed recently and should be available in v1.7.0
