### ISSUE TITLE
Where is the doc for Prerelease

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#530]
**Describe the bug**

**To Reproduce**
```python
<insert your code here>
```
error:
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**

**Platform (please complete the following information):**
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by AtmaMani** [comment]
@guyn2gis I guess you noticed the v1.7.0 on the conda channel with `prelease` label and asking about that. We will finalize 1.7.0 and publish it by the end of Oct. If you are looking for docs, the `master` branch of this repo has all the docs.
