### ISSUE TITLE
Arcgis Python Api on Azure Databricks

### ISSUE THREAD

**Issue by ghost** [Esri/arcgis-python-api#531]
**Is your feature request related to a problem? Please describe.**
I would like to have arcgis in Azure Databricks, run on Spark. I am aware that GeoAnalytics Server has support for big data processing, and contain tools that run on Spark. However, can we bring the tools into Databricks?

**Describe the solution you'd like**
I would like to know if there is any support for Databricks or if this feature is considered "work in progress". 

**A side note:**
Please note that our data science team is leveraging Azure Databricks for big data processing and machine learning training/inference.

Thank you

**Comment by AtmaMani** [comment]
@issa-s-ayoub we will discuss this internally and post and update

**Comment by pcdcvx** [comment]
@AtmaMani - is there an update for this? A process (without extensive use of the ArcGIS API for Python) was published recently.

https://github.com/mraad/spark-esri/blob/master/spark_dbconnect.ipynb

**Comment by pcdcvx** [comment]
@skalisky Hi Shannon - the use of the ArcGIS API for Python has been demonstrated in Azure Databricks and also from ArcGIS Pro notebooks using Databricks Connect. Are you aware of any limitations to the use of the API for data engineering workflows?

**Comment by nanaeaubry** [comment]
Hello, closing this issue since we have discussed internally, made note of the enhancement, and will be working on this in the coming releases. Thank you for your suggestion.
