### ISSUE TITLE
Type error prevents "arcgis.gis.admin.PortalLicense" from working properly

### ISSUE THREAD

**Issue by earlmedina** [Esri/arcgis-python-api#537]
**Describe the bug**
There's a very minor syntax issue that prevents "arcgis.gis.admin.PortalLicense" from working properly (arcgis/gis/admin/_system.py)

**Platform (please complete the following information):**
 - RHEL 7/Windows 10
 - Chrome/Firefox
 - Python API Version 1.6.2

**To Reproduce**
```python
import arcgis
url="https://machine.domain.com/portal"
username="hari"
password="seldon"
gis = arcgis.gis.GIS(url, username, password)
portaladminurl = "https://machine.domain.com/portal/portaladmin"
test = arcgis.gis.admin.PortalLicense(portaladminurl, gis)
```
Produces the error:
**NameError: name 'License' is not defined**

**Screenshots**
![image](https://user-images.githubusercontent.com/29366220/67720835-4cc48600-f992-11e9-8172-4932811ec488.png)

**Solution**
At first, I thought the problem was due to a missing import statement for the License class:
`from ._license import License`

But this then produced this error:
![image](https://user-images.githubusercontent.com/29366220/67720945-9319e500-f992-11e9-9ed5-3f8a4d82996a.png)

The real cause of the issue is the `Super` syntax used when initializing the PortalLicense object.
Changing the format from super(Derived, self).__init__() to  super().__init__() resolves the issue:

![image](https://user-images.githubusercontent.com/29366220/67721138-0de30000-f993-11e9-86e4-81542fa41cf2.png)

![image](https://user-images.githubusercontent.com/29366220/67721447-c7da6c00-f993-11e9-968b-4df29027afc5.png)

**Comment by jyaistMap** [comment]
Thanks @earlmedina 
We've submitted a PR to fix this for the next release.
