### ISSUE TITLE
Make ArcGIS Server site healthcheck accessible - if not already?

### ISSUE THREAD

**Issue by pcsswamin** [Esri/arcgis-python-api#538]
Is  https://<host>/<instance>/rest/info/healthCheck  accessible via this api? if yes, can you please direct me towards it? 

I am only dealing with a standalone ArcGIS Server? no portal involved?

**Comment by CMPeng** [comment]
@pcsswamin Unfortunately, there is currently no Python API function that supports `healthCheck`, and no short-term plan in developing one. You might want to try a workaround, as to write your own function in supporting this, e.g.

```
# importing the requests library 
import requests 

def health_check_post_requests(server_url):
    # defining the api-endpoint  
    API_ENDPOINT = server_url + "/rest/info/healthcheck"

    # data to be sent to api 
    data = {'f':'html'} 

    # sending post request and saving response as response object 
    r = requests.post(url = API_ENDPOINT, data = data) 

    # extracting response text  
    print(r.status_code, r.reason)
    pastebin_resp = r.text 
    print("The pastebin response is:%s"%pastebin_resp) 
```
Please let us know how this works out for you. thanks!
