### ISSUE TITLE
ProfileManager.save_as()  - Local variable referenced before assignment.

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#543]
API 1.7

When trying to save_as() to a new profile the code references an unassigned config variable.

![save_as](https://user-images.githubusercontent.com/889468/68389008-35d81d80-0162-11ea-9dfc-73c590a94078.PNG)

**Comment by AtmaMani** [comment]
@HakonD I can reproduce this bug and have fixed it. It will be available in the next release.
