### ISSUE TITLE
Deep Learning graphic card requirement - CUDA Compute capability

### ISSUE THREAD

**Issue by holubvl3** [Esri/arcgis-python-api#544]
Hello,

I would like to ask, what is the minimal requirement to graphic card for deep learning in Esri (Python API learn module / ArcGIS PRO - Deep learning tools). 

I have installed as documented - fastai=1.0.39 pytorch=1.0.0 torchvision, and it seems that everything works well. The probelm begins with data.show_batch() where I get error - **_Found GPU0 Quadro K4000 which is of cuda capability 3.0_**

It seems, that this GPU is no longer supported by underlying PyTorch. Esri documentation states, that CC 3.0 is required - this seems to be a bug in docuemntation.

Thank you.

Vladimir

**Comment by achapkowski** [comment]
@Yongyao please verify the documentation is or is not correct.

**Comment by CMPeng** [comment]
@priyankatuteja Can you please provide some leads onto this issue? Thanks!

**Comment by priyankatuteja** [comment]
@holubvl3 Could you point me to  Esri documentation that states CC 3.0 is required.

**Comment by holubvl3** [comment]
Dear @priyankatuteja, because the only requirements about CC 3.0 is in Spatial Analyst page, we take over this recommnedation for whole PRO, since there is no infomation about such requriements for Image analyst nor Deep Learning toolset.

**Comment by priyankatuteja** [comment]
Hi @holubvl3, Spatial Analyst requirements are only applicable for spatial analyst tools and ArcGIS Pro. The requirements for the deep learning support in ArcGIS API for Python are coming from the pytorch 1.0.0 and fastai 1.0.39 dependencies.

**Comment by priyankatuteja** [comment]
As per Pytorch 1.0.0 release notes, it supports  CC 6.0 and higher. Please refer to the GPU requirements section in [Pytorch 1.0.0 release notes](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_19-01.html#rel_19-01).

**Comment by holubvl3** [comment]
Dear @priyankatuteja, thank you for clarification. I understand that, but it would be great to have the information also in ArcGIS PRO - Deep Learning toolset/Python/ArcGIS PRO requirements API learn module.

**Comment by holubvl3** [comment]
@priyankatuteja  thank you for the documentation. So there is a big update between version PRO 2.4, where some older Pytorch was used, because GPU (Quadro M2000) with CC 3.5 works fine in deep learning toolset.

So now in 2.5 do we need GPU with minimal CC 6.0, since there will be used the Pytorch 1.0.0?  Is that correct?

**Comment by priyankatuteja** [comment]
Hi, @holubvl3 Thanks for your feedback! It is a good suggestion to have this required information in ArcGIS Pro as well. Additionally, It is correct that CC for Pro 2.5 is 6.0 since  Pro 2.5 uses pytorch1.1.0, not 1.0.0. The requirement again comes from PyTorch.

**Comment by holubvl3** [comment]
Dear @priyankatuteja, thank you so much for clarification and consideration about updating the documentation.

**Comment by scdub** [comment]
@holubvl3 I realize this is an old thread, but since then [we've added explicit GPGPU requirements to the Pro help](https://pro.arcgis.com/en/pro-app/latest/get-started/arcgis-pro-system-requirements.htm#GUID-B8F08895-1162-47A5-B2A0-2B8D5550155E) which include details on the supported compute level. We still support back down to CC 3.7 cards as of the Pro 3.1 release.

**Comment by holubvl3** [comment]
That´s great. Thank you @scdub!
