### ISSUE TITLE
Issues Logging In with Logging In

### ISSUE THREAD

**Issue by guyn2gis** [Esri/arcgis-python-api#546]
We have Active directory and Built In accounts, and our built in accounts are causing issues when logging in, where we cannot generate a token and thus fail to login.  Is there a License level that is needed to run the arcgis api.  I have no issue, but a user at the city is seeing issues.  Any ideas.  I am an admin, and he is not.

**Comment by guyn2gis** [comment]
This is the error.

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-d51495f0baac> in <module>
----> 1 gis = GIS("https://www.arcgis.com", "mdroberts18", "nora11406!")

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\gis\__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
    332                                    "argument when connecting to the GIS.")
    333             else:
--> 334                 raise e
    335         try:
    336             if url.lower().find("arcgis.com") > -1 and \

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\gis\__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
    320                                            verify_cert=self._verify_cert,
    321                                            client_id=self._client_id,
--> 322                                            referer=self._referer)
    323 
    324             if not (self._utoken is None):

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\portalpy.py in __init__(self, url, username, password, key_file, cert_file, expiration, referer, proxy_host, proxy_port, connection, workdir, tokenurl, verify_cert, client_id)
    161                                              proxy_port=proxy_port,
    162                                              verify_cert=verify_cert,
--> 163                                              client_id=client_id)
    164         #self.get_version(True)
    165         self.get_properties(True)

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\connection.py in __init__(self, baseurl, tokenurl, username, password, key_file, cert_file, expiration, all_ssl, referer, proxy_host, proxy_port, connection, verify_cert, client_id)
    306 
    307         if cert_file is None and key_file is None:
--> 308             self.login(username, password, expiration, client_id)
    309 
    310     #----------------------------------------------------------------------

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\connection.py in login(self, username, password, expiration, client_id)
    557 
    558             if username is not None and password is not None:
--> 559                 newtoken = self.generate_token(username, password, expiration, client_id)
    560 
    561                 if newtoken:

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\connection.py in generate_token(self, username, password, expiration, client_id)
    422                 if self.baseurl.endswith('/'):
    423                     resp = self.post('generateToken', postdata,
--> 424                                      ssl=True, add_token=False)
    425                 else:
    426                     resp = self.post('/generateToken', postdata,

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\connection.py in post(self, path, postdata, files, ssl, compress, is_retry, use_ordered_dict, add_token, verify_cert, token, try_json, out_folder, file_name, force_bytes, add_headers)
   1175                                          verify_cert=verify_cert, is_retry=True)
   1176 
-> 1177                 self._handle_json_error(resp_json['error'], errorcode)
   1178                 return None
   1179 

C:\Users\tcronine\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone4\lib\site-packages\arcgis\_impl\connection.py in _handle_json_error(self, error, errorcode)
   1196 
   1197         errormessage = errormessage + "\n(Error Code: " + str(errorcode) +")"
-> 1198         raise RuntimeError(errormessage)
   1199 
   1200 class _StrictURLopener(request.FancyURLopener):

RuntimeError: Unable to generate token.
Invalid username or password.
(Error Code: 400)

**Comment by CMPeng** [comment]
@guyn2gis 
What's your domain name? Can you please try the command again, but with domain attached before the appearance of the user name, e.g.
`gisldap = GIS("https://portalname.domain.com/webadapter_name", "DomainName\\UserName", "password")`
More, please refer to https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/

**Comment by achapkowski** [comment]
Closing due to lack of response
