### ISSUE TITLE
could not convert string to float in prepare_data function in module arcgis.learn

### ISSUE THREAD

**Issue by coni99** [Esri/arcgis-python-api#561]
**Describe the bug**
Due to my Slovak locale settings my system is using comma (,) in float number values. But the code to convert a string to float using float() function requires a dot (.) value. 

**To Reproduce**
```python
https://learn.arcgis.com/en/projects/use-deep-learning-to-assess-palm-tree-health/
https://downloads.esri.com/learnarcgis/use-deep-learning-to-assess-palm-tree-health/deeplearning.zip
```
error:
```python
could not convert string to float: '395,31'
```
**Screenshots**
![Snímka+obrazovky+(15)](https://user-images.githubusercontent.com/34895999/69501437-349a4500-0f05-11ea-982e-7ec158837d0c.png)

**Expected behavior**
I believe the user should not handle this type of error simply because the code is not written well. There should be a some kind of pre-check function that determines what locale is being used in the system and based on that a numerical value representation of arcgis API should be adjusted automatically. So that a user should not dwelve for 2 weeks the root of this problem just to find out that his locale has to be changed to some friendly country code as depicted here by a blue color https://upload.wikimedia.org/wikipedia/commons/a/a8/DecimalSeparator.svg

**Platform (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Chrome latest
 - Python API Version 1.6.2

**Additional context**
Whole problem is described at the bottom of this issue: https://community.esri.com/message/890543

**Comment by CMPeng** [comment]
@priyankatuteja  Can you please take a look at this issue and see if it is a bug that needs quick fix? thanks!

**Comment by priyankatuteja** [comment]
@CMPeng This issue needs fix in export training data tool in Pro,  Python API does not need any fix.  Sangeet Mathew could look into this issue.

**Comment by CMPeng** [comment]
Thanks @priyankatuteja  - Do you mind closing this issue when it is done fixing, or being migrated to backlogs for ArcGIS Pro?

**Comment by priyankatuteja** [comment]
You're Welcome! No worries @CMPeng I will do that as it gets fixed. Will also migrate it to Pro team backlogs.

**Comment by kuttamuwa** [comment]
Wasn't fixed yet, i guess. Can you give the solution? At least we don't wait for you to do.

**Comment by priyankatuteja** [comment]
@kuttamuwa You could try this workaround https://community.esri.com/t5/imagery-and-remote-sensing/deep-learning-to-assess-palm-tree-prepare-data-problem/m-p/411499/highlight/true#M3770
