### ISSUE TITLE
Update Group User Role

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#563]
I would like to be able to update a user's role in a group to be a Group Manager. I currently have a script reassigning ownership of all AGOL groups to our admin account, but I would like for the old owner to still be a group manager. I currently have to manually do this since there is no way to do it with the API.

I've also made an ArcGIS Idea: https://community.esri.com/ideas/17280-update-group-role-python-api

**Comment by CMPeng** [comment]
@BrettFrahm 
There is currently no short-term plan for adding the `update user role` function into the Group Module. You might want to consider using these workarounds:
1. To remove the user (whose role is group user) from the group, and invite it back into the group as group_admin: e.g.
```
group_obj.remove_users(['user_a'])
group_obj.invite_users('user_a', role='group_admin')
```
2. Or you can wrap up the POST request directly, such as:
```
# importing the requests library 
import requests 
def update_admins_post_requests(group_obj, gis, username):
    # defining the api-endpoint  
    API_ENDPOINT = "<REST API end node>/community/groups/{}/updateUsers".format(group_obj.id)

    # your API key here 
    API_KEY = '<your web_app_token>'

    # data to be sent to api 
    data = {'api_dev_key':API_KEY, 
                'admins':username, 
               'f':'json'} 

    # sending post request and saving response as response object 
    r = requests.post(url = API_ENDPOINT, data = data) 

    # extracting response text  
    print(r.status_code, r.reason)
    pastebin_resp = r.text 
    print("The pastebin response is:%s"%pastebin_resp) 
```
Please let us know how these approaches work for you. In the meantime, will discuss with the team to see if there are similar requests coming in asking for the API function.

**Comment by BrettFrahm** [comment]
@CMPeng 

Both of those workarounds look excellent, I'll test these soon. Thank you for the reply and for looking into this. It would be nice to have a straightforward function for this, but these workarounds look satisfactory for the short-term.
