### ISSUE TITLE
Error in Visualizing Route Layer on Arcpy Jupyter Notebook. (ArcGis)

### ISSUE THREAD

**Issue by Sudeepa14** [Esri/arcgis-python-api#567]
I tried to visualized route between two points using arcpy in jupyter notebook. Network module is activated in my esiri account. Even though it visualizes the map I cant see the route on that as the [tutorial][1] shows. Can someone help me here? Here is the code i used. I guess the problem with visualization. However I can see the following message on the console.
`[esri.views.LayerViewFactory] Failed to create view for layer 'Terrain3D, id:worldElevation' of type 'elevation'`.[![enter image description here][2]][2] (I tried with both **windows, linux, and [notebook.esiri.com][3]** environments and the results is still the same )

    from copy import deepcopy
    from datetime import datetime
    from IPython.display import HTML
    import json
    import pandas as pd
    from arcgis.gis import GIS
    import arcgis.network as network
    import arcgis.geocoding as geocoding

    user_name = 'user'
    password = 'pw'
    my_gis = GIS('https://www.arcgis.com', user_name, password)

    route_service_url = my_gis.properties.helperServices.route.url
    route_service = network.RouteLayer(route_service_url, gis=my_gis)

    stops = '''-3.203062,55.906437; -3.190080,55.935570'''

    route_layer = network.RouteLayer(route_service_url, gis=my_gis)
    result = route_layer.solve(stops=stops, 
                           directions_language='en-US', 
    return_routes=True,
                           return_stops=True, return_directions=False,
                           return_barriers=False, 
    return_polygon_barriers=False,
                           return_polyline_barriers=False)

    my_map = my_gis.map('Braidburn Valley', zoomlevel=13)
    my_map

  [1]: https://developers.arcgis.com/python/guide/performing-route-analyses/
  [2]: https://i.stack.imgur.com/61u0P.png
  [3]: https://notebooks.esri.com/

**Comment by AtmaMani** [comment]
@Sudeepa14  in your snippet, you are not adding the computed route to the map. You are stopping at creating and displaying an empty map.

Further, try the new and revised doc at https://developers.arcgis.com/python/guide/part2-find-routes/ Please Reopen this issue if you still run into issues/
