### ISSUE TITLE
Add Web Layer - Stored Credentials

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#569]
How would I be able to Add a web item to arcgis online with stored credentials using the python api?

I've looked through the documentation found publish(), add(), and register(), but I did not see anything about being able to store credentials? Thanks!

**Comment by BrettFrahm** [comment]
Issue closed. An ESRI analyst helped me with this. Example code below for anybody that is interested.

from arcgis.gis import GIS

gis = GIS('https://www.arcgis.com','arch0000')
token = gis._con.token

item_properties = {

"title":"TestAdd2",

"tags":"test",
"url":"https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure/FeatureServer",

"type":"Feature Service",
"description":"Test Me",
"serviceUsername":"user1",
"servicePassword":"user1",
"token":token

}

gis.content.add(data="https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure/FeatureServer",owner="arch0000",item_properties=item_properties)

**Comment by achapkowski** [comment]
To add the stored credentials you need to add three keys to your `item_properties`

```python
{
"ur"l: "YOUR URL",
"serviceUsername": "YOUR USERNAME",
"servicePassword" : " YOUR PASSWORD"
}
```

**Comment by BrettFrahm** [comment]
Hey @achapkowski ,

Thanks for the reply. So you didn't include the token aspect that the ESRI analyst gave me. Is providing the token in item_properties not necessary for this process to work? Thanks!

**Comment by achapkowski** [comment]
The `additem` method automatically appends a token to the REST call.
