### ISSUE TITLE
curveRings in output from geometry.buffer() breaks display

### ISSUE THREAD

**Issue by HakonD** [Esri/arcgis-python-api#570]
**Describe the bug**
The buffer method returns an object with curveRings, this seems to break display().

**To Reproduce**
In a Jupyter notebook:

```python
_mysdf = somelayer.query("1=1", out_sr=32632).sdf
display(_mysdf.spatial.bbox.buffer(250))
```
error:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\pro24clone\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~\AppData\Local\ESRI\conda\envs\pro24clone\lib\site-packages\arcgis\geometry\_types.py in _repr_svg_(self)
    425                 '<g transform="{3}">{4}</g></svg>'
    426                 ).format(view_box, width, height, transform,
--> 427                          self.svg(scale_factor))
    428 
    429     #----------------------------------------------------------------------

~\AppData\Local\ESRI\conda\envs\pro24clone\lib\site-packages\arcgis\geometry\_types.py in svg(self, scale_factor, fill_color)
   2618         rings = []
   2619         s = ""
-> 2620         for ring in self['rings']:
   2621             rings = ring
   2622             exterior_coords = [

~\AppData\Local\ESRI\conda\envs\pro24clone\lib\site-packages\arcgis\geometry\_types.py in __getitem__(self, k)
    172     #----------------------------------------------------------------------
    173     def __getitem__(self, k):
--> 174         return dict.__getitem__(self, k)
    175 ########################################################################
    176 class GeometryFactory(type):

KeyError: 'rings'
```
**Screenshots**
![curveRings1](https://user-images.githubusercontent.com/889468/70519327-0c812780-1b3c-11ea-9938-fa7ec9308719.png)
![curveRings2](https://user-images.githubusercontent.com/889468/70519349-130f9f00-1b3c-11ea-94c9-1f4fd05134d7.png)

**Expected behavior**
Display of result without error

**Platform (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Python API Version 1.7`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by HakonD** [comment]
Aha, it's a feature ;)

Display is not a big deal, but the curveRings are troublesome in many ways, eg. polygons with them are not useable as geometry.filters and I believe they deserve some scrutiny.
<img width="594" alt="snip_20191211203108" src="https://user-images.githubusercontent.com/889468/70653685-3f6b0e80-1c55-11ea-88e2-ea229b562b08.png">

Seems a simple workaround is to generalize the buffered polygon before use.

```python
_bbox = arcgis.geometry.Geometry({'rings': [[[5.0, 60.0], [5.0, 62], [7.0, 62], [7.0, 60.0], [5.0, 60.0]]],
                                  'spatialReference': {'wkid': 4326, 'latestWkid': 4326}})
print("--- buffer() ---")
_bbox1 = _bbox.buffer(0.5)
print(_bbox1)
print("\n--- generalize() ---")
_bbox2 =_bbox1.generalize(0.05)
print(_bbox2)
display(_bbox2)
```
<img width="803" alt="snip_20191211203512" src="https://user-images.githubusercontent.com/889468/70653983-c15b3780-1c55-11ea-9809-546b34bb157e.png">

**Comment by achapkowski** [comment]
I forget when we fixed this, but it's fixed:
![image](https://user-images.githubusercontent.com/5131271/162440230-dddbe8fb-0c40-4e03-83bb-970d127e498a.png)
