### ISSUE TITLE
Getting the mapped road edge (segment, way) IDs from the polyline (route result path [arcgis generated result or result generated by other routing service])

### ISSUE THREAD

**Issue by Sudeepa14** [Esri/arcgis-python-api#573]
I want to get the mapped road edge(segment) list from the route results (using path attribute).

I tried to raise the problem in the community and didn't get any direct answer whether we could use arcgis python api to do this. I was suggested to use arcpy **Split By Attributes** and **Copy Traversed Source Features tool**. Is this possible in the api? My goal is to find **the closest** (by distance) **edge** from the **resulting edge list** (mapped road segment list) to a **specific given point** (a coordinate). Is that something possible in the api or are there any arcgis product which could facilitate that? **Help appreciated**.

**Comment by Sudeepa14** [comment]
[This tutorial](https://community.esri.com/groups/navigator/blog/2019/09/05/transforming-polylines-into-route-layers-tutorial) shows some parts of the problems but I'm just wondering whether we can achieve that using the API.

**Comment by CMPeng** [comment]
@Sudeepa14 
If you input analysis source (the resulting edge list (mapped road segment list, as you mentioned above) and the near source (the given point) are in the form of services, then you can use the API `arcgis.features.use_proximity.find_nearest` in getting the closest edge. 

The reference to the tool and samples can be found in https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.features.use_proximity.html#find-nearest and https://developers.arcgis.com/python/guide/part4-find-closest-facilities/#Method-2---using-arcgis.features.use_proximity.find_nearest
