### ISSUE TITLE
detect_objects_using_deep_learning() got an unexpected keyword argument 'process_all_raster_items'

### ISSUE THREAD

**Issue by LinoSun** [Esri/arcgis-python-api#575]
**Describe the bug**
The bug appeared when I used the detect_objects_using_deep_learning method. .

**To Reproduce**
```python
from arcgis.gis import GIS
from arcgis.learn import Model,detect_objects
model = Model()
model.from_model_path('my_deeplearning_model_path')
im = GIS('my_gis').layers[0]
detect_objects(input_raster=im,model=model)
```
error:
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-23-5f272dd2c670> in <module>()
----> 1 arcgis.learn.detect_objects(input_raster=im,model=model)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/arcgis/learn/__init__.py in detect_objects(input_raster, model, model_arguments, output_name, run_nms, confidence_score_field, class_value_field, max_overlap_ratio, context, process_all_raster_items, gis, future, **kwargs)
    245                                                                         process_all_raster_items=process_all_raster_items,
    246                                                                         future=future,
--> 247                                                                         **kwargs)
    248 
    249     """

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/arcgis/_impl/tools.py in detect_objects_using_deep_learning(self, input_raster, model, output_objects, model_arguments, run_nms, confidence_score_field, class_value_field, max_overlap_ratio, process_all_raster_items, context, future, **kwargs)
   6200                                                                  context=context,
   6201                                                                  gis=self._gis,
-> 6202                                                                  future=True)
   6203         else:
   6204             gpjob = self._tbx.detect_objects_using_deep_learning(input_raster=input_raster,

TypeError: detect_objects_using_deep_learning() got an unexpected keyword argument 'process_all_raster_items'
```
**Screenshots**
![image](https://user-images.githubusercontent.com/44741345/70976138-5e025700-20e6-11ea-853c-7d46f6f5d1d4.png)

**Expected behavior**

**Platform (please complete the following information):**
 - OS: Linux
 - Browser [chrome]
 - Python API Version [`1.7.0`]

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by LinoSun** [comment]
@rohitgeo @ajturner

**Comment by rohitgeo** [comment]
The model parameter in detect_objects() call should be a Deep Learning Model Package item on the portal. It is not a local Model object loaded using from_model.

**Comment by LinoSun** [comment]
Many thanks

**Comment by LinoSun** [comment]
But it still doesn't work. @rohitgeo 

```
from arcgis.gis import GIS
from arcgis.learn import Model,detect_objects
gis = GIS('my_portal')
im = gis.content.get('my_image').layers[0]
model_package = gis.content.get('my_deeplearning_package')
model = Model(model_package)
model.install()
detect_objects(input_raster=im,model=model)
```

I noticed that the source code has changed, I don't know if it is related to this error。

![image](https://user-images.githubusercontent.com/44741345/71053261-e76a6580-2188-11ea-9456-4186954300e1.png)




![image](https://user-images.githubusercontent.com/44741345/71052561-aa9d6f00-2186-11ea-9152-e7b6be123f5c.png)

**Comment by rohitgeo** [comment]
@rhea-j do you know about this error?

**Comment by rhea-j** [comment]
@LinoSun 
What version of raster analysis server are you using?

**Comment by LinoSun** [comment]
> @LinoSun
> What version of raster analysis server are you using?

10.8 Prerelease

**Comment by rhea-j** [comment]
@LinoSun 
process_all_raster_items parameter was added to the 10.8 server after the 10.8 pre-release, Python API assumes that the raster analysis server would have the parameter as it is a 10.8 server. 

As a workaround, you can run this statement  before you run the detect_objects function

gis._tools.rasteranalysis.properties["currentVersion"]=10.71

Can you kindly try this workaround.

**Comment by LinoSun** [comment]
@rhea-j  
Dear Rhea,this workaround worked.Thanks a lot.
And I got a surprise：
![image](https://user-images.githubusercontent.com/44741345/71167654-0bfd3500-2290-11ea-81c8-12c7b39e74f1.png)

I will continue to solve the problem, but I still want to ask if you have encountered this error.Thanks again.

**Comment by rhea-j** [comment]
@LinoSun Can you kindly try passing values for model_arguments parameter.

**Comment by divyanshj16** [comment]
Here is an example.

```python
context = {'cellSize': '1',    ## Change it with the cell size you trained your model on
           'processorType':'GPU',  ## If you have GPU, you can set this
           'extent':{'xmin': -11392183,  ## Set the extent you want to inference on
                     'ymin': 3764168,
                     'xmax': -11385824,
                     'ymax': 3766079, 'spatialReference': {'latestWkid': 3857, 'wkid': 102100}}}

model_arguments = {
    'padding': '56',   ## this should be 1/4 of the image size you trained on.
    'threshold': '0.5',  ## Confidence above with objects will be detected.
    'nms_overlap':'0.1', ## Non maximum suppression 
    'batch_size': '16',  ## reduce this if you have memory issues on your server 
    'exclude_pad_detections': 'True' ## You can pass false and see if results improve.
}

detect_objects(item,
               model=detect_objects_model,  
               model_arguments=model_arguments,
               output_name='layername',
               context=context)
```

**Comment by LinoSun** [comment]
@rhea-j @divyanshj16 Thanks a lot.
