### ISSUE TITLE
clone_items crash for feature service URL with non-ascii character when cloning attachements

### ISSUE THREAD

**Issue by jeaneric** [Esri/arcgis-python-api#578]
**Describe the bug**
When using the clone_items function on a feature service that have non-ascii character in their service URL (é for example), the function crash when cloning attachments.

**code**
```python
target_gis.content.clone_items(items=items_to_clone,
                                   folder=target_folder,
                                   copy_data=True,
                                   search_existing_items=False)
```

**Relevant error messages:**
```python
C:\ProgramData\Anaconda3\lib\site-packages\arcgis\features\layer.py in _list_attachments(self, oid)
--> 341         return self._con.get(path=url, params=params, token=self._token)
C:\ProgramData\Anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
--> 525         response = self._open(req, data)

_ItemCreateException: ("Failed to create Feature Service xxxxxxx: 'ascii' codec can't encode character '\\xe9' in position 63: ordinal not in range(128)", <Item title:"xxxxxxxxx" type:Feature Layer Collection owner:yyyyyyyy>)
```

**Expected behavior**
clone_items to successfully clone the feature service.

**Platform:**
- Windows server / Anaconda / Jupyter Notebook / Python 3.7.4
- API version 1.6.0

**Additional context**
I spotted at least 2 places in the code that the URL should be quoted:
- layer.py -> _list_attachments function
- managers.py -> download function

**Comment by achapkowski** [comment]
@jeaneric thank you for reporting this, we will take a look and get back to you.

Does the Item's title have non-ascii characters or the feature service url?

**Comment by CMPeng** [comment]
@jyaistMap when have time, can you please follow up with @jeaneric and @achapkowski to see if this bug shall be added to the current milestone? thanks!!
