### ISSUE TITLE
Expose additional batch geocoding parameters

### ISSUE THREAD

**Issue by jrmatchett** [Esri/arcgis-python-api#581]
It would be useful if the `batch_geocode` function included the additional parameters supported by the [`geocodeAddresses`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm) REST API, particularly `locationType` and `preferredLabelValues`.

**Comment by achapkowski** [comment]
Fixed and added to v1.8.0 release of the API, thank you for suggesting this.
