### ISSUE TITLE
Fail to execute object detection on video

### ISSUE THREAD

**Issue by samuello4** [Esri/arcgis-python-api#586]
I have followed every step in the Automate Road Surface Investigation Using Deep Learning sample notebook. After performing prediction on a single image, I can't process anymore as there is no road surface video provided. I would like to know how kind of metadata should be included for performing prediction on video?

I have taken a road surface video and use the API to do prediction on that video but it doesn't work.

**Comment by Hiromu-Nakamura** [comment]
@samuello4 You need a MISB formatted csv file which includes lat, lon, timestamp, etc. representing your video's metadata. Pass the csv to "metadata_file" parameter of predict_video method.

You can find what kind of information should be included in the csv at Full Motion Video 1.4 user manual (p. 65).
https://community.esri.com/thread/209187-is-full-motion-video-14-user-manual-available-for-download-outside-of-esri

**Comment by samuello4** [comment]
@Hiromu-Nakamura Thank you so much for your information. I really appreciate it.

I have one more question.
Is there any suggestion on the automatic geotagging tool? It is possible to take a road surface video by an iPhone?

**Comment by Hiromu-Nakamura** [comment]
@samuello4 
> Is there any suggestion on the automatic geotagging tool?

Unfortunately, as long as I know, video file with MISB format is not popular in Japan where I am living in. Therefore, I am not familiar with this field as well.
However, there are [some discussions](https://community.esri.com/community/gis/imagery-and-remote-sensing/blog/2018/09/10/how-do-we-process-video-from-a-dji-drone-to-bring-it-into-fmv-for-arcgis) about which drones and tools can be used for FMV for ArcGIS. Maybe, these drones can take lat, lon, and other sensing data with video.

> It is possible to take a road surface video by an iPhone?

I think technically you can. For the demo shared with the last comment, I have used two smart phone; one for taking video, and another one for sensing lat, lon, and timestamp with [this app](https://apps.apple.com/us/app/sensorlog/id388014573).
The app can output csv file with various data sensed by iPhone. Then, you can format it to follow MISB format (I filled out only lat, lon, and timestamp, and others were zero). After that, pass the video and csv to the predict_video method.
**Note that this is tricky way and I do not know the detail about the logic of predict_video method and how it is inplemented, so the result can be incorrect**. At least, timestamp will not completely synchronize with the video. Also, the GPS will be not so accurate compared with more sophisticated device.

Hope someone who know the detail about it support this comment.

**Comment by priyankatuteja** [comment]
@samuello4 I hope this helped you. Please reopen issue if required.
