### ISSUE TITLE
Properties and methods under Machine class return error.

### ISSUE THREAD

**Issue by Hiromu-Nakamura** [Esri/arcgis-python-api#590]
**Describe the bug**
Properties and methods under Machine class return error.

**To Reproduce**
```python
from arcgis.gis import GIS
from arcgis.gis import server

# user credential
user = "portaladmin"
# portal url
target_portal = r"https://your-portal.com/portal/"

# machine object
machine = server.Machine(url = r"https://your-portal.com/server/admin/machines/YOUR-MACHINE.ESRI.COM", gis = gis)

machine.hardware # AttributeError
machine.ssl_certificates # AttributeError
```
error:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\ESRI\conda\envs\170\lib\site-packages\arcgis\gis\server\_common\_base.py in __getattr__(self, name)
     81         try:
---> 82             return self._properties.__getitem__(name)
     83         except:

~\AppData\Local\ESRI\conda\envs\170\lib\site-packages\arcgis\_impl\common\_mixins.py in __getitem__(self, key)
    339         """
--> 340         return self._mapping[key]
    341 

KeyError: 'hardware'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-30-f89bf6693ff9> in <module>
----> 1 machine.hardware

~\AppData\Local\ESRI\conda\envs\170\lib\site-packages\arcgis\gis\server\_common\_base.py in __getattr__(self, name)
     85                 if k.lower() == name.lower():
     86                     return v
---> 87             raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, name))
     88     #----------------------------------------------------------------------
     89     def __getitem__(self, key):

AttributeError: 'Machine' object has no attribute 'hardware'
```
**Screenshots**
![2020-01-28_16h19_22](https://user-images.githubusercontent.com/20600894/73243164-4391c200-41ea-11ea-9236-bf4205ec02c7.png)

**Expected behavior**
Hardware properties are returned like below
![2020-01-28_16h22_45](https://user-images.githubusercontent.com/20600894/73243238-78057e00-41ea-11ea-87ad-4863361e2d15.png)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 72.0.2 (64-bit), Edge Version 79.0.309.71 (Official build) (64-bit)
 - Python API Version: 1.7.0

**Additional context**
URL in Machine object
(<Machine at https://your-portal.com/server/admin/machines/YOUR-MACHINE.ESRI.COM>) is correctly navigate to ArcGIS Server Administrator Directory. So, I suppose the workflow is valid, but sorry if it is not a bug.

Thanks.

**Comment by Hiromu-Nakamura** [comment]
Should have written the environment of the server side.
- OS: Windows Server 2019
- Versino of ArcGIS Enterprise: 10.7.1

**Comment by achapkowski** [comment]
So this is a federated machine?  Have you tried accessing the server through the GIS object?

**Comment by Hiromu-Nakamura** [comment]
@achapkowski Thank you for your response.
Yes. I have a base deployment of the ArcGIS Enterprise in a single machine:
- ArcGIS Server (federated with the Portal for ArcGIS below)
- Portal for ArcGIS
- ArcGIS Data Store
- (Two) ArcGIS Web Adaptor (s)

**Comment by Hiromu-Nakamura** [comment]
@achapkowski 
Sorry again, I haven't answer the second question.
> Have you tried accessing the server through the GIS object?
I think yes. I suppose specifying GIS object in the code above means it.
`machine = server.Machine(url = r"https://your-portal.com/server/admin/machines/YOUR-MACHINE.ESRI.COM", gis = gis)`
