### ISSUE TITLE
Error in population-exploration-dashboard Sample

### ISSUE THREAD

**Issue by mschenker** [Esri/arcgis-python-api#592]
**Describe the bug**
The "Explore the population" Sample fails with the error message AttributeError: 'GeoSeries' object has no attribute '_delete_index'

**To Reproduce**
1. Open the sample notebook https://developers.arcgis.com/python/sample-notebooks/population-exploration-dashboard/
2. Click on "Try it live"
3. Enter your username and password in the first cell
4. Execute the Sample
5. Click on "Fetch Extent"
--> The error message will be displayed
error:
AttributeError: 'GeoSeries' object has no attribute '_delete_index'
```

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by priyankatuteja** [comment]
@mschenker We have updated the notebook and it should be working without errors now, Thanks for reporting it.
