### ISSUE TITLE
Item cannot be shared with group having users_update_items=True

### ISSUE THREAD

**Issue by capdragon** [Esri/arcgis-python-api#594]
**Describe the bug**
Using Python API, an Item cannot be shared with a group which has the users_update_items=True property. 

**To Reproduce**
```python
from arcgis.gis import GIS
import time

itemToShareId = "e3224ccb110247399956c958a58bdcc1"
orgUrl = "https://myorg.maps.arcgis.com"
ownerUserName = "username"
ownerPassword = "password"
groupNormalName = "TEST - My Normal Group"
groupUpdateableItemsName = "TEST - My Updatable Group"

print("Connecting...")
gis = GIS(orgUrl, ownerUserName, ownerPassword)


# get item to share
item = gis.content.get(itemToShareId)
print("Creating groups...")
# Create a normal group
groupNormal = gis.groups.create(groupNormalName, "tag1, tag2", "normal group", "normal group", access='private', is_invitation_only=True)

# Create Group that is allowed to update content (users_update_items=True).
groupUpdatable = gis.groups.create(groupUpdateableItemsName, "tag1, tag2", "Group that is allowed to update content", "Group that is allowed to update content", users_update_items=True, access='private', is_invitation_only=True)
print("Waiting for groups (20 seconds)...")
# give groups some time to bake on AGOL (20 seconds).
time.sleep(20)
print("Sharing items...")
# share item with both groups:
item.share(groups=[groupNormal])
item.share(groups=[groupUpdatable])

print("NOW GO CHECK THE GROUPS! Only will be shared with one")

```
error:
```python
No error, in fact `result['results'][0]['notSharedWith']` return None.
```

**Expected behavior**
I expect the item to be shared with the group which has users_update_items set to True.
In the code above, I would expect the item to be shared with both groups, but only is shared with the normal group.

**Platform (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)` 1.6.1

**Additional context**

**Comment by rvg296** [comment]
@capdragon I think the default parameter `allow_members_to_edit` in `item.share` is `False`. We have to change the parameter to be True in order for that to be shared with groups that have `users_update_items=True`. I have tested this and it worked fine in version 1.7.1.
Here is a link for the API reference.
[https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html?highlight=item%20share#arcgis.gis.Item.share](Python API) . Can you try once and let me know if that works for you.

**Comment by capdragon** [comment]
> Can you try once and let me know if that works for you.

Sure enough! It worked. Thanks @rvg296
