### ISSUE TITLE
arcgis.tools.list_bigdata_datasets fails because manifest does not contain PATH and TYPE objects

### ISSUE THREAD

**Issue by mindzia** [Esri/arcgis-python-api#6]
Hello,
first of all method declaration:
def list_bigdata_datasets(self, server_path):
parameter SERVER_PATH should be renamed to DATA_STORE_NAME or similar, as it requires call:
gae.list_bigdata_datasets("bdfs2")
when original URL is: https://mportal.hnit-baltic.lt:6443/arcgis/admin/data/items/bigDataFileShares/bdfs2/manifest

I have manifest generated by ArcGIS Server (NYC Taxi sample data from training material). Manifest does not contain JSON objects TYPE and PATH, and thus method fails executing:
for dataset in res['datasets']:
   print("/server/datastores/bigDataFileShares/" + server_path + '/' + dataset['path'] + ' ('+ dataset['type'] + ')')

[NYC_Taxi_2015_manifest.zip](https://github.com/Esri/arcgis-python-api/files/444844/NYC_Taxi_2015_manifest.zip)

ArcGIS for Server + Portal + DataStore version 10.5 beta.

Regards,

Mindaugas

**Comment by rohitgeo** [comment]
@mindzia thank you for reporting this - this issue has been resolved in v0.3-beta released last week. The sample notebook at https://developers.arcgis.com/python/sample-notebooks/Analyze-NewYork-city-taxi-data/ shows how to register and use New York taxi data.
