### ISSUE TITLE
Unet

### ISSUE THREAD

**Issue by EveryoneInOne** [Esri/arcgis-python-api#604]
hi,
i  want to use Unet for do what i see in this notebook https://developers.arcgis.com/python/sample-notebooks/extracting-building-footprints-from-drone-data/
but it dont work for me, so i try do it with another feature layer (forest) and i aftee use data.show_batch(rows=2, alpha=0.7)
my results are 
![image](https://user-images.githubusercontent.com/45751944/74843526-57819d00-532c-11ea-83bc-b591cdd9bf64.png)

and i think it is fine but after that i want to implement UNet Calssifier(model = arcgis.learn.models.UnetClassifier(data)) and this work for this data but when i start learn model i have error with CUDA Memory out or RuntimeError: CUDA error: device-side assert triggered.
I try use smaller size_batch and with size_batch=1 still is the same.
![image](https://user-images.githubusercontent.com/45751944/74843937-f3aba400-532c-11ea-98f2-c36be1c883d8.png)

Can u help me with  that problem ?
i can do it on your data if u can fix that .
Casue i need that
Thanks for help
my arcgis python version is 1.7.1 and i use arcgis pro 2.4 
if i do lesson from arcgis for palm detection and my leayers with using SSD everythin works and i can use my own model in Arcgis pro to detect features on sattelite image

**Comment by achapkowski** [comment]
Try setting in your script the following environment

```python
import os
os.environ['CUDA_LAUNCH_BLOCKING']=1
```

Put this at the top of your script/notebook.

**Comment by priyankatuteja** [comment]
@EveryoneInOne Let us know if this fix worked for you. Thanks!

**Comment by priyankatuteja** [comment]
````
import os
%env CUDA_VISIBLE_DEVICES=0
os.environ["CUDA_VISIBLE_DEVICES"]="0"
````

You can try this alternatively if needed.

**Comment by priyankatuteja** [comment]
@EveryoneInOne You will be glad to know that we have released a newer version of Arcgis API for Python i.e. 1.8.3. I hope your issue got fixed. If not, please consider updating the version and retrying. I am closing the issue, open if needed.
