### ISSUE TITLE
Get 'returned NULL without setting an error' when saving spatially enabled dataframe to file geodatabase

### ISSUE THREAD

**Issue by phill0304** [Esri/arcgis-python-api#606]
**Describe the bug**
When saving a spatially enabled dataframe to file geodatabase receiving 'returned NULL without setting error' 

**To Reproduce**
create spatially enabled dataframe called sdf...
sdf.spatial.to_featureclass(location=r'c:/sandbox/CMCorn.gdb/planting_modified')
```
error:
SystemError                               Traceback (most recent call last)
<ipython-input-14-56bc3db63847> in <module>
      1 import arcpy
----> 2 sdf.spatial.to_featureclass(location=r'c:/sandbox/CMCorn.gdb/planting_modified')

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\geo\_accessor.py in to_featureclass(self, location, overwrite)
   1923         return to_featureclass(self,
   1924                                location=location,
-> 1925                                overwrite=overwrite)
   1926     #----------------------------------------------------------------------
   1927     def to_table(self, location, overwrite=True):

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\geo\_io\fileops.py in to_featureclass(geo, location, overwrite, validate)
    610 
    611         array = np.array([], np.dtype(dtypes))
--> 612         arcpy.da.ExtendTable(fc, oidfld, array, join_dummy, append_only=False)
    613 
    614         # 3. Insert the Data

SystemError: <da.funcInfo object at 0x000001AF3BF980F8> returned NULL without setting an error
```

**Expected behavior**
dataframe saves to file geodatabase

**Platform (please complete the following information):**
 - OS: windows
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
@phill0304 can you post your source data?

**Comment by phill0304** [comment]
[for_andrew.gdb.zip](https://github.com/Esri/arcgis-python-api/files/4232359/for_andrew.gdb.zip)

Source layer for spatially enabled dataframe is in gdb attached above. I access the file using the pd.DataFrame.spatial.from_featureclass() method. I make some modifications to dataframe then try to save to a new file and get error.

**Comment by phill0304** [comment]
@achapkowski Saving to shapefile works as expected

**Comment by achapkowski** [comment]
@phill0304 thanks for the data, I'll take a look.

**Comment by achapkowski** [comment]
Is the source a Hosted Feature Layer or are you reading the feature class in, and then exporting the results?

**Comment by achapkowski** [comment]
can you tell me what you changed on the dataframe?  I am able to import/export it without issue.

**Comment by phill0304** [comment]
@achapkowski I access the data from the geodatabase directly (no hosted feature layer). I just tested to see if I could save without making modifications and the method worked fine. Only errors when I make modifications. I'm adding a field with unique guids to the dataframe and exporting.

here's code for adding uid to dataframe:

def add_id(infeatures):
    sdf = pd.DataFrame.spatial.from_featureclass(infeatures)
    uuids  = []
    for index, row in sdf.iterrows():
        myid = uuid.uuid4()
        uuids.append(myid)
    sdf.insert(1, 'id', value = uuids)
    loc = os.path.dirname(infeatures)
    output = os.path.join(loc, 'planting_ids')
    sdf.spatial.to_featureclass(output)
    return output

**Comment by phill0304** [comment]
@achapkowski I fixed the problem. If I convert the uuid to a string before adding to the list and then insert to dataframe it seems to work for me.

Thanks for your help

**Comment by achapkowski** [comment]
UUID is not a string or a value that can be saved to a feature class.  You need to convert it to a string.  Do the following:

```python
import uuid
sdf['id'] = None
sdf['id'] = sdf['id'].apply(lambda x: str(uuid.uuid4()))
```

**Comment by DavidAnderson-USFS** [comment]
I am having this same problem.  It seems to be related to the number of fields exported.
This statement works, albeit very slowly
`veg_eru_df[['id2','stm_state','R3ERUCODE','SHAPE']].spatial.to_featureclass(fc_name,overwrite=True,sanitize_columns=False)`
This one does not work
`veg_eru_df[['uuid','id2','stm_state','R3ERUCODE','Quad_mean_diam_tr_gr_1','SC_DESC','Tree_canopy_cov','CC_DESC','Canopy_layering','Dominance_type','Shrub_cover','Shrub_DESC','Lifeform','Shrub_dominance','Herb_cover','Herb_dominance','SHAPE']].spatial.to_featureclass(fc_name,overwrite=True,sanitize_columns=False)`
I did add a UUID field as suggested in the comments above.  That did not fix theproblem.  

I am using 
Python 3.7.10 [MSC v.1927 64 bit (AMD64)]
Pandas 1.2.3
arcgis 1.8.5
