### ISSUE TITLE
Export map gis.map()

### ISSUE THREAD

**Issue by mateuspontesmoraes** [Esri/arcgis-python-api#607]
Hello,

I'd like to know if is possible export a map to PNG, for exemple:

![image](https://user-images.githubusercontent.com/11629395/74989584-888eca00-541f-11ea-86d9-1182e19ab942.png)

And to save the instance map like PNG

**Comment by DavidJVitale** [comment]
Hi @mateuspontesmoraes , this can be done [`MapView.take_screenshot()`](https://developers.arcgis.com/python/api-reference/arcgis.widgets.html#arcgis.widgets.MapView.take_screenshot)

```python
# Run this cell and display a map in a Jupyter Notebook
from arcgis.gis import GIS
gis = GIS()
map = gis.map()
map
```

```python
# After the above cell has rendered, run this cell to save map as a .PNG
map.take_screenshot(file_path=r"/path/to/location/output.png")
```

Let me know if you run into any issues, happy to help!

**Comment by mateuspontesmoraes** [comment]
Hi @DavidJVitale thanks thank you very much!
But I'm yet this problem, I'm doing a script standalone, I readed the documentation that is only possible to use MapView.take_screenshot() on Jupyter Notebook.

Is there another possibilite to export my map with a pin to png?

Thank you @DavidJVitale

**Comment by DavidJVitale** [comment]
> Hi @DavidJVitale thanks thank you very much!
> But I'm yet this problem, I'm doing a script standalone, I readed the documentation that is only possible to use MapView.take_screenshot() on Jupyter Notebook.
> 
> Is there another possibilite to export my map with a pin to png?
> 
> Thank you @DavidJVitale

@mateuspontesmoraes Unfortunately, this is only possible in a Jupyter Notebook environment. The `take_screenshot()` functionality relies on the ArcGIS JS API being loaded in a notebook. This does not happen when you are running a standalone script in a headless environment, so it's not possible using that function. Sorry about that, I'm not aware of any other way to get a screenshot.
