### ISSUE TITLE
Missing and/or denied access to data to evaluate notebook(s)

### ISSUE THREAD

**Issue by leonard-psu** [Esri/arcgis-python-api#617]
I would like to use these notebooks for teaching purposes. Some notebooks require access to data not provided in the data folder. The most common problem is accessing data hosted at geosaurus.maps.arcgis.com which is not accessible to most users.

**Notebook**: detecting_settlements_using_supervised_classification_and_deep_learning
**Missing**: classificationPointsSaharanpur https://geosaurus.maps.arcgis.com/home/item.html?id=e28c2a88d38747f9860a44f103d1aec5

**Notebook**: automate_building_footprint_extraction_using_instance_segmentation
**Missing**:  MaskRCNN_training_data_Berlin

**Steps to reproduce the behavior:**
Access the notebook not logged into ESRI account/group

**Comment by rbjelinek** [comment]
I'm also unable to access the data 

**Under this login**
gis = GIS("https://pythonapi.playground.esri.com/portal/home/", "arcgis_python", "amazing_arcgis_123")

**and this search**
test = gis.content.search('owner:api_data_owner')

**yields the following results**
[<Item title:"bigDataFileShares_all_hurricanes" type:Big Data File Share owner:api_data_owner>,
 <Item title:"C_D8" type:Imagery Layer owner:api_data_owner>,
 <Item title:"conser_wm" type:Imagery Layer owner:api_data_owner>,
 <Item title:"D9" type:Imagery Layer owner:api_data_owner>,
 <Item title:"landsat_pviot_345" type:Imagery Layer owner:api_data_owner>,
 <Item title:"D_D9" type:Imagery Layer owner:api_data_owner>,
 <Item title:"roads" type:Feature Layer Collection owner:api_data_owner>,
 <Item title:"drone_b_features" type:Feature Layer Collection owner:api_data_owner>,
 <Item title:"C_D3" type:Imagery Layer owner:api_data_owner>,
 <Item title:"geonamesras" type:Imagery Layer owner:api_data_owner>]

When going through the documentation, I was under the impression all reproduction data should be uploaded to the enterprise portal under api_data_owner.  From browsing there must be ~100 different tutorials so unless I missed something in the docs I think there's a sizable gap.

Any help from the ESRI team or others that may have gotten around this issue would be much appreciated

**Comment by priyankatuteja** [comment]
@rbjelinek The items provided in the sample notebook are public and these can be downloaded without needing to login using any credentials.

Berlin imagery: https://pythonapi.playground.esri.com/portal/home/item.html?id=c0bd94a10c4649fcb755ee375ae45f2f
Berlin footprints: https://ivt.maps.arcgis.com/home/item.html?id=7d3f633a325f4dcf962c82284098ce9d
exported training data: https://geosaurus.maps.arcgis.com/home/item.html?id=637825446a3641c2b602ee854776ed47

**Comment by priyankatuteja** [comment]
@rbjelinek Please feel free to reopen the issue if you find missing data in any sample notebook. However, the above mentioned notebooks have data available publicly, therefore closing the issue.
