### ISSUE TITLE
Add keywords to attachments.

### ISSUE THREAD

**Issue by DanCranford** [Esri/arcgis-python-api#622]
I am trying to migrate data from one Survey123 feature service to another.  The attachments have keywords that are searchable with the Python API [Search Function](https://developers.arcgis.com/python/api-reference/arcgis.features.managers.html#arcgis.features.managers.AttachmentManager.search)
I don't see any way to add or update those keywords in the other functions on the Python or REST APIs.

```python
layer.attachments.add(oid, file_path)
layer.attachments.search()

result:
[{'PARENTOBJECTID': --oid--,
  'PARENTGLOBALID': '--globalid-',
  'ID': 1,
  'NAME': 'EXCAVATION_SKETCH.JPG',
  'CONTENTTYPE': 'image/jpeg',
  'SIZE': 79684,
  'KEYWORDS': '',
  'IMAGE_PREVIEW': '--url--',
  'GLOBALID': '--globalid-',
  'DOWNLOAD_URL': '--url--'}]
```

If possible, I'd like to be able to edit or modify the keywords for attachments.  I have a workaround for now, adapted from this [GeoNet thread](https://community.esri.com/thread/211727-is-there-a-easy-way-to-update-the-keyword-associated-with-an-feature-attachment
), but it would be great if it's possible to add an additional argument to the attachments.add and attachment.update functions.

```python
#Function to post the attachment to the specific feature
def add_attachment(url, token, oid, attachment, attkeyword):
    att_url = '{}/{}/addAttachment'.format(url, oid)
    files = {'attachment': (os.path.basename(attachment), open(attachment, 'rb'), 'image/jpeg')}
    params = {'keywords': attKeyword,'token': token,'f': 'json'}
    r = requests.post(att_url, params, files=files)
    return r
```

**Comment by achapkowski** [comment]
Thanks for your suggestion, we'll review it and get back to you.

**Comment by fattmox** [comment]
+1
I too am using this work around - it would be a lot cleaner to have an optional parameter for KEYWORDS

**Comment by achapkowski** [comment]
Add in v2
