### ISSUE TITLE
training SDD model consistently causing DPC_WATCHDOG_VIOLATION windows bluescreen crash

### ISSUE THREAD

**Issue by tyhayward** [Esri/arcgis-python-api#628]
**Describe the bug**
When attempting to train a SSD model using arcgis.learn I am consistently running into DPC_WATCHDOG_VIOLATION. 

It seems to be happening when I am using backbone='' arguments. It has happened using resnet50,101,152, densenet121. This is happening when using both the lr_find() function and then when training the model - typically when I am a few (3 or so) epochs in and then it just freezes - the PC freezes and then it will bluescreen and reboot. 

Previously it seems the GPU has crashed although it is only using 4gb - 6gb /11 gb in the nvidia-smi. I have had ERR! next to the GPU fan and Pwr Usage/Cap in smi but the bluescreen did not happen but it seemed to crash the GPU. 

note: this is not even on my full dataset - it is on a smaller export to test hyperparameters on but unfortunately the PC is crashing non-stop. It has happened 10+ times on several different variations. 

**To Reproduce**
unsure how someone else would be able to reproduce this. 
I am not getting a python error as the machine freezes and then subsequently gives me the DPC_WATCHDOG_VIOLATION and then reboots. 
**Screenshots**
![image](https://user-images.githubusercontent.com/54058249/76099398-f3650700-5fc2-11ea-98d7-cd6bd4746efa.png)

![image](https://user-images.githubusercontent.com/54058249/76099607-48a11880-5fc3-11ea-8c30-a9c70feadde7.png)
here you can see therer are no error codes ect as when i reopen the notebook after the crash it is just as it was when it froze. 

**Expected behavior**
Expect the model to train without crashing the PC. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Jupyter is running in Edge but I also have Chrome. 
arcgis API version = 1.8.0
fastai version = 1.0.54
torch version = 1.1.0
torchvision version = 0.3.0
**Additional context**
GPU: GeForce RTX 2080 Ti - latest drivers updated. 
CPU: i9-7940X 3.1 GHz.
Solid state drive
64gb RAM
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
Can you post your code so we can see if we can reproduce it or spot any errors?

**Comment by tyhayward** [comment]
```python
%%time
import arcgis
from arcgis.learn import SingleShotDetector, prepare_data
import fastai
import torch
import torchvision

print("arcgis API version =", arcgis.__version__)
print("fastai version =", fastai.__version__)
print("torch version =", torch.__version__)
print("torchvision version =", torchvision.__version__)

data_path = r'E:\DeepLearning\TrainingChips_v4'

data = prepare_data(data_path, {1: 'empty', 2: 'contains waste'}, batch_size=8)
data.classes
ssd = SingleShotDetector(data, grids=[5], zooms=[1.0], ratios=[[1,1]], backbone='resnet50')
ssd.lr_find()
ssd.fit(epochs=3, lr= 0.001737800828749376)
```

It has just crashed - bluescreened-  again running with no backbone argument (default resnet34) and this time it produced the following error:

```python

RuntimeError                              Traceback (most recent call last)
<timed eval> in <module>

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\arcgis\learn\models\_arcgis_model.py in fit(self, epochs, lr, one_cycle, early_stopping, checkpoint, tensorboard, **kwargs)
    437 
    438         if one_cycle:
--> 439             self.learn.fit_one_cycle(epochs, lr, callbacks=callbacks, **kwargs)
    440         else:
    441             self.learn.fit(epochs, lr, callbacks=callbacks, **kwargs)

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\fastai\train.py in fit_one_cycle(learn, cyc_len, max_lr, moms, div_factor, pct_start, final_div, wd, callbacks, tot_epochs, start_epoch)
     20     callbacks.append(OneCycleScheduler(learn, max_lr, moms=moms, div_factor=div_factor, pct_start=pct_start,
     21                                        final_div=final_div, tot_epochs=tot_epochs, start_epoch=start_epoch))
---> 22     learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
     23 
     24 def lr_find(learn:Learner, start_lr:Floats=1e-7, end_lr:Floats=10, num_it:int=100, stop_div:bool=True, wd:float=None):

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\fastai\basic_train.py in fit(self, epochs, lr, wd, callbacks)
    198         callbacks = [cb(self) for cb in self.callback_fns + listify(defaults.extra_callback_fns)] + listify(callbacks)
    199         if defaults.extra_callbacks is not None: callbacks += defaults.extra_callbacks
--> 200         fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
    201 
    202     def create_opt(self, lr:Floats, wd:Floats=0.)->None:

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\fastai\basic_train.py in fit(epochs, learn, callbacks, metrics)
     99             for xb,yb in progress_bar(learn.data.train_dl, parent=pbar):
    100                 xb, yb = cb_handler.on_batch_begin(xb, yb)
--> 101                 loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
    102                 if cb_handler.on_batch_end(loss): break
    103 

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\fastai\basic_train.py in loss_batch(model, xb, yb, loss_func, opt, cb_handler)
     28 
     29     if not loss_func: return to_detach(out), yb[0].detach()
---> 30     loss = loss_func(out, *yb)
     31 
     32     if opt is not None:

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\arcgis\learn\models\_ssd.py in _ssd_loss(self, pred, targ1, targ2, print_it)
    417         lcs, lls = 0., 0.
    418         for b_c,b_bb,bbox,clas in zip(*pred, targ1, targ2):
--> 419             loc_loss, clas_loss = self._ssd_1_loss(b_c, b_bb,bbox.to(self._device), clas.to(self._device), print_it)
    420             lls += loc_loss
    421             lcs += clas_loss

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\arcgis\learn\models\_ssd.py in _ssd_1_loss(self, b_c, b_bb, bbox, clas, print_it)
    396 
    397     def _ssd_1_loss(self, b_c, b_bb, bbox, clas, print_it=False):
--> 398         bbox,clas = self._get_y(bbox,clas)
    399         bbox = self._normalize_bbox(bbox)
    400 

~\AppData\Local\ESRI\conda\envs\DeepLearning_v2\lib\site-packages\arcgis\learn\models\_ssd.py in _get_y(self, bbox, clas)
    378         except Exception:
    379             bbox = torch.zeros(size=[0, 4])
--> 380         bb_keep = ((bbox[:,2]-bbox[:,0])>0).nonzero()[:,0]
    381         return bbox[bb_keep],clas[bb_keep]
    382 

RuntimeError: copy_if failed to synchronize: unspecified launch failure

```

**Comment by priyankatuteja** [comment]
@tyhayward  I have run the same code on my system and just changed the data path.
![image](https://user-images.githubusercontent.com/39754605/76106365-b3227a80-5ffc-11ea-9ea2-3d51ca346395.png)

This works fine with backbone 'resnet50' as well as default backbone.

Can you clean reboot your system using steps at https://www.windowscentral.com/how-clean-boot-windows-10 and retry running it.

**Comment by tyhayward** [comment]
@priyankatuteja it will be very difficult to clean boot windows 10 as this is a government PC. Are there no other less drastic steps that can be taken previously? Prior to the arcpro 2.5 update I had this workflow running fine.

**Comment by achapkowski** [comment]
You can try forcing cuda to clean the cache, this could clean things up.

```
torch.cuda.empty_cache()
```

And restart your kernel.

**Comment by tyhayward** [comment]
@priyankatuteja I attempted to run the same training data in arcpro over the weekend using the new geoprocessing tool 'train deep learning model' but unforturtunately I ran into the following error 40 mins intro training:

```python 
 Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\Scripts\TrainDeepLearningModel.py", line 145, in <module>
    execute()
  File "c:\program files\arcgis\pro\Resources\ArcToolbox\Scripts\TrainDeepLearningModel.py", line 134, in execute
    callbacks=[ProgressCallback(training_model_object, max_epochs, show_accuracy=show_accuracy)]
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\DeepLearning_v2\Lib\site-packages\arcgis\learn\models\_arcgis_model.py", line 439, in fit
    self.learn.fit_one_cycle(epochs, lr, callbacks=callbacks, **kwargs)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\DeepLearning_v2\Lib\site-packages\fastai\train.py", line 22, in fit_one_cycle
    learn.fit(cyc_len, max_lr, wd=wd, callbacks=callbacks)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\DeepLearning_v2\Lib\site-packages\fastai\basic_train.py", line 200, in fit
    fit(epochs, self, metrics=self.metrics, callbacks=self.callbacks+callbacks)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\DeepLearning_v2\Lib\site-packages\fastai\basic_train.py", line 101, in fit
    loss = loss_batch(learn.model, xb, yb, learn.loss_func, learn.opt, cb_handler)
  File "C:\Users\Thayward\AppData\Local\ESRI\conda\envs\DeepLearning_v2\Lib\site-packages\fastai\basic_train.py", line 38, in loss_batch
    return loss.detach().cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
 Failed to execute (TrainDeepLearningModel).
```

Note: ON a smaller subset of the training data (one i extracted to play about with hyperparameters on) I am too able to run a say 10 epochs and it runs lr_find() easyily - it is happening when I am trying to use my full set of training data.  The training data has been extracted using arcgispro's extract training data for deep learning so there should be no issues with it. This is really frustrating as the same workflow  was working fine in September. 

![image](https://user-images.githubusercontent.com/54058249/76193002-fd615280-61da-11ea-9c24-e9b9dd5c6669.png)

I am working with my IT consultant to see about running in a clean reboot. 

@achapkowski I restart the kernal each time. I will try to empty the cache next time I attempt this although the PC is normally in a fresh boot with no other operations running anyway - when I check the smi I am only using 700-800 mb GPU in a standing state. 

Any further suggestions would be greatly appreciated. 
Thanks
ty

**Comment by priyankatuteja** [comment]
@tyhayward I checked my system's cude version. It is 10.1, so  you may try downgrading the cuda version to 10.1. Meanwhile I am also trying to update it to 10.2 as you are using that. In case I am able to reproduce the same error.

**Comment by priyankatuteja** [comment]
@tyhayward We have a latest arcgis version 1.8.3 recently released. If you're facing issues with 1.8.0, please consider updating the version and reopen the issue if needed. Thanks!

**Comment by priyankatuteja** [comment]
@tyhayward We have a latest arcgis version 1.8.3 recently released. If you're facing issues with 1.8.0, please consider updating the version and reopen the issue if needed. Thanks!
