### ISSUE TITLE
Support Jupyter environment >= 6.0.0

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/arcgis-python-api#629]
I would love to work in the current Jupyter environment 6.0.1. It seems the map widget is only working with Jupyter environments <= 5.7.8.

Please support Jupyter environments >= 6.0.0.

**Comment by achapkowski** [comment]
@gisfromscratch can you post your python packages in your environment?

```
conda list
```

This will help us reproduce what you are seeing.

**Comment by gisfromscratch** [comment]
@achapkowski Sure, here it is:
[conda-list.txt](https://github.com/Esri/arcgis-python-api/files/4315019/conda-list.txt)

**Comment by AtmaMani** [comment]
This is supported in v1.9.1 of the Python API.
