### ISSUE TITLE
group.remove_users is not called correctly in notebook "move_existing_user_content_to_a_new_user"

### ISSUE THREAD

**Issue by fabanc** [Esri/arcgis-python-api#656]
**Describe the bug**
The code that removes a user from a group in the notebook `move_existing_user_content_to_a_new_user` fails.

**To Reproduce**
Prior to running the notebook:
 - Make sure the user define by variable `old_userid` is a member of a group (not an owner)

```python
usergroups = olduser['groups']

for group in usergroups:
    grp = gis.groups.get(group['id'])
    if (grp.owner == orig_userid):
        grp.reassign_to(new_userid)
    else:
        grp.add_users(new_userid)
        grp.remove_users(orig_userid)
        print(remove_message) # Added for debugging. Not in the original notebook
```
error:

The API will fail to remove the user from the group and the pring statement will return
`{'notRemoved': ['f', 'a', 'n', 'c', 'e', 'l', 'i', '_', '1']}`
**Screenshots**

The code that is currently in the notbook and fail. I have just added the return value of at grp.remove_users(orig_userid). The error message returned by portal is printed here.

![image](https://user-images.githubusercontent.com/520324/78198333-44e3a300-7456-11ea-8437-723a28677050.png)

When that code has run, we can see that the user fancelin_1 was not removed from group.
![image](https://user-images.githubusercontent.com/520324/78198583-01d5ff80-7457-11ea-89d7-d800d1984afe.png)

The fix, is to put the user name in a list. Note: this is not how it is supposed to work according to documentation as defined there: https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Group.remove_users 

```python
usergroups = olduser['groups']

for group in usergroups:
    grp = gis.groups.get(group['id'])
    if (grp.owner == orig_userid):
        grp.reassign_to(new_userid)
    else:
        grp.add_users(new_userid)
        remove_message = grp.remove_users([orig_userid])
        print(remove_message)
```

This time we can see the code succeeded.
![image](https://user-images.githubusercontent.com/520324/78198677-58433e00-7457-11ea-8e60-c3c564a7ac4e.png)

I can see in portal that the user fancelin_1 is now removed from the group, as it is supposed to be.
![image](https://user-images.githubusercontent.com/520324/78198731-845ebf00-7457-11ea-850a-f06e6c540637.png)

**Expected behavior**
The code that remove a user of a group should succeed and it does not. The fix is provided in the section above. But keep in mind that the fix required to make the sample work goes against what is stated in the documentation at 
https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Group.remove_users

Which means , your guys may have an API but or a documentation issue on the top of this issue which is that the sample does not remove a user from a group as expected.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge, Chrome
 - Python API Version 1.6, 1.7, 1.8

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by priyankatuteja** [comment]
@fabanc Thanks for your feedback! I Will work on improving the doc. Let us know as and when you get such issues.

**Comment by priyankatuteja** [comment]
@fabanc Thanks for your feedback! I Will work on improving the doc. Let us know as and when you get such issues.
