### ISSUE TITLE
NameError: name 'england_weather_stations_layer' is not defined

### ISSUE THREAD

**Issue by boundaryT** [Esri/arcgis-python-api#659]
`#Access spatial dataframe
england_weather_stations_layer_sdf =pd.DataFrame.spatial.from_layer(england_weather_stations_layer)
england_weather_stations_layer_sdf.head()`

> NameError                                 Traceback (most recent call last)
<ipython-input-8-9a2bdbb42e62> in <module>
      1 #Access spatial dataframe
----> 2 england_weather_stations_layer_sdf = pd.DataFrame.spatial.from_layer(england_weather_stations_layer)
      3 england_weather_stations_layer_sdf.head()

NameError: name 'england_weather_stations_layer' is not defined

**Comment by priyankatuteja** [comment]
@moonlanderr Can you please look into this.

**Comment by priyankatuteja** [comment]
@boundaryT You need to make sure that you have got this cell running successfully

**Comment by priyankatuteja** [comment]
@boundaryT You need to make sure that you have got this cell running successfully
