### ISSUE TITLE
Map viewer does not work with Jupyter

### ISSUE THREAD

**Issue by Boukary** [Esri/arcgis-python-api#676]
Map viewer does not work on ArcGIS Python API, with Jupyter notebook and Jupyter lab also
Any idea on how to solve this issue?

**To Reproduce**
```python
from arcgis.gis import GIS
my_gis = GIS()
my_gis.map()
```
error:
```python
MapView(layout=Layout(height='400px', width='100%'))
Image
```
**Screenshots**
![image](https://user-images.githubusercontent.com/8126372/80365024-780f2b80-8876-11ea-9e77-348086bed21d.png)
![image](https://user-images.githubusercontent.com/8126372/80366274-88280a80-8878-11ea-97d5-b03a7096246f.png)
![image](https://user-images.githubusercontent.com/8126372/80366700-36cc4b00-8879-11ea-97bd-3ea55d23baed.png) : Nothing is Shown

**Platform:**
 - OS: Windows 10
 - Browser: Chrome
 - Python API Version : 1.8.0 and 1.7.1

**Comment by achapkowski** [comment]
Can you open your browser console and see if any messages are printed there?

**Comment by achapkowski** [comment]
Do you have themes applied to the Jupyter notebook?  Try removing the themes and see what happens.  Themes overwrite default css and can effect widgets.

**Comment by Boukary** [comment]
Hi @achapkowski 

Thanks for your reply

I put the default theme as requested. 

in Jupyter Lab, I see this error on the console : 
![image](https://user-images.githubusercontent.com/8126372/80422776-53df3900-88ce-11ea-958a-a4e2a9e764ce.png)

in Jupyter Notebook, I see this error on the console : 
![image](https://user-images.githubusercontent.com/8126372/80422892-7e30f680-88ce-11ea-9345-a68776f137e1.png)

**Comment by Boukary** [comment]
@achapkowski do you have any idea about when the next release ? is it planned to fix some of those issues?

**Comment by achapkowski** [comment]
@Boukary it looks like for Jupyter notebooks the widgets are not installed and ipywidgets is not installed either, so it won't work.

Is this running on a local instance of JupyterLab and Notebook?  


### The map widget isn't displaying
Try running these commands: 
* ```jupyter nbextension install --py --sys-prefix arcgis``` (for enabling the map widget for Jupyter notebook)
* ```jupyter nbextension enable --py --sys-prefix arcgis``` (to initialize the map widget in the browser every time the notebook loads)

**Comment by achapkowski** [comment]
In regards to a release, we are planning a release around User Conference 2020.  We will take a look at this issue but I can't promise we'll have a fix because first we need to triage the issue.  This could be something isolated to your environment.  Ensure you remove ad blockers as well and re-install the API.

**Comment by Boukary** [comment]
@achapkowski forget it, it was a very stupid mistake, I didn't know that you should install nodejs and nmp with those [jupyter lab extensions](https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/) to make it work. 

Thanks anyway
Looking forward to UC2020
