### ISSUE TITLE
feature layer related records query returns dictionary that does not create a featureset when passed to the from_dict() function

### ISSUE THREAD

**Issue by ATL2001** [Esri/arcgis-python-api#680]
According to the API doc, it looks to me like the feature layer query_related_records function should return a feature set, however it seems to be returning a feature set, not a big deal but worth mentioning.

the larger issue for me is that when the the resulting dictionary is sent to the FeatureSet.from_dict() function, the resulting feature set from that function has no features

**To Reproduce**
```python
import pandas as pd

import arcpy
import arcgis
from arcgis.gis import GIS
from arcgis.features import FeatureLayer, GeoAccessor, GeoSeriesAccessor, FeatureSet, Feature
un =  "username"
pwd = "password"
gis = GIS(username=un, password=pwd)

print(f"arcgis python API version: {arcgis.__version__}")
feature_layer = FeatureLayer (r"https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/TestingRelates_WSL1/FeatureServer/0")
related_records = feature_layer.query_related_records("1,2,3", 0, "Latitude,Longitude,Head")
print(f"related_records type = {type(related_records)}  <-- looking at the API doc i think this should be a featureset")

print("that's ok, we can turn the dictionary into a featureset, right?")
featureset = FeatureSet.from_dict(related_records)
print(f"There are {len(featureset.features)} features in the featureset, however there should be 3 features in the featureset")
```

results in:
```
arcgis python API version: 1.8.0
related_records type = <class 'dict'>  <-- looking at the API doc i think this should be a featureset
that's ok, we can turn the dictionary into a featureset, right?
There are 0 features in the featureset, however there should be 3 features in the featureset
```

**Expected behavior**
I'd expect this to result in a featureset with three features.

**Platform (please complete the following information):**
 - OS: windows
 - Python API Version 1.8.0

**Additional context**
I've added the following code after the "if 'features' in featureset_dict:" section to the feature.py module (line 936) to get the from_dict function to work on my machine for my purposes.  I'm not sure that what I've written will handle all cases, but it does seem to be working for what I need :
```python
        elif 'relatedRecordGroups' in featureset_dict:
            for feat in featureset_dict['relatedRecordGroups']:
                features.append(Feature.from_dict(feat["relatedRecords"][0]))    
```
after this the same code that I provided above results in: 
```
arcgis python API version: 1.8.0
related_records type = <class 'dict'>  <-- looking at the API doc i think this should be a featureset
that's ok, we can turn the dictionary into a featureset, right?
There are 3 features in the featureset, however there should be 3 features in the featureset
```

hopefully this helps 
-aTL

**Comment by CMPeng** [comment]
Hi @ATL2001 There are two ways to solve this issue:
1. We recommend using a direct query for the purpose of deriving dict for certain features inside a feature service and later creating them as a FeatureSet, you can try:
```
direct_query = feature_layer.query(where="objectId<4", out_fields='Latitude,Longitude,Head')
direct_query # returns a FeatureSet with 3 features
```
2. Or following your workflow, after getting `related_records`, you need to have one line of:
```
related_records["features"] = related_records["relatedRecordGroups"]
```
before calling `featureset = FeatureSet.from_dict(related_records)`; This one-line of code is to add a new kvp "features" which are essential for `from_dict` to recognize if there are any features in the dict.
