### ISSUE TITLE
advanced_search Documentation

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#683]
**Describe the bug**
Seeing this error when trying to run advanced_search from ContentManager. Documentation doesn't even specify a 'q' or 'searchUserAccess' and 'bbox' and 'categories' are listed as optional in documentation.

**To Reproduce**
```python
ago = arcgis.gis.GIS("********", "******", "******")
ago_search = ago.content.advanced_search(query="", sort_field='type', sort_order='asc')
```
error:
```python
<Unable to perform search.
'q', 'bbox', 'categories' or 'searchUserAccess' parameter must be specified.>
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 1.7.0

**Comment by achapkowski** [comment]
set query to *
