### ISSUE TITLE
select_by_location fails on spatial dataframe

### ISSUE THREAD

**Issue by jessenestler** [Esri/arcgis-python-api#695]
**Describe the bug**
SpatialDataFrame.select_by_location() fails when arcpy is not installed

**To Reproduce**
```python
# no arcpy installed, use shapely instead
from arcigs.geometry import Geometry, SpatialDataFrame
compare_geom = Geometry()
sdf = SpatialDataFrame()
out_sdf = sdf.select_by_location(compare_geom, matches_only=True)
```
error:
```python
~/anaconda3/envs/conda_env/lib/python3.8/site-packages/arcgis/features/_data/geodataset/geodataframe.py in select_by_location(self, other, matches_only)
   1979 
   1980         """
-> 1981         if isinstance(other, Geometry):
   1982             if self.geometry_type.lower() == 'point':
   1983                 res = self.within(other)

NameError: name 'Geometry' is not defined
```
**Expected behavior**
I expect the select_by_location on spatial dataframes to accept `shapely` geometry types and set-theoretic comparisons as input, not just `arcpy`. At the very least, having the documentation note that the operation is only possible with `arcpy` would be sufficient in the interim.

**Platform (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Browser: Chrome
 - Python API Version `1.8.0`

**Additional context**
I have `shapely` installed as the main package for geometric comparisons. On mac, so no `arcpy` available.

**Comment by achapkowski** [comment]
The `SpatialDataFrame` is deprecated.  Please use the `spatial` accessor instead.
