### ISSUE TITLE
Add support for pandas nullable integer data type (Int64)

### ISSUE THREAD

**Issue by ghaefele** [Esri/arcgis-python-api#698]
**Description**
An export with **to_featureclass (GeoAccessor)** from a pandas dataframe (sedf) fails, if the dataframe has a field with a **nullable integer data type** (**I**nt64)

**Describe the solution you'd like**
Add support for pandas "**Int64**" (nullable integer data type) and [pandas.NA](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html).

**Comment by matt6697** [comment]
The following code fails silently when the spatial dataframe contains an **int64** column :

```
sdf = GeoAccessor.from_geodataframe(data)
sdf.spatial.to_featureclass('memory/geodataframe')
arcpy.MakeFeatureLayer_management('memory/geodataframe','memory/geodataframe')
```
![image](https://user-images.githubusercontent.com/32440697/160210910-46bba6d8-506c-4936-9ce9-96ef67a06a3b.png)


No Python error is returned by arcpy but the attribute table of the generated featureclass is empty.

![image](https://user-images.githubusercontent.com/32440697/160211010-1d555ff9-6f30-47f0-bd21-dcebba2ee023.png)

**Comment by achapkowski** [comment]
@matt6697 can you please post a small reproducible sample with code we can run locally?

**Comment by matt6697** [comment]
When the **int64** group column is defined in the dataframe, the generated featureclass is empty and code fails silently :

```
import pandas as pd
import arcpy
from arcgis import GeoAccessor

df = pd.DataFrame({
    'group': [2327490580, 2347490581, 3442810439], 
    'colors': ['red', 'white', 'blue'], 
    'long': [10, 20, 30], 
    'lat': [15, 20, 25]})

sdf = GeoAccessor.from_xy(df, 'long', 'lat', sr=4326)
sdf.spatial.to_featureclass('memory/int64issue')
```

**sdf.dtypes**
```
group        int64
colors      object
long         int64
lat          int64
SHAPE     geometry
dtype: object

**Comment by matt6697** [comment]
Hi @achapkowski, is the provided sample good for you ? Did you manage to find the issue in arcpy ?

**Comment by achapkowski** [comment]
@matt6697 to work around this, I suggest you cast your `group` value from int64 to float.  The dataset you are working with only support writing to int32 not int64.  I would suggest you reach out to support and ask for int64 support.

```
df.goup = df.group.astype(float)
```
