### ISSUE TITLE
arcgis.viz MapView _handle_map_msg() incorrect number of arguments

### ISSUE THREAD

**Issue by BobEntwistle** [Esri/arcgis-python-api#7]
Hi,

When using `arcgis.viz MapView` in a Jupyter Notebook, I have found that left click, hold and drag will move the map as desired, however on release an error is produced:

`---------------------------------------------------------------------------`
`TypeError                                 Traceback (most recent call last)`
`TypeError: _handle_map_msg() takes 3 positional arguments but 4 were given`

If useful, this is my version and set-up:
`Python 3.5.1 | Continuum Analystics, Inc. | (default, Jun 15 2016, 15:32:45)`
`[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux`

Regards,

Bob

**Comment by AtmaMani** [comment]
@BobEntwistle Thanks for reporting, this issue has been fixed. Please try the next release of the API scheduled for later half of Sep 2016.

**Comment by rohitgeo** [comment]
@BobEntwistle v0.3 beta is now out and this is resolved there. Thanks for reporting the issue.
