### ISSUE TITLE
jupyter kernel always restarts when training PointCNN model.

### ISSUE THREAD

**Issue by LinoSun** [Esri/arcgis-python-api#700]
**Describe the bug**
Jupyter kernel always restarts when training PointCNN model.Maybe cased by large IO requests,I don't know.Has anyone meets the same issue?

**To Reproduce**
```python
data = prepare_data(path, batch_size=36, dataset_type='PointCloud')
model=PointCNN(data)
model.lr_find(allow_plot=True)
```
error:
details in attached picture
**Screenshots**
![image](https://user-images.githubusercontent.com/44741345/82804277-920f4e80-9eb4-11ea-9cd4-b40ec28771d7.png)

**Platform (please complete the following information):**
 - OS: [centos]
 - Browser [chrome]
 - Python API Version [`1.8`]

**Comment by LinoSun** [comment]
@AtmaMani

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
