### ISSUE TITLE
HTTPError where Portal set to allow Http connections

### ISSUE THREAD

**Issue by geompc** [Esri/arcgis-python-api#715]
When trying to clone items from Portal 10.6.1 to another 10.6.1 Portal the API throws an error, "Error cloning data: HTTPError: this service url encountered an HTTP Error:"

```python
    target_gis.content.clone_items(data,"Dashboard",copy_data=False,
                                   search_existing_items=True,item_mapping=item_mapping_dict)
```

error:
```python
Logged into Portal in STAGING
Logged into Portal in TEST
Attempting to migrate item.....<Item title:"Scenarios" type:Dashboard owner:username>
Error cloning data: HTTPError: this service url encountered an HTTP Error: http://portalurl/hosting/rest/services/Hosted/servicename/FeatureServer
```
**Screenshots**
After changing this Security setting in Portal (requires Admin access) the same code works successfully
![image](https://user-images.githubusercontent.com/30782013/84978892-2f8f3280-b182-11ea-9d2a-6c375e371ba0.png)

**Expected behavior**
API shouldn't default to http, it should attempt https first. The items being copied are all referenced with Https.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Python API Version - tried with 1.5.1 & 1.6.1

**Comment by achapkowski** [comment]
Using HTTP can be a security risk and normally the API always tries to use HTTPS.  If the item being cloned has a URL of HTTP is will honor that URL.
