### ISSUE TITLE
Deeplab inside ArcGIS Pro : Slow and Weird results !!!

### ISSUE THREAD

**Issue by Boukary** [Esri/arcgis-python-api#717]
**Describe the bug**
I m using Deeplab Tensorflow model to do segmentation on a raster layer using ArcGIS Pro built-in Python raster functions for TensorFlow. I mainly have 2 issues : 

1 - The results are good but it took me **13hours** when I use **Classify Pixels using Deep Learning Tool**. When I do it outside ArcGIS it only takes **4min**. I think something is wrong with Deeplab implementation used with ArcGIS Pro.

2 - The predicted segmentation raster layer look weird, you can see those rectangle patterns (see image below), is there any way to remove or at least reduce that effect?

**To Reproduce**
You can reproduce that by using any Deeplab TensorFlow model to segment a raster layer (RGB image) inside ArcGIS Pro 2.5.1 using Classify Pixels using Deep Learning Tool.

**Screenshots**
![image](https://user-images.githubusercontent.com/8126372/85453348-acac1480-b593-11ea-936d-586b26a36481.png)

**Expected behavior**
Fast results with no weird rectangular patterns

**Platform (please complete the following information):**
 - OS: Windows 10
 - ArcGIS Pro : 2.5.1
 - Python API Version : 1.7.1

Thanks

**Comment by rohitgeo** [comment]
The right place to report this is at https://github.com/Esri/raster-deep-learning 

This repo is for ArcGIS API for Python and ArcGIS.learn.

You can let us know if you see these issues with the arcgis.learn DeepLab implementation in this repo.
