### ISSUE TITLE
item.shared_with does not return groups with 'shared update' capability

### ISSUE THREAD

**Issue by ah-rspb** [Esri/arcgis-python-api#721]
**Describe the bug**

'shared update' groups not returned when using item.shared_with. This is proving an issue for migrating content to new accounts as we need to unshare item from group, reassign onwer and then reshare with group
run https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html?highlight=shared_with#arcgis.gis.Item.shared_with

**To Reproduce**
Share an item with a group with 'shared update'  and a normal group capability using the UI
Run
groups = item.shared_with

'shared update' group is not returned

run https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html?highlight=shared_with#arcgis.gis.Item.shared_with
```python
groups = item.shared_with
groups["groups"]
```
error:
```python

```
**Screenshots**

**Expected behavior**
shared update group should be returned

**Platform (please complete the following information):**
 - OS: AGOL notebook
 - Browser chrome
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
This issue should be resolved at `v1.8.3`
