### ISSUE TITLE
Detail information on vmtilocaldataset column values

### ISSUE THREAD

**Issue by Hiromu-Nakamura** [Esri/arcgis-python-api#727]
**Is your feature request related to a problem? Please describe.**
It would be appreciated if there is detail information, such as a guide document, on vmtilocaldataset column which is generated after executing [predict_video](https://developers.arcgis.com/python/api-reference/arcgis.learn.html#arcgis.learn.SingleShotDetector.predict_video) method.

Several values will be added to the single new column like the following picture;
![2020-07-06_19h41_30](https://user-images.githubusercontent.com/20600894/86591039-b722d100-bfcb-11ea-87f0-961db805898f.png)
I assume that the first integer is the number of detected objects, however,  there is no detail information about what these values mean.

**Describe the solution you'd like**
It would be appreciated if there is a detail documents about what these values mean

**Describe alternatives you've considered**
It would be more useful if the several new columns associated with each of these values are created after executing the method,
and each column is named explicitly.

**Additional context**
N/A

**Comment by nanaeaubry** [comment]
This issue is older and will be closed in an effort to remove stale issues. Please feel free to reopen if needed.
