### ISSUE TITLE
arcgis.geometry.functions.union returns Geometry with empty spatial reference

### ISSUE THREAD

**Issue by jessenestler** [Esri/arcgis-python-api#737]
**Describe the bug**
Calling arcgis.geometry.union on a list of Geometry objects successfully creates a new Geometry, but the `spatial_reference attribute = None`.

**To Reproduce**
```python
# Imports
from arcgis.gis import GIS
from arcgis.features import FeatureLayer

# GIS env
sr = 2876 #  NAD83(HARN) / Colorado North (ftUS)
gis = GIS()

# Set up FeatureLayer
url = "url/to/feature/service"
feature = FeatureLayer(url)
feature_set = city.query(out_sr=sr)
geoms = [poly.geometry for poly in feature_set.features]
unioned = union(spatial_ref=sr, geometries=geoms, gis=gis)

unioned.spatial_reference #  returns None
```
**Error:**
No error, silently returns `None`

**Expected behavior**
The output `unioned` Geometry should inherit from its components.

**Platform:**
 - OS: macOS Catalina 10.15.4
 - Python API Version: 1.8.2

**Additional context**
As I'm working locally on my mac, I'm working exclusively with the `shapely` lib.

**Comment by jessenestler** [comment]
For now, my workaround is to reconstruct the polygon from a dict:

```python
unioned = union(spatial_ref=sr, geometries=geoms, gis=gis)
new_union = arcgis.geometry.Geometry({"rings": unioned.rings, "spatialReference": {"wkid": sr}})
```

**Comment by AtmaMani** [comment]
Thanks for reporting, I am able to reproduce this. We will investigate and try to fix it for the next release
