### ISSUE TITLE
Support/Implement __geo_interface__

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#74]
I suggest adding [`__geo_interface__`](https://gist.github.com/sgillies/2217756) support to [`arcgis.features`](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.features.toc.html) and [`arcgis.geometry`](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.geometry.html).

[`__geo_interface__`](https://gist.github.com/sgillies/2217756)  is "a GeoJSON-like protocol for geo-spatial (GIS) vector data."  It follows a similar model/idea as NumPy's [Array Interface](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html).  It was proposed or put forward in 2013, and more than a dozen geospatial Python applications (see [Python Geo_interface applications](https://github.com/mlaloux/Python-geo_interface-applications)) implement the protocol.  The protocol allows for simple and efficient transferring of features and geometries between various geospatial Python packages.

ArcPy currently supports `__geo_interface__` in its [Geometry classes](http://desktop.arcgis.com/en/arcmap/latest/analyze/arcpy-classes/geometry.htm) (*it can be argued there is only partial support since the current implementation is broken in several ways*).    On a system with both ArcPy and Shapely installed, passing a geometry object from the former to the latter can be done efficiently with a single function call:
```Python
>>> import arcpy
>>> from shapely.geometry import shape
>>> 
>>> arc_polygon = arcpy.FromWKT('POLYGON((0 0, 10 0, 10 10, 0 10, 0 0))',
...                             arcpy.SpatialReference(3857))
... 
>>> arc_polygon.area
100.0
>>> 
>>> shapely_polygon = shape(arc_polygon)  # pass ArcPy geometry to Shapely
>>> 
>>> shapely_polygon.area
100.0
>>> shapely_polygon.buffer(1.0).area
143.13654849054595
>>>
```
Granted, there are numerous ways features and geometry objects can be passed between geospatial Python packages, but `__geo_interface__` represents an established, open, well-adopted, and efficient means that should be supported within the [ArcGIS Python API](https://developers.arcgis.com/python/).  Additionally, the protocol is lightweight and straightforward to implement.

**Comment by rohitgeo** [comment]
Thank you for the suggestion. Geometry and SpatialDataFrame now implement __geo_interface__.
