### ISSUE TITLE
RuntimeError: DataLoader worker (pid 6000) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by LinoSun** [Esri/arcgis-python-api#743]
**Describe the bug**
Out of memory whilie training DeepLearning model.

**To Reproduce**
```python
from arcgis.learn import prepare_data,SingleShotDetector
data_path = r'samples_data_path'
data =prepare_data(data_path,batch_size=128,dataset_type='PASCAL_VOC_rectangles',chip_size=512)
model = SingleShotDetector(data)
lr = model.lr_find()
model.fit(200,lr)
```
error:
```python
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lino/anaconda3/envs/arcgis181/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lino/anaconda3/envs/arcgis181/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/lino/anaconda3/envs/arcgis181/lib/python3.7/site-packages/arcgis/learn/_data.py", line 130, in _bb_pad_collate
    return torch.cat(imgs,0), (bboxes,labels)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 402653184 bytes. Error code 12 (Cannot allocate memory).
```
**Screenshots**
![image](https://user-images.githubusercontent.com/44741345/88246326-b9c03e80-cccc-11ea-804b-990b9d0b951d.png)
![image](https://user-images.githubusercontent.com/44741345/88246297-a614d800-cccc-11ea-9d54-80bbead78035.png)
![image](https://user-images.githubusercontent.com/44741345/88246336-c93f8780-cccc-11ea-8335-f14d93ec42a8.png)
![image](https://user-images.githubusercontent.com/44741345/88246353-d3618600-cccc-11ea-9c51-8dc9c492b99e.png)

**Expected behavior**

**Platform (please complete the following information):**
 - OS: [CentOS Linux release 7.7.1908 (Core)]
 - Browser [chrome]
 - Python API Version [ `1.8.2`]

**Additional context**

**Comment by rohitgeo** [comment]
This is an error due to limited shared memory available to the process. Please try reducing the batch size or making more memory available to the process
