### ISSUE TITLE
DistributedDataParallel

### ISSUE THREAD

**Issue by chiheye** [Esri/arcgis-python-api#756]
My computer is multiple GPUs, and I tried to use distributed data parallel to run multi card data on a single machine, but failed

**Comment by achapkowski** [comment]
Can you please expands upon what you did are doing by providing code.  Your description is not enough for us to reproduce or triage the issue.

**Comment by rohitgeo** [comment]
See [here](https://nbviewer.jupyter.org/github/Esri/arcgis-python-api/blob/master/guide/14-deep-learning/utilize_multiple_gpus_to_train_model.ipynb) for explanation on how to use multiple GPUs to train arcgis.learn models.
