### ISSUE TITLE
Slight GIS doc confusion

### ISSUE THREAD

**Issue by nixta** [Esri/arcgis-python-api#76]
The GIS.map() documentation refers to a "map widget" but it seems it should say "MapView widget".

I'm new to Python and to arcgis-python-api, so it could be this is an acceptable convention, but it threw me and had me looking for a `Map` type somewhere to see what I could do with the returned object (and really I was looking for a `MapView`).

Worth updating?

**Comment by AtmaMani** [comment]
@nixta are you referring to this doc [http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.html#arcgis.gis.GIS.map](http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.html#arcgis.gis.GIS.map)

**Comment by nixta** [comment]
I'm sorry. Yes, @AtmaMani. Can't believe I left that out :)

Perhaps instead of "Creates a map widget centered..." something like "Creates a MapView widget that displays a map centered..."?

**Comment by AtmaMani** [comment]
Yes, I guess we can change it to "Creates a MapView widget...." like you said.
