### ISSUE TITLE
Pandas DataFrames and tables Problem

### ISSUE THREAD

**Issue by acanivano** [Esri/arcgis-python-api#771]
I have a service published in ArcGis Online that consists of a layer and two related tables.
I have to access one of the tables to write a url and I'm using Pandas to do it. Until now it worked correctly, but now I get the following error.

```
item = gis.content.get("xxxxxxxxxxx")
foto = (item.tables)[1]
field_service_dataframe = pd.DataFrame.spatial.from_layer(foto)

```
error:
`Could not load the dataset: 'PropertyMap' instance has no attribute 'drawingInfo'`

If I want to access the layer, I can create the dataframe correctly; however with a table I can't.
Is it normal that only the data of the layer can be accessed or I have something missing in my code?

**Comment by achapkowski** [comment]
This issue will be resolved in the next release, which will be near the end of the year.

**Comment by jhuillery** [comment]
This issue was never fixed. It is still active

**Comment by achapkowski** [comment]
The issue is resolved in the next release, which will be 1.9.0.

**Comment by koelker12** [comment]
Is there a release window or timeframe for 1.9.0?

**Comment by achapkowski** [comment]
Tentatively around UC 2021.
