### ISSUE TITLE
Updating credits

### ISSUE THREAD

**Issue by vassilo** [Esri/arcgis-python-api#778]
Is there away to upgrade the credits assigned to a user via the python API?

**Comment by achapkowski** [comment]
see: https://developers.arcgis.com/python/api-reference/arcgis.gis.admin.html?highlight=allocate#arcgis.gis.admin.CreditManager.allocate

From your admin GIS object:

```python
gis.admin.credits.allocate(...)
```

**Comment by vassilo** [comment]
Thank you.
