### ISSUE TITLE
States sample data is missing DBF.

### ISSUE THREAD

**Issue by seansweeney** [Esri/arcgis-python-api#781]
**Describe the bug**
In the arcgis-python-api/guide/05-working-with-the-spatially-enabled-dataframe/data.zip file, the states shapefile is missing the DBF component and therefore can't be opened.

**To Reproduce**
```python
# Unzip the data to arcgis-python-api/guide/05-working-with-the-spatially-enabled-dataframe/data
data_pth = r'data'
states = r"states.shp"
sdf_join = pd.DataFrame.spatial.from_featureclass(os.path.join(data_pth, states))
```
error:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-f550f831b55c> in <module>
      1 sdf_target = pd.DataFrame.spatial.from_featureclass(os.path.join(data_pth, cities))
----> 2 sdf_join = pd.DataFrame.spatial.from_featureclass(os.path.join(data_pth, states))

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_accessor.py in from_featureclass(location, **kwargs)
   2324         :returns: pandas.core.frame.DataFrame
   2325         """
-> 2326         return from_featureclass(filename=location, **kwargs)
   2327     #----------------------------------------------------------------------
   2328     @staticmethod

~\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\lib\site-packages\arcgis\features\geo\_io\fileops.py in from_featureclass(filename, **kwargs)
    398                              where_clause=where_clause,
    399                              sql_clause=sql_clause,
--> 400                              spatial_reference=sr) as rows:
    401             srows = []
    402             for row in rows:

RuntimeError: cannot open 'data\states.shp'
```

**Expected behavior**
States shapefile opens without error (as cities does).

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Python API Version 1.8.2

**Comment by achapkowski** [comment]
try adding a period backslash to the front of the path.  Also is the directory `data` in the same folder at the script?

```r".\data\states.shp"```

**Comment by seansweeney** [comment]
> try adding a period backslash to the front of the path. Also is the directory `data` in the same folder at the script?
> 
> `r".\data\states.shp"`

Sorry if I wasn't clear - The path reference to the data is not the issue.  The zip file of sample data is missing states.dbf (one of the three required components of a shapefile).

**Comment by achapkowski** [comment]
@DavidJVitale or @AtmaMani can you take a look at the file for this guide?

**Comment by AtmaMani** [comment]
@seansweeney thank you for reporting this. For the next version of the API, we will revise the SeDF guide series and will fix this. We are also moving away from including data in this repo to hosting them as items in ArcGIS Online. This is to reduce the size of this repo.
