### ISSUE TITLE
Add support for PDF in Survey123 generate_report

### ISSUE THREAD

**Issue by DanCranford** [Esri/arcgis-python-api#787]
Hey all -

The [generate_report](https://developers.arcgis.com/python/api-reference/arcgis.apps.survey123.html#arcgis.apps.survey123.Survey.generate_report) function currently supports Word Document (docx) outputs by default.    

I was able to output a pdf by modifying the API code as follows

```python
    params = {
        # changed outputFormat from "docx" to "pdf"
        "outputFormat" : "pdf",
        "queryParameters" : where,
        "portalUrl" : survey._si._gis._url,
        "templateItemId" : report_template.id,
        "outputFileName" : "%s_report_%s" % (survey._si.title.replace(" ", "_"), uuid.uuid4().hex[:6]),
        "surveyItemId" : survey._si.id,
        "featureLayerUrl" : survey._ssi.layers[0]._url.replace("_fieldworker", ""),
        "utcOffset" : utc_offset,
        "uploadInfo" : json.dumps(None),
        "f": "json",
        "username": survey._si._gis.users.me.username
    }
```

It would be awesome if the output format could be added as a parameter that enabled a choice between docx and pdf.

**Comment by achapkowski** [comment]
@DanCranford I'll add this to the list and try to get it in.  Thank you for the suggestion.

**Comment by BrettFrahm** [comment]
Just wanting to add my voice. Recently needed this for my project and ended up using the REST API to accomplish what I wanted. Generating PDF reports with the Python API would be very helpful. Thanks!

**Comment by kpmcgurk** [comment]
+1, this would be super helpful.

**Comment by nanaeaubry** [comment]
This has been added
