### ISSUE TITLE
Identify_Items_That_Use_Insecure_URLS Notebook Error - csv file

### ISSUE THREAD

**Issue by Count0Int** [Esri/arcgis-python-api#796]
When running against arcgis.com, with proper credentials, notebook throws an error:

```
FileNotFoundError                         Traceback (most recent call last)
In  [40]:
Line 1:     main()

In  [39]:
Line 14:    all_urls_path, insecure_items_path = create_csvs()

In  [34]:
Line 16:    with open(file_path, 'w') as file:

FileNotFoundError: [Errno 2] No such file or directory: '/arcgis/home/ALL_URLs-Tue Sep 22 13:37:41 2020.csv'

```

Running the notebook inside of ArcGIS Pro 2.6.1

**Comment by achapkowski** [comment]
So you are using ArcGIS' Notebook Environment? or are you running the notebook in Pro 2.6.1?  Can you post your notebook?

One thing to check is if there is a variable called : "/arcgis/home" if so, update it to the environment it's running in.

**Comment by Count0Int** [comment]
Hello,

Yes I am using the notebook environment in ArcGIS Pro 2.6.1.

The notebook isn't changed from the download from here (Identify_Items_That_Use_Insecure_URLs.ipynb), other than credentials.  The only difference really, is that I am pointing the connection to AGOL instead of our Portal.

gis = GIS("https://www.arcgis.com/", "username", "password")

Using my org username and password of course.

This line sets the variable to the value that is throwing an error later:

workspace = "/arcgis/home"

It is used in the section to create the csv's.  If I am running this against AGOL, should I set this path to something different?

I was thinking about re-writing the section that is writing csv's into the portal, and just saving them on the pc I am running the notebook from, but I thought there should be a quick fix so it would run as is without a significant rewrite.

Any suggestions, greatly appreciated.  I am hoping to modify this notebook once working to help document all layers used in all maps in our AGOL instance.

**Comment by Count0Int** [comment]
Update on this.

I uploaded the notebook to run in AGOL and it works perfectly.  I didn't see in the documentation, but obviously these examples are meant to run in AGOL and not an ArcGIS Pro Notebook without some modifications.  Hopefully this helps someone in the future.
