### ISSUE TITLE
Running error when user name contains a dot (ie 'firstname.lastname' in AppData path)

### ISSUE THREAD

**Issue by sfaraut** [Esri/arcgis-python-api#800]
Execution stop with error when user name contains a dot (ie 'firstname.lastname' ).

`data_path = Path(os.path.join(filepath.rsplit('.')[0]))`

Path string contains then a dot and split function occurs on first dot of path:
'C:\\Users\\XXX~1.YYY\\AppData\\Local\\Temp\\ArcGISProTemp11600\\detecting_and_categorizing_brick_kilns_from_satellite_imagery.zip'
rather than last dot of file extension (.zip)!!!

Can be changed to:
```
import os
data_path = Path(os.path.join(os.path.splitext(filepath)[0]))
```

**Comment by priyankatuteja** [comment]
@sfaraut Thanks, will fix it soon

**Comment by priyankatuteja** [comment]
Fixed.

**Comment by priyankatuteja** [comment]
https://developers.arcgis.com/python/sample-notebooks/detecting-and-categorizing-brick-kilns-from-satellite-imagery/
