### ISSUE TITLE
Problem With Accessing GIS Python Playground Portal

### ISSUE THREAD

**Issue by RickyOpenware** [Esri/arcgis-python-api#821]
I tried to run the following line both locally and your "Try It Live", and get error
gis = arcgis.GIS('https://python.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')

Unable to sign user because a software authorization error.
If I try to log in to the portal using web browswer , get the same error.

**Comment by priyankatuteja** [comment]
portal_url = "https://pythonapi.playground.esri.com/portal"
portal_user = "arcgis_python"
portal_pwd = "amazing_arcgis_123"

Please try with the correct url. Let us know if it still doesn't work.

**Comment by LuisRguezEsriSpain** [comment]
With this url, user and password:
portal_url = "https://pythonapi.playground.esri.com/portal"
portal_user = "arcgis_python"
portal_pwd = "amazing_arcgis_123"

I get this error message:

Invalid username or password.

**Comment by priyankatuteja** [comment]
cc @rwmajor2  Could you look into this

**Comment by AdilGambarov** [comment]
I've had the same problem with accessing   "https://pythonapi.playground.esri.com/portal". 
Any progress on the issue?

**Comment by rwmajor2** [comment]
@priyankatuteja Password reset.
