### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by hemingwaylane** [Esri/arcgis-python-api#828]
I'm trying to use the map widget in Jupyter Lab and it errors with _Error displaying widget: model not found_:
![image](https://user-images.githubusercontent.com/35620077/98609058-224e1e00-22b2-11eb-80c1-1305fdf18faa.png)

 My arcgis-map-ipywidget and Python API versions don't match and I'm not sure how to get them to match. The arcgis-map-ipywidget is 1.8.3 and the API is 1.8.2:
![image](https://user-images.githubusercontent.com/35620077/98608995-00ed3200-22b2-11eb-912c-cf63fe634ca0.png)

**Comment by DavidJVitale** [comment]
@hemingwaylane run this in your command line:

```jupyter labextension install arcgis-map-ipywidget@1.8.2```

We cut a pre-release of 1.8.3 on conda and npm. You need to have a match of 1.8.2 on conda and on jupyter labextension list

**Comment by hemingwaylane** [comment]
@DavidJVitale - That did the trick. Thank you!
