### ISSUE TITLE
Create Schema In Category Manager Fails

### ISSUE THREAD

**Issue by Hlindemann** [Esri/arcgis-python-api#849]
**Describe the bug**
When overloading the schema method the setter is never triggered for class arcgis.gis.admin.CategoryManager(gis).schema(value)

If drill into the class then I observe that 
```python    
@property
    def schema(self):
```
is called instead of the overload
```python
    @schema.setter
    def schema(self, value):
```
in _catagoryschema.py line 81

**To Reproduce**
```python
from arcgis.gis import GIS
from arcgis.gis.admin import CategoryManager

gis = GIS("URL", 'USERNAME', 'PASSWORD')
manager = CategoryManager(gis)

new_schema = [{
    "title": "Themes",
    "categories":
        [{"title": "Basemaps", "categories":
            [{"title": "Partner Basemap"}, {"title": "Esri Basemaps", "categories": [{"title": "Esri Redlands Basemap"},
            {"title": "Esri Highland Basemap"}]}]},
         {"title": "Region", "categories": [{"title": "US"}, {"title": "World"}]}]
}]

manager.schema(new_schema)
```
error:
```python
Traceback (most recent call last):
  File "E:/Code/Python3/EsriProduction/acgis_api_2020/main.py", line 16, in <module>
    manager.schema(new_schema)
TypeError: 'dict' object is not callable
```
**Screenshots**
When passing in the schema the code jumps to the schema method instead of the setter
![image](https://user-images.githubusercontent.com/21313366/101133617-bbeac000-3611-11eb-8586-6918ea3e3820.png)
![image](https://user-images.githubusercontent.com/21313366/101133669-dd4bac00-3611-11eb-93c2-410ba721f3ac.png)

**Expected behavior**
I expect the schema to be created

**Platform (please complete the following information):**
 - OS: Windows Server 2016; Windows 10 
 - Browser: N/A
 - Python API Version 1.8.3.post2

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by priyankatuteja** [comment]
![image](https://user-images.githubusercontent.com/39754605/104799174-f049c280-57f2-11eb-8555-0130c234978c.png)

@Hlindemann Could you try it the way it's shown in the screenshot above.

**Comment by Hlindemann** [comment]
Hi @priyankatuteja, than you very much for the assistance the workflow described above is working. 

Would it be possible to just update the documentation with an example I don't think the setter decorator is widely used in the API and this is probably going to cause some confusion down the road again.

Kind Regards
Henry
