### ISSUE TITLE
Issue installing with Python 3.6

### ISSUE THREAD

**Issue by apulverizer** [Esri/arcgis-python-api#85]
When attempting to install the package with Python 3.6 as shown below:
```bash
anaconda_test/anaconda/bin/conda create -n arcgis_fresh3.6 python=3.6 anaconda
anaconda_test/anaconda/bin/conda install -n arcgis_fresh3.6 -c esri arcgis
```
I get the following error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - arcgis -> python 3.4* -> openssl 1.0.1*
  - arcgis -> python 3.4* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

If I create a virtual environment using Python 3.5, it installs and works as expected. 

If you use the latest anaconda releases it will default to Python 3.6 which is how I originally found this error. Only tested this issue on Mac x86_64 anaconda.

Documentation says it supports 3.5 or higher 

> The ArcGIS API for Python requires Python 3.5 or higher.

**Comment by scw** [comment]
I've reproduced this locally. The Python 3.6 Mac x86_64 package was missing, I've uploaded it and can now install in Python 3.6 correctly. Could you confirm it works on your end?

Thanks, Shaun

**Comment by apulverizer** [comment]
Works for me now as well. Thanks.
