### ISSUE TITLE
Question: When will 1.8.3 be released?

### ISSUE THREAD

**Issue by EdFarrell** [Esri/arcgis-python-api#852]
Can you provide a timeline or estimated timeline for the release of 1.8.3, and subsequent availability on pypi? Thank you.

**Comment by DavidJVitale** [comment]
Hi @EdFarrell . The python packages for 1.8.3 have already been released on pypi and anaconda, you can install via

`pip install arcgis`

or

`conda install -c esri arcgis`

We haven't updated the public facing documentation yet announcing this, showcasing new features etc. That should be released in the next few weeks. @AtmaMani can say more.

**Comment by EdFarrell** [comment]
@DavidJVitale - thanks! I was looking at the release page in GitHub instead of just checking pypi. Any docs on new features would be great. I needed this version specifically for Workforce integration with the new Workforce projects (instead of "classic"). Closing this.

**Comment by AtmaMani** [comment]
@EdFarrell per the current plan, the API will be released next Friday (12/18/2020). You can see the new samples, guides in this milestone: https://github.com/Esri/arcgis-python-api/milestone/3. For a raw look into what's new in 1.8.3, you can checkout the release notes PR at https://github.com/Esri/arcgis-python-api/pull/820. This is work-in-progress.
