### ISSUE TITLE
ArcGIS Python API- No Fill Symbol converted to black

### ISSUE THREAD

**Issue by PoojaGambhir16** [Esri/arcgis-python-api#854]
**Describe the bug**
While cloning web map from AGOL to Enterprise, I have updated the Polygon symbol with no fill and set only outline layer. 
But when content cloned into Enterprise the polygon is shown with Black fill. Some how None fill is getting converted to Black fill.
**To Reproduce**
1)  Create a webmap with polygon symbol fill as None
2) Now clone the webmap using python API
3) Cloned map will show black color as fill instead of no color

```python
<insert your code here>
```
error:
```python
<copy the full error message here>
```
**Screenshots**

**Expected behavior**

**Platform (please complete the following information):**
 - Python API Version [e.g. `1.6.2`] (you can get this by typing `print(arcgis.__version__)`

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by achapkowski** [comment]
@PoojaGambhir16 Can you try updating to v1.8.3 and see if your issue is fixed.  The 1.6.2 version is quite old.

**Comment by PoojaGambhir16** [comment]
As suggested, I upgraded the api to 1.8.3 but still the issue persists. 
Setting the polygon layer fill color blank 
Then migrated my web map using python api and cloned map shows polygon layer with black fill .

**Comment by PoojaGambhir16** [comment]
Anyone facing same issue while cloning web map having no-fill polygon layers?

**Comment by PoojaGambhir16** [comment]
I tried to clone web map from one portal environment to another using polygon layer with no fill and same issue the polygon is shown with black color. I have checked the json created as well it is showing correct value as None but still I am getting this issue

![image](https://user-images.githubusercontent.com/62989674/102245204-2d215180-3ef5-11eb-947f-c8caaa653256.png)

**Comment by nanaeaubry** [comment]
@PoojaGambhir16 We have made some updates and hope this issue is resolved. If you are still having issues please let us know.
