### ISSUE TITLE
Provide method to use "Export Item" REST endpoint

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/arcgis-python-api#87]
I am writing a [script] where I need to use the [Export Item] REST endpoint to export from a Feature Layer to a Feature Collection. As far as I can tell there doesn't seem to be a way to access [Export Item] via the ArcGIS Python API. (Or if there is, it doesn't seem to be documented.)

[Export Item]:http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Export_Item/02r30000008s000000/
[script]:https://github.com/WSDOT-GIS/wsdot-traffic-gp/blob/master/update_fc.py

**Comment by JeffJacobson** [comment]
I never figured out a way to do this with the `arcgis` package, but did manage a [workaround](https://github.com/WSDOT-GIS/wsdot-traffic-agol-update/blob/master/arcgisext/__init__.py).

**Comment by rohitgeo** [comment]
@JeffJacobson thanks for reporting this. We are working on adding export() method to the Item class.

**Comment by rohitgeo** [comment]
Item.export method was added for this: http://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.Item.export
