### ISSUE TITLE
create a "to_file" method on the GeoAccessor object

### ISSUE THREAD

**Issue by jeweinberg** [Esri/arcgis-python-api#887]
It would be extremely convenient if the GeoAccessor had a to_file function that would save the dataframe to disk using different drivers. Example drivers would be geojson, gpkg, shp.

```
df.spatial.to_file(df, driver='gpkg')
df.spatial.read_file('path/df', driver='gpkg')
```

**Comment by AtmaMani** [comment]
The [`df.spatial.to_featureclass()`](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#arcgis.features.GeoAccessor.to_featureclass) can be used to write the DF to shapefiles, fgdb etc. We will support geopackages in the near future. Are there any other formats?

**Comment by jeweinberg** [comment]
I can only get to_featureclass to create shape files. How do you use it to create other files? The documentation says nothing about to_featureclass handling other format types. I would like it to handle geojson, gpkg and shape. Also calling it to_featureclass doesn't seem to make sense either. It makes the api confusing, to_featureclass sounds like you are converting the python object type. It doesn't sound like your are writing data to disk. to_file would have been a much better choice for a name on that.
