### ISSUE TITLE
location-Parameter in suggest not optional

### ISSUE THREAD

**Issue by jm-esri** [Esri/arcgis-python-api#888]
In the arcgis.geocoding module, the function suggest has an (optional) **location** parameter - but at the moment (Version 1.8.1) this parameter is required.

Example:
from arcgis.geocoding import suggest
results = suggest(text='Kranzberg, Ringstrasse 7')

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
In  [80]:
Line 2:     results = suggest(text='Kranzberg, Ringstrasse 7')

TypeError: suggest() missing 1 required positional argument: 'location'
---------------------------------------------------------------------------

**Comment by priyankatuteja** [comment]
@jm-esri We are glad to inform you that the latest version of arcgis api for python i.e. 1.8.3 now has this parameter optional.

![image](https://user-images.githubusercontent.com/39754605/104748624-f2227000-5777-11eb-83fb-9e79d56eaced.png)
