### ISSUE TITLE
Cannot export notebook in ArcGIS Pro

### ISSUE THREAD

**Issue by d3netxer** [Esri/arcgis-python-api#891]
**Describe the bug**
I am following the documentation.

**To Reproduce**
```python
```
# this is version1
%%bash
ipython nbconvert  'Index.ipynb'
```

```
error:
```python
---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\ast.py, in parse:
Line 35:    return compile(source, filename, mode, PyCF_ONLY_AST)

SyntaxError: invalid syntax (<string>, line 3)
---------------------------------------------------------------------------
```

**Expected behavior**
I want to export my notebook. Also, when I try to save different versions of the notebook in different ArcGIS Pro Projects, they all link to the same notebook.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Python API Version: 1.8.3

**Comment by priyankatuteja** [comment]
@d3netxer Could you please share the steps to reproduce this behavior.

**Comment by achapkowski** [comment]
Closing because no response for a two year old issue.  Please post the steps and we will readdress it.
