### ISSUE TITLE
Invalid dependencies in pip

### ISSUE THREAD

**Issue by tino415** [Esri/arcgis-python-api#899]
**Describe the bug**
Today I tried to install this library using pip on python 3.5 (on esri community forum I got answer that it is because of python version)

**To Reproduce**
Install on python 3.5 and try to require it
```python
from arcgis.gis import GIS
from arcgis.features import GeoAccessor, GeoSeriesAccessor
```
error:
```python
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-876ff2e6ffd8>", line 1, in <module>
    from arcgis.gis import GIS

  File "/usr/local/lib/python3.5/site-packages/arcgis/__init__.py", line 3, in <module>
    from . import (features, geoanalytics, geocoding, geometry,

  File "/usr/local/lib/python3.5/site-packages/arcgis/features/__init__.py", line 22, in <module>
    from .layer import FeatureLayer, Table, FeatureLayerCollection

  File "/usr/local/lib/python3.5/site-packages/arcgis/features/layer.py", line 254
    attachment_path = os.path.join(path, f'{md5_hash}.jpg')
                                                         ^
SyntaxError: invalid syntax
```

**Expected behavior**
To by able to use library

**Platform (please complete the following information):**
 - Debian Jessie
 - python 3.5

**Additional context**
I think it should by fixed or removed python 3.5 from pip package as supported python version

**Comment by DavidJVitale** [comment]
Thank you @tino415 . You are correct that the Python API will not work with python3.5, due to our use of fstrings (introduced at python3.6). We have stopped releasing 3.5 conda packages, but we forgot to do this for pip. 

I will work on removing the 3.5 information in the setup.py file for our future releases.
