### ISSUE TITLE
ArcGIS Python API (Beta) URLs and Content Causing Confusion

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#90]
It turns out, quite a few of the ArcGIS Python API (Beta) URLs and Content are still alive and well.  In and of itself, I don't think that would be an issue, but the URLs are basically the same as the current non-Beta URLs.    Some users are stumbling onto the older URLs, but not realizing they are the older URLs, and they are getting confused with the examples and instructions that aren't working.

For example, Install and set up:
**ArcGIS Python API (Beta)**
https://developers.arcgis.com/python/guide/Install-and-set-up/

**ArcGIS API for Python (1.0.1)**
https://developers.arcgis.com/python/guide/install-and-set-up/

Notice, the only difference in the URLs is a capital "I" in the Beta URL.  There are dozens and dozens of other examples I could provide.

The fact that the URLs are so similar, nearly identical, is tripping people up.  I would recommend the Beta URLs either be shutdown completely or redirect to the current URL.

**Comment by AtmaMani** [comment]
@bixb0012 thanks for bringing this to our attention. We will get the old pages removed.

**Comment by AtmaMani** [comment]
This issue has been resolved. Old URLs such as [https://developers.arcgis.com/python/guide/Install-and-set-up/](https://developers.arcgis.com/python/guide/Install-and-set-up/) will redirect to [https://developers.arcgis.com/python/guide/install-and-set-up/](https://developers.arcgis.com/python/guide/install-and-set-up/)
