### ISSUE TITLE
show_batch(), lr_find() not working on RTX 3070.

### ISSUE THREAD

**Issue by davidgaworski** [Esri/arcgis-python-api#901]
**Describe the bug**
After upgrading my PC with a 3070 the arcgis.learn no longer executes as expected. It takes 30 minutes to show_batch() and the images are pixelated and not displaying properly.

**Troubleshooting Steps**
I've done a clean install of windows and ArcGIS Pro / Deep Learning toolkit. I've tried running the notebook in ArcGIS Pro and Jupyter Notebooks with no luck.

**To Reproduce**
```python
import os
from pathlib import Path

import arcgis
from arcgis.gis import GIS
from arcgis.learn import prepare_data, MaskRCNN

data_path = r"C:\Users\Gaworski\Documents\AI_DATASETS\BuildingOnlyRNNC"

data = prepare_data(path=data_path,chip_size=400,batch_size=8)

data.show_batch(rows=2) #This is where is stops working
```

**Expected behavior**
This was working on my old 980ti and works on my other PC with a 1060 6GB

**Platform (please complete the following information):**
 - OS: Windows
 - CPU: i7 3770k
 - GPU: RTX 3070
 - RAM: 12GB

**Comment by priyankatuteja** [comment]
@davidgaworski What version of ArcGIS Pro are you using? Could you also share the output from show batch? Moreover, are you facing any errors moving ahead with training of the model. Incase, you are facing error in model.lr_find(), please share the error trace too.

**Comment by AngadKundra** [comment]
@davidgaworski in addition to the above steps,

you could perform another check to make sure torch is able to access your gpu.

import torch
print(torch.cuda.is_available())
print(torch.device("cuda"))

**Comment by davidgaworski** [comment]
> @davidgaworski What version of ArcGIS Pro are you using? Could you also share the output from show batch? Moreover, are you facing any errors moving ahead with training of the model. Incase, you are facing error in model.lr_find(), please share the error trace too.

Pro is version 2.6, but my primary tool has always been using the notebook server outside of Pro. Below is the output of batch, it took over 30 minutes to show up, but was clear this time. No errors are outputting from any steps, the batch just never seems to load when I start lr_find() or model.fit() which is very odd. For fit() I just get stuck on 0/0 for the first epoch.

![BatchOutput](https://user-images.githubusercontent.com/17102711/104797028-b93ac900-5780-11eb-9a2e-665da3b76a31.PNG)



> @davidgaworski in addition to the above steps,
> 
> you could perform another check to make sure torch is able to access your gpu.
> 
> import torch
> print(torch.cuda.is_available())
> print(torch.device("cuda"))

Output is:
True
cuda

**Comment by priyankatuteja** [comment]
> No errors are outputting from any steps, the batch just never seems to load when I start lr_find() or model.fit() which is very odd. For fit() I just get stuck on 0/98 for the first epoch.

I think if you aren't getting any error and the same workflow runs fine on other PC, could you try with a smaller batch size may be 2 or 4. Also, as you run it, check with the help of task manager if GPU is getting utilized or not and how much GPU memory is getting consumed/or is available.

**Comment by davidgaworski** [comment]
> > No errors are outputting from any steps, the batch just never seems to load when I start lr_find() or model.fit() which is very odd. For fit() I just get stuck on 0/98 for the first epoch.
> 
> I think if you aren't getting any error and the same workflow runs fine on other PC, could you try with a smaller batch size may be 2 or 4. Also, as you run it, check with the help of task manager if GPU is getting utilized or not and how much GPU memory is getting consumed/or is available.



My resources are not taxes, this is the screenshot for when the batch is called and running. This was something I posted on GeoNet before coming here. 

I've since installed 16gb of RAM and still having the same issues. Even on a PC without a GPU show_batch runs this in about 10 seconds. Show_batch of any amount (1,2,4) leads to almost the exact same load time as 8.

![Show_Batch_Slow](https://user-images.githubusercontent.com/17102711/104798808-379e6780-578f-11eb-8538-b0e3fe6fb640.PNG)

**Comment by AngadKundra** [comment]
@davidgaworski

After model initialization,
could you print the value of model._device

This is an internal variable which stores the device on which the model has been loaded. This will help us in confirming if the model has been loaded on GPU or not.

**Comment by bugrazen** [comment]
I have same issue and I don't figuredart.
How can I fix this?

![image](https://user-images.githubusercontent.com/95212909/145030375-5c27b631-95f3-44aa-a0f2-6544e9ddf907.png)


![image](https://user-images.githubusercontent.com/95212909/145217103-e4d7d95b-b7a5-444c-b648-75dc92bd25f4.png)
