### ISSUE TITLE
Create View layer from arcgis api for python

### ISSUE THREAD

**Issue by PeaceNlove** [Esri/arcgis-python-api#904]
**Is your feature request related to a problem? Please describe.**
In Portal for ArcGIS, you can create a View Layer from a hosted feature service. I would like to do the same from the Python API. However, I cannot find such function in the documentation or on the properties or functions of the item and layer objects when debugging this sample code

```python

gis = arcgis.GIS("pro")
servicename= 'MyHostedService'
searchresult = gis.content.search(query='title:"{}"'.format(servicename), item_type='Feature Service')
myhostedservice = searchresult[0]

#now I would like a function like this
myhostedservice.createView(props, etc)
#expected result would be a layer view the same way you can create in Portal

```

**Describe the solution you'd like**
A function to create a view layer from a hosted feature service

**Comment by achapkowski** [comment]
The create_view functionality exists on the `FeatureLayerCollectionManager`.  

See: https://developers.arcgis.com/python/api-reference/arcgis.features.managers.html?highlight=create_view#arcgis.features.managers.FeatureLayerCollectionManager.create_view

Sample Code.

```python
item = gis.content.get("<some item id>")
lyr = item.layers[0]
view = lyr.container.manager.create_view("my_first_view")
view
```

**Comment by jialiu77845** [comment]
How about creating a view from more than one feature layer? I'd like to create a view from a Hosted Feature Layer (with sublayers) and another standalone Hosted Feature Layer. Can I add item of the 2nd Hosted Feature Layer to a FeatureLayerCollection from the 1st Hosted Feature Layer, and how?
