### ISSUE TITLE
arcgis.gis.admin.Collaboration.sync_status

### ISSUE THREAD

**Issue by cdflint** [Esri/arcgis-python-api#917]
**Is your feature request related to a problem? Please describe.**
Missing functionality between sync and sync_details.  The output of sync is a dict with the keys jobId, key and success.  The sync_details requires a syncId as input and jobId != syncId.  Implementing a sync_status step would provide the python api a programmatic way of querying all syncId's for a particular workspace_id.  Provided function below was tested on Enterprise 10.8.1 with Python API v1.8.4.  

```python
#----------------------------------------------------------------------
    def sync_status(self, workspace_id):
        """
        Query the syncStatus REST endpoint for a list of statuses and their properties including syncId.

        ===========================     ====================================================================
        **Argument**                    **Description**
        ---------------------------     --------------------------------------------------------------------
        workspace_id                    Required string. Workspace ID to remove from the link.
        ===========================     ====================================================================

        :returns: dict  

        """
        params = {
            'f' : 'json'
        }
        data_path = f"{self._basepath}/workspaces/{workspace_id}/syncStatus"
        con = self._portal.con
        return con.post(path=data_path, postdata=params)
    #----------------------------------------------------------------------
```

**Describe the solution you'd like**
Implement above snippet.

**Additional context**
Enterprise 10.8.1
Python API v1.8.4

**Comment by achapkowski** [comment]
Thank you for reporting this.  We will add it to the list of things to consider adding to the 1.9 release.  

This is about missing this method: https://developers.arcgis.com/rest/users-groups-and-items/sync-status.htm

**Comment by achapkowski** [comment]
added
