### ISSUE TITLE
Group remove_users argument differs between documentation and implementation

### ISSUE THREAD

**Issue by wiringa** [Esri/arcgis-python-api#918]
**Describe the bug**
The argument taken by the `remove_users` method of `arcgis.gis.Group` does not match [its documentation](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Group.remove_users). The documentation calls for "a comma-separated list of users to be removed," the method expects a list or iterable.

**To Reproduce**
No error is produced. Users are not properly removed from a group when documentation is followed.
```python
result = gis.groups.search("doc bug demo group")[0]
print(result.get_members())
print(result.remove_users("steveg_umntc;wiringa_nosso2"))
print(result.get_members())
```

Output:
```python
{'owner': 'wiringa_umntc', 'admins': ['wiringa_umntc'], 'users': ['steveg_umntc', 'wiringa_nosso2']}
{'notRemoved': ['s', 't', 'e', 'v', 'g', '_', 'u', 'm', 'n', 'c', ';', 'w', 'i', 'r', 'a', 'o', '2']}
{'owner': 'wiringa_umntc', 'admins': ['wiringa_umntc'], 'users': ['steveg_umntc', 'wiringa_nosso2']}
```

**Expected behavior**
`remove_users` argument should match the documentation.

**Platform (please complete the following information):**
 - OS: n/a (notebook in ArcGIS Online)
 - Browser: n/a
 - Python API Version: 1.8.1

**Comment by achapkowski** [comment]
@jyaistMap Please take a look at the doc.

**Comment by mohi9282** [comment]
@wiringa I was not able to reproduce the issue. Both comma-separated list and string work fine with the latest version V1.9.0.

![image](https://user-images.githubusercontent.com/35741513/135353814-9386a607-6f8f-4e4a-8446-6f4b4c085967.png)

**Comment by wiringa** [comment]
Thanks, @mohi9282. I suggest including that it takes a list in the [API doc](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Group.remove_users), It still has `usernames` described as "Required string. A comma-separated list of users to be removed." It's very convenient that it takes a list.

**Comment by mohi9282** [comment]
@wiringa yes, we will update the doc to correctly reflect the usage of a list.
