### ISSUE TITLE
Clip_analysis tool of Arcgis API

### ISSUE THREAD

**Issue by farzanehashemabadi** [Esri/arcgis-python-api#919]
Dear all,
I use arcpy library for Clip_analysis, but now I want run my script with Arcgis API, so how can I Clip_analysis by Arcgis package?
also I want to know what are replacements of "arcpy.env.workspace", "arcpy.ListFeatureClasses" and "arcpy.da.SearchCursor" in Arcgis API?
my old script attached below.

###Clip and calculate Risk value ###

import os
import arcpy
#import shapefile
import glob
from arcpy import env

    
#setting my source and target geodatabase 
base_dir = os.path.dirname(__file__)

#setting my clip feature (which is a polygon)
clippers_dir = os.path.join (base_direct, "clipper")
clippers = glob.glob(clippers_dir + '/*.shp')

#Iterate in base path and work with folders

src_dir = os.path.join (base_direct, "Results_winter2016")
for src_dir 

    des_dir = os.path.join (src_dir, "clipped")
    if not os.path.exists(des_dir):
                os.mkdir(des_dir)
    #r"C:\Users\Farzane\Desktop\Master97\Gnome modeling\Postprocessing\clipped"

        

    #set a workspace    
    arcpy.env.workspace = src_dir

    fclist = arcpy.ListFeatureClasses()

    #make list of Grids
    Grid_list = [0 for i in range(len(clippers))]

    ###########################################          

    for fc in fclist:
        src_file_dir, src_file_name = src_dir, fc
        for index, cfs in enumerate(clippers):
            
            clipper_dir, clipper_name = os.path.split(cfs)
            clipper_name = src_file_name.split('.')[0] + "_" + clipper_name 
            output_dir = os.path.join(des_dir , clipper_name)
            clipped = arcpy.Clip_analysis(fc,cfs,output_dir)
please help me. 
thanks

**Comment by achapkowski** [comment]
related to issue #920
