### ISSUE TITLE
Clipping by Using Arcgis API for python?

### ISSUE THREAD

**Issue by farzanehashemabadi** [Esri/arcgis-python-api#920]
use ArcPy library for Clip_analysis, but now I want run my script with ArcGIS API for Python, so how can I Clip using the ArcGIS API for Python?

My script with ArcPy attached below.

###Clip and calculate Risk value ###

import os
import arcpy
#import shapefile
import glob
from arcpy import env

#setting my source and target geodatabase
base_dir = os.path.dirname(file)

#setting my clip feature (which is a polygon)
clippers_dir = os.path.join (base_direct, "clipper")
clippers = glob.glob(clippers_dir + '/*.shp')

#Iterate in base path and work with folders

src_dir = os.path.join (base_direct, "Results_winter2016")
for src_dir

des_dir = os.path.join (src_dir, "clipped")
if not os.path.exists(des_dir):
            os.mkdir(des_dir)
#r"C:\Users\Farzane\Desktop\Master97\Gnome modeling\Postprocessing\clipped"

    

#set a workspace    
arcpy.env.workspace = src_dir

fclist = arcpy.ListFeatureClasses()

#make list of Grids

I want to know what is replacement ArcPy Module in ArcGis API?

**Comment by achapkowski** [comment]
Take a look at these guides: https://developers.arcgis.com/python/guide/part3-spatial-operations-on-geometries/
