### ISSUE TITLE
Clone_items returns _ItemCreateException

### ISSUE THREAD

**Issue by ts178409** [Esri/arcgis-python-api#924]
**Describe the bug**

I am attempting to clone a group of items in ArcGIS Online that inclues hosted feature layers, views, web maps, and web apps. These items have relationship classes based on script-generated keys that populate string fields, such as 'visit_key', 'survey_key', etc. The source items have been used extensively and work well in ArcGIS Online. We want to clone them so we can start over for a new data collection period and avoid manually recreating all these items in ArcGIS Online. 

When attempting to run the code below, we receive an error related to a duplicate key. I am unsure if not having duplicate field names that act as indexes is a known limitation of this function, so I am reporting here as an issue. It would be great to know if this can be fixed or if there is a work-around. 

**To Reproduce**

Create a hosted feature layer with string indexes. Attempt to run clone_items() function on it. 
 
```python
# gets token from an authenticated ArcGIS Pro session, since our USBR AGOL organization doesn't allow
# user/pass authentication, this is the easiest way to authenticate w/ AGOL
gis = GIS("pro")
token_response = arcpy.GetSigninToken()
# gets just the token value from the token_response
token = token_response['token']


# declare url of REST endpoint for the source feature service
root_def = "0daa453f745040529d7bfb2b0633ccfe"
root = "eed08fc43d794836a971c80f0cbd1f5a"
wa_view_edit_admin = "f00f40b781d9452e9cc5e45e166dd549"
wa_view_edit = "87d580dee27247b29cc013c6786451ed"
wm_collect = "f5869fb29a244b71abf16ef40c12b568"
wm_collect_backup = "6e824e6b2d3b490eb04db60c33322160"
wm_view_edit = "db9ac3ceda0f42fd83b8353029135d0e"
wm_view_edit_admin = "08039941ef324c5eae06b592dd9621d0"
wm_view_edit_all = "89a246059177489095f4b110ab53b665"
fsv_root_filter = "00739ef8d1a44667b5372a4624c3d6d7"
fsv_root_view_edit_own = "b238cd73cf2948dba0f34850e7c5bfe0"
fsv_root_view_edit_own_filter = "c4d3a090f23e43808f10518008c7f3ab"
fsv_simple_symbology = "8b41f4547d6b49ac9d65cdd9302eb24c"

item = gis.content.get(wa_view_edit_admin)

# item_id_list = [root_def, root, wa_view_edit_admin, wa_view_edit, wm_collect, wm_collect_backup, wm_view_edit, wm_view_edit_admin, wm_view_edit_all,
#               fsv_root_filter, fsv_root_view_edit_own, fsv_root_view_edit_own_filter, fsv_simple_symbology]

# item_list = []
# for item_id in item_id_list:
#     item = gis.content.get(item_id)
#     print(item)
#     item_list.append(item)
    
# clone_items(items, folder=None, item_extent=None, use_org_basemap=False, copy_data=True, copy_global_ids=False, search_existing_items=True, item_mapping=None, group_mapping=None, owner=None)    

clone_list = gis.content.clone_items([item], folder='Clone Test')    
```
error:
```python
_ItemCreateException: ("Failed to create Feature Service F02_BPM_2021_FS_root: Unable to add feature service definition.\nThe operation failed because an index or statistics with name 'visit_key_unidx' already exists on table 'db_3473.user_3473.F02_BPM_2020_FS_root_467e4b9333484d0696427a05a9377426_VISIT'.\n(Error Code: 400)", <Item title:"F02_BPM_2020_FS_root_467e4b9333484d0696427a05a9377426" type:Feature Layer Collection owner:tsizemore@usbr.gov_USBR>)
```
**Screenshots**

**Expected behavior**
I expect the items to clone to a folder in ArcGIS Online called "Clone Test".

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Python API Version 3.6.10

**Additional context**
Add any other context about the problem here, attachments etc.

**Comment by mohi9282** [comment]
@ts178409 could you please provide an example of a "hosted feature layer with string indexes"? I tried to access some of the items mentioned in the issue but they are not accessible.

**Comment by ts178409** [comment]
Hi Mohi, 

Thanks for the response. We ended up going down a different path, so I don't need to solve this issue anymore. 

Travis
