### ISSUE TITLE
Try it live part of Automatic road extraction using deep learning tutorial 

### ISSUE THREAD

**Issue by Mbarzegar-unimelb** [Esri/arcgis-python-api#925]
**Describe the bug**
Try it live part of Automatic road extraction using deep learning tutorial doesn't work.

**To Reproduce**
from arcgis.learn import prepare_data, MultiTaskRoadExtractor
import os, zipfile
from pathlib import Path
from arcgis.gis import GIS
gis = GIS('home')
training_data = gis.content.get('b7bbf2f5f4184960890afeabbdb51a32')
training_data
filepath = training_data.download(file_name=training_data.name)
with zipfile.ZipFile(filepath, 'r') as zip_ref:
    zip_ref.extractall(Path(filepath).parent)
output_path = Path(os.path.join(filepath.split('.')[0]))
data = prepare_data(output_path, chip_size=512, batch_size=10)
data.classes

error:
Exception                                 Traceback (most recent call last)
In  [7]:
Line 1:     data = prepare_data(output_path, chip_size=512, batch_size=10)

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\learn\_data.py, in prepare_data:
Line 926:   raise Exception("Could not infer dataset type. Please specify a supported dataset type or ensure that the path contains valid esri files")

Exception: Could not infer dataset type. Please specify a supported dataset type or ensure that the path contains valid esri files
```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
output for data 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Python API Version: 1.8.3, ArcGIS Pro 2.7

**Comment by priyankatuteja** [comment]
The code you shared seems to be outdated. Could you please use the updated notebook again.
https://geosaurus.maps.arcgis.com/home/item.html?id=72b6c19f5944424f830b44346f0fef89 Click on try it live button, log in using credentials: https://geosaurus.maps.arcgis.com, arcgis_python, P@ssword123
