### ISSUE TITLE
solve_closest_facility tool gives an error while creating spatial reference

### ISSUE THREAD

**Issue by mariamjamilah** [Esri/arcgis-python-api#926]
Hello,

While running the following [sample notebook] (https://developers.arcgis.com/python/sample-notebooks/finding-hospitals-closest-to-an-incident/), I get the below error when executing the "solve_closest_facility" tool. I have tried using a different spatial reference as well as using different user accounts to make the gis connection, but nothing helps. Please advice.

Exception: An error occurred with exporting the FeatureSet with message: Object: CreateObject error creating spatial reference

**Comment by CMPeng** [comment]
Hi @mariamjamilah I cannot repro the issue on my end when using the "Try it live" samples, FeatureSet are created and exported successfully. Can you please provide more details for your failed attempt?
 - are you using the same credentials as in the sample?
 - are you using a customized routing service instead of the default service on AGOL?
 - If nothing is changed, can you please give the sample a 2nd try? Thanks!

**Comment by CMPeng** [comment]
Closing the issue due to inactivity

**Comment by compukab** [comment]
I'm getting the same error.
When running the sample through the 'Try it Live' button everything works ok.
But when I try to run the notebook in ArcGIS Pro 2.9 I get the following error:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
In  [57]:
Line 6:     accumulate_attribute_names=['Kilometers','TravelTime'])

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\network\_layer.py, in solve_closest_facility:
Line 1134:  "facilities": _handle_spatial_inputs(facilities),

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\network\_layer.py, in _handle_spatial_inputs:
Line 45:    return data.sdf.spatial.__feature_set__

File C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\features\feature.py, in sdf:
Line 836:   % str(e)

Exception: An error occurred with exporting the FeatureSet with message: Object: CreateObject error creating spatial reference
---------------------------------------------------------------------------
