### ISSUE TITLE
arcgis.gis.server.admin.administration.Server Continues to Mangle arcgis.gis._impl._con._connection.Connection 

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#927]
This bug report looks very similar to https://github.com/Esri/arcgis-python-api/issues/748 because the "fix" for that defect didn't actually fix the defect, it simply replaced one defect with a new defect.

Using the same code samples from the original bug report:
```python
from arcgis.gis.server import Server

url = r"https://fqdn/arcgis/admin"
username = # username
password = # password

svr = Server(url, username=username, password=password)
```
In the 1.7.x branch, the connection looks like the following:
```python
>>> svr
<Server at https://fqdn/arcgis/admin>
>>> svr._con.baseurl
'https://fqdn/arcgis/admin'
>>>
```
while in the 1.8.4 branch the connection looks like:
```python
>>> svr
<Server at https://fqdn/arcgis/admin>
>>> svr._con.baseurl
'https://fqdn/arcgis/rest/services/'
>>>
```

Although the `baseurl` is a valid url, unlike with 1.8.0 through 1.8.2, I don't think it is the correct url.

With 1.7.x:
```python
>>> svr._con.is_logged_in
True
>>> svr.properties
{
  "isServerLicensed": "true",
  "resources": [
    "machines",
    "clusters",
    "system",
    "services",
    "security",
    "data",
    "uploads",
    "logs",
    "mode",
    "usagereports",
    "webhooks"
  ],
  "currentVersion": 10.71,
  "fullVersion": "10.7.1",
  "acceptLanguage": null
}
>>>
```
while 1.8.4 gives:
```python
>>> svr._con.is_logged_in
True
>>> svr.properties
{
  "status": "error",
  "messages": [
    "Unauthorized access. Token not found. You can generate a token using the 'generateToken' operation."
  ],
  "code": 499
}
>>>
```
Regardless of what `svr._con.is_logged_in` returns, it is clear the user isn't logged into the server since trying to retrieve something as basic as properties returns an unauthorized access error.

**Comment by bixb0012** [comment]
OK, I worked with Esri Support to isolate why I see this behavior still but some others don't.  It relates to the authentication settings for GIS Server. 
[#BUG-000138559 Unable to authenticate with ArcGIS API for Python when using 'GIS Server' as Authentication Tier and 'Windows Domain' as User Store. ](https://my.esri.com/#/support/bugs/BUG-000138559)

**Comment by CMPeng** [comment]
Issue fixed and will be addressed in next release.
