### ISSUE TITLE
Python api running in google colab

### ISSUE THREAD

**Issue by salmagro** [Esri/arcgis-python-api#928]
Dear awesome ESRI community.

Are there plans or a method to run the API and the deep learning capabilities in **google colab**?

If yes, what will be the process to have it running?

There is some discussion around this topic on https://github.com/googlecolab/colabtools/issues/498 and https://github.com/googlecolab/colabtools/issues/1255

Appreciate your comments.

**Comment by priyankatuteja** [comment]
@salmagro Thanks for reaching out to us.

**Steps for using arcgis api for python and deep learning capabilities on google colab:**
1. Run the following block of code in one cell.
```
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

conda install -c esri -c fastai -c pytorch -c anaconda arcgis=1.8.4 ujson scikit-image=0.15.0 pillow=7.1.2 libtiff=4.1.0 fastai=1.0.60 pytorch=1.4.0 torchvision=0.5.0 python=3.7.9 --yes --no-pin
```
2. Run the following block of code in another cell.
```
import sys
sys.path
 
 
import sys
_ = (sys.path
 .append("/usr/local/lib/python3.7/site-packages"))
```
3. Continue with usual workflow, to refer please see [this notebook](https://colab.research.google.com/drive/10B7YH11eO1XulbHuTG9S7sqP7Uy7h_8H?usp=sharing).


**Steps to run arcgis without deep learning capability:**
1.  Run the following block of code in one cell.
```
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

conda install -c esri arcgis --yes --no-pin
```
2. Run the following block of code in another cell.
```
import sys
sys.path
 
 
import sys
_ = (sys.path
 .append("/usr/local/lib/python3.7/site-packages"))
```
3. Continue with usual workflow, to refer please see [this notebook](https://colab.research.google.com/drive/1ymyOR98D4FdHVY-USFJB4IK2iyAu2vxi?usp=sharing).

Please note:  Third party map widgets do not display in colab's env.

**Comment by priyankatuteja** [comment]
@salmagro We are glad to tell that, we offer ArcGIS Notebook Server with a ready to use deep learning environment  which is GPU enabled. To experience it, you could use these credentials:
https://geosaurus.maps.arcgis.com, arcgis_python, P@ssword123. 
![image](https://user-images.githubusercontent.com/39754605/109330682-f4e9a800-7881-11eb-9559-1499019cdc8c.png)

To utilize GPU, create a notebook using 'Advanced with GPU support' option.

**Comment by schenardi** [comment]
I was not successful with the hints of @priyankatuteja to make arcgis deep learning running in colab. Since I do not want to move everything inside ArcGIS Notebook server (for cost reason but also because I do not have it in my developer account) it would be very desirable that Esri supports common patterns/environments for python and machine learning. 

We all want to bring GIS and ML together and this only works with useful setups. 

Thanks for leaving the "GIS-Bubble"...
