### ISSUE TITLE
Property Description on User Class

### ISSUE THREAD

**Issue by jdcarls2** [Esri/arcgis-python-api#933]
**Describe the bug**
The table of properties in the *User* class lists the **disable()**  method description where the **disabled** boolean property should be.

See https://github.com/Esri/arcgis-python-api/blob/master/apidoc/arcgis.gis.toc.html#L2074

**Comment by jyaistMap** [comment]
Thanks @jdcarls2. Updated the doc strings to correct this. Should be reflected in the api reference next week.
