### ISSUE TITLE
Update: GeoNet => Esri Community

### ISSUE THREAD

**Issue by isaacviel** [Esri/arcgis-python-api#934]
All references to `GeoNet` need to change to `Esri Community`

New logo:

https://github.com/ArcGIS/esri-product-logos/tree/master/Esri%20Community

Use either `Esri Community` or `the Esri Community`

Example: https://developers.arcgis.com/python/support/

**Comment by achapkowski** [comment]
@mohi9282  and @AtmaMani please take a look at this issue.

**Comment by AtmaMani** [comment]
@isaacviel the text comes from https://github.com/ArcGIS/arcgis-for-developers/blob/master/src/layouts/documentation/_support.html#L36. Since its a common location (not specific to Python API), who should edit this? We can send a PR but want to ensure its a safe edit.

**Comment by AtmaMani** [comment]
cc @priyankatuteja

**Comment by isaacviel** [comment]
Thanks @AtmaMani. I must have missed that one when I made some site changes. I've fixed this instance. However, I wanted to leave this issue open as a reminder to scan all of the Python doc for GeoNet references and change them to Esri Community. If there are no more reference, feel free to close this issue.

**Comment by mohi9282** [comment]
I have scanned various areas of the website and could not locate any other references of GeoNet. Closing the issue for now.

**Comment by isaacviel** [comment]
Thanks @mohi9282!
