### ISSUE TITLE
Detecting Swimming Pool - naip_ml missing

### ISSUE THREAD

**Issue by DjebelV** [Esri/arcgis-python-api#939]
Hi, just trying to execute the notebook which can be found here 
-> https://geosaurus.maps.arcgis.com/home/item.html?id=122fb4b5a2094f3398b1d96381022f64

But looks like the naip_ml does not exist anymore ?

Jerome

**Comment by CMPeng** [comment]
Hi @DjebelV we are looking into the public enterprise where the `naip_ml` image service is published. Seems that the image server is having issues starting the service right now. Will get back to you when issue is solved. Thanks for logging the issue.

**Comment by rwmajor2** [comment]
@CMPeng Service is now running with appropriate license.
