### ISSUE TITLE
Sample Script Failing to Copy Item 

### ISSUE THREAD

**Issue by tquink** [Esri/arcgis-python-api#94]
Tried utilizing the clone_portal_users_groups_and_content.ipynb sample, but it continues to fail when copying items. (Error Below).  Also, there are a few places where it references sourceusers and later calls source_users, same with system_users and systemusers

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-7fcac6e97dca> in <module>()
     25 
     26         for folder in folders:
---> 27             target.content.create_folder(folder, user)
     28             folder_items = user.items(folder['title'])
     29             for item in folderitems:

C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\arcgis\gis.py in create_folder(self, folder, owner)
   1663             else:
   1664                 owner_name = owner
-> 1665             if self._portal.get_folder_id(owner_name, folder) is None:
   1666                 return self._portal.create_folder(owner_name, folder)
   1667             else:

C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\arcgis\_impl\portalpy.py in get_folder_id(self, owner, folder_name)
   2190             # Loop through each folder JSON object
   2191             for fldr in resp['folders']:
-> 2192                 if fldr['title'].upper() == folder_name.upper():  # Force both strings to upper case for comparison
   2193                     return fldr['id']
   2194         return None # no such folder found for this owner

AttributeError: 'dict' object has no attribute 'upper'

**Comment by AtmaMani** [comment]
@tquink thank you. We have addressed these issues (fails on folders, wrong variable names) and the updated notebook is in the `dev` branch. We will merge with `master` during the next release.

**Comment by rohitgeo** [comment]
This issue was fixed in v1.2
