### ISSUE TITLE
Group property "provider_group_name" does not exist

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-python-api#951]
**Describe the bug**

The group property "provider_group_name" does not exist:
```KeyError: 'provider_group_name```

**To Reproduce**

First, create a group and secure it with an enterprise group. Then retrieve that group and try to access the "provider_group_name" property:
```python
secured_group = ent_gis.groups.get("mygroupid")
secured_group.provider
'enterprise'
secured_group.provider_group_name
```
error:
```python
raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, name))
AttributeError: 'Group' object has no attribute 'provider_group_name'
```

**Expected behavior**
I would like to be able to retrieve the enterprise group configured to restrict access. It is available on the sharing API properties in "providerGroupName" property. Don't why it is not propagated.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Python API Version: 1.8.4

**Additional context**
The purpurse of the script is retrieve a list of all the enterprise groups used to secured Portal for ArcGIS groups. Any workaround to achieve that in the meantime ?

Thanks !

**Comment by AtmaMani** [comment]
To access the provider group name, please access it as : `<arcgis.gis.Group>.providerGroupName` instead of `provider_group_name`

**Comment by Biboba** [comment]
Sorry, I forget to say that I tried that and it is returning empty None while group does exist and is returned from the REST API ?
