### ISSUE TITLE
ArcGIS Pro 2.0 Python and Conda Versions

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#96]
Any hope of getting Python updated to 3.6.x and conda to 4.3.x in ArcGIS Pro 2.0?

**Comment by scw** [comment]
ArcGIS Pro 2.0 will continue to ship with Python 3.5, but will upgrade conda to the 4.3.x series. If you're able to join the beta program, you can get early access to the Python updates to try out the new versions yourself. Python 3.6 looks like a great release, and of course you can use it with the Python API by creating a new environment.

**Comment by bixb0012** [comment]
@scw, thanks for the update.  I figured the release of 3.6 was too recent to make it into Pro 2.0, but I am glad to see conda is getting updated.
