### ISSUE TITLE
GIS Server: add support for 'Use Local Directory' property if directory is a cache

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-python-api#966]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure a local cache directory on my GIS Server as described here:
https://enterprise.arcgis.com/en/server/latest/publish-services/windows/configure-ha-caches.htm

So far I tried the following to get access to GIS Server directory API:

```python
from arcgis.gis import GIS

portal_url = "https://hostname.company.com/portal"
portal_user = "siteadmin"
portal_pwd = "foo"

ent_gis = GIS(portal_url, portal_user, portal_pwd, verify_cert=False)
# assuming you have a GIS Server associated with your Portal
help(ent_gis.admin.servers.list()[0].system.directories().get("arcgiscache").edit)

Help on method edit in module arcgis.gis.server.admin._system:
edit(physical_path, cleanup_mode, max_age, description) method of arcgis.gis.server.admin._system.ServerDirectory instance
```

There is no way to configure "useLocalDir" and "localDirectoryPath" properties when it is a cache directory.

**Describe the solution you'd like**
I would like to be able to pass those properties to the edit method. So additional optional properties "use_local_dir" and "local_directory_path" would be required to this method.

Thanks for listening !

**Comment by AtmaMani** [comment]
Planned for v1.9 of the Python API. @Biboba thanks for reporting.
