### ISSUE TITLE
"Palette" is misspelled

### ISSUE THREAD

**Issue by drewlevitt** [Esri/arcgis-python-api#976]
**Describe the bug**
In a number of locations within the API, "palette" is misspelled as "pallette". For example, in `arcgis.features.GeoAccessor.plot()`, there is an optional keyword argument `pallette`. This misspelling makes it likely that English speakers familiar with the correct spelling will pass a `palette` keyword argument which will crash the method call.

**Expected behavior**
One l, two ts.

**Platform**
All

**Suggested fix**
Find and replace "pallette" -> "palette" throughout the codebase and documentation. (Maybe keep "pallette" around as an alias for "palette" so this isn't a breaking change.)

**Comment by priyankatuteja** [comment]
@achapkowski We should consider fixing the spelling from pallette to palette. At the same time for backward compatibility, we could support both keywords in our code. 

@drewlevitt Thanks for reporting it.

**Comment by achapkowski** [comment]
This is resolved in the next release 1.9.0
