### ISSUE TITLE
Can't load spatial dataframe into sql using 'to_sql()'

### ISSUE THREAD

**Issue by sms8812** [Esri/arcgis-python-api#978]
**Describe the bug**
I can't get a spatial dataframe to load into sql using 'to_sql()'

**To Reproduce**
```
df = pd.DataFrame.spatial.from_featureclass(pathtofc)
conn = sqlite3.connect(':memory:')
df.to_sql('ANYNAME', conn, index=False)

```
error:
```
AttributeError: 'GeoType' object has no attribute 'base'
```
**Expected behavior**
I can load and read a regular pandas dataframe in sqlite3. Is it a bug or is there a workaround? Is there a library other than sqlite3 that works with spatial dataframes?

**Platform (please complete the following information):**
 - OS: [10.0.18363 N/A Build 18363]
 - Python API Version [1.8.4]  
  -sqlite3[3.35.4]

**Comment by achapkowski** [comment]
This is an issue with sqlite not knowing how to convert the Geometry datatype and isn't anything the SeDF is doing wrong.  The solution might be to use the to_featureclass and export the data to a geopackage, which is a sqlite database.

**Comment by sms8812** [comment]
Thanks Andrew!
