### ISSUE TITLE
RoleManager.all() - Return Role ID

### ISSUE THREAD

**Issue by BrettFrahm** [Esri/arcgis-python-api#985]
**Is your feature request related to a problem? Please describe.**
not related to existing bug/problem

```
portal = api.GIS("***", "***", "***")
roleMan_portal = api.RoleManager(portal)
portal_roles = roleMan_portal.all(max_roles=1000)
print(portal_roles)
```

**Describe the solution you'd like**
In the RoleManager.all() function it would be very useful if it returned the roleid. All I'm getting right now is the name and description.

**Describe alternatives you've considered**
Need to manually keep a list of roleids within my script.

**Additional context**
syncing roles between arcgis online and portal users, need a way to lookup the roleid for a role in portal that has the same name as a role in arcgis online.

**Comment by achapkowski** [comment]
When you get the role object back there is a property called `role_id` that can return the `id` value you need.

```python
gis = GIS(profile='your_profile`)
role = gis.users.roles.all()[0]
print(role.role_id)
```
