### ISSUE TITLE
Expose an item's folder item as a property of the item for better access to human-readable folder title

### ISSUE THREAD

**Issue by jacobdadams** [Esri/arcgis-python-api#986]
**Is your feature request related to a problem? Please describe.**
Currently, getting the folder name for an item requires custom helper functions or dense comprehensions, such as this from the [cloning content guide](https://developers.arcgis.com/python/guide/cloning-content/):

```python
next(f['title'] for f in source.users.me.folders 
     if f['id'] == hosted_fs.ownerFolder)
```

**Describe the solution you'd like**
Exposing the folder object as a property of the item object could be more clear and accessible by allowing direct access to the folder object instead of having to round-trip through the list of the user's folders: 

```python
print(f'{hosted_fs.title}: {hosted_fs.folder['title']})
```

**Describe alternatives you've considered**
The method above for on-the-fly folder referencing. Also, building a dictionary mapping ids to folder names for a user before doing anything, such as [in this code](https://github.com/agrc/auditor/blob/master/src/auditor/auditor.py#L280-L312).

**Additional context**
n/a

**Comment by mohi9282** [comment]
@jacobdadams the fix for this issue is being implemented and will be available with the next release in Oct'21.
