### ISSUE TITLE
Use arcgis-python-api in Spyder instead of Jupyter Notebook?  Getting "Widget Javascript not detected."

### ISSUE THREAD

**Issue by jedisom** [Esri/arcgis-python-api#99]
I've seen several issues logged abou the "Widget Javascript not detected." warnings/errors when starting to use arcgis-python-api in Jupyter notebooks(Issues #10...).  I can follow the instructions and get the following result:

![image](https://cloud.githubusercontent.com/assets/17888881/26651746/95ee595a-4602-11e7-8d0d-1daff510be22.png)

However, when I try a similar setup, but run Spyder...

    (C:\Users\username\Anaconda2) C:\Windows\system32>activate py35
    
    (py35) C:\Windows\system32>jupyter nbextension enable --py widgetsnbextension
    Enabling notebook extension jupyter-js-widgets/extension...
          - Validating: ok

    (py35) C:\Windows\system32>spyder

I get... 

![image](https://cloud.githubusercontent.com/assets/17888881/26652185/e6201b6a-4603-11e7-9e61-c0a73e433292.png)

Has anyone successfully run the arcgis python package from Spyder?  If so, am I missing something?  Or, is the arcgis package incompatible with Spyder (even using the IPython console within Spyder)?

**Comment by rohitgeo** [comment]
The widget is only available with the Jupyter notebook.

**Comment by scw** [comment]
Hello @jedisom, Spyder doesn't yet support notebooks. The IPython console is a rich interface which can render graphics such as plots (images), but to support notebooks requires a full browser rendering experience. If you're interested in this functionality, you might want to follow the progress of the [spyder-notebook](https://github.com/spyder-ide/spyder-notebook) plugin. It's still a work in progress, but it aims to bring that functionality to Spyder.
