### ISSUE TITLE
How to encrypt password?

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-python-api#990]
_As a sysadmin, I want to automate updating the database connection details in the ArcGIS Server data store settings, so that my services will continue to access the data in the database.  I want to host this in Lambda and avoid using Arcpy._

This[ ArcGIS Python API sample ](https://support.esri.com/en/technical-article/000022551)from Esri, looks very close to what we need.  However, it makes no mention on how to encrypt the password. Where does that variable _sample_1_ come from?
![image](https://user-images.githubusercontent.com/2769383/116017222-5f507600-a682-11eb-91c4-81ef664672e8.png)

Looking at the help for [DataItem](https://developers.arcgis.com/rest/enterprise-administration/server/dataitem.htm):

> It is recommended that you encrypt the credentials using the encryption scheme before storing it into the server. This can be achieved by invoking Get Database Connection String tool inside the Publishing Tools toolbox published as a system service on the server.

This would indicate that there might be a step missing in the linked python script.  Struggling to find much documentation/samples on how to use 'Get Database Connection String' using Python API.

How would we extend the Esri script to Encrypt a new password that we update against an existing DataStore item?

**Comment by achapkowski** [comment]
Try this: 
```python
        gis = GIS(profile="your_enterprise_connection_profile")

        servers = gis.admin.servers.list()
        server = servers[0] # hosting server
        r = server.datastores.generate_connection_string(sde=fp)
```

**Comment by AtmaMani** [comment]
@simongis in the sample script on the page https://support.esri.com/en/technical-article/000022551, the line `server1.datastores.generate_connection_string(r"C:\Users\user\AppData\Roaming\ESRI\Desktop10.x\ArcCatalog\Sample.sde")` will return the encrypted connection string. This then gets fed into the dictionary that is composed later on.

The script has a bug where it does not capture that into a variable. Instead it just pastes the value into the dictionary. Hence the confusion.

The snippet @achapkowski provide above should get you that string.

Please reopen if this does not address your issue.

**Comment by simongis** [comment]
This is perfect.  Thanks @AtmaMani & @achapkowski for the help and script, will test it out later in week.
