### ISSUE TITLE
arcgis.gis.Item.publish with Item ID Does Not Publish with Specified ID

### ISSUE THREAD

**Issue by nfink-nlt** [Esri/arcgis-python-api#991]
**Describe the bug**
When attempting to republish a layer with the same item ID in ArcGIS Online, a new item ID is generated. Documents specify you can select the item ID: https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html?highlight=publish#arcgis.gis.Item.publish

**To Reproduce**
```python
fs_id='96a0b1f35afc46c3a394d233f3cdcee9'
file_item = gis.content.add(item_properties=file_properties, data=data.geojson, folder=folder_name)
fl = file_item.publish(item_id=fs_id)
```
**Expected behavior**
Expected that the feature service would be published with the specified item ID

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Python API Version: 1.8.5

**Comment by achapkowski** [comment]
We have resolved this issue in the next release already.  Thank you for reporting it.
