### ISSUE TITLE
Jupyter Lab, unable to use Map Widget

### ISSUE THREAD

**Issue by mrkjns** [Esri/arcgis-python-api#995]
When using Jupyter Lab, I'm unable to instansiate the map widget, against either AGOL or ArcGIS Enterprise.  I've followed the steps provided here: 
https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/
However, I seem unable to align the arcgis-map-ipywidget with the arcgis api.  The arcgis api has been updated to 1.8.5, however, through npm etc. i cannot seem to manage to update the arcgis-map.ipywidget to 1.8.5 and it seems "stuck" on 1.8.1.

When trying:

map = gis.map()
map1.

i get the following:

![image](https://user-images.githubusercontent.com/56536899/116676801-57a11200-a99f-11eb-84a2-fd8c6393ee72.png)

Os: Win 10
Browser: Edge
Python API version: 1.8.5

**Comment by CMPeng** [comment]
@mrkjns Thanks for following up with us.
We have logged it an issue for future releases, and are working actively to have our api compatible with Jupyterlab3. For now, the restriction is to have jupyterlab >=2.0.0, but lower than 3.0.0
For now, please make sure the versions of your jupyter, jupyterlab, and the arcgis-map-ipywidget meet the requirements as mentioned in https://developers.arcgis.com/python/guide/using-the-jupyter-lab-environment/
