### ISSUE TITLE
Working with SSL certificates not possible using high available portal site

### ISSUE THREAD

**Issue by esristeinicke** [Esri/arcgis-python-api#996]
**Describe the bug**
The **Security > SSLCertificates** resource is not available under the Security section when using a high available portal site and have to be accessed under the **Machines > Machine_FQDN > SSLCertificates** section.

**To Reproduce**
```python
gis.admin.security.ssl.list()
```
error:
```python
This resource is not accessible for highly available Portals. Please use the sslCertificates API available within the Machines API.
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8af8ee9d77dc>", line 1, in <module>
    gis.admin.security.ssl.list()
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\gis\admin\_security.py", line 354, in ssl
    self._ssl = SSLCertificates(url=url, gis=self._gis)
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\gis\admin\_security.py", line 454, in __init__
    **kwargs)
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\gis\admin\_base.py", line 29, in __init__
    self._init(connection=self._con)
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\gis\admin\_base.py", line 37, in _init
    params=params)
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\_impl\connection.py", line 902, in get
    self._handle_json_error(resp_json['error'], errorcode)
  File "C:\Python\Anaconda3\lib\site-packages\arcgis\_impl\connection.py", line 1203, in _handle_json_error
    raise RuntimeError(errormessage)
RuntimeError: This resource is not accessible for highly available Portals. Please use the sslCertificates API available within the Machines API.
(Error Code: 500)
```
**Expected behavior**
Also support **SSLCertificates** when using high available portal sites, or make the resource available at the Machine level.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Chrome Version 90.0.4430.93 (Official Build) (64-bit)
 - Python API Version: 1.8.5

**Comment by achapkowski** [comment]
@mohi9282 please review this.

**Comment by nanaeaubry** [comment]
Cannot reproduce with our Enterprise and with Python 2.0.1

**Comment by Ayushyadav19** [comment]
Hi @nanaeaubry ,

Is this has been resolved if yes then can you please provide me the function name.

Thanks 
Ayush

**Comment by nanaeaubry** [comment]
Hello,
We closed the issue because we cannot reproduce it on our end using the various machines. In order to get better help with your machine we recommend contacting Esri support for this issue.

Here is the results I get from our Portal:
![image](https://user-images.githubusercontent.com/19919283/205092646-8090b044-714d-4984-a733-ecf9e154bbf4.png)

**Comment by esristeinicke** [comment]
Hello,

This issue allies only when working with "highly available Portals." If you have only one portal machine, this issue does not exist.

**Comment by esristeinicke** [comment]
![image](https://user-images.githubusercontent.com/33834351/205104296-b2392297-6102-432f-b64d-bfb9d5dd506c.png)

**Comment by nanaeaubry** [comment]
@esristeinicke Are you able to share with us a highly available portal configuration for us to test this with? We are trying to locate why the issue would be occurring in security.

cc @achapkowski

**Comment by nanaeaubry** [comment]
Hi @esristeinicke so we confirmed what you stated that it is best practice to use the Machine property for ssl_certificates.

We cannot remove what we have in security due to backwards compatibility until a major version change. However we will direct users to this machine endpoint.

https://developers.arcgis.com/python/api-reference/arcgis.gis.mission.html#arcgis.gis.mission._machines.Machine.ssl_certificates

**Comment by nanaeaubry** [comment]
You can expect to see this change reflected in the next release. Thank you for notifying us about it
